# GENERATED by scripts/generate_builtin_ops.py from extension_api.json — do not edit.
extends Node2D
# Task 134 B: the GDScript half of builtin_parity_smoke.tscn. Prints the same two lines as
# BuiltinParitySmoke.kt; scripts/runtime_smoke.sh requires the two to be identical.

const SCALES := [0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0]
var seed := 2463534242
var hashes := {}
var hash_order := []
# The edge row's decimals: ±0 (-0.0 built from bytes: GDScript merges the 0.0 and -0.0
# literals), NaN, ±INF, .5 ties, a tiny normal.
var edge := false
var edge_values := [PackedByteArray([0, 0, 0, 0, 0, 0, 0, 0]).decode_double(0),
	PackedByteArray([0, 0, 0, 0, 0, 0, 0, 0x80]).decode_double(0), NAN, INF, -INF, 0.5, -0.5, 1.5, 2.5, -2.5,
	1e-30, 3.0]


func _ready() -> void:
	for i in 256:
		pure_round()
	report("pure=n=256 " + summary())
	hashes.clear()
	hash_order.clear()
	edge = true
	for i in 64:
		edge_round()
	edge = false
	report("edge=n=64 " + summary())
	hashes.clear()
	hash_order.clear()
	for i in 8:
		facade_round()
	report("facade=n=8 " + summary())
	hashes.clear()
	hash_order.clear()
	constants()
	report("const=n=1 " + summary())


func constants() -> void:
	mix("Vector2.ZERO", Vector2.ZERO)
	mix("Vector2.ONE", Vector2.ONE)
	mix("Vector2.INF", Vector2.INF)
	mix("Vector2.LEFT", Vector2.LEFT)
	mix("Vector2.RIGHT", Vector2.RIGHT)
	mix("Vector2.UP", Vector2.UP)
	mix("Vector2.DOWN", Vector2.DOWN)
	mix("Vector2.AXIS_X", Vector2.AXIS_X)
	mix("Vector2.AXIS_Y", Vector2.AXIS_Y)
	mix("Vector3.ZERO", Vector3.ZERO)
	mix("Vector3.ONE", Vector3.ONE)
	mix("Vector3.INF", Vector3.INF)
	mix("Vector3.LEFT", Vector3.LEFT)
	mix("Vector3.RIGHT", Vector3.RIGHT)
	mix("Vector3.UP", Vector3.UP)
	mix("Vector3.DOWN", Vector3.DOWN)
	mix("Vector3.FORWARD", Vector3.FORWARD)
	mix("Vector3.BACK", Vector3.BACK)
	mix("Vector3.MODEL_LEFT", Vector3.MODEL_LEFT)
	mix("Vector3.MODEL_RIGHT", Vector3.MODEL_RIGHT)
	mix("Vector3.MODEL_TOP", Vector3.MODEL_TOP)
	mix("Vector3.MODEL_BOTTOM", Vector3.MODEL_BOTTOM)
	mix("Vector3.MODEL_FRONT", Vector3.MODEL_FRONT)
	mix("Vector3.MODEL_REAR", Vector3.MODEL_REAR)
	mix("Vector3.AXIS_X", Vector3.AXIS_X)
	mix("Vector3.AXIS_Y", Vector3.AXIS_Y)
	mix("Vector3.AXIS_Z", Vector3.AXIS_Z)
	mix("Vector4.ZERO", Vector4.ZERO)
	mix("Vector4.ONE", Vector4.ONE)
	mix("Vector4.INF", Vector4.INF)
	mix("Vector4.AXIS_X", Vector4.AXIS_X)
	mix("Vector4.AXIS_Y", Vector4.AXIS_Y)
	mix("Vector4.AXIS_Z", Vector4.AXIS_Z)
	mix("Vector4.AXIS_W", Vector4.AXIS_W)
	mix("Quaternion.IDENTITY", Quaternion.IDENTITY)
	mix("Plane.PLANE_YZ", Plane.PLANE_YZ)
	mix("Plane.PLANE_XZ", Plane.PLANE_XZ)
	mix("Plane.PLANE_XY", Plane.PLANE_XY)
	mix("Basis.IDENTITY", Basis.IDENTITY)
	mix("Basis.FLIP_X", Basis.FLIP_X)
	mix("Basis.FLIP_Y", Basis.FLIP_Y)
	mix("Basis.FLIP_Z", Basis.FLIP_Z)
	mix("Transform3D.IDENTITY", Transform3D.IDENTITY)
	mix("Transform3D.FLIP_X", Transform3D.FLIP_X)
	mix("Transform3D.FLIP_Y", Transform3D.FLIP_Y)
	mix("Transform3D.FLIP_Z", Transform3D.FLIP_Z)
	mix("Transform2D.IDENTITY", Transform2D.IDENTITY)
	mix("Transform2D.FLIP_X", Transform2D.FLIP_X)
	mix("Transform2D.FLIP_Y", Transform2D.FLIP_Y)
	mix("Projection.IDENTITY", Projection.IDENTITY)
	mix("Projection.ZERO", Projection.ZERO)
	mix("Projection.PLANE_NEAR", Projection.PLANE_NEAR)
	mix("Projection.PLANE_FAR", Projection.PLANE_FAR)
	mix("Projection.PLANE_LEFT", Projection.PLANE_LEFT)
	mix("Projection.PLANE_TOP", Projection.PLANE_TOP)
	mix("Projection.PLANE_RIGHT", Projection.PLANE_RIGHT)
	mix("Projection.PLANE_BOTTOM", Projection.PLANE_BOTTOM)
	mix("Color.ALICE_BLUE", Color.ALICE_BLUE)
	mix("Color.ANTIQUE_WHITE", Color.ANTIQUE_WHITE)
	mix("Color.AQUA", Color.AQUA)
	mix("Color.AQUAMARINE", Color.AQUAMARINE)
	mix("Color.AZURE", Color.AZURE)
	mix("Color.BEIGE", Color.BEIGE)
	mix("Color.BISQUE", Color.BISQUE)
	mix("Color.BLACK", Color.BLACK)
	mix("Color.BLANCHED_ALMOND", Color.BLANCHED_ALMOND)
	mix("Color.BLUE", Color.BLUE)
	mix("Color.BLUE_VIOLET", Color.BLUE_VIOLET)
	mix("Color.BROWN", Color.BROWN)
	mix("Color.BURLYWOOD", Color.BURLYWOOD)
	mix("Color.CADET_BLUE", Color.CADET_BLUE)
	mix("Color.CHARTREUSE", Color.CHARTREUSE)
	mix("Color.CHOCOLATE", Color.CHOCOLATE)
	mix("Color.CORAL", Color.CORAL)
	mix("Color.CORNFLOWER_BLUE", Color.CORNFLOWER_BLUE)
	mix("Color.CORNSILK", Color.CORNSILK)
	mix("Color.CRIMSON", Color.CRIMSON)
	mix("Color.CYAN", Color.CYAN)
	mix("Color.DARK_BLUE", Color.DARK_BLUE)
	mix("Color.DARK_CYAN", Color.DARK_CYAN)
	mix("Color.DARK_GOLDENROD", Color.DARK_GOLDENROD)
	mix("Color.DARK_GRAY", Color.DARK_GRAY)
	mix("Color.DARK_GREEN", Color.DARK_GREEN)
	mix("Color.DARK_KHAKI", Color.DARK_KHAKI)
	mix("Color.DARK_MAGENTA", Color.DARK_MAGENTA)
	mix("Color.DARK_OLIVE_GREEN", Color.DARK_OLIVE_GREEN)
	mix("Color.DARK_ORANGE", Color.DARK_ORANGE)
	mix("Color.DARK_ORCHID", Color.DARK_ORCHID)
	mix("Color.DARK_RED", Color.DARK_RED)
	mix("Color.DARK_SALMON", Color.DARK_SALMON)
	mix("Color.DARK_SEA_GREEN", Color.DARK_SEA_GREEN)
	mix("Color.DARK_SLATE_BLUE", Color.DARK_SLATE_BLUE)
	mix("Color.DARK_SLATE_GRAY", Color.DARK_SLATE_GRAY)
	mix("Color.DARK_TURQUOISE", Color.DARK_TURQUOISE)
	mix("Color.DARK_VIOLET", Color.DARK_VIOLET)
	mix("Color.DEEP_PINK", Color.DEEP_PINK)
	mix("Color.DEEP_SKY_BLUE", Color.DEEP_SKY_BLUE)
	mix("Color.DIM_GRAY", Color.DIM_GRAY)
	mix("Color.DODGER_BLUE", Color.DODGER_BLUE)
	mix("Color.FIREBRICK", Color.FIREBRICK)
	mix("Color.FLORAL_WHITE", Color.FLORAL_WHITE)
	mix("Color.FOREST_GREEN", Color.FOREST_GREEN)
	mix("Color.FUCHSIA", Color.FUCHSIA)
	mix("Color.GAINSBORO", Color.GAINSBORO)
	mix("Color.GHOST_WHITE", Color.GHOST_WHITE)
	mix("Color.GOLD", Color.GOLD)
	mix("Color.GOLDENROD", Color.GOLDENROD)
	mix("Color.GRAY", Color.GRAY)
	mix("Color.GREEN", Color.GREEN)
	mix("Color.GREEN_YELLOW", Color.GREEN_YELLOW)
	mix("Color.HONEYDEW", Color.HONEYDEW)
	mix("Color.HOT_PINK", Color.HOT_PINK)
	mix("Color.INDIAN_RED", Color.INDIAN_RED)
	mix("Color.INDIGO", Color.INDIGO)
	mix("Color.IVORY", Color.IVORY)
	mix("Color.KHAKI", Color.KHAKI)
	mix("Color.LAVENDER", Color.LAVENDER)
	mix("Color.LAVENDER_BLUSH", Color.LAVENDER_BLUSH)
	mix("Color.LAWN_GREEN", Color.LAWN_GREEN)
	mix("Color.LEMON_CHIFFON", Color.LEMON_CHIFFON)
	mix("Color.LIGHT_BLUE", Color.LIGHT_BLUE)
	mix("Color.LIGHT_CORAL", Color.LIGHT_CORAL)
	mix("Color.LIGHT_CYAN", Color.LIGHT_CYAN)
	mix("Color.LIGHT_GOLDENROD", Color.LIGHT_GOLDENROD)
	mix("Color.LIGHT_GRAY", Color.LIGHT_GRAY)
	mix("Color.LIGHT_GREEN", Color.LIGHT_GREEN)
	mix("Color.LIGHT_PINK", Color.LIGHT_PINK)
	mix("Color.LIGHT_SALMON", Color.LIGHT_SALMON)
	mix("Color.LIGHT_SEA_GREEN", Color.LIGHT_SEA_GREEN)
	mix("Color.LIGHT_SKY_BLUE", Color.LIGHT_SKY_BLUE)
	mix("Color.LIGHT_SLATE_GRAY", Color.LIGHT_SLATE_GRAY)
	mix("Color.LIGHT_STEEL_BLUE", Color.LIGHT_STEEL_BLUE)
	mix("Color.LIGHT_YELLOW", Color.LIGHT_YELLOW)
	mix("Color.LIME", Color.LIME)
	mix("Color.LIME_GREEN", Color.LIME_GREEN)
	mix("Color.LINEN", Color.LINEN)
	mix("Color.MAGENTA", Color.MAGENTA)
	mix("Color.MAROON", Color.MAROON)
	mix("Color.MEDIUM_AQUAMARINE", Color.MEDIUM_AQUAMARINE)
	mix("Color.MEDIUM_BLUE", Color.MEDIUM_BLUE)
	mix("Color.MEDIUM_ORCHID", Color.MEDIUM_ORCHID)
	mix("Color.MEDIUM_PURPLE", Color.MEDIUM_PURPLE)
	mix("Color.MEDIUM_SEA_GREEN", Color.MEDIUM_SEA_GREEN)
	mix("Color.MEDIUM_SLATE_BLUE", Color.MEDIUM_SLATE_BLUE)
	mix("Color.MEDIUM_SPRING_GREEN", Color.MEDIUM_SPRING_GREEN)
	mix("Color.MEDIUM_TURQUOISE", Color.MEDIUM_TURQUOISE)
	mix("Color.MEDIUM_VIOLET_RED", Color.MEDIUM_VIOLET_RED)
	mix("Color.MIDNIGHT_BLUE", Color.MIDNIGHT_BLUE)
	mix("Color.MINT_CREAM", Color.MINT_CREAM)
	mix("Color.MISTY_ROSE", Color.MISTY_ROSE)
	mix("Color.MOCCASIN", Color.MOCCASIN)
	mix("Color.NAVAJO_WHITE", Color.NAVAJO_WHITE)
	mix("Color.NAVY_BLUE", Color.NAVY_BLUE)
	mix("Color.OLD_LACE", Color.OLD_LACE)
	mix("Color.OLIVE", Color.OLIVE)
	mix("Color.OLIVE_DRAB", Color.OLIVE_DRAB)
	mix("Color.ORANGE", Color.ORANGE)
	mix("Color.ORANGE_RED", Color.ORANGE_RED)
	mix("Color.ORCHID", Color.ORCHID)
	mix("Color.PALE_GOLDENROD", Color.PALE_GOLDENROD)
	mix("Color.PALE_GREEN", Color.PALE_GREEN)
	mix("Color.PALE_TURQUOISE", Color.PALE_TURQUOISE)
	mix("Color.PALE_VIOLET_RED", Color.PALE_VIOLET_RED)
	mix("Color.PAPAYA_WHIP", Color.PAPAYA_WHIP)
	mix("Color.PEACH_PUFF", Color.PEACH_PUFF)
	mix("Color.PERU", Color.PERU)
	mix("Color.PINK", Color.PINK)
	mix("Color.PLUM", Color.PLUM)
	mix("Color.POWDER_BLUE", Color.POWDER_BLUE)
	mix("Color.PURPLE", Color.PURPLE)
	mix("Color.REBECCA_PURPLE", Color.REBECCA_PURPLE)
	mix("Color.RED", Color.RED)
	mix("Color.ROSY_BROWN", Color.ROSY_BROWN)
	mix("Color.ROYAL_BLUE", Color.ROYAL_BLUE)
	mix("Color.SADDLE_BROWN", Color.SADDLE_BROWN)
	mix("Color.SALMON", Color.SALMON)
	mix("Color.SANDY_BROWN", Color.SANDY_BROWN)
	mix("Color.SEA_GREEN", Color.SEA_GREEN)
	mix("Color.SEASHELL", Color.SEASHELL)
	mix("Color.SIENNA", Color.SIENNA)
	mix("Color.SILVER", Color.SILVER)
	mix("Color.SKY_BLUE", Color.SKY_BLUE)
	mix("Color.SLATE_BLUE", Color.SLATE_BLUE)
	mix("Color.SLATE_GRAY", Color.SLATE_GRAY)
	mix("Color.SNOW", Color.SNOW)
	mix("Color.SPRING_GREEN", Color.SPRING_GREEN)
	mix("Color.STEEL_BLUE", Color.STEEL_BLUE)
	mix("Color.TAN", Color.TAN)
	mix("Color.TEAL", Color.TEAL)
	mix("Color.THISTLE", Color.THISTLE)
	mix("Color.TOMATO", Color.TOMATO)
	mix("Color.TRANSPARENT", Color.TRANSPARENT)
	mix("Color.TURQUOISE", Color.TURQUOISE)
	mix("Color.VIOLET", Color.VIOLET)
	mix("Color.WEB_GRAY", Color.WEB_GRAY)
	mix("Color.WEB_GREEN", Color.WEB_GREEN)
	mix("Color.WEB_MAROON", Color.WEB_MAROON)
	mix("Color.WEB_PURPLE", Color.WEB_PURPLE)
	mix("Color.WHEAT", Color.WHEAT)
	mix("Color.WHITE", Color.WHITE)
	mix("Color.WHITE_SMOKE", Color.WHITE_SMOKE)
	mix("Color.YELLOW", Color.YELLOW)
	mix("Color.YELLOW_GREEN", Color.YELLOW_GREEN)
	mix("Vector2i.ZERO", Vector2i.ZERO)
	mix("Vector2i.ONE", Vector2i.ONE)
	mix("Vector2i.MIN", Vector2i.MIN)
	mix("Vector2i.MAX", Vector2i.MAX)
	mix("Vector2i.LEFT", Vector2i.LEFT)
	mix("Vector2i.RIGHT", Vector2i.RIGHT)
	mix("Vector2i.UP", Vector2i.UP)
	mix("Vector2i.DOWN", Vector2i.DOWN)
	mix("Vector2i.AXIS_X", Vector2i.AXIS_X)
	mix("Vector2i.AXIS_Y", Vector2i.AXIS_Y)
	mix("Vector3i.ZERO", Vector3i.ZERO)
	mix("Vector3i.ONE", Vector3i.ONE)
	mix("Vector3i.MIN", Vector3i.MIN)
	mix("Vector3i.MAX", Vector3i.MAX)
	mix("Vector3i.LEFT", Vector3i.LEFT)
	mix("Vector3i.RIGHT", Vector3i.RIGHT)
	mix("Vector3i.UP", Vector3i.UP)
	mix("Vector3i.DOWN", Vector3i.DOWN)
	mix("Vector3i.FORWARD", Vector3i.FORWARD)
	mix("Vector3i.BACK", Vector3i.BACK)
	mix("Vector3i.AXIS_X", Vector3i.AXIS_X)
	mix("Vector3i.AXIS_Y", Vector3i.AXIS_Y)
	mix("Vector3i.AXIS_Z", Vector3i.AXIS_Z)
	mix("Vector4i.ZERO", Vector4i.ZERO)
	mix("Vector4i.ONE", Vector4i.ONE)
	mix("Vector4i.MIN", Vector4i.MIN)
	mix("Vector4i.MAX", Vector4i.MAX)
	mix("Vector4i.AXIS_X", Vector4i.AXIS_X)
	mix("Vector4i.AXIS_Y", Vector4i.AXIS_Y)
	mix("Vector4i.AXIS_Z", Vector4i.AXIS_Z)
	mix("Vector4i.AXIS_W", Vector4i.AXIS_W)


func pure_round() -> void:
	pure0()
	pure1()
	pure2()
	pure3()
	pure4()
	pure5()
	pure6()
	pure7()
	pure8()
	pure9()
	pure10()
	pure11()
	pure12()
	pure13()
	pure14()
	pure15()
	pure16()
	pure17()
	pure18()
	pure19()
	pure20()
	pure21()
	pure22()
	pure23()
	pure24()
	pure25()
	pure26()
	pure27()
	pure28()
	pure29()
	pure30()
	pure31()
	pure32()
	pure33()
	pure34()
	pure35()
	pure36()
	pure37()
	pure38()
	pure39()
	pure40()
	pure41()
	pure42()
	pure43()
	pure44()
	pure45()
	pure46()
	pure47()
	pure48()
	pure49()
	pure50()
	pure51()
	pure52()
	pure53()
	pure54()
	pure55()
	pure56()
	pure57()
	pure58()
	pure59()
	pure60()
	pure61()
	pure62()
	pure63()
	pure64()
	pure65()
	pure66()
	pure67()
	pure68()
	pure69()
	pure70()
	pure71()
	pure72()
	pure73()
	pure74()
	pure75()
	pure76()
	pure77()
	pure78()
	pure79()
	pure80()
	pure81()
	pure82()
	pure83()
	pure84()
	pure85()
	pure86()
	pure87()
	pure88()
	pure89()
	pure90()
	pure91()
	pure92()
	pure93()
	pure94()
	pure95()
	pure96()
	pure97()
	pure98()
	pure99()
	pure100()
	pure101()
	pure102()
	pure103()
	pure104()
	pure105()
	pure106()
	pure107()
	pure108()
	pure109()
	pure110()
	pure111()
	pure112()
	pure113()
	pure114()
	pure115()
	pure116()
	pure117()
	pure118()
	pure119()
	pure120()
	pure121()
	pure122()
	pure123()
	pure124()
	pure125()
	pure126()
	pure127()
	pure128()
	pure129()
	pure130()
	pure131()
	pure132()
	pure133()
	pure134()
	pure135()
	pure136()
	pure137()
	pure138()
	pure139()
	pure140()
	pure141()
	pure142()
	pure143()
	pure144()
	pure145()
	pure146()
	pure147()
	pure148()
	pure149()
	pure150()
	pure151()
	pure152()
	pure153()
	pure154()
	pure155()
	pure156()
	pure157()
	pure158()
	pure159()
	pure160()
	pure161()
	pure162()
	pure163()
	pure164()
	pure165()
	pure166()
	pure167()
	pure168()
	pure169()
	pure170()
	pure171()
	pure172()
	pure173()
	pure174()
	pure175()
	pure176()
	pure177()
	pure178()
	pure179()
	pure180()
	pure181()
	pure182()
	pure183()
	pure184()
	pure185()
	pure186()
	pure187()
	pure188()
	pure189()
	pure190()
	pure191()
	pure192()
	pure193()
	pure194()
	pure195()
	pure196()
	pure197()
	pure198()
	pure199()
	pure200()
	pure201()
	pure202()
	pure203()
	pure204()
	pure205()
	pure206()
	pure207()
	pure208()
	pure209()
	pure210()
	pure211()
	pure212()
	pure213()
	pure214()
	pure215()
	pure216()
	pure217()
	pure218()
	pure219()
	pure220()
	pure221()
	pure222()
	pure223()
	pure224()
	pure225()
	pure226()
	pure227()
	pure228()
	pure229()
	pure230()
	pure231()
	pure232()
	pure233()
	pure234()
	pure235()
	pure236()
	pure237()
	pure238()
	pure239()
	pure240()
	pure241()
	pure242()
	pure243()
	pure244()
	pure245()
	pure246()
	pure247()
	pure248()
	pure249()
	pure250()
	pure251()
	pure252()
	pure253()
	pure254()
	pure255()
	pure256()
	pure257()
	pure258()
	pure259()
	pure260()
	pure261()
	pure262()
	pure263()
	pure264()
	pure265()
	pure266()
	pure267()
	pure268()
	pure269()
	pure270()
	pure271()
	pure272()
	pure273()
	pure274()
	pure275()
	pure276()
	pure277()
	pure278()
	pure279()
	pure280()
	pure281()
	pure282()
	pure283()
	pure284()
	pure285()
	pure286()
	pure287()
	pure288()
	pure289()
	pure290()
	pure291()
	pure292()
	pure293()
	pure294()
	pure295()
	pure296()
	pure297()
	pure298()
	pure299()
	pure300()
	pure301()
	pure302()
	pure303()
	pure304()
	pure305()
	pure306()
	pure307()
	pure308()
	pure309()
	pure310()
	pure311()
	pure312()
	pure313()
	pure314()
	pure315()
	pure316()
	pure317()
	pure318()
	pure319()
	pure320()
	pure321()
	pure322()
	pure323()
	pure324()
	pure325()
	pure326()
	pure327()
	pure328()
	pure329()
	pure330()
	pure331()
	pure332()
	pure333()
	pure334()


func edge_round() -> void:
	pure0()
	pure1()
	pure2()
	pure3()
	pure4()
	pure5()
	pure7()
	pure8()
	pure9()
	pure10()
	pure11()
	pure12()
	pure13()
	pure14()
	pure15()
	pure16()
	pure17()
	pure18()
	pure19()
	pure20()
	pure21()
	pure22()
	pure23()
	pure24()
	pure25()
	pure26()
	pure27()
	pure28()
	pure29()
	pure30()
	pure31()
	pure32()
	pure33()
	pure34()
	pure38()
	pure39()
	pure40()
	pure41()
	pure42()
	pure43()
	pure44()
	pure45()
	pure46()
	pure47()
	pure48()
	pure49()
	pure50()
	pure51()
	pure52()
	pure54()
	pure55()
	pure56()
	pure57()
	pure59()
	pure60()
	pure61()
	pure62()
	pure63()
	pure64()
	pure65()
	pure66()
	pure67()
	pure68()
	pure69()
	pure70()
	pure71()
	pure72()
	pure73()
	pure74()
	pure75()
	pure76()
	pure77()
	pure78()
	pure79()
	pure80()
	pure81()
	pure82()
	pure83()
	pure84()
	pure85()
	pure86()
	pure87()
	pure91()
	pure92()
	pure93()
	pure94()
	pure95()
	pure96()
	pure97()
	pure98()
	pure99()
	pure100()
	pure101()
	pure103()
	pure104()
	pure105()
	pure106()
	pure107()
	pure108()
	pure109()
	pure110()
	pure111()
	pure112()
	pure113()
	pure114()
	pure115()
	pure116()
	pure117()
	pure118()
	pure119()
	pure120()
	pure121()
	pure122()
	pure123()
	pure124()
	pure125()
	pure126()
	pure127()
	pure128()
	pure129()
	pure130()
	pure131()
	pure132()
	pure133()
	pure134()
	pure135()
	pure136()
	pure137()
	pure138()
	pure139()
	pure140()
	pure142()
	pure143()
	pure144()
	pure145()
	pure146()
	pure147()
	pure148()
	pure149()
	pure150()
	pure151()
	pure152()
	pure153()
	pure154()
	pure155()
	pure156()
	pure157()
	pure158()
	pure159()
	pure160()
	pure161()
	pure162()
	pure163()
	pure164()
	pure165()
	pure166()
	pure167()
	pure168()
	pure169()
	pure170()
	pure171()
	pure172()
	pure173()
	pure174()
	pure175()
	pure176()
	pure177()
	pure178()
	pure179()
	pure180()
	pure181()
	pure182()
	pure183()
	pure184()
	pure185()
	pure186()
	pure187()
	pure188()
	pure189()
	pure190()
	pure191()
	pure192()
	pure193()
	pure194()
	pure195()
	pure196()
	pure197()
	pure198()
	pure199()
	pure200()
	pure201()
	pure202()
	pure203()
	pure204()
	pure205()
	pure206()
	pure207()
	pure208()
	pure209()
	pure210()
	pure211()
	pure212()
	pure213()
	pure214()
	pure215()
	pure216()
	pure217()
	pure218()
	pure219()
	pure220()
	pure221()
	pure222()
	pure223()
	pure224()
	pure225()
	pure226()
	pure227()
	pure228()
	pure229()
	pure230()
	pure231()
	edge_finite232()
	pure233()
	pure234()
	pure235()
	pure236()
	pure237()
	pure238()
	pure239()
	pure240()
	pure241()
	pure242()
	pure245()
	pure246()
	pure247()
	pure248()
	pure249()
	pure250()
	pure251()
	pure252()
	pure253()
	pure254()
	pure255()
	pure256()
	pure257()
	pure258()
	pure259()
	pure260()
	pure261()
	pure262()
	pure263()
	pure264()
	pure265()
	pure266()
	pure267()
	pure268()
	pure269()
	pure270()
	pure273()
	pure274()
	pure275()
	pure276()
	pure277()
	pure278()
	pure279()
	pure280()
	pure281()
	pure282()
	pure283()
	pure284()
	pure285()
	pure286()
	pure287()
	pure288()
	pure289()
	pure290()
	pure291()
	pure292()
	pure293()
	pure294()
	pure295()
	pure296()
	pure297()
	pure300()
	pure301()
	pure302()
	pure303()
	pure304()
	pure305()
	pure306()
	pure307()
	pure308()
	pure309()
	pure310()
	pure311()
	pure312()
	pure313()
	pure314()
	pure315()
	pure316()
	pure317()
	pure318()
	pure319()
	pure320()
	pure321()
	pure322()
	pure323()
	pure324()
	pure325()
	pure326()
	pure327()
	pure328()
	pure329()
	pure330()
	pure331()
	pure333()
	pure334()


func facade_round() -> void:
	facade0()
	facade1()
	facade2()
	facade3()
	facade4()
	facade5()
	facade6()
	facade7()
	facade8()
	facade9()
	facade10()
	facade11()
	facade12()
	facade13()
	facade14()
	facade15()
	facade16()
	facade17()
	facade18()
	facade19()
	facade20()
	facade21()
	facade22()
	facade23()
	facade24()
	facade25()
	facade26()
	facade27()
	facade28()
	facade29()
	facade30()
	facade31()
	facade32()
	facade33()
	facade34()
	facade35()
	facade36()
	facade37()
	facade38()
	facade39()
	facade40()
	facade41()
	facade42()
	facade43()
	facade44()
	facade45()
	facade46()
	facade47()
	facade48()
	facade49()
	facade50()
	facade51()
	facade52()
	facade53()
	facade54()
	facade55()
	facade56()
	facade57()
	facade58()
	facade59()
	facade60()
	facade61()
	facade62()
	facade63()
	facade64()
	facade65()
	facade66()
	facade67()
	facade68()
	facade69()
	facade70()
	facade71()
	facade72()
	facade73()
	facade74()
	facade75()
	facade76()
	facade77()
	facade78()
	facade79()
	facade80()
	facade81()
	facade82()
	facade83()
	facade84()
	facade85()
	facade86()
	facade87()
	facade88()
	facade89()
	facade90()
	facade91()
	facade92()
	facade93()
	facade94()
	facade95()
	facade96()
	facade97()
	facade98()
	facade99()
	facade100()
	facade101()
	facade102()
	facade103()
	facade104()
	facade105()
	facade106()
	facade107()
	facade108()
	facade109()
	facade110()
	facade111()
	facade112()
	facade113()
	facade114()
	facade115()
	facade116()
	facade117()
	facade118()
	facade119()
	facade120()
	facade121()
	facade122()
	facade123()
	facade124()
	facade125()
	facade126()
	facade127()
	facade128()
	facade129()
	facade130()
	facade131()
	facade132()
	facade133()
	facade134()
	facade135()
	facade136()
	facade137()
	facade138()
	facade139()
	facade140()
	facade141()
	facade142()
	facade143()
	facade144()
	facade145()
	facade146()
	facade147()
	facade148()
	facade149()
	facade150()
	facade151()
	facade152()
	facade153()
	facade154()
	facade155()
	facade156()
	facade157()
	facade158()
	facade159()
	facade160()
	facade161()
	facade162()


func pure0() -> void:
	var l = Vector2(nv(), nv())
	mix("unary- Vector2", -l)


func pure1() -> void:
	var l = Vector2(nv(), nv())
	mix("unary+ Vector2", +l)


func pure2() -> void:
	var l = Vector2(nv(), nv())
	var r = ri()
	mix("Vector2 * int", l * r)


func pure3() -> void:
	var l = Vector2(nv(), nv())
	var r = ri()
	mix("Vector2 / int", l / r)


func pure4() -> void:
	var l = Vector2(nv(), nv())
	var r = nv()
	mix("Vector2 * float", l * r)


func pure5() -> void:
	var l = Vector2(nv(), nv())
	var r = nv()
	mix("Vector2 / float", l / r)


func pure6() -> void:
	var l = Vector2(nv(), nv())
	var r = Vector2(nv(), nv())
	mix("Vector2 < Vector2", l < r)


func pure7() -> void:
	var l = Vector2(nv(), nv())
	var r = Vector2(nv(), nv())
	mix("Vector2 + Vector2", l + r)


func pure8() -> void:
	var l = Vector2(nv(), nv())
	var r = Vector2(nv(), nv())
	mix("Vector2 - Vector2", l - r)


func pure9() -> void:
	var l = Vector2(nv(), nv())
	var r = Vector2(nv(), nv())
	mix("Vector2 * Vector2", l * r)


func pure10() -> void:
	var l = Vector2(nv(), nv())
	var r = Vector2(nv(), nv())
	mix("Vector2 / Vector2", l / r)


func pure11() -> void:
	var l = Vector2(nv(), nv())
	var r = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	mix("Vector2 * Transform2D", l * r)


func pure12() -> void:
	var b = Vector2(nv(), nv())
	var a0 = Vector2(nv(), nv())
	mix("Vector2.direction_to", b.direction_to(a0))


func pure13() -> void:
	var b = Vector2(nv(), nv())
	var a0 = Vector2(nv(), nv())
	mix("Vector2.distance_to", b.distance_to(a0))


func pure14() -> void:
	var b = Vector2(nv(), nv())
	var a0 = Vector2(nv(), nv())
	mix("Vector2.distance_squared_to", b.distance_squared_to(a0))


func pure15() -> void:
	var b = Vector2(nv(), nv())
	mix("Vector2.length", b.length())


func pure16() -> void:
	var b = Vector2(nv(), nv())
	mix("Vector2.length_squared", b.length_squared())


func pure17() -> void:
	var b = Vector2(nv(), nv())
	var a0 = nv()
	mix("Vector2.limit_length", b.limit_length(a0))


func pure18() -> void:
	var b = Vector2(nv(), nv())
	mix("Vector2.normalized", b.normalized())


func pure19() -> void:
	var b = Vector2(nv(), nv())
	var a0 = Vector2(nv(), nv())
	mix("Vector2.is_equal_approx", b.is_equal_approx(a0))


func pure20() -> void:
	var b = Vector2(nv(), nv())
	mix("Vector2.is_zero_approx", b.is_zero_approx())


func pure21() -> void:
	var b = Vector2(nv(), nv())
	mix("Vector2.is_finite", b.is_finite())


func pure22() -> void:
	var b = Vector2(nv(), nv())
	var a0 = nv()
	mix("Vector2.posmod", b.posmod(a0))


func pure23() -> void:
	var b = Vector2(nv(), nv())
	var a0 = Vector2(nv(), nv())
	mix("Vector2.posmodv", b.posmodv(a0))


func pure24() -> void:
	var b = Vector2(nv(), nv())
	var a0 = Vector2(nv(), nv())
	mix("Vector2.project", b.project(a0))


func pure25() -> void:
	var b = Vector2(nv(), nv())
	var a0 = Vector2(nv(), nv())
	var a1 = nv()
	mix("Vector2.lerp", b.lerp(a0, a1))


func pure26() -> void:
	var b = Vector2(nv(), nv())
	mix("Vector2.max_axis_index", b.max_axis_index())


func pure27() -> void:
	var b = Vector2(nv(), nv())
	mix("Vector2.min_axis_index", b.min_axis_index())


func pure28() -> void:
	var b = Vector2(nv(), nv())
	var a0 = Vector2(nv(), nv())
	var a1 = nv()
	mix("Vector2.move_toward", b.move_toward(a0, a1))


func pure29() -> void:
	var b = Vector2(nv(), nv())
	mix("Vector2.orthogonal", b.orthogonal())


func pure30() -> void:
	var b = Vector2(nv(), nv())
	mix("Vector2.floor", b.floor())


func pure31() -> void:
	var b = Vector2(nv(), nv())
	mix("Vector2.ceil", b.ceil())


func pure32() -> void:
	var b = Vector2(nv(), nv())
	mix("Vector2.round", b.round())


func pure33() -> void:
	var b = Vector2(nv(), nv())
	mix("Vector2.aspect", b.aspect())


func pure34() -> void:
	var b = Vector2(nv(), nv())
	var a0 = Vector2(nv(), nv())
	mix("Vector2.dot", b.dot(a0))


func pure35() -> void:
	var b = Vector2(nv(), nv())
	var a0 = Vector2(nv(), nv()).normalized()
	mix("Vector2.slide", b.slide(a0))


func pure36() -> void:
	var b = Vector2(nv(), nv())
	var a0 = Vector2(nv(), nv()).normalized()
	mix("Vector2.bounce", b.bounce(a0))


func pure37() -> void:
	var b = Vector2(nv(), nv())
	var a0 = Vector2(nv(), nv()).normalized()
	mix("Vector2.reflect", b.reflect(a0))


func pure38() -> void:
	var b = Vector2(nv(), nv())
	var a0 = Vector2(nv(), nv())
	mix("Vector2.cross", b.cross(a0))


func pure39() -> void:
	var b = Vector2(nv(), nv())
	mix("Vector2.abs", b.abs())


func pure40() -> void:
	var b = Vector2(nv(), nv())
	mix("Vector2.sign", b.sign())


func pure41() -> void:
	var b = Vector2(nv(), nv())
	var a0 = Vector2(nv(), nv())
	var a1 = Vector2(nv(), nv())
	mix("Vector2.clamp", b.clamp(a0, a1))


func pure42() -> void:
	var b = Vector2(nv(), nv())
	var a0 = nv()
	var a1 = nv()
	mix("Vector2.clampf", b.clampf(a0, a1))


func pure43() -> void:
	var b = Vector2(nv(), nv())
	var a0 = Vector2(nv(), nv())
	mix("Vector2.min", b.min(a0))


func pure44() -> void:
	var b = Vector2(nv(), nv())
	var a0 = nv()
	mix("Vector2.minf", b.minf(a0))


func pure45() -> void:
	var b = Vector2(nv(), nv())
	var a0 = Vector2(nv(), nv())
	mix("Vector2.max", b.max(a0))


func pure46() -> void:
	var b = Vector2(nv(), nv())
	var a0 = nv()
	mix("Vector2.maxf", b.maxf(a0))


func pure47() -> void:
	var l = Vector3(nv(), nv(), nv())
	mix("unary- Vector3", -l)


func pure48() -> void:
	var l = Vector3(nv(), nv(), nv())
	mix("unary+ Vector3", +l)


func pure49() -> void:
	var l = Vector3(nv(), nv(), nv())
	var r = ri()
	mix("Vector3 * int", l * r)


func pure50() -> void:
	var l = Vector3(nv(), nv(), nv())
	var r = ri()
	mix("Vector3 / int", l / r)


func pure51() -> void:
	var l = Vector3(nv(), nv(), nv())
	var r = nv()
	mix("Vector3 * float", l * r)


func pure52() -> void:
	var l = Vector3(nv(), nv(), nv())
	var r = nv()
	mix("Vector3 / float", l / r)


func pure53() -> void:
	var l = Vector3(nv(), nv(), nv())
	var r = Vector3(nv(), nv(), nv())
	mix("Vector3 < Vector3", l < r)


func pure54() -> void:
	var l = Vector3(nv(), nv(), nv())
	var r = Vector3(nv(), nv(), nv())
	mix("Vector3 + Vector3", l + r)


func pure55() -> void:
	var l = Vector3(nv(), nv(), nv())
	var r = Vector3(nv(), nv(), nv())
	mix("Vector3 - Vector3", l - r)


func pure56() -> void:
	var l = Vector3(nv(), nv(), nv())
	var r = Vector3(nv(), nv(), nv())
	mix("Vector3 * Vector3", l * r)


func pure57() -> void:
	var l = Vector3(nv(), nv(), nv())
	var r = Vector3(nv(), nv(), nv())
	mix("Vector3 / Vector3", l / r)


func pure58() -> void:
	var l = Vector3(nv(), nv(), nv())
	var r = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Vector3 * Quaternion", l * r)


func pure59() -> void:
	var l = Vector3(nv(), nv(), nv())
	var r = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
	mix("Vector3 * Basis", l * r)


func pure60() -> void:
	var l = Vector3(nv(), nv(), nv())
	var r = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	mix("Vector3 * Transform3D", l * r)


func pure61() -> void:
	var b = Vector3(nv(), nv(), nv())
	mix("Vector3.min_axis_index", b.min_axis_index())


func pure62() -> void:
	var b = Vector3(nv(), nv(), nv())
	mix("Vector3.max_axis_index", b.max_axis_index())


func pure63() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	mix("Vector3.direction_to", b.direction_to(a0))


func pure64() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	mix("Vector3.distance_to", b.distance_to(a0))


func pure65() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	mix("Vector3.distance_squared_to", b.distance_squared_to(a0))


func pure66() -> void:
	var b = Vector3(nv(), nv(), nv())
	mix("Vector3.length", b.length())


func pure67() -> void:
	var b = Vector3(nv(), nv(), nv())
	mix("Vector3.length_squared", b.length_squared())


func pure68() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = nv()
	mix("Vector3.limit_length", b.limit_length(a0))


func pure69() -> void:
	var b = Vector3(nv(), nv(), nv())
	mix("Vector3.normalized", b.normalized())


func pure70() -> void:
	var b = Vector3(nv(), nv(), nv())
	mix("Vector3.is_normalized", b.is_normalized())


func pure71() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	mix("Vector3.is_equal_approx", b.is_equal_approx(a0))


func pure72() -> void:
	var b = Vector3(nv(), nv(), nv())
	mix("Vector3.is_zero_approx", b.is_zero_approx())


func pure73() -> void:
	var b = Vector3(nv(), nv(), nv())
	mix("Vector3.is_finite", b.is_finite())


func pure74() -> void:
	var b = Vector3(nv(), nv(), nv())
	mix("Vector3.inverse", b.inverse())


func pure75() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	var a1 = Vector3(nv(), nv(), nv())
	mix("Vector3.clamp", b.clamp(a0, a1))


func pure76() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = nv()
	var a1 = nv()
	mix("Vector3.clampf", b.clampf(a0, a1))


func pure77() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	var a1 = nv()
	mix("Vector3.lerp", b.lerp(a0, a1))


func pure78() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	var a1 = nv()
	mix("Vector3.move_toward", b.move_toward(a0, a1))


func pure79() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	mix("Vector3.dot", b.dot(a0))


func pure80() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	mix("Vector3.cross", b.cross(a0))


func pure81() -> void:
	var b = Vector3(nv(), nv(), nv())
	mix("Vector3.abs", b.abs())


func pure82() -> void:
	var b = Vector3(nv(), nv(), nv())
	mix("Vector3.floor", b.floor())


func pure83() -> void:
	var b = Vector3(nv(), nv(), nv())
	mix("Vector3.ceil", b.ceil())


func pure84() -> void:
	var b = Vector3(nv(), nv(), nv())
	mix("Vector3.round", b.round())


func pure85() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = nv()
	mix("Vector3.posmod", b.posmod(a0))


func pure86() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	mix("Vector3.posmodv", b.posmodv(a0))


func pure87() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	mix("Vector3.project", b.project(a0))


func pure88() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("Vector3.slide", b.slide(a0))


func pure89() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("Vector3.bounce", b.bounce(a0))


func pure90() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("Vector3.reflect", b.reflect(a0))


func pure91() -> void:
	var b = Vector3(nv(), nv(), nv())
	mix("Vector3.sign", b.sign())


func pure92() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	mix("Vector3.min", b.min(a0))


func pure93() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = nv()
	mix("Vector3.minf", b.minf(a0))


func pure94() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	mix("Vector3.max", b.max(a0))


func pure95() -> void:
	var b = Vector3(nv(), nv(), nv())
	var a0 = nv()
	mix("Vector3.maxf", b.maxf(a0))


func pure96() -> void:
	var l = Vector4(nv(), nv(), nv(), nv())
	mix("unary- Vector4", -l)


func pure97() -> void:
	var l = Vector4(nv(), nv(), nv(), nv())
	mix("unary+ Vector4", +l)


func pure98() -> void:
	var l = Vector4(nv(), nv(), nv(), nv())
	var r = ri()
	mix("Vector4 * int", l * r)


func pure99() -> void:
	var l = Vector4(nv(), nv(), nv(), nv())
	var r = ri()
	mix("Vector4 / int", l / r)


func pure100() -> void:
	var l = Vector4(nv(), nv(), nv(), nv())
	var r = nv()
	mix("Vector4 * float", l * r)


func pure101() -> void:
	var l = Vector4(nv(), nv(), nv(), nv())
	var r = nv()
	mix("Vector4 / float", l / r)


func pure102() -> void:
	var l = Vector4(nv(), nv(), nv(), nv())
	var r = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4 < Vector4", l < r)


func pure103() -> void:
	var l = Vector4(nv(), nv(), nv(), nv())
	var r = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4 + Vector4", l + r)


func pure104() -> void:
	var l = Vector4(nv(), nv(), nv(), nv())
	var r = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4 - Vector4", l - r)


func pure105() -> void:
	var l = Vector4(nv(), nv(), nv(), nv())
	var r = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4 * Vector4", l * r)


func pure106() -> void:
	var l = Vector4(nv(), nv(), nv(), nv())
	var r = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4 / Vector4", l / r)


func pure107() -> void:
	var l = Vector4(nv(), nv(), nv(), nv())
	var r = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	mix("Vector4 * Projection", l * r)


func pure108() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.min_axis_index", b.min_axis_index())


func pure109() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.max_axis_index", b.max_axis_index())


func pure110() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.length", b.length())


func pure111() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.length_squared", b.length_squared())


func pure112() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.abs", b.abs())


func pure113() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.sign", b.sign())


func pure114() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.floor", b.floor())


func pure115() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.ceil", b.ceil())


func pure116() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.round", b.round())


func pure117() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = Vector4(nv(), nv(), nv(), nv())
	var a1 = nv()
	mix("Vector4.lerp", b.lerp(a0, a1))


func pure118() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = nv()
	mix("Vector4.posmod", b.posmod(a0))


func pure119() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.posmodv", b.posmodv(a0))


func pure120() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = Vector4(nv(), nv(), nv(), nv())
	var a1 = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.clamp", b.clamp(a0, a1))


func pure121() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = nv()
	var a1 = nv()
	mix("Vector4.clampf", b.clampf(a0, a1))


func pure122() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.normalized", b.normalized())


func pure123() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.direction_to", b.direction_to(a0))


func pure124() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.distance_to", b.distance_to(a0))


func pure125() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.distance_squared_to", b.distance_squared_to(a0))


func pure126() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.dot", b.dot(a0))


func pure127() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.inverse", b.inverse())


func pure128() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.is_equal_approx", b.is_equal_approx(a0))


func pure129() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.is_zero_approx", b.is_zero_approx())


func pure130() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.is_finite", b.is_finite())


func pure131() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.min", b.min(a0))


func pure132() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = nv()
	mix("Vector4.minf", b.minf(a0))


func pure133() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.max", b.max(a0))


func pure134() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = nv()
	mix("Vector4.maxf", b.maxf(a0))


func pure135() -> void:
	var l = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("unary- Quaternion", -l)


func pure136() -> void:
	var l = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("unary+ Quaternion", +l)


func pure137() -> void:
	var l = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var r = ri()
	mix("Quaternion * int", l * r)


func pure138() -> void:
	var l = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var r = ri()
	mix("Quaternion / int", l / r)


func pure139() -> void:
	var l = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var r = nv()
	mix("Quaternion * float", l * r)


func pure140() -> void:
	var l = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var r = nv()
	mix("Quaternion / float", l / r)


func pure141() -> void:
	var l = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var r = Vector3(nv(), nv(), nv())
	mix("Quaternion * Vector3", l * r)


func pure142() -> void:
	var l = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var r = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Quaternion + Quaternion", l + r)


func pure143() -> void:
	var l = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var r = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Quaternion - Quaternion", l - r)


func pure144() -> void:
	var l = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var r = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Quaternion * Quaternion", l * r)


func pure145() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Quaternion.length", b.length())


func pure146() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Quaternion.length_squared", b.length_squared())


func pure147() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Quaternion.normalized", b.normalized())


func pure148() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var a0 = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Quaternion.is_equal_approx", b.is_equal_approx(a0))


func pure149() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Quaternion.is_finite", b.is_finite())


func pure150() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var a0 = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Quaternion.dot", b.dot(a0))


func pure151() -> void:
	var l = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	mix("unary- Plane", -l)


func pure152() -> void:
	var l = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	mix("unary+ Plane", +l)


func pure153() -> void:
	var l = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	var r = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	mix("Plane * Transform3D", l * r)


func pure154() -> void:
	var b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	mix("Plane.get_center", b.get_center())


func pure155() -> void:
	var b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	mix("Plane.is_point_over", b.is_point_over(a0))


func pure156() -> void:
	var b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	mix("Plane.distance_to", b.distance_to(a0))


func pure157() -> void:
	var b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	var a1 = nv()
	mix("Plane.has_point", b.has_point(a0, a1))


func pure158() -> void:
	var b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	mix("Plane.project", b.project(a0))


func pure159() -> void:
	var b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	var a0 = Vector3(nv(), nv(), nv())
	var a1 = Vector3(nv(), nv(), nv())
	mix("Plane.intersects_ray", b.intersects_ray(a0, a1))


func pure160() -> void:
	var l = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	var r = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	mix("Rect2 * Transform2D", l * r)


func pure161() -> void:
	var b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	mix("Rect2.get_center", b.get_center())


func pure162() -> void:
	var b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	mix("Rect2.get_area", b.get_area())


func pure163() -> void:
	var b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	mix("Rect2.has_area", b.has_area())


func pure164() -> void:
	var b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	var a0 = Vector2(nv(), nv())
	mix("Rect2.has_point", b.has_point(a0))


func pure165() -> void:
	var b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	var a0 = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	mix("Rect2.is_equal_approx", b.is_equal_approx(a0))


func pure166() -> void:
	var b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	var a0 = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	var a1 = rb()
	mix("Rect2.intersects", b.intersects(a0, a1))


func pure167() -> void:
	var b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	var a0 = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	mix("Rect2.encloses", b.encloses(a0))


func pure168() -> void:
	var b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	var a0 = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	mix("Rect2.intersection", b.intersection(a0))


func pure169() -> void:
	var b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	var a0 = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	mix("Rect2.merge", b.merge(a0))


func pure170() -> void:
	var b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	var a0 = Vector2(nv(), nv())
	mix("Rect2.expand", b.expand(a0))


func pure171() -> void:
	var b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	var a0 = Vector2(nv(), nv())
	mix("Rect2.get_support", b.get_support(a0))


func pure172() -> void:
	var b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	var a0 = nv()
	mix("Rect2.grow", b.grow(a0))


func pure173() -> void:
	var b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	var a0 = rs()
	var a1 = nv()
	mix("Rect2.grow_side", b.grow_side(a0, a1))


func pure174() -> void:
	var b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	var a0 = nv()
	var a1 = nv()
	var a2 = nv()
	var a3 = nv()
	mix("Rect2.grow_individual", b.grow_individual(a0, a1, a2, a3))


func pure175() -> void:
	var b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	mix("Rect2.abs", b.abs())


func pure176() -> void:
	var l = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	var r = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	mix("AABB * Transform3D", l * r)


func pure177() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.get_center", b.get_center())


func pure178() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.get_volume", b.get_volume())


func pure179() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.has_volume", b.has_volume())


func pure180() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.has_surface", b.has_surface())


func pure181() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	var a0 = Vector3(nv(), nv(), nv())
	mix("AABB.has_point", b.has_point(a0))


func pure182() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	var a0 = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.is_equal_approx", b.is_equal_approx(a0))


func pure183() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	var a0 = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.intersects", b.intersects(a0))


func pure184() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	var a0 = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.encloses", b.encloses(a0))


func pure185() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	var a0 = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.merge", b.merge(a0))


func pure186() -> void:
	var l = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
	var r = ri()
	mix("Basis * int", l * r)


func pure187() -> void:
	var l = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
	var r = ri()
	mix("Basis / int", l / r)


func pure188() -> void:
	var l = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
	var r = nv()
	mix("Basis * float", l * r)


func pure189() -> void:
	var l = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
	var r = nv()
	mix("Basis / float", l / r)


func pure190() -> void:
	var l = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
	var r = Vector3(nv(), nv(), nv())
	mix("Basis * Vector3", l * r)


func pure191() -> void:
	var l = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
	var r = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
	mix("Basis * Basis", l * r)


func pure192() -> void:
	var b = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
	var a0 = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
	mix("Basis.is_equal_approx", b.is_equal_approx(a0))


func pure193() -> void:
	var l = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	var r = ri()
	mix("Transform3D * int", l * r)


func pure194() -> void:
	var l = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	var r = ri()
	mix("Transform3D / int", l / r)


func pure195() -> void:
	var l = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	var r = nv()
	mix("Transform3D * float", l * r)


func pure196() -> void:
	var l = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	var r = nv()
	mix("Transform3D / float", l / r)


func pure197() -> void:
	var l = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	var r = Vector3(nv(), nv(), nv())
	mix("Transform3D * Vector3", l * r)


func pure198() -> void:
	var l = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	var r = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	mix("Transform3D * Plane", l * r)


func pure199() -> void:
	var l = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	var r = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("Transform3D * AABB", l * r)


func pure200() -> void:
	var l = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	var r = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	mix("Transform3D * Transform3D", l * r)


func pure201() -> void:
	var l = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	var r = PackedVector3Array([Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())])
	mix("Transform3D * PackedVector3Array", l * r)


func pure202() -> void:
	var b = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	var a0 = Vector3(nv(), nv(), nv())
	mix("Transform3D.translated", b.translated(a0))


func pure203() -> void:
	var b = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	var a0 = Vector3(nv(), nv(), nv())
	mix("Transform3D.translated_local", b.translated_local(a0))


func pure204() -> void:
	var b = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	var a0 = Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))
	mix("Transform3D.is_equal_approx", b.is_equal_approx(a0))


func pure205() -> void:
	var l = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	var r = ri()
	mix("Transform2D * int", l * r)


func pure206() -> void:
	var l = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	var r = ri()
	mix("Transform2D / int", l / r)


func pure207() -> void:
	var l = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	var r = nv()
	mix("Transform2D * float", l * r)


func pure208() -> void:
	var l = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	var r = nv()
	mix("Transform2D / float", l / r)


func pure209() -> void:
	var l = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	var r = Vector2(nv(), nv())
	mix("Transform2D * Vector2", l * r)


func pure210() -> void:
	var l = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	var r = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	mix("Transform2D * Rect2", l * r)


func pure211() -> void:
	var l = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	var r = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	mix("Transform2D * Transform2D", l * r)


func pure212() -> void:
	var l = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	var r = PackedVector2Array([Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv())])
	mix("Transform2D * PackedVector2Array", l * r)


func pure213() -> void:
	var b = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	mix("Transform2D.inverse", b.inverse())


func pure214() -> void:
	var b = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	mix("Transform2D.get_origin", b.get_origin())


func pure215() -> void:
	var b = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	var a0 = Vector2(nv(), nv())
	mix("Transform2D.translated", b.translated(a0))


func pure216() -> void:
	var b = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	var a0 = Vector2(nv(), nv())
	mix("Transform2D.translated_local", b.translated_local(a0))


func pure217() -> void:
	var b = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	var a0 = Vector2(nv(), nv())
	mix("Transform2D.basis_xform", b.basis_xform(a0))


func pure218() -> void:
	var b = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	var a0 = Vector2(nv(), nv())
	mix("Transform2D.basis_xform_inv", b.basis_xform_inv(a0))


func pure219() -> void:
	var b = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	var a0 = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
	mix("Transform2D.is_equal_approx", b.is_equal_approx(a0))


func pure220() -> void:
	var l = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	var r = Vector4(nv(), nv(), nv(), nv())
	mix("Projection * Vector4", l * r)


func pure221() -> void:
	var l = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	var r = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	mix("Projection * Projection", l * r)


func pure222() -> void:
	var l = Color(nv(), nv(), nv(), nv())
	mix("unary- Color", -l)


func pure223() -> void:
	var l = Color(nv(), nv(), nv(), nv())
	mix("unary+ Color", +l)


func pure224() -> void:
	var l = Color(nv(), nv(), nv(), nv())
	var r = ri()
	mix("Color * int", l * r)


func pure225() -> void:
	var l = Color(nv(), nv(), nv(), nv())
	var r = ri()
	mix("Color / int", l / r)


func pure226() -> void:
	var l = Color(nv(), nv(), nv(), nv())
	var r = nv()
	mix("Color * float", l * r)


func pure227() -> void:
	var l = Color(nv(), nv(), nv(), nv())
	var r = nv()
	mix("Color / float", l / r)


func pure228() -> void:
	var l = Color(nv(), nv(), nv(), nv())
	var r = Color(nv(), nv(), nv(), nv())
	mix("Color + Color", l + r)


func pure229() -> void:
	var l = Color(nv(), nv(), nv(), nv())
	var r = Color(nv(), nv(), nv(), nv())
	mix("Color - Color", l - r)


func pure230() -> void:
	var l = Color(nv(), nv(), nv(), nv())
	var r = Color(nv(), nv(), nv(), nv())
	mix("Color * Color", l * r)


func pure231() -> void:
	var l = Color(nv(), nv(), nv(), nv())
	var r = Color(nv(), nv(), nv(), nv())
	mix("Color / Color", l / r)


func pure232() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	var a0 = rb()
	mix("Color.to_html", b.to_html(a0))


func pure233() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	var a0 = Color(nv(), nv(), nv(), nv())
	var a1 = Color(nv(), nv(), nv(), nv())
	mix("Color.clamp", b.clamp(a0, a1))


func pure234() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	mix("Color.inverted", b.inverted())


func pure235() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	var a0 = Color(nv(), nv(), nv(), nv())
	var a1 = nv()
	mix("Color.lerp", b.lerp(a0, a1))


func pure236() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	mix("Color.get_luminance", b.get_luminance())


func pure237() -> void:
	var l = Vector2i(ri(), ri())
	mix("unary- Vector2i", -l)


func pure238() -> void:
	var l = Vector2i(ri(), ri())
	mix("unary+ Vector2i", +l)


func pure239() -> void:
	var l = Vector2i(ri(), ri())
	var r = ri()
	mix("Vector2i * int", l * r)


func pure240() -> void:
	var l = Vector2i(ri(), ri())
	var r = rnz()
	mix("Vector2i / int", l / r)


func pure241() -> void:
	var l = Vector2i(ri(), ri())
	var r = rnz()
	mix("Vector2i % int", l % r)


func pure242() -> void:
	var l = Vector2i(ri(), ri())
	var r = nv()
	mix("Vector2i * float", l * r)


func pure243() -> void:
	var l = Vector2i(ri(), ri())
	var r = nv()
	mix("Vector2i / float", l / r)


func pure244() -> void:
	var l = Vector2i(ri(), ri())
	var r = Vector2i(ri(), ri())
	mix("Vector2i < Vector2i", l < r)


func pure245() -> void:
	var l = Vector2i(ri(), ri())
	var r = Vector2i(ri(), ri())
	mix("Vector2i + Vector2i", l + r)


func pure246() -> void:
	var l = Vector2i(ri(), ri())
	var r = Vector2i(ri(), ri())
	mix("Vector2i - Vector2i", l - r)


func pure247() -> void:
	var l = Vector2i(ri(), ri())
	var r = Vector2i(ri(), ri())
	mix("Vector2i * Vector2i", l * r)


func pure248() -> void:
	var l = Vector2i(ri(), ri())
	var r = Vector2i(rnz(), rnz())
	mix("Vector2i / Vector2i", l / r)


func pure249() -> void:
	var l = Vector2i(ri(), ri())
	var r = Vector2i(rnz(), rnz())
	mix("Vector2i % Vector2i", l % r)


func pure250() -> void:
	var b = Vector2i(ri(), ri())
	mix("Vector2i.aspect", b.aspect())


func pure251() -> void:
	var b = Vector2i(ri(), ri())
	mix("Vector2i.max_axis_index", b.max_axis_index())


func pure252() -> void:
	var b = Vector2i(ri(), ri())
	mix("Vector2i.min_axis_index", b.min_axis_index())


func pure253() -> void:
	var b = Vector2i(ri(), ri())
	var a0 = Vector2i(ri(), ri())
	mix("Vector2i.distance_to", b.distance_to(a0))


func pure254() -> void:
	var b = Vector2i(ri(), ri())
	var a0 = Vector2i(ri(), ri())
	mix("Vector2i.distance_squared_to", b.distance_squared_to(a0))


func pure255() -> void:
	var b = Vector2i(ri(), ri())
	mix("Vector2i.length", b.length())


func pure256() -> void:
	var b = Vector2i(ri(), ri())
	mix("Vector2i.length_squared", b.length_squared())


func pure257() -> void:
	var b = Vector2i(ri(), ri())
	mix("Vector2i.sign", b.sign())


func pure258() -> void:
	var b = Vector2i(ri(), ri())
	mix("Vector2i.abs", b.abs())


func pure259() -> void:
	var b = Vector2i(ri(), ri())
	var a0 = Vector2i(ri(), ri())
	var a1 = Vector2i(ri(), ri())
	mix("Vector2i.clamp", b.clamp(a0, a1))


func pure260() -> void:
	var b = Vector2i(ri(), ri())
	var a0 = ri()
	var a1 = ri()
	mix("Vector2i.clampi", b.clampi(a0, a1))


func pure261() -> void:
	var b = Vector2i(ri(), ri())
	var a0 = Vector2i(ri(), ri())
	mix("Vector2i.min", b.min(a0))


func pure262() -> void:
	var b = Vector2i(ri(), ri())
	var a0 = ri()
	mix("Vector2i.mini", b.mini(a0))


func pure263() -> void:
	var b = Vector2i(ri(), ri())
	var a0 = Vector2i(ri(), ri())
	mix("Vector2i.max", b.max(a0))


func pure264() -> void:
	var b = Vector2i(ri(), ri())
	var a0 = ri()
	mix("Vector2i.maxi", b.maxi(a0))


func pure265() -> void:
	var l = Vector3i(ri(), ri(), ri())
	mix("unary- Vector3i", -l)


func pure266() -> void:
	var l = Vector3i(ri(), ri(), ri())
	mix("unary+ Vector3i", +l)


func pure267() -> void:
	var l = Vector3i(ri(), ri(), ri())
	var r = ri()
	mix("Vector3i * int", l * r)


func pure268() -> void:
	var l = Vector3i(ri(), ri(), ri())
	var r = rnz()
	mix("Vector3i / int", l / r)


func pure269() -> void:
	var l = Vector3i(ri(), ri(), ri())
	var r = rnz()
	mix("Vector3i % int", l % r)


func pure270() -> void:
	var l = Vector3i(ri(), ri(), ri())
	var r = nv()
	mix("Vector3i * float", l * r)


func pure271() -> void:
	var l = Vector3i(ri(), ri(), ri())
	var r = nv()
	mix("Vector3i / float", l / r)


func pure272() -> void:
	var l = Vector3i(ri(), ri(), ri())
	var r = Vector3i(ri(), ri(), ri())
	mix("Vector3i < Vector3i", l < r)


func pure273() -> void:
	var l = Vector3i(ri(), ri(), ri())
	var r = Vector3i(ri(), ri(), ri())
	mix("Vector3i + Vector3i", l + r)


func pure274() -> void:
	var l = Vector3i(ri(), ri(), ri())
	var r = Vector3i(ri(), ri(), ri())
	mix("Vector3i - Vector3i", l - r)


func pure275() -> void:
	var l = Vector3i(ri(), ri(), ri())
	var r = Vector3i(ri(), ri(), ri())
	mix("Vector3i * Vector3i", l * r)


func pure276() -> void:
	var l = Vector3i(ri(), ri(), ri())
	var r = Vector3i(rnz(), rnz(), rnz())
	mix("Vector3i / Vector3i", l / r)


func pure277() -> void:
	var l = Vector3i(ri(), ri(), ri())
	var r = Vector3i(rnz(), rnz(), rnz())
	mix("Vector3i % Vector3i", l % r)


func pure278() -> void:
	var b = Vector3i(ri(), ri(), ri())
	mix("Vector3i.min_axis_index", b.min_axis_index())


func pure279() -> void:
	var b = Vector3i(ri(), ri(), ri())
	mix("Vector3i.max_axis_index", b.max_axis_index())


func pure280() -> void:
	var b = Vector3i(ri(), ri(), ri())
	var a0 = Vector3i(ri(), ri(), ri())
	mix("Vector3i.distance_to", b.distance_to(a0))


func pure281() -> void:
	var b = Vector3i(ri(), ri(), ri())
	var a0 = Vector3i(ri(), ri(), ri())
	mix("Vector3i.distance_squared_to", b.distance_squared_to(a0))


func pure282() -> void:
	var b = Vector3i(ri(), ri(), ri())
	mix("Vector3i.length", b.length())


func pure283() -> void:
	var b = Vector3i(ri(), ri(), ri())
	mix("Vector3i.length_squared", b.length_squared())


func pure284() -> void:
	var b = Vector3i(ri(), ri(), ri())
	mix("Vector3i.sign", b.sign())


func pure285() -> void:
	var b = Vector3i(ri(), ri(), ri())
	mix("Vector3i.abs", b.abs())


func pure286() -> void:
	var b = Vector3i(ri(), ri(), ri())
	var a0 = Vector3i(ri(), ri(), ri())
	var a1 = Vector3i(ri(), ri(), ri())
	mix("Vector3i.clamp", b.clamp(a0, a1))


func pure287() -> void:
	var b = Vector3i(ri(), ri(), ri())
	var a0 = ri()
	var a1 = ri()
	mix("Vector3i.clampi", b.clampi(a0, a1))


func pure288() -> void:
	var b = Vector3i(ri(), ri(), ri())
	var a0 = Vector3i(ri(), ri(), ri())
	mix("Vector3i.min", b.min(a0))


func pure289() -> void:
	var b = Vector3i(ri(), ri(), ri())
	var a0 = ri()
	mix("Vector3i.mini", b.mini(a0))


func pure290() -> void:
	var b = Vector3i(ri(), ri(), ri())
	var a0 = Vector3i(ri(), ri(), ri())
	mix("Vector3i.max", b.max(a0))


func pure291() -> void:
	var b = Vector3i(ri(), ri(), ri())
	var a0 = ri()
	mix("Vector3i.maxi", b.maxi(a0))


func pure292() -> void:
	var l = Vector4i(ri(), ri(), ri(), ri())
	mix("unary- Vector4i", -l)


func pure293() -> void:
	var l = Vector4i(ri(), ri(), ri(), ri())
	mix("unary+ Vector4i", +l)


func pure294() -> void:
	var l = Vector4i(ri(), ri(), ri(), ri())
	var r = ri()
	mix("Vector4i * int", l * r)


func pure295() -> void:
	var l = Vector4i(ri(), ri(), ri(), ri())
	var r = rnz()
	mix("Vector4i / int", l / r)


func pure296() -> void:
	var l = Vector4i(ri(), ri(), ri(), ri())
	var r = rnz()
	mix("Vector4i % int", l % r)


func pure297() -> void:
	var l = Vector4i(ri(), ri(), ri(), ri())
	var r = nv()
	mix("Vector4i * float", l * r)


func pure298() -> void:
	var l = Vector4i(ri(), ri(), ri(), ri())
	var r = nv()
	mix("Vector4i / float", l / r)


func pure299() -> void:
	var l = Vector4i(ri(), ri(), ri(), ri())
	var r = Vector4i(ri(), ri(), ri(), ri())
	mix("Vector4i < Vector4i", l < r)


func pure300() -> void:
	var l = Vector4i(ri(), ri(), ri(), ri())
	var r = Vector4i(ri(), ri(), ri(), ri())
	mix("Vector4i + Vector4i", l + r)


func pure301() -> void:
	var l = Vector4i(ri(), ri(), ri(), ri())
	var r = Vector4i(ri(), ri(), ri(), ri())
	mix("Vector4i - Vector4i", l - r)


func pure302() -> void:
	var l = Vector4i(ri(), ri(), ri(), ri())
	var r = Vector4i(ri(), ri(), ri(), ri())
	mix("Vector4i * Vector4i", l * r)


func pure303() -> void:
	var l = Vector4i(ri(), ri(), ri(), ri())
	var r = Vector4i(rnz(), rnz(), rnz(), rnz())
	mix("Vector4i / Vector4i", l / r)


func pure304() -> void:
	var l = Vector4i(ri(), ri(), ri(), ri())
	var r = Vector4i(rnz(), rnz(), rnz(), rnz())
	mix("Vector4i % Vector4i", l % r)


func pure305() -> void:
	var b = Vector4i(ri(), ri(), ri(), ri())
	mix("Vector4i.min_axis_index", b.min_axis_index())


func pure306() -> void:
	var b = Vector4i(ri(), ri(), ri(), ri())
	mix("Vector4i.max_axis_index", b.max_axis_index())


func pure307() -> void:
	var b = Vector4i(ri(), ri(), ri(), ri())
	mix("Vector4i.length", b.length())


func pure308() -> void:
	var b = Vector4i(ri(), ri(), ri(), ri())
	mix("Vector4i.length_squared", b.length_squared())


func pure309() -> void:
	var b = Vector4i(ri(), ri(), ri(), ri())
	mix("Vector4i.sign", b.sign())


func pure310() -> void:
	var b = Vector4i(ri(), ri(), ri(), ri())
	mix("Vector4i.abs", b.abs())


func pure311() -> void:
	var b = Vector4i(ri(), ri(), ri(), ri())
	var a0 = Vector4i(ri(), ri(), ri(), ri())
	var a1 = Vector4i(ri(), ri(), ri(), ri())
	mix("Vector4i.clamp", b.clamp(a0, a1))


func pure312() -> void:
	var b = Vector4i(ri(), ri(), ri(), ri())
	var a0 = ri()
	var a1 = ri()
	mix("Vector4i.clampi", b.clampi(a0, a1))


func pure313() -> void:
	var b = Vector4i(ri(), ri(), ri(), ri())
	var a0 = Vector4i(ri(), ri(), ri(), ri())
	mix("Vector4i.min", b.min(a0))


func pure314() -> void:
	var b = Vector4i(ri(), ri(), ri(), ri())
	var a0 = ri()
	mix("Vector4i.mini", b.mini(a0))


func pure315() -> void:
	var b = Vector4i(ri(), ri(), ri(), ri())
	var a0 = Vector4i(ri(), ri(), ri(), ri())
	mix("Vector4i.max", b.max(a0))


func pure316() -> void:
	var b = Vector4i(ri(), ri(), ri(), ri())
	var a0 = ri()
	mix("Vector4i.maxi", b.maxi(a0))


func pure317() -> void:
	var b = Vector4i(ri(), ri(), ri(), ri())
	var a0 = Vector4i(ri(), ri(), ri(), ri())
	mix("Vector4i.distance_to", b.distance_to(a0))


func pure318() -> void:
	var b = Vector4i(ri(), ri(), ri(), ri())
	var a0 = Vector4i(ri(), ri(), ri(), ri())
	mix("Vector4i.distance_squared_to", b.distance_squared_to(a0))


func pure319() -> void:
	var b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	mix("Rect2i.get_center", b.get_center())


func pure320() -> void:
	var b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	mix("Rect2i.get_area", b.get_area())


func pure321() -> void:
	var b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	mix("Rect2i.has_area", b.has_area())


func pure322() -> void:
	var b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	var a0 = Vector2i(ri(), ri())
	mix("Rect2i.has_point", b.has_point(a0))


func pure323() -> void:
	var b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	var a0 = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	mix("Rect2i.intersects", b.intersects(a0))


func pure324() -> void:
	var b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	var a0 = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	mix("Rect2i.encloses", b.encloses(a0))


func pure325() -> void:
	var b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	var a0 = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	mix("Rect2i.intersection", b.intersection(a0))


func pure326() -> void:
	var b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	var a0 = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	mix("Rect2i.merge", b.merge(a0))


func pure327() -> void:
	var b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	var a0 = Vector2i(ri(), ri())
	mix("Rect2i.expand", b.expand(a0))


func pure328() -> void:
	var b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	var a0 = ri()
	mix("Rect2i.grow", b.grow(a0))


func pure329() -> void:
	var b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	var a0 = rs()
	var a1 = ri()
	mix("Rect2i.grow_side", b.grow_side(a0, a1))


func pure330() -> void:
	var b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	var a0 = ri()
	var a1 = ri()
	var a2 = ri()
	var a3 = ri()
	mix("Rect2i.grow_individual", b.grow_individual(a0, a1, a2, a3))


func pure331() -> void:
	var b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
	mix("Rect2i.abs", b.abs())


func pure332() -> void:
	var l = rid_from(rl())
	var r = rid_from(rl())
	mix("RID < RID", l < r)


func pure333() -> void:
	var b = rid_from(rl())
	mix("RID.is_valid", b.is_valid())


func pure334() -> void:
	var b = rid_from(rl())
	mix("RID.get_id", b.get_id())


func facade0() -> void:
	var b = Vector2(nv(), nv()).normalized()
	mix("Vector2.angle", b.angle())


func facade1() -> void:
	var b = Vector2(nv(), nv()).normalized()
	var a0 = Vector2(nv(), nv()).normalized()
	mix("Vector2.angle_to", b.angle_to(a0))


func facade2() -> void:
	var b = Vector2(nv(), nv()).normalized()
	var a0 = Vector2(nv(), nv()).normalized()
	mix("Vector2.angle_to_point", b.angle_to_point(a0))


func facade3() -> void:
	var b = Vector2(nv(), nv()).normalized()
	mix("Vector2.is_normalized", b.is_normalized())


func facade4() -> void:
	var b = Vector2(nv(), nv()).normalized()
	var a0 = Vector2(nv(), nv()).normalized()
	var a1 = nv()
	mix("Vector2.slerp", b.slerp(a0, a1))


func facade5() -> void:
	var b = Vector2(nv(), nv()).normalized()
	var a0 = Vector2(nv(), nv()).normalized()
	var a1 = Vector2(nv(), nv()).normalized()
	var a2 = Vector2(nv(), nv()).normalized()
	var a3 = nv()
	mix("Vector2.cubic_interpolate", b.cubic_interpolate(a0, a1, a2, a3))


func facade6() -> void:
	var b = Vector2(nv(), nv()).normalized()
	var a0 = Vector2(nv(), nv()).normalized()
	var a1 = Vector2(nv(), nv()).normalized()
	var a2 = Vector2(nv(), nv()).normalized()
	var a3 = nv()
	var a4 = nv()
	var a5 = nv()
	var a6 = nv()
	mix("Vector2.cubic_interpolate_in_time", b.cubic_interpolate_in_time(a0, a1, a2, a3, a4, a5, a6))


func facade7() -> void:
	var b = Vector2(nv(), nv()).normalized()
	var a0 = Vector2(nv(), nv()).normalized()
	var a1 = Vector2(nv(), nv()).normalized()
	var a2 = Vector2(nv(), nv()).normalized()
	var a3 = nv()
	mix("Vector2.bezier_interpolate", b.bezier_interpolate(a0, a1, a2, a3))


func facade8() -> void:
	var b = Vector2(nv(), nv()).normalized()
	var a0 = Vector2(nv(), nv()).normalized()
	var a1 = Vector2(nv(), nv()).normalized()
	var a2 = Vector2(nv(), nv()).normalized()
	var a3 = nv()
	mix("Vector2.bezier_derivative", b.bezier_derivative(a0, a1, a2, a3))


func facade9() -> void:
	var b = Vector2(nv(), nv()).normalized()
	var a0 = nv()
	mix("Vector2.rotated", b.rotated(a0))


func facade10() -> void:
	var b = Vector2(nv(), nv()).normalized()
	var a0 = Vector2(nv(), nv()).normalized()
	mix("Vector2.snapped", b.snapped(a0))


func facade11() -> void:
	var b = Vector2(nv(), nv()).normalized()
	var a0 = nv()
	mix("Vector2.snappedf", b.snappedf(a0))


func facade12() -> void:
	var a0 = nv()
	mix("Vector2.from_angle", Vector2.from_angle(a0))


func facade13() -> void:
	var b = Vector3(nv(), nv(), nv()).normalized()
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("Vector3.angle_to", b.angle_to(a0))


func facade14() -> void:
	var b = Vector3(nv(), nv(), nv()).normalized()
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	var a1 = Vector3(nv(), nv(), nv()).normalized()
	mix("Vector3.signed_angle_to", b.signed_angle_to(a0, a1))


func facade15() -> void:
	var b = Vector3(nv(), nv(), nv()).normalized()
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("Vector3.snapped", b.snapped(a0))


func facade16() -> void:
	var b = Vector3(nv(), nv(), nv()).normalized()
	var a0 = nv()
	mix("Vector3.snappedf", b.snappedf(a0))


func facade17() -> void:
	var b = Vector3(nv(), nv(), nv()).normalized()
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	var a1 = nv()
	mix("Vector3.rotated", b.rotated(a0, a1))


func facade18() -> void:
	var b = Vector3(nv(), nv(), nv()).normalized()
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	var a1 = nv()
	mix("Vector3.slerp", b.slerp(a0, a1))


func facade19() -> void:
	var b = Vector3(nv(), nv(), nv()).normalized()
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	var a1 = Vector3(nv(), nv(), nv()).normalized()
	var a2 = Vector3(nv(), nv(), nv()).normalized()
	var a3 = nv()
	mix("Vector3.cubic_interpolate", b.cubic_interpolate(a0, a1, a2, a3))


func facade20() -> void:
	var b = Vector3(nv(), nv(), nv()).normalized()
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	var a1 = Vector3(nv(), nv(), nv()).normalized()
	var a2 = Vector3(nv(), nv(), nv()).normalized()
	var a3 = nv()
	var a4 = nv()
	var a5 = nv()
	var a6 = nv()
	mix("Vector3.cubic_interpolate_in_time", b.cubic_interpolate_in_time(a0, a1, a2, a3, a4, a5, a6))


func facade21() -> void:
	var b = Vector3(nv(), nv(), nv()).normalized()
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	var a1 = Vector3(nv(), nv(), nv()).normalized()
	var a2 = Vector3(nv(), nv(), nv()).normalized()
	var a3 = nv()
	mix("Vector3.bezier_interpolate", b.bezier_interpolate(a0, a1, a2, a3))


func facade22() -> void:
	var b = Vector3(nv(), nv(), nv()).normalized()
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	var a1 = Vector3(nv(), nv(), nv()).normalized()
	var a2 = Vector3(nv(), nv(), nv()).normalized()
	var a3 = nv()
	mix("Vector3.bezier_derivative", b.bezier_derivative(a0, a1, a2, a3))


func facade23() -> void:
	var b = Vector3(nv(), nv(), nv()).normalized()
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("Vector3.outer", b.outer(a0))


func facade24() -> void:
	var b = Vector3(nv(), nv(), nv()).normalized()
	mix("Vector3.octahedron_encode", b.octahedron_encode())


func facade25() -> void:
	var a0 = Vector2(nv(), nv()).normalized()
	mix("Vector3.octahedron_decode", Vector3.octahedron_decode(a0))


func facade26() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = Vector4(nv(), nv(), nv(), nv())
	var a1 = Vector4(nv(), nv(), nv(), nv())
	var a2 = Vector4(nv(), nv(), nv(), nv())
	var a3 = nv()
	mix("Vector4.cubic_interpolate", b.cubic_interpolate(a0, a1, a2, a3))


func facade27() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = Vector4(nv(), nv(), nv(), nv())
	var a1 = Vector4(nv(), nv(), nv(), nv())
	var a2 = Vector4(nv(), nv(), nv(), nv())
	var a3 = nv()
	var a4 = nv()
	var a5 = nv()
	var a6 = nv()
	mix("Vector4.cubic_interpolate_in_time", b.cubic_interpolate_in_time(a0, a1, a2, a3, a4, a5, a6))


func facade28() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.snapped", b.snapped(a0))


func facade29() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	var a0 = nv()
	mix("Vector4.snappedf", b.snappedf(a0))


func facade30() -> void:
	var b = Vector4(nv(), nv(), nv(), nv())
	mix("Vector4.is_normalized", b.is_normalized())


func facade31() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Quaternion.is_normalized", b.is_normalized())


func facade32() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Quaternion.inverse", b.inverse())


func facade33() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Quaternion.log", b.log())


func facade34() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Quaternion.exp", b.exp())


func facade35() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var a0 = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Quaternion.angle_to", b.angle_to(a0))


func facade36() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var a0 = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var a1 = nv()
	mix("Quaternion.slerp", b.slerp(a0, a1))


func facade37() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var a0 = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var a1 = nv()
	mix("Quaternion.slerpni", b.slerpni(a0, a1))


func facade38() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var a0 = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var a1 = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var a2 = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var a3 = nv()
	mix("Quaternion.spherical_cubic_interpolate", b.spherical_cubic_interpolate(a0, a1, a2, a3))


func facade39() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var a0 = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var a1 = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var a2 = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var a3 = nv()
	var a4 = nv()
	var a5 = nv()
	var a6 = nv()
	mix("Quaternion.spherical_cubic_interpolate_in_time", b.spherical_cubic_interpolate_in_time(a0, a1, a2, a3, a4, a5, a6))


func facade40() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	var a0 = rs()
	mix("Quaternion.get_euler", b.get_euler(a0))


func facade41() -> void:
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("Quaternion.from_euler", Quaternion.from_euler(a0))


func facade42() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Quaternion.get_axis", b.get_axis())


func facade43() -> void:
	var b = Quaternion(nv(), nv(), nv(), nv()).normalized()
	mix("Quaternion.get_angle", b.get_angle())


func facade44() -> void:
	var b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	mix("Plane.normalized", b.normalized())


func facade45() -> void:
	var b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	var a0 = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	mix("Plane.is_equal_approx", b.is_equal_approx(a0))


func facade46() -> void:
	var b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	mix("Plane.is_finite", b.is_finite())


func facade47() -> void:
	var b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	var a0 = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	var a1 = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	mix("Plane.intersect_3", b.intersect_3(a0, a1))


func facade48() -> void:
	var b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	var a1 = Vector3(nv(), nv(), nv()).normalized()
	mix("Plane.intersects_segment", b.intersects_segment(a0, a1))


func facade49() -> void:
	var b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	mix("Rect2.is_finite", b.is_finite())


func facade50() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.abs", b.abs())


func facade51() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.is_finite", b.is_finite())


func facade52() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	var a0 = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
	mix("AABB.intersects_plane", b.intersects_plane(a0))


func facade53() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	var a0 = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.intersection", b.intersection(a0))


func facade54() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("AABB.expand", b.expand(a0))


func facade55() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	var a0 = nv()
	mix("AABB.grow", b.grow(a0))


func facade56() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("AABB.get_support", b.get_support(a0))


func facade57() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.get_longest_axis", b.get_longest_axis())


func facade58() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.get_longest_axis_index", b.get_longest_axis_index())


func facade59() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.get_longest_axis_size", b.get_longest_axis_size())


func facade60() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.get_shortest_axis", b.get_shortest_axis())


func facade61() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.get_shortest_axis_index", b.get_shortest_axis_index())


func facade62() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("AABB.get_shortest_axis_size", b.get_shortest_axis_size())


func facade63() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	var a0 = rs()
	mix("AABB.get_endpoint", b.get_endpoint(a0))


func facade64() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	var a1 = Vector3(nv(), nv(), nv()).normalized()
	mix("AABB.intersects_segment", b.intersects_segment(a0, a1))


func facade65() -> void:
	var b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	var a1 = Vector3(nv(), nv(), nv()).normalized()
	mix("AABB.intersects_ray", b.intersects_ray(a0, a1))


func facade66() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	mix("Basis.inverse", b.inverse())


func facade67() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	mix("Basis.transposed", b.transposed())


func facade68() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	mix("Basis.orthonormalized", b.orthonormalized())


func facade69() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	mix("Basis.determinant", b.determinant())


func facade70() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	var a1 = nv()
	mix("Basis.rotated", b.rotated(a0, a1))


func facade71() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("Basis.scaled", b.scaled(a0))


func facade72() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("Basis.scaled_local", b.scaled_local(a0))


func facade73() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	mix("Basis.get_scale", b.get_scale())


func facade74() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	var a0 = rs()
	mix("Basis.get_euler", b.get_euler(a0))


func facade75() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("Basis.tdotx", b.tdotx(a0))


func facade76() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("Basis.tdoty", b.tdoty(a0))


func facade77() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("Basis.tdotz", b.tdotz(a0))


func facade78() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	var a0 = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	var a1 = nv()
	mix("Basis.slerp", b.slerp(a0, a1))


func facade79() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	mix("Basis.is_conformal", b.is_conformal())


func facade80() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	mix("Basis.is_finite", b.is_finite())


func facade81() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	mix("Basis.is_orthonormal", b.is_orthonormal())


func facade82() -> void:
	var b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
	mix("Basis.get_rotation_quaternion", b.get_rotation_quaternion())


func facade83() -> void:
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	var a1 = Vector3(nv(), nv(), nv()).normalized()
	var a2 = rb()
	mix("Basis.looking_at", Basis.looking_at(a0, a1, a2))


func facade84() -> void:
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("Basis.from_scale", Basis.from_scale(a0))


func facade85() -> void:
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	var a1 = rs()
	mix("Basis.from_euler", Basis.from_euler(a0, a1))


func facade86() -> void:
	var b = Transform3D(Basis(Quaternion(nv(), nv(), nv(), nv()).normalized()), Vector3(nv(), nv(), nv()))
	mix("Transform3D.inverse", b.inverse())


func facade87() -> void:
	var b = Transform3D(Basis(Quaternion(nv(), nv(), nv(), nv()).normalized()), Vector3(nv(), nv(), nv()))
	mix("Transform3D.affine_inverse", b.affine_inverse())


func facade88() -> void:
	var b = Transform3D(Basis(Quaternion(nv(), nv(), nv(), nv()).normalized()), Vector3(nv(), nv(), nv()))
	mix("Transform3D.orthonormalized", b.orthonormalized())


func facade89() -> void:
	var b = Transform3D(Basis(Quaternion(nv(), nv(), nv(), nv()).normalized()), Vector3(nv(), nv(), nv()))
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	var a1 = nv()
	mix("Transform3D.rotated", b.rotated(a0, a1))


func facade90() -> void:
	var b = Transform3D(Basis(Quaternion(nv(), nv(), nv(), nv()).normalized()), Vector3(nv(), nv(), nv()))
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	var a1 = nv()
	mix("Transform3D.rotated_local", b.rotated_local(a0, a1))


func facade91() -> void:
	var b = Transform3D(Basis(Quaternion(nv(), nv(), nv(), nv()).normalized()), Vector3(nv(), nv(), nv()))
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("Transform3D.scaled", b.scaled(a0))


func facade92() -> void:
	var b = Transform3D(Basis(Quaternion(nv(), nv(), nv(), nv()).normalized()), Vector3(nv(), nv(), nv()))
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	mix("Transform3D.scaled_local", b.scaled_local(a0))


func facade93() -> void:
	var b = Transform3D(Basis(Quaternion(nv(), nv(), nv(), nv()).normalized()), Vector3(nv(), nv(), nv()))
	var a0 = Vector3(nv(), nv(), nv()).normalized()
	var a1 = Vector3(nv(), nv(), nv()).normalized()
	var a2 = rb()
	mix("Transform3D.looking_at", b.looking_at(a0, a1, a2))


func facade94() -> void:
	var b = Transform3D(Basis(Quaternion(nv(), nv(), nv(), nv()).normalized()), Vector3(nv(), nv(), nv()))
	var a0 = Transform3D(Basis(Quaternion(nv(), nv(), nv(), nv()).normalized()), Vector3(nv(), nv(), nv()))
	var a1 = nv()
	mix("Transform3D.interpolate_with", b.interpolate_with(a0, a1))


func facade95() -> void:
	var b = Transform3D(Basis(Quaternion(nv(), nv(), nv(), nv()).normalized()), Vector3(nv(), nv(), nv()))
	mix("Transform3D.is_finite", b.is_finite())


func facade96() -> void:
	var b = rotation_2d(Vector2(nv(), nv()).normalized(), Vector2(nv(), nv()))
	mix("Transform2D.affine_inverse", b.affine_inverse())


func facade97() -> void:
	var b = rotation_2d(Vector2(nv(), nv()).normalized(), Vector2(nv(), nv()))
	mix("Transform2D.get_rotation", b.get_rotation())


func facade98() -> void:
	var b = rotation_2d(Vector2(nv(), nv()).normalized(), Vector2(nv(), nv()))
	mix("Transform2D.get_scale", b.get_scale())


func facade99() -> void:
	var b = rotation_2d(Vector2(nv(), nv()).normalized(), Vector2(nv(), nv()))
	mix("Transform2D.get_skew", b.get_skew())


func facade100() -> void:
	var b = rotation_2d(Vector2(nv(), nv()).normalized(), Vector2(nv(), nv()))
	mix("Transform2D.orthonormalized", b.orthonormalized())


func facade101() -> void:
	var b = rotation_2d(Vector2(nv(), nv()).normalized(), Vector2(nv(), nv()))
	var a0 = nv()
	mix("Transform2D.rotated", b.rotated(a0))


func facade102() -> void:
	var b = rotation_2d(Vector2(nv(), nv()).normalized(), Vector2(nv(), nv()))
	var a0 = nv()
	mix("Transform2D.rotated_local", b.rotated_local(a0))


func facade103() -> void:
	var b = rotation_2d(Vector2(nv(), nv()).normalized(), Vector2(nv(), nv()))
	var a0 = Vector2(nv(), nv()).normalized()
	mix("Transform2D.scaled", b.scaled(a0))


func facade104() -> void:
	var b = rotation_2d(Vector2(nv(), nv()).normalized(), Vector2(nv(), nv()))
	var a0 = Vector2(nv(), nv()).normalized()
	mix("Transform2D.scaled_local", b.scaled_local(a0))


func facade105() -> void:
	var b = rotation_2d(Vector2(nv(), nv()).normalized(), Vector2(nv(), nv()))
	mix("Transform2D.determinant", b.determinant())


func facade106() -> void:
	var b = rotation_2d(Vector2(nv(), nv()).normalized(), Vector2(nv(), nv()))
	var a0 = rotation_2d(Vector2(nv(), nv()).normalized(), Vector2(nv(), nv()))
	var a1 = nv()
	mix("Transform2D.interpolate_with", b.interpolate_with(a0, a1))


func facade107() -> void:
	var b = rotation_2d(Vector2(nv(), nv()).normalized(), Vector2(nv(), nv()))
	mix("Transform2D.is_conformal", b.is_conformal())


func facade108() -> void:
	var b = rotation_2d(Vector2(nv(), nv()).normalized(), Vector2(nv(), nv()))
	mix("Transform2D.is_finite", b.is_finite())


func facade109() -> void:
	var b = rotation_2d(Vector2(nv(), nv()).normalized(), Vector2(nv(), nv()))
	var a0 = Vector2(nv(), nv()).normalized()
	mix("Transform2D.looking_at", b.looking_at(a0))


func facade110() -> void:
	var a0 = rb()
	mix("Projection.create_depth_correction", Projection.create_depth_correction(a0))


func facade111() -> void:
	var a0 = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
	mix("Projection.create_light_atlas_rect", Projection.create_light_atlas_rect(a0))


func facade112() -> void:
	var a0 = nv()
	var a1 = nv()
	var a2 = nv()
	var a3 = nv()
	var a4 = rb()
	mix("Projection.create_perspective", Projection.create_perspective(a0, a1, a2, a3, a4))


func facade113() -> void:
	var a0 = nv()
	var a1 = nv()
	var a2 = nv()
	var a3 = nv()
	var a4 = rb()
	var a5 = rs()
	var a6 = nv()
	var a7 = nv()
	mix("Projection.create_perspective_hmd", Projection.create_perspective_hmd(a0, a1, a2, a3, a4, a5, a6, a7))


func facade114() -> void:
	var a0 = rs()
	var a1 = nv()
	var a2 = nv()
	var a3 = nv()
	var a4 = nv()
	var a5 = nv()
	var a6 = nv()
	var a7 = nv()
	mix("Projection.create_for_hmd", Projection.create_for_hmd(a0, a1, a2, a3, a4, a5, a6, a7))


func facade115() -> void:
	var a0 = nv()
	var a1 = nv()
	var a2 = nv()
	var a3 = nv()
	var a4 = nv()
	var a5 = nv()
	mix("Projection.create_orthogonal", Projection.create_orthogonal(a0, a1, a2, a3, a4, a5))


func facade116() -> void:
	var a0 = nv()
	var a1 = nv()
	var a2 = nv()
	var a3 = nv()
	var a4 = rb()
	mix("Projection.create_orthogonal_aspect", Projection.create_orthogonal_aspect(a0, a1, a2, a3, a4))


func facade117() -> void:
	var a0 = nv()
	var a1 = nv()
	var a2 = nv()
	var a3 = nv()
	var a4 = nv()
	var a5 = nv()
	mix("Projection.create_frustum", Projection.create_frustum(a0, a1, a2, a3, a4, a5))


func facade118() -> void:
	var a0 = nv()
	var a1 = nv()
	var a2 = Vector2(nv(), nv()).normalized()
	var a3 = nv()
	var a4 = nv()
	var a5 = rb()
	mix("Projection.create_frustum_aspect", Projection.create_frustum_aspect(a0, a1, a2, a3, a4, a5))


func facade119() -> void:
	var a0 = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
	mix("Projection.create_fit_aabb", Projection.create_fit_aabb(a0))


func facade120() -> void:
	var b = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	mix("Projection.determinant", b.determinant())


func facade121() -> void:
	var b = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	var a0 = nv()
	mix("Projection.perspective_znear_adjusted", b.perspective_znear_adjusted(a0))


func facade122() -> void:
	var b = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	var a0 = rs()
	mix("Projection.get_projection_plane", b.get_projection_plane(a0))


func facade123() -> void:
	var b = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	mix("Projection.flipped_y", b.flipped_y())


func facade124() -> void:
	var b = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	var a0 = Vector2(nv(), nv()).normalized()
	mix("Projection.jitter_offseted", b.jitter_offseted(a0))


func facade125() -> void:
	var a0 = nv()
	var a1 = nv()
	mix("Projection.get_fovy", Projection.get_fovy(a0, a1))


func facade126() -> void:
	var b = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	mix("Projection.get_z_far", b.get_z_far())


func facade127() -> void:
	var b = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	mix("Projection.get_z_near", b.get_z_near())


func facade128() -> void:
	var b = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	mix("Projection.get_aspect", b.get_aspect())


func facade129() -> void:
	var b = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	mix("Projection.get_fov", b.get_fov())


func facade130() -> void:
	var b = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	mix("Projection.is_orthogonal", b.is_orthogonal())


func facade131() -> void:
	var b = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	mix("Projection.get_viewport_half_extents", b.get_viewport_half_extents())


func facade132() -> void:
	var b = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	mix("Projection.get_far_plane_half_extents", b.get_far_plane_half_extents())


func facade133() -> void:
	var b = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	mix("Projection.inverse", b.inverse())


func facade134() -> void:
	var b = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	var a0 = rs()
	mix("Projection.get_pixels_per_meter", b.get_pixels_per_meter(a0))


func facade135() -> void:
	var b = Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))
	mix("Projection.get_lod_multiplier", b.get_lod_multiplier())


func facade136() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	mix("Color.to_argb32", b.to_argb32())


func facade137() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	mix("Color.to_abgr32", b.to_abgr32())


func facade138() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	mix("Color.to_rgba32", b.to_rgba32())


func facade139() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	mix("Color.to_argb64", b.to_argb64())


func facade140() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	mix("Color.to_abgr64", b.to_abgr64())


func facade141() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	mix("Color.to_rgba64", b.to_rgba64())


func facade142() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	var a0 = nv()
	mix("Color.lightened", b.lightened(a0))


func facade143() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	var a0 = nv()
	mix("Color.darkened", b.darkened(a0))


func facade144() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	var a0 = Color(nv(), nv(), nv(), nv())
	mix("Color.blend", b.blend(a0))


func facade145() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	mix("Color.srgb_to_linear", b.srgb_to_linear())


func facade146() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	mix("Color.linear_to_srgb", b.linear_to_srgb())


func facade147() -> void:
	var b = Color(nv(), nv(), nv(), nv())
	var a0 = Color(nv(), nv(), nv(), nv())
	mix("Color.is_equal_approx", b.is_equal_approx(a0))


func facade148() -> void:
	var a0 = rs()
	mix("Color.hex", Color.hex(a0))


func facade149() -> void:
	var a0 = rs()
	mix("Color.hex64", Color.hex64(a0))


func facade150() -> void:
	var a0 = "#ff8000"
	mix("Color.html", Color.html(a0))


func facade151() -> void:
	var a0 = "#ff8000"
	mix("Color.html_is_valid", Color.html_is_valid(a0))


func facade152() -> void:
	var a0 = "#ff8000"
	var a1 = Color(nv(), nv(), nv(), nv())
	mix("Color.from_string", Color.from_string(a0, a1))


func facade153() -> void:
	var a0 = nv()
	var a1 = nv()
	var a2 = nv()
	var a3 = nv()
	mix("Color.from_hsv", Color.from_hsv(a0, a1, a2, a3))


func facade154() -> void:
	var a0 = nv()
	var a1 = nv()
	var a2 = nv()
	var a3 = nv()
	mix("Color.from_ok_hsl", Color.from_ok_hsl(a0, a1, a2, a3))


func facade155() -> void:
	var a0 = rs()
	mix("Color.from_rgbe9995", Color.from_rgbe9995(a0))


func facade156() -> void:
	var a0 = rs()
	var a1 = rs()
	var a2 = rs()
	var a3 = rs()
	mix("Color.from_rgba8", Color.from_rgba8(a0, a1, a2, a3))


func facade157() -> void:
	var b = Vector2i(ri(), ri())
	var a0 = Vector2i(ri(), ri())
	mix("Vector2i.snapped", b.snapped(a0))


func facade158() -> void:
	var b = Vector2i(ri(), ri())
	var a0 = rs()
	mix("Vector2i.snappedi", b.snappedi(a0))


func facade159() -> void:
	var b = Vector3i(ri(), ri(), ri())
	var a0 = Vector3i(ri(), ri(), ri())
	mix("Vector3i.snapped", b.snapped(a0))


func facade160() -> void:
	var b = Vector3i(ri(), ri(), ri())
	var a0 = rs()
	mix("Vector3i.snappedi", b.snappedi(a0))


func facade161() -> void:
	var b = Vector4i(ri(), ri(), ri(), ri())
	var a0 = Vector4i(ri(), ri(), ri(), ri())
	mix("Vector4i.snapped", b.snapped(a0))


func facade162() -> void:
	var b = Vector4i(ri(), ri(), ri(), ri())
	var a0 = rs()
	mix("Vector4i.snappedi", b.snappedi(a0))


func edge_finite232() -> void:
	var b = Color(nvf(), nvf(), nvf(), nvf())
	var a0 = rb()
	mix("Color.to_html", b.to_html(a0))


func next_random() -> int:
	seed = seed ^ ((seed << 13) & 0xFFFFFFFF)
	seed = seed ^ (seed >> 17)
	seed = seed ^ ((seed << 5) & 0xFFFFFFFF)
	return seed


func nv() -> float:
	var r := next_random()
	if edge:
		return edge_values[r % edge_values.size()]
	return ((r % 200001) - 100000) / 10000.0 * SCALES[(r >> 24) % 7]


func nvf() -> float:
	var finite := [edge_values[0], edge_values[1], 0.5, -0.5, 1.5, 2.5, -2.5, 1e-30, 3.0]
	return finite[next_random() % finite.size()]


func ri() -> int:
	return (next_random() % 60001) - 30000


func rnz() -> int:
	var v := ri()
	return 1 if v == 0 else v


func rs() -> int:
	return next_random() % 6


func rl() -> int:
	return next_random()


func rb() -> bool:
	return (next_random() & 1) == 1


func rid_from(value: int) -> RID:
	return rid_from_int64(value)


func rotation_2d(x: Vector2, origin: Vector2) -> Transform2D:
	return Transform2D(x, x.orthogonal(), origin)


func mix_bits(name: String, bits: int) -> void:
	if not hashes.has(name):
		hashes[name] = 2166136261
		hash_order.append(name)
	hashes[name] = ((hashes[name] ^ bits) * 16777619) & 0xFFFFFFFF


func mix_long(name: String, value: int) -> void:
	mix_bits(name, value & 0xFFFFFFFF)
	mix_bits(name, (value >> 32) & 0xFFFFFFFF)


func mix(name: String, value) -> void:
	if value == null:
		mix_long(name, -1)
	elif value is float:
		if is_nan(value):
			mix_long(name, 0x7FF8000000000000)
		else:
			mix_long(name, PackedFloat64Array([value]).to_byte_array().decode_s64(0))
	elif value is bool:
		mix_long(name, 1 if value else 0)
	elif value is int:
		mix_long(name, value)
	elif value is String:
		for i in value.length():
			mix_long(name, value.unicode_at(i))
	elif value is RID:
		mix_long(name, value.get_id())
	elif value is Vector2 or value is Vector2i:
		for c in [value.x, value.y]: mix(name, c)
	elif value is Vector3 or value is Vector3i:
		for c in [value.x, value.y, value.z]: mix(name, c)
	elif value is Vector4 or value is Vector4i or value is Quaternion:
		for c in [value.x, value.y, value.z, value.w]: mix(name, c)
	elif value is Color:
		for c in [value.r, value.g, value.b, value.a]: mix(name, c)
	elif value is Rect2 or value is Rect2i or value is AABB:
		for c in [value.position, value.size]: mix(name, c)
	elif value is Plane:
		for c in [value.normal, value.d]: mix(name, c)
	elif value is Basis:
		for c in [value.x, value.y, value.z]: mix(name, c)
	elif value is Transform2D:
		for c in [value.x, value.y, value.origin]: mix(name, c)
	elif value is Transform3D:
		for c in [value.basis, value.origin]: mix(name, c)
	elif value is Projection:
		for c in [value.x, value.y, value.z, value.w]: mix(name, c)
	elif value is PackedVector2Array or value is PackedVector3Array:
		for c in value: mix(name, c)
	else:
		push_error("no parity mix for %s" % type_string(typeof(value)))


func summary() -> String:
	var parts := []
	for name in hash_order:
		parts.append("%s=%x" % [name.replace(" ", "_"), hashes[name]])
	return " ".join(parts)


func report(line: String) -> void:
	printerr("[kanama:kt] BuiltinParity gdscript ", line)
