package net.multigesture.kanama.processor

/** One Web script model paired with its Godot resource path. */
internal data class WebScriptInput(val model: ScriptModel, val resourcePath: String)

/**
 * Minimal static Kotlin/Wasm registry for Task 57 Phase 0.
 *
 * This emitter intentionally covers only the scalar/lifecycle slice used by the bridge probe. It
 * proves that the shared ScriptModel can drive Web codegen without copying the iOS emitter or
 * introducing reflection. Preview breadth belongs after the benchmark GO gate.
 */
internal class WebScriptCodeEmitter(inputs: List<WebScriptInput>) {
  private val scripts = inputs.sortedWith(compareBy({ it.resourcePath }, { it.model.fqName }))

  data class ProxySource(
    val sourceResourcePath: String,
    val proxyResourcePath: String,
    val fileName: String,
    val source: String,
  )

  fun proxySources(): List<ProxySource> =
    scripts.mapIndexed { index, input ->
      val fileName = input.model.simpleName
      ProxySource(
        sourceResourcePath = input.resourcePath,
        proxyResourcePath = "res://kanama-web/generated/$fileName.gd",
        fileName = fileName,
        source = proxySource(index + 1, input.model),
      )
    }

  fun proxyManifest(): String = buildString {
    appendLine("# source-resource\tproxy-resource\tgenerated-file")
    proxySources().forEach { proxy ->
      appendLine("${proxy.sourceResourcePath}\t${proxy.proxyResourcePath}\t${proxy.fileName}.gd")
    }
  }

  fun registrySource(): String = buildString {
    appendLine("// Generated by KanamaProcessor — do not edit.")
    appendLine("package net.multigesture.kanama.web.generated")
    appendLine()
    appendLine("import net.multigesture.kanama.web.KanamaWebScript")
    appendLine("import net.multigesture.kanama.web.WebMemberDescriptor")
    appendLine("import net.multigesture.kanama.web.WebObjectId")
    appendLine("import net.multigesture.kanama.web.WebScriptDescriptor")
    scripts.forEach { appendLine("import ${it.model.fqName}") }
    appendLine()
    appendLine("object KanamaWebProjectRegistry {")
    appendLine("  const val PROTOCOL_VERSION: Int = 1")
    appendLine()
    appendLine("  val scripts: List<WebScriptDescriptor> =")
    appendLine("    listOf(")
    scripts.forEachIndexed { index, input -> appendDescriptor(index + 1, input) }
    appendLine("    )")
    appendLine()
    appendLine("  fun create(scriptId: Int, objectId: Int): KanamaWebScript =")
    appendLine("    when (scriptId) {")
    scripts.forEachIndexed { index, input ->
      appendLine("      ${index + 1} -> ${input.model.simpleName}(WebObjectId(objectId))")
    }
    appendLine("      else -> unknown(\"script\", scriptId)")
    appendLine("    }")
    appendLine()
    appendReadyDispatcher()
    appendProcessDispatcher()
    appendDrawDispatcher()
    appendExitTreeDispatcher()
    appendNoArgsMethodDispatcher()
    appendStringPropertyGetter()
    appendStringPropertySetter()
    appendLongMethodDispatcher()
    appendLine("  private fun unknown(kind: String, id: Int): Nothing =")
    appendLine("    error(\"Unknown Kanama Web \$kind id=\$id\")")
    appendLine("}")
  }

  private fun StringBuilder.appendDescriptor(scriptId: Int, input: WebScriptInput) {
    val model = input.model
    appendLine("      WebScriptDescriptor(")
    appendLine("        id = $scriptId,")
    appendLine("        resourcePath = ${quote(input.resourcePath)},")
    appendLine("        className = ${quote(model.fqName)},")
    appendLine("        attachTo = ${quote(model.attachTo)},")
    appendMemberList("properties", model.properties.map { it.godotName })
    appendMemberList("virtuals", model.virtuals.map { it.virtualName })
    appendMemberList("methods", model.methods.map { it.godotName })
    appendMemberList("signals", model.signals.map { it.godotName })
    appendLine("      ),")
  }

  private fun StringBuilder.appendMemberList(label: String, names: List<String>) {
    val members =
      names.mapIndexed { index, name -> "WebMemberDescriptor(${index + 1}, ${quote(name)})" }
    appendLine("        $label = listOf(${members.joinToString(", ")}),")
  }

  private fun StringBuilder.appendReadyDispatcher() {
    appendLine("  fun ready(scriptId: Int, script: KanamaWebScript) {")
    appendLine("    when (scriptId) {")
    scripts.forEachIndexed { index, input ->
      val ready = input.model.virtuals.firstOrNull { it.virtualName == "_ready" }
      val body =
        if (ready == null) "Unit"
        else "(script as ${input.model.simpleName}).${ready.kotlinMethodName}()"
      appendLine("      ${index + 1} -> $body")
    }
    appendLine("      else -> unknown(\"script\", scriptId)")
    appendLine("    }")
    appendLine("  }")
    appendLine()
  }

  private fun StringBuilder.appendProcessDispatcher() {
    appendLine("  fun process(scriptId: Int, script: KanamaWebScript, delta: Double) {")
    appendLine("    when (scriptId) {")
    scripts.forEachIndexed { index, input ->
      val process = input.model.virtuals.firstOrNull { it.virtualName == "_process" }
      val body =
        if (process == null) "Unit"
        else "(script as ${input.model.simpleName}).${process.kotlinMethodName}(delta)"
      appendLine("      ${index + 1} -> $body")
    }
    appendLine("      else -> unknown(\"script\", scriptId)")
    appendLine("    }")
    appendLine("  }")
    appendLine()
  }

  private fun StringBuilder.appendDrawDispatcher() {
    appendLine("  fun draw(scriptId: Int, script: KanamaWebScript) {")
    appendLine("    when (scriptId) {")
    scripts.forEachIndexed { index, input ->
      val virtual = input.model.virtuals.firstOrNull { it.virtualName == "_draw" }
      val method =
        input.model.methods.firstOrNull {
          it.godotName == "_draw" && it.args.isEmpty() && it.returnType == null
        }
      val body =
        when {
          virtual != null -> "(script as ${input.model.simpleName}).${virtual.kotlinMethodName}()"
          method != null -> "(script as ${input.model.simpleName}).${method.kotlinName}()"
          else -> "Unit"
        }
      appendLine("      ${index + 1} -> $body")
    }
    appendLine("      else -> unknown(\"script\", scriptId)")
    appendLine("    }")
    appendLine("  }")
    appendLine()
  }

  private fun StringBuilder.appendExitTreeDispatcher() {
    appendLine("  fun exitTree(scriptId: Int, script: KanamaWebScript) {")
    appendLine("    when (scriptId) {")
    scripts.forEachIndexed { index, input ->
      val exitTree = input.model.virtuals.firstOrNull { it.virtualName == "_exit_tree" }
      val body =
        if (exitTree == null) "Unit"
        else "(script as ${input.model.simpleName}).${exitTree.kotlinMethodName}()"
      appendLine("      ${index + 1} -> $body")
    }
    appendLine("      else -> unknown(\"script\", scriptId)")
    appendLine("    }")
    appendLine("  }")
    appendLine()
  }

  private fun StringBuilder.appendNoArgsMethodDispatcher() {
    appendLine("  fun callNoArgs(scriptId: Int, methodId: Int, script: KanamaWebScript) {")
    appendLine("    when (scriptId) {")
    scripts.forEachIndexed { scriptIndex, input ->
      appendLine("      ${scriptIndex + 1} -> when (methodId) {")
      input.model.methods.forEachIndexed { methodIndex, method ->
        if (method.args.isEmpty() && method.returnType == null) {
          appendLine(
            "        ${methodIndex + 1} -> (script as ${input.model.simpleName}).${method.kotlinName}()"
          )
        }
      }
      appendLine("        else -> unknown(\"method\", methodId)")
      appendLine("      }")
    }
    appendLine("      else -> unknown(\"script\", scriptId)")
    appendLine("    }")
    appendLine("  }")
    appendLine()
  }

  private fun StringBuilder.appendStringPropertyGetter() {
    appendLine(
      "  fun getStringProperty(scriptId: Int, propertyId: Int, script: KanamaWebScript): String ="
    )
    appendLine("    when (scriptId) {")
    scripts.forEachIndexed { scriptIndex, input ->
      appendLine("      ${scriptIndex + 1} -> when (propertyId) {")
      input.model.properties.forEachIndexed { propertyIndex, property ->
        if (property.type == TypeMapping.STRING) {
          appendLine(
            "        ${propertyIndex + 1} -> (script as ${input.model.simpleName}).${property.kotlinName}"
          )
        }
      }
      appendLine("        else -> unknown(\"property\", propertyId)")
      appendLine("      }")
    }
    appendLine("      else -> unknown(\"script\", scriptId)")
    appendLine("    }")
    appendLine()
  }

  private fun StringBuilder.appendStringPropertySetter() {
    appendLine(
      "  fun setStringProperty(scriptId: Int, propertyId: Int, script: KanamaWebScript, value: String) {"
    )
    appendLine("    when (scriptId) {")
    scripts.forEachIndexed { scriptIndex, input ->
      appendLine("      ${scriptIndex + 1} -> when (propertyId) {")
      input.model.properties.forEachIndexed { propertyIndex, property ->
        if (property.type == TypeMapping.STRING && property.isMutable) {
          appendLine(
            "        ${propertyIndex + 1} -> (script as ${input.model.simpleName}).${property.kotlinName} = value"
          )
        }
      }
      appendLine("        else -> unknown(\"property\", propertyId)")
      appendLine("      }")
    }
    appendLine("      else -> unknown(\"script\", scriptId)")
    appendLine("    }")
    appendLine("  }")
    appendLine()
  }

  private fun StringBuilder.appendLongMethodDispatcher() {
    appendLine(
      "  fun callLong(scriptId: Int, methodId: Int, script: KanamaWebScript, value: Long): Long ="
    )
    appendLine("    when (scriptId) {")
    scripts.forEachIndexed { scriptIndex, input ->
      appendLine("      ${scriptIndex + 1} -> when (methodId) {")
      input.model.methods.forEachIndexed { methodIndex, method ->
        if (
          method.returnType == TypeMapping.INT &&
            method.args.size == 1 &&
            method.args.single().type == TypeMapping.INT
        ) {
          appendLine(
            "        ${methodIndex + 1} -> (script as ${input.model.simpleName}).${method.kotlinName}(value)"
          )
        }
      }
      appendLine("        else -> unknown(\"method\", methodId)")
      appendLine("      }")
    }
    appendLine("      else -> unknown(\"script\", scriptId)")
    appendLine("    }")
    appendLine()
  }

  private fun proxySource(scriptId: Int, model: ScriptModel): String = buildString {
    appendLine("# Generated by KanamaProcessor — do not edit.")
    appendLine("extends ${model.attachTo}")
    appendLine()
    model.signals.forEach { signal ->
      val args = signal.args.joinToString(", ") { "${it.name}: ${gdType(it.type)}" }
      appendLine("signal ${signal.godotName}($args)")
    }
    if (model.signals.isNotEmpty()) appendLine()
    model.properties.forEach { property ->
      val defaultValue = property.defaultLiteral ?: gdDefault(property.type)
      appendLine("@export var ${property.godotName}: ${gdType(property.type)} = $defaultValue")
    }

    if (model.attachTo == "Resource") return@buildString

    appendLine()
    appendLine("const _KANAMA_SCRIPT_ID: int = $scriptId")
    appendLine("var _kanama_bridge")
    appendLine("var _kanama_handle: int = 0")
    appendLine("var _kanama_apply_callback")
    appendLine("var _kanama_immediate_callback")
    appendLine("var _kanama_resource_callback")
    appendLine("var _kanama_signal_callback")
    appendLine("var _kanama_resource_release_callback")
    appendLine("var _kanama_construct_callback")
    appendLine("var _kanama_object_handles: Dictionary = {}")
    appendLine()
    appendLine("func _ready() -> void:")
    appendLine("\tif not OS.has_feature(\"web\"):")
    appendLine("\t\treturn")
    appendLine("\t_kanama_bridge = JavaScriptBridge.get_interface(\"KanamaWebBridge\")")
    appendLine("\tif _kanama_bridge == null:")
    appendLine("\t\tpush_error(\"Kanama Web bridge was not initialized before Godot\")")
    appendLine("\t\treturn")
    appendLine(
      "\t_kanama_apply_callback = JavaScriptBridge.create_callback(_kanama_apply_commands)"
    )
    appendLine(
      "\t_kanama_immediate_callback = JavaScriptBridge.create_callback(_kanama_immediate_call)"
    )
    appendLine(
      "\t_kanama_resource_callback = JavaScriptBridge.create_callback(_kanama_resource_load)"
    )
    appendLine("\t_kanama_signal_callback = JavaScriptBridge.create_callback(_kanama_signal_emit)")
    appendLine(
      "\t_kanama_resource_release_callback = JavaScriptBridge.create_callback(_kanama_resource_release)"
    )
    appendLine(
      "\t_kanama_construct_callback = JavaScriptBridge.create_callback(_kanama_construct_object)"
    )
    appendLine("\t_kanama_bridge.installApplyCallback(_kanama_apply_callback)")
    appendLine("\t_kanama_bridge.installImmediateCallback(_kanama_immediate_callback)")
    appendLine("\t_kanama_bridge.installResourceCallback(_kanama_resource_callback)")
    appendLine("\t_kanama_bridge.installSignalCallback(_kanama_signal_callback)")
    appendLine("\t_kanama_bridge.installResourceReleaseCallback(_kanama_resource_release_callback)")
    appendLine("\t_kanama_bridge.installConstructCallback(_kanama_construct_callback)")
    appendLine("\t_kanama_handle = int(_kanama_bridge.create(_KANAMA_SCRIPT_ID))")
    appendLine("\tif _kanama_handle == 0:")
    appendLine("\t\tpush_error(\"Kanama Web script construction failed\")")
    appendLine("\t\t_kanama_clear_callbacks()")
    appendLine("\t\treturn")
    appendLine("\tif self is Node2D:")
    appendLine("\t\tvar target := self as Node2D")
    appendLine(
      "\t\t_kanama_bridge.refreshPositionSnapshot(_kanama_handle, target.position.x, target.position.y)"
    )
    appendLine("\t\tvar viewport_rect := target.get_viewport_rect()")
    appendLine(
      "\t\t_kanama_bridge.refreshViewportRectSnapshot(_kanama_handle, viewport_rect.position.x, viewport_rect.position.y, viewport_rect.size.x, viewport_rect.size.y)"
    )
    model.properties.forEachIndexed { index, property ->
      if (property.type == TypeMapping.STRING) {
        appendLine(
          "\t_kanama_bridge.setStringProperty(_kanama_handle, ${index + 1}, ${property.godotName})"
        )
      }
    }
    appendLine("\t_kanama_bridge.ready(_kanama_handle)")
    val immediateMethod =
      model.methods.withIndex().firstOrNull { (_, method) ->
        method.returnType == TypeMapping.INT &&
          method.args.size == 1 &&
          method.args.single().type == TypeMapping.INT
      }
    if (immediateMethod != null) {
      appendLine(
        "\tvar immediate_result := int(_kanama_bridge.callInt(_kanama_handle, ${immediateMethod.index + 1}, 47))"
      )
      appendLine("\t_kanama_bridge.recordImmediateResult(immediate_result)")
    }
    appendLine("\t_kanama_bridge.recordReady(_kanama_handle)")
    appendLine()
    appendLine("func _process(delta: float) -> void:")
    appendLine("\tif _kanama_handle != 0:")
    appendLine("\t\tif self is Node2D:")
    appendLine("\t\t\tvar target := self as Node2D")
    appendLine("\t\t\tvar viewport_rect := target.get_viewport_rect()")
    appendLine(
      "\t\t\t_kanama_bridge.refreshViewportRectSnapshot(_kanama_handle, viewport_rect.position.x, viewport_rect.position.y, viewport_rect.size.x, viewport_rect.size.y)"
    )
    appendLine("\t\t_kanama_bridge.frame(_kanama_handle, delta)")
    appendLine()
    appendLine("func _draw() -> void:")
    appendLine("\tif _kanama_handle != 0:")
    appendLine("\t\t_kanama_bridge.draw(_kanama_handle)")
    appendLine()
    appendLine("func _exit_tree() -> void:")
    appendLine("\tif _kanama_handle == 0:")
    appendLine("\t\t_kanama_clear_callbacks()")
    appendLine("\t\treturn")
    appendLine("\tvar freed_handle := _kanama_handle")
    appendLine("\t_kanama_bridge.free(_kanama_handle)")
    appendLine("\t_kanama_handle = 0")
    appendLine("\t_kanama_clear_callbacks()")
    appendLine("\t_kanama_object_handles.clear()")
    appendLine("\t_kanama_bridge.recordFreed(freed_handle)")
    appendLine()
    appendLine("func _kanama_clear_callbacks() -> void:")
    appendLine("\tif _kanama_bridge == null:")
    appendLine("\t\treturn")
    appendLine("\t_kanama_bridge.clearApplyCallback()")
    appendLine("\t_kanama_bridge.clearImmediateCallback()")
    appendLine("\t_kanama_bridge.clearResourceCallback()")
    appendLine("\t_kanama_bridge.clearSignalCallback()")
    appendLine("\t_kanama_bridge.clearResourceReleaseCallback()")
    appendLine("\t_kanama_bridge.clearConstructCallback()")
    appendLine("\t_kanama_apply_callback = null")
    appendLine("\t_kanama_immediate_callback = null")
    appendLine("\t_kanama_resource_callback = null")
    appendLine("\t_kanama_signal_callback = null")
    appendLine("\t_kanama_resource_release_callback = null")
    appendLine("\t_kanama_construct_callback = null")
    appendLine()
    appendLine("func _kanama_apply_commands(args: Array) -> int:")
    appendLine(
      "\tvar bytes: PackedByteArray = JavaScriptBridge.js_buffer_to_packed_byte_array(args[0])"
    )
    appendLine("\tvar command_count := int(args[1])")
    appendLine("\tvar applied := 0")
    appendLine("\tvar last_value := 0")
    appendLine("\tvar offset := 0")
    appendLine("\tfor command_index in range(command_count):")
    appendLine("\t\tvar opcode := bytes.decode_s32(offset)")
    appendLine("\t\tvar object_handle := bytes.decode_s32(offset + 4)")
    appendLine(
      "\t\tvar target_object: Object = self if object_handle == _kanama_handle else _kanama_object_handles.get(object_handle)"
    )
    appendLine("\t\tif opcode == 100 and object_handle == _kanama_handle:")
    appendLine("\t\t\tlast_value = bytes.decode_s32(offset + 8)")
    appendLine("\t\t\tset_meta(\"kanama_web_scalar\", last_value)")
    appendLine("\t\t\tif self is Node2D:")
    appendLine("\t\t\t\tvar target := self as Node2D")
    appendLine("\t\t\t\ttarget.position = Vector2(float(last_value % 640), target.position.y)")
    appendLine("\t\t\tapplied += 1")
    appendLine("\t\t\toffset += 16")
    appendLine("\t\telif opcode == 3 and target_object is Node2D:")
    appendLine("\t\t\tvar target := target_object as Node2D")
    appendLine("\t\t\tvar position_x := bytes.decode_float(offset + 8)")
    appendLine("\t\t\tvar position_y := bytes.decode_float(offset + 12)")
    appendLine("\t\t\ttarget.position = Vector2(position_x, position_y)")
    appendLine("\t\t\tlast_value = int(position_x)")
    appendLine("\t\t\tapplied += 1")
    appendLine("\t\t\toffset += 16")
    appendLine("\t\telif opcode == 5 and object_handle == _kanama_handle and self is CanvasItem:")
    appendLine("\t\t\t(self as CanvasItem).queue_redraw()")
    appendLine("\t\t\tapplied += 1")
    appendLine("\t\t\toffset += 8")
    appendLine("\t\telif opcode == 6 and object_handle == _kanama_handle and self is CanvasItem:")
    appendLine("\t\t\tvar texture_handle := bytes.decode_s32(offset + 8)")
    appendLine("\t\t\tvar texture := _kanama_object_handles.get(texture_handle) as Texture2D")
    appendLine("\t\t\tif texture == null:")
    appendLine("\t\t\t\tpush_error(\"Unknown Kanama Web texture handle: %d\" % texture_handle)")
    appendLine("\t\t\t\tbreak")
    appendLine(
      "\t\t\tvar draw_position := Vector2(bytes.decode_float(offset + 12), bytes.decode_float(offset + 16))"
    )
    appendLine(
      "\t\t\tvar modulate := Color(bytes.decode_float(offset + 20), bytes.decode_float(offset + 24), bytes.decode_float(offset + 28), bytes.decode_float(offset + 32))"
    )
    appendLine("\t\t\t(self as CanvasItem).draw_texture(texture, draw_position, modulate)")
    appendLine("\t\t\tapplied += 1")
    appendLine("\t\t\toffset += 36")
    appendLine("\t\telif opcode == 13 and target_object is Node:")
    appendLine("\t\t\tvar child_handle := bytes.decode_s32(offset + 8)")
    appendLine("\t\t\tvar child := _kanama_object_handles.get(child_handle) as Node")
    appendLine("\t\t\tif child == null:")
    appendLine("\t\t\t\tpush_error(\"Unknown Kanama Web child handle: %d\" % child_handle)")
    appendLine("\t\t\t\tbreak")
    appendLine(
      "\t\t\t(target_object as Node).add_child(child, bytes.decode_s32(offset + 12) != 0, bytes.decode_s32(offset + 16))"
    )
    appendLine("\t\t\tapplied += 1")
    appendLine("\t\t\toffset += 20")
    appendLine("\t\telif opcode == 14 and target_object is Node:")
    appendLine("\t\t\tvar child_handle := bytes.decode_s32(offset + 8)")
    appendLine("\t\t\tvar child := _kanama_object_handles.get(child_handle) as Node")
    appendLine("\t\t\tif child == null:")
    appendLine("\t\t\t\tpush_error(\"Unknown Kanama Web child handle: %d\" % child_handle)")
    appendLine("\t\t\t\tbreak")
    appendLine("\t\t\t(target_object as Node).remove_child(child)")
    appendLine("\t\t\tapplied += 1")
    appendLine("\t\t\toffset += 12")
    appendLine("\t\telif opcode == 15 and target_object is Node:")
    appendLine("\t\t\t_kanama_object_handles.erase(object_handle)")
    appendLine("\t\t\t(target_object as Node).queue_free()")
    appendLine("\t\t\tapplied += 1")
    appendLine("\t\t\toffset += 8")
    appendLine("\t\telif opcode == 16 and target_object is Sprite2D:")
    appendLine("\t\t\tvar texture_handle := bytes.decode_s32(offset + 8)")
    appendLine(
      "\t\t\tvar texture: Texture2D = null if texture_handle == 0 else _kanama_object_handles.get(texture_handle) as Texture2D"
    )
    appendLine("\t\t\tif texture_handle != 0 and texture == null:")
    appendLine("\t\t\t\tpush_error(\"Unknown Kanama Web texture handle: %d\" % texture_handle)")
    appendLine("\t\t\t\tbreak")
    appendLine("\t\t\t(target_object as Sprite2D).set_texture(texture)")
    appendLine("\t\t\tapplied += 1")
    appendLine("\t\t\toffset += 12")
    appendLine("\t\telse:")
    appendLine(
      "\t\t\tpush_error(\"Invalid Kanama Web command opcode/object: %d/%d\" % [opcode, object_handle])"
    )
    appendLine("\t\t\tbreak")
    appendLine("\t_kanama_bridge.recordApplied(applied, last_value)")
    appendLine("\treturn applied")
    appendLine()
    appendLine("func _kanama_immediate_call(args: Array) -> int:")
    appendLine("\tvar object_handle := int(args[0])")
    appendLine("\tvar result := -1")
    appendLine("\tif object_handle == _kanama_handle:")
    appendLine("\t\tresult = get_child_count(bool(args[1]))")
    appendLine("\t_kanama_bridge.recordImmediateChildCount(result)")
    appendLine("\treturn result")
    appendLine()
    appendLine("func _kanama_resource_load(args: Array) -> int:")
    appendLine("\tvar resource_handle := int(args[0])")
    appendLine("\tvar path := String(args[1])")
    appendLine("\tvar type_hint := String(args[2])")
    appendLine("\tvar cache_mode := int(args[3])")
    appendLine("\tvar resource := ResourceLoader.load(path, type_hint, cache_mode)")
    appendLine("\tif resource == null:")
    appendLine("\t\t_kanama_bridge.recordImmediateResourceHandle(0)")
    appendLine("\t\treturn 0")
    appendLine("\t_kanama_object_handles[resource_handle] = resource")
    appendLine("\t_kanama_bridge.recordImmediateResourceHandle(resource_handle)")
    appendLine("\treturn resource_handle")
    appendLine()
    appendLine("func _kanama_signal_emit(args: Array) -> int:")
    appendLine("\tvar object_handle := int(args[0])")
    appendLine("\tvar result := ERR_INVALID_PARAMETER")
    appendLine("\tif object_handle == _kanama_handle:")
    appendLine("\t\tresult = emit_signal(String(args[1]), int(args[2]))")
    appendLine("\t_kanama_bridge.recordImmediateSignalResult(result)")
    appendLine("\treturn result")
    appendLine()
    appendLine("func _kanama_resource_release(args: Array) -> int:")
    appendLine("\tvar resource_handle := int(args[0])")
    appendLine("\tvar released := int(_kanama_object_handles.erase(resource_handle))")
    appendLine("\t_kanama_bridge.recordImmediateResourceRelease(released)")
    appendLine("\treturn released")
    appendLine()
    appendLine("func _kanama_construct_object(args: Array) -> int:")
    appendLine("\tvar object_handle := int(args[0])")
    appendLine("\tvar requested_class := String(args[1])")
    appendLine("\tvar value := ClassDB.instantiate(requested_class)")
    appendLine("\tif value == null or not value is Node:")
    appendLine("\t\t_kanama_bridge.recordImmediateConstructHandle(0)")
    appendLine("\t\treturn 0")
    appendLine("\t_kanama_object_handles[object_handle] = value")
    appendLine("\t_kanama_bridge.recordImmediateConstructHandle(object_handle)")
    appendLine("\treturn object_handle")

    model.methods.forEachIndexed { index, method ->
      if (method.args.isEmpty() && method.returnType == null && method.godotName != "_draw") {
        appendLine()
        appendLine("func ${method.godotName}() -> void:")
        appendLine("\t_kanama_bridge.callNoArgs(_kanama_handle, ${index + 1})")
      }
      if (
        method.returnType == TypeMapping.INT &&
          method.args.size == 1 &&
          method.args.single().type == TypeMapping.INT
      ) {
        val arg = method.args.single()
        appendLine()
        appendLine("func ${method.godotName}(${arg.name}: int) -> int:")
        appendLine(
          "\treturn int(_kanama_bridge.callInt(_kanama_handle, ${index + 1}, ${arg.name}))"
        )
      }
    }
  }

  private fun gdType(type: TypeMapping): String =
    when (type) {
      TypeMapping.STRING -> "String"
      TypeMapping.INT -> "int"
      TypeMapping.FLOAT -> "float"
      TypeMapping.BOOL -> "bool"
      else -> "Variant"
    }

  private fun gdDefault(type: TypeMapping): String =
    when (type) {
      TypeMapping.STRING -> "\"\""
      TypeMapping.INT -> "0"
      TypeMapping.FLOAT -> "0.0"
      TypeMapping.BOOL -> "false"
      else -> "null"
    }

  private fun quote(value: String): String = buildString {
    append('"')
    value.forEach { char ->
      when (char) {
        '\\' -> append("\\\\")
        '"' -> append("\\\"")
        '\n' -> append("\\n")
        '\r' -> append("\\r")
        '\t' -> append("\\t")
        else -> append(char)
      }
    }
    append('"')
  }
}
