package net.multigesture.kanama.api

import java.lang.foreign.MemorySegment
import net.multigesture.kanama.binding.runtime.ObjectCalls

// GENERATED desktop/Android companion for LightmapGIData (scripts/generate_api_wrapper.py --write-tree).
// DO NOT EDIT BY HAND. These members are not in the shared wrapper tree: iOS has no audited
// ObjectCalls helper for their ptrcall shape yet (or does not host a wrapper type they use), so
// they compile for desktop/Android only. Re-run the generator when iOS gains the helper.
// KANAMA-IOS-GAP LightmapGIData waits on: ptrcallWithObjectListArg
// Index: docs/reference/generated/ios-shape-gap.md

/**
 * The lightmap atlas textures generated by the lightmapper.
 *
 * Generated from Godot docs: LightmapGIData.set_lightmap_textures
 */
fun LightmapGIData.setLightmapTextures(lightTextures: List<TextureLayered>) {
    checkOpen()
    ObjectCalls.ptrcallWithObjectListArg(setLightmapTexturesBind, handle, lightTextures)
}

/**
 * The shadowmask atlas textures generated by the lightmapper.
 *
 * Generated from Godot docs: LightmapGIData.set_shadowmask_textures
 */
fun LightmapGIData.setShadowmaskTextures(shadowmaskTextures: List<TextureLayered>) {
    checkOpen()
    ObjectCalls.ptrcallWithObjectListArg(setShadowmaskTexturesBind, handle, shadowmaskTextures)
}

private const val SET_LIGHTMAP_TEXTURES_HASH = 381264803L
private val setLightmapTexturesBind by lazy {
    ObjectCalls.getMethodBind("LightmapGIData", "set_lightmap_textures", SET_LIGHTMAP_TEXTURES_HASH)
}

private const val SET_SHADOWMASK_TEXTURES_HASH = 381264803L
private val setShadowmaskTexturesBind by lazy {
    ObjectCalls.getMethodBind("LightmapGIData", "set_shadowmask_textures", SET_SHADOWMASK_TEXTURES_HASH)
}
