// GENERATED by scripts/generate_builtin_ops.py from extension_api.json — do not edit.
@file:Suppress("UNUSED_VARIABLE", "NAME_SHADOWING")

package net.multigesture.kanama.types

import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Task 134 B/D1: the value types compiled to Wasm run the runtime smoke's builtin parity row (the
 * same fixed-seed inputs, entry for entry; an entry without a recorded hash only consumes its
 * draws) and must produce the hashes Godot 4.7.2's GDScript printed for it, recorded in
 * `scripts/fixtures/builtin_parity_expected.json` (`generate_builtin_ops.py --record-parity`; the
 * runtime smoke re-checks the recording against the live GDScript line).
 */
class WebBuiltinParityTest {
  @Test
  fun webMembersMatchGodot() {
    repeat(256) { round() }
    skip(124288) // the edge row
    repeat(8) { facadeRound() }
    val wrong =
      (EXPECTED + EXPECTED_FACADE).filter { (key, hash) -> hashes[key]?.toString(16) != hash }.keys
    assertEquals(emptySet(), wrong, "entries whose hash differs from Godot's")
  }

  private fun round() {
    pure0()
    pure1()
    pure2()
    pure3()
    pure4()
    pure5()
    pure6()
    pure7()
    pure8()
    pure9()
    pure10()
    pure11()
    pure12()
    pure13()
    pure14()
    pure15()
    pure16()
    pure17()
    pure18()
    pure19()
    pure20()
    pure21()
    pure22()
    pure23()
    pure24()
    pure25()
    pure26()
    pure27()
    pure28()
    pure29()
    pure30()
    pure31()
    pure32()
    pure33()
    pure34()
    pure35()
    pure36()
    pure37()
    pure38()
    pure39()
    pure40()
    pure41()
    pure42()
    pure43()
    pure44()
    pure45()
    pure46()
    pure47()
    pure48()
    pure49()
    pure50()
    pure51()
    pure52()
    pure53()
    pure54()
    pure55()
    pure56()
    pure57()
    pure58()
    pure59()
    pure60()
    pure61()
    pure62()
    pure63()
    pure64()
    pure65()
    pure66()
    pure67()
    pure68()
    pure69()
    pure70()
    pure71()
    pure72()
    pure73()
    pure74()
    pure75()
    pure76()
    pure77()
    pure78()
    pure79()
    pure80()
    pure81()
    pure82()
    pure83()
    pure84()
    pure85()
    pure86()
    pure87()
    pure88()
    pure89()
    pure90()
    pure91()
    pure92()
    pure93()
    pure94()
    pure95()
    pure96()
    pure97()
    pure98()
    pure99()
    pure100()
    pure101()
    pure102()
    pure103()
    pure104()
    pure105()
    pure106()
    pure107()
    pure108()
    pure109()
    pure110()
    pure111()
    pure112()
    pure113()
    pure114()
    pure115()
    pure116()
    pure117()
    pure118()
    pure119()
    pure120()
    pure121()
    pure122()
    pure123()
    pure124()
    pure125()
    pure126()
    pure127()
    pure128()
    pure129()
    pure130()
    pure131()
    pure132()
    pure133()
    pure134()
    pure135()
    pure136()
    pure137()
    pure138()
    pure139()
    pure140()
    pure141()
    pure142()
    pure143()
    pure144()
    pure145()
    pure146()
    pure147()
    pure148()
    pure149()
    pure150()
    pure151()
    pure152()
    skip(16) // Plane * Transform3D
    pure154()
    pure155()
    pure156()
    pure157()
    pure158()
    pure159()
    pure160()
    pure161()
    pure162()
    pure163()
    pure164()
    pure165()
    pure166()
    pure167()
    pure168()
    pure169()
    pure170()
    pure171()
    pure172()
    pure173()
    pure174()
    pure175()
    pure176()
    pure177()
    pure178()
    pure179()
    pure180()
    pure181()
    pure182()
    pure183()
    pure184()
    pure185()
    pure186()
    pure187()
    pure188()
    pure189()
    pure190()
    pure191()
    pure192()
    pure193()
    pure194()
    pure195()
    pure196()
    pure197()
    pure198()
    pure199()
    pure200()
    pure201()
    pure202()
    pure203()
    pure204()
    pure205()
    pure206()
    pure207()
    pure208()
    pure209()
    pure210()
    pure211()
    pure212()
    pure213()
    pure214()
    pure215()
    pure216()
    pure217()
    pure218()
    pure219()
    pure220()
    pure221()
    pure222()
    pure223()
    pure224()
    pure225()
    pure226()
    pure227()
    pure228()
    pure229()
    pure230()
    pure231()
    pure232()
    pure233()
    pure234()
    pure235()
    pure236()
    pure237()
    pure238()
    pure239()
    pure240()
    pure241()
    pure242()
    pure243()
    pure244()
    pure245()
    pure246()
    pure247()
    pure248()
    pure249()
    pure250()
    pure251()
    pure252()
    pure253()
    pure254()
    pure255()
    pure256()
    pure257()
    pure258()
    pure259()
    pure260()
    pure261()
    pure262()
    pure263()
    pure264()
    pure265()
    pure266()
    pure267()
    pure268()
    pure269()
    pure270()
    pure271()
    pure272()
    pure273()
    pure274()
    pure275()
    pure276()
    pure277()
    pure278()
    pure279()
    pure280()
    pure281()
    pure282()
    pure283()
    pure284()
    pure285()
    pure286()
    pure287()
    pure288()
    pure289()
    pure290()
    pure291()
    pure292()
    pure293()
    pure294()
    pure295()
    pure296()
    pure297()
    pure298()
    pure299()
    pure300()
    pure301()
    pure302()
    pure303()
    pure304()
    pure305()
    pure306()
    pure307()
    pure308()
    pure309()
    pure310()
    pure311()
    pure312()
    pure313()
    pure314()
    pure315()
    pure316()
    pure317()
    pure318()
    pure319()
    pure320()
    pure321()
    pure322()
    pure323()
    pure324()
    pure325()
    pure326()
    pure327()
    pure328()
    pure329()
    pure330()
    pure331()
    pure332()
    pure333()
    pure334()
  }

  /** The facade row: the methods the Web build runs in Kotlin (WebLocalBuiltins), task 134 D1. */
  private fun facadeRound() {
    facade0()
    skip(4) // Vector2.angle_to
    skip(4) // Vector2.angle_to_point
    skip(2) // Vector2.is_normalized
    skip(5) // Vector2.slerp
    skip(9) // Vector2.cubic_interpolate
    skip(12) // Vector2.cubic_interpolate_in_time
    skip(9) // Vector2.bezier_interpolate
    skip(9) // Vector2.bezier_derivative
    facade9()
    skip(4) // Vector2.snapped
    skip(3) // Vector2.snappedf
    skip(1) // Vector2.from_angle
    skip(6) // Vector3.angle_to
    facade14()
    skip(6) // Vector3.snapped
    skip(4) // Vector3.snappedf
    facade17()
    skip(7) // Vector3.slerp
    skip(13) // Vector3.cubic_interpolate
    skip(16) // Vector3.cubic_interpolate_in_time
    skip(13) // Vector3.bezier_interpolate
    skip(13) // Vector3.bezier_derivative
    skip(6) // Vector3.outer
    skip(3) // Vector3.octahedron_encode
    skip(2) // Vector3.octahedron_decode
    skip(17) // Vector4.cubic_interpolate
    skip(20) // Vector4.cubic_interpolate_in_time
    skip(8) // Vector4.snapped
    skip(5) // Vector4.snappedf
    skip(4) // Vector4.is_normalized
    skip(4) // Quaternion.is_normalized
    skip(4) // Quaternion.inverse
    skip(4) // Quaternion.log
    skip(4) // Quaternion.exp
    skip(8) // Quaternion.angle_to
    facade36()
    skip(9) // Quaternion.slerpni
    skip(17) // Quaternion.spherical_cubic_interpolate
    skip(20) // Quaternion.spherical_cubic_interpolate_in_time
    skip(5) // Quaternion.get_euler
    skip(3) // Quaternion.from_euler
    skip(4) // Quaternion.get_axis
    skip(4) // Quaternion.get_angle
    skip(4) // Plane.normalized
    skip(8) // Plane.is_equal_approx
    skip(4) // Plane.is_finite
    skip(12) // Plane.intersect_3
    skip(10) // Plane.intersects_segment
    skip(4) // Rect2.is_finite
    skip(6) // AABB.abs
    skip(6) // AABB.is_finite
    skip(10) // AABB.intersects_plane
    skip(12) // AABB.intersection
    skip(9) // AABB.expand
    skip(7) // AABB.grow
    skip(9) // AABB.get_support
    skip(6) // AABB.get_longest_axis
    skip(6) // AABB.get_longest_axis_index
    skip(6) // AABB.get_longest_axis_size
    skip(6) // AABB.get_shortest_axis
    skip(6) // AABB.get_shortest_axis_index
    skip(6) // AABB.get_shortest_axis_size
    skip(7) // AABB.get_endpoint
    skip(12) // AABB.intersects_segment
    skip(12) // AABB.intersects_ray
    facade66()
    facade67()
    facade68()
    facade69()
    facade70()
    facade71()
    skip(7) // Basis.scaled_local
    facade73()
    skip(5) // Basis.get_euler
    skip(7) // Basis.tdotx
    skip(7) // Basis.tdoty
    skip(7) // Basis.tdotz
    skip(9) // Basis.slerp
    skip(4) // Basis.is_conformal
    skip(4) // Basis.is_finite
    skip(4) // Basis.is_orthonormal
    facade82()
    skip(7) // Basis.looking_at
    skip(3) // Basis.from_scale
    skip(4) // Basis.from_euler
    skip(7) // Transform3D.inverse
    skip(7) // Transform3D.affine_inverse
    facade88()
    skip(11) // Transform3D.rotated
    skip(11) // Transform3D.rotated_local
    skip(10) // Transform3D.scaled
    skip(10) // Transform3D.scaled_local
    skip(14) // Transform3D.looking_at
    skip(15) // Transform3D.interpolate_with
    skip(7) // Transform3D.is_finite
    skip(4) // Transform2D.affine_inverse
    skip(4) // Transform2D.get_rotation
    skip(4) // Transform2D.get_scale
    skip(4) // Transform2D.get_skew
    skip(4) // Transform2D.orthonormalized
    skip(5) // Transform2D.rotated
    skip(5) // Transform2D.rotated_local
    skip(6) // Transform2D.scaled
    skip(6) // Transform2D.scaled_local
    skip(4) // Transform2D.determinant
    skip(9) // Transform2D.interpolate_with
    skip(4) // Transform2D.is_conformal
    skip(4) // Transform2D.is_finite
    skip(6) // Transform2D.looking_at
    skip(1) // Projection.create_depth_correction
    skip(4) // Projection.create_light_atlas_rect
    skip(5) // Projection.create_perspective
    skip(8) // Projection.create_perspective_hmd
    skip(8) // Projection.create_for_hmd
    skip(6) // Projection.create_orthogonal
    skip(5) // Projection.create_orthogonal_aspect
    skip(6) // Projection.create_frustum
    skip(7) // Projection.create_frustum_aspect
    skip(6) // Projection.create_fit_aabb
    skip(16) // Projection.determinant
    skip(17) // Projection.perspective_znear_adjusted
    skip(17) // Projection.get_projection_plane
    skip(16) // Projection.flipped_y
    skip(18) // Projection.jitter_offseted
    skip(2) // Projection.get_fovy
    skip(16) // Projection.get_z_far
    skip(16) // Projection.get_z_near
    skip(16) // Projection.get_aspect
    skip(16) // Projection.get_fov
    skip(16) // Projection.is_orthogonal
    skip(16) // Projection.get_viewport_half_extents
    skip(16) // Projection.get_far_plane_half_extents
    skip(16) // Projection.inverse
    skip(17) // Projection.get_pixels_per_meter
    skip(16) // Projection.get_lod_multiplier
    skip(4) // Color.to_argb32
    skip(4) // Color.to_abgr32
    skip(4) // Color.to_rgba32
    skip(4) // Color.to_argb64
    skip(4) // Color.to_abgr64
    skip(4) // Color.to_rgba64
    skip(5) // Color.lightened
    skip(5) // Color.darkened
    skip(8) // Color.blend
    skip(4) // Color.srgb_to_linear
    skip(4) // Color.linear_to_srgb
    skip(8) // Color.is_equal_approx
    skip(1) // Color.hex
    skip(1) // Color.hex64
    skip(4) // Color.from_string
    skip(4) // Color.from_hsv
    skip(4) // Color.from_ok_hsl
    skip(1) // Color.from_rgbe9995
    skip(4) // Color.from_rgba8
    skip(4) // Vector2i.snapped
    skip(3) // Vector2i.snappedi
    skip(6) // Vector3i.snapped
    skip(4) // Vector3i.snappedi
    skip(8) // Vector4i.snapped
    skip(5) // Vector4i.snappedi
  }

  private fun pure0() {
    val l = Vector2(nv(), nv())
    mix("unary- Vector2", -l)
  }

  private fun pure1() {
    val l = Vector2(nv(), nv())
    mix("unary+ Vector2", +l)
  }

  private fun pure2() {
    val l = Vector2(nv(), nv())
    val r = ri().toLong()
    mix("Vector2 * int", l * r)
  }

  private fun pure3() {
    val l = Vector2(nv(), nv())
    val r = ri().toLong()
    mix("Vector2 / int", l / r)
  }

  private fun pure4() {
    val l = Vector2(nv(), nv())
    val r = nv()
    mix("Vector2 * float", l * r)
  }

  private fun pure5() {
    val l = Vector2(nv(), nv())
    val r = nv()
    mix("Vector2 / float", l / r)
  }

  private fun pure6() {
    val l = Vector2(nv(), nv())
    val r = Vector2(nv(), nv())
    mix("Vector2 < Vector2", l < r)
  }

  private fun pure7() {
    val l = Vector2(nv(), nv())
    val r = Vector2(nv(), nv())
    mix("Vector2 + Vector2", l + r)
  }

  private fun pure8() {
    val l = Vector2(nv(), nv())
    val r = Vector2(nv(), nv())
    mix("Vector2 - Vector2", l - r)
  }

  private fun pure9() {
    val l = Vector2(nv(), nv())
    val r = Vector2(nv(), nv())
    mix("Vector2 * Vector2", l * r)
  }

  private fun pure10() {
    val l = Vector2(nv(), nv())
    val r = Vector2(nv(), nv())
    mix("Vector2 / Vector2", l / r)
  }

  private fun pure11() {
    val l = Vector2(nv(), nv())
    val r = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    mix("Vector2 * Transform2D", l * r)
  }

  private fun pure12() {
    val b = Vector2(nv(), nv())
    val a0 = Vector2(nv(), nv())
    mix("Vector2.direction_to", b.directionTo(a0))
  }

  private fun pure13() {
    val b = Vector2(nv(), nv())
    val a0 = Vector2(nv(), nv())
    mix("Vector2.distance_to", b.distanceTo(a0))
  }

  private fun pure14() {
    val b = Vector2(nv(), nv())
    val a0 = Vector2(nv(), nv())
    mix("Vector2.distance_squared_to", b.distanceSquaredTo(a0))
  }

  private fun pure15() {
    val b = Vector2(nv(), nv())
    mix("Vector2.length", b.length())
  }

  private fun pure16() {
    val b = Vector2(nv(), nv())
    mix("Vector2.length_squared", b.lengthSquared())
  }

  private fun pure17() {
    val b = Vector2(nv(), nv())
    val a0 = nv()
    mix("Vector2.limit_length", b.limitLength(a0))
  }

  private fun pure18() {
    val b = Vector2(nv(), nv())
    mix("Vector2.normalized", b.normalized())
  }

  private fun pure19() {
    val b = Vector2(nv(), nv())
    val a0 = Vector2(nv(), nv())
    mix("Vector2.is_equal_approx", b.isEqualApprox(a0))
  }

  private fun pure20() {
    val b = Vector2(nv(), nv())
    mix("Vector2.is_zero_approx", b.isZeroApprox())
  }

  private fun pure21() {
    val b = Vector2(nv(), nv())
    mix("Vector2.is_finite", b.isFinite())
  }

  private fun pure22() {
    val b = Vector2(nv(), nv())
    val a0 = nv()
    mix("Vector2.posmod", b.posmod(a0))
  }

  private fun pure23() {
    val b = Vector2(nv(), nv())
    val a0 = Vector2(nv(), nv())
    mix("Vector2.posmodv", b.posmodv(a0))
  }

  private fun pure24() {
    val b = Vector2(nv(), nv())
    val a0 = Vector2(nv(), nv())
    mix("Vector2.project", b.project(a0))
  }

  private fun pure25() {
    val b = Vector2(nv(), nv())
    val a0 = Vector2(nv(), nv())
    val a1 = nv()
    mix("Vector2.lerp", b.lerp(a0, a1))
  }

  private fun pure26() {
    val b = Vector2(nv(), nv())
    mix("Vector2.max_axis_index", b.maxAxisIndex())
  }

  private fun pure27() {
    val b = Vector2(nv(), nv())
    mix("Vector2.min_axis_index", b.minAxisIndex())
  }

  private fun pure28() {
    val b = Vector2(nv(), nv())
    val a0 = Vector2(nv(), nv())
    val a1 = nv()
    mix("Vector2.move_toward", b.moveToward(a0, a1))
  }

  private fun pure29() {
    val b = Vector2(nv(), nv())
    mix("Vector2.orthogonal", b.orthogonal())
  }

  private fun pure30() {
    val b = Vector2(nv(), nv())
    mix("Vector2.floor", b.floor())
  }

  private fun pure31() {
    val b = Vector2(nv(), nv())
    mix("Vector2.ceil", b.ceil())
  }

  private fun pure32() {
    val b = Vector2(nv(), nv())
    mix("Vector2.round", b.round())
  }

  private fun pure33() {
    val b = Vector2(nv(), nv())
    mix("Vector2.aspect", b.aspect())
  }

  private fun pure34() {
    val b = Vector2(nv(), nv())
    val a0 = Vector2(nv(), nv())
    mix("Vector2.dot", b.dot(a0))
  }

  private fun pure35() {
    val b = Vector2(nv(), nv())
    val a0 = Vector2(nv(), nv()).normalized()
    mix("Vector2.slide", b.slide(a0))
  }

  private fun pure36() {
    val b = Vector2(nv(), nv())
    val a0 = Vector2(nv(), nv()).normalized()
    mix("Vector2.bounce", b.bounce(a0))
  }

  private fun pure37() {
    val b = Vector2(nv(), nv())
    val a0 = Vector2(nv(), nv()).normalized()
    mix("Vector2.reflect", b.reflect(a0))
  }

  private fun pure38() {
    val b = Vector2(nv(), nv())
    val a0 = Vector2(nv(), nv())
    mix("Vector2.cross", b.cross(a0))
  }

  private fun pure39() {
    val b = Vector2(nv(), nv())
    mix("Vector2.abs", b.abs())
  }

  private fun pure40() {
    val b = Vector2(nv(), nv())
    mix("Vector2.sign", b.sign())
  }

  private fun pure41() {
    val b = Vector2(nv(), nv())
    val a0 = Vector2(nv(), nv())
    val a1 = Vector2(nv(), nv())
    mix("Vector2.clamp", b.clamp(a0, a1))
  }

  private fun pure42() {
    val b = Vector2(nv(), nv())
    val a0 = nv()
    val a1 = nv()
    mix("Vector2.clampf", b.clampf(a0, a1))
  }

  private fun pure43() {
    val b = Vector2(nv(), nv())
    val a0 = Vector2(nv(), nv())
    mix("Vector2.min", b.min(a0))
  }

  private fun pure44() {
    val b = Vector2(nv(), nv())
    val a0 = nv()
    mix("Vector2.minf", b.minf(a0))
  }

  private fun pure45() {
    val b = Vector2(nv(), nv())
    val a0 = Vector2(nv(), nv())
    mix("Vector2.max", b.max(a0))
  }

  private fun pure46() {
    val b = Vector2(nv(), nv())
    val a0 = nv()
    mix("Vector2.maxf", b.maxf(a0))
  }

  private fun pure47() {
    val l = Vector3(nv(), nv(), nv())
    mix("unary- Vector3", -l)
  }

  private fun pure48() {
    val l = Vector3(nv(), nv(), nv())
    mix("unary+ Vector3", +l)
  }

  private fun pure49() {
    val l = Vector3(nv(), nv(), nv())
    val r = ri().toLong()
    mix("Vector3 * int", l * r)
  }

  private fun pure50() {
    val l = Vector3(nv(), nv(), nv())
    val r = ri().toLong()
    mix("Vector3 / int", l / r)
  }

  private fun pure51() {
    val l = Vector3(nv(), nv(), nv())
    val r = nv()
    mix("Vector3 * float", l * r)
  }

  private fun pure52() {
    val l = Vector3(nv(), nv(), nv())
    val r = nv()
    mix("Vector3 / float", l / r)
  }

  private fun pure53() {
    val l = Vector3(nv(), nv(), nv())
    val r = Vector3(nv(), nv(), nv())
    mix("Vector3 < Vector3", l < r)
  }

  private fun pure54() {
    val l = Vector3(nv(), nv(), nv())
    val r = Vector3(nv(), nv(), nv())
    mix("Vector3 + Vector3", l + r)
  }

  private fun pure55() {
    val l = Vector3(nv(), nv(), nv())
    val r = Vector3(nv(), nv(), nv())
    mix("Vector3 - Vector3", l - r)
  }

  private fun pure56() {
    val l = Vector3(nv(), nv(), nv())
    val r = Vector3(nv(), nv(), nv())
    mix("Vector3 * Vector3", l * r)
  }

  private fun pure57() {
    val l = Vector3(nv(), nv(), nv())
    val r = Vector3(nv(), nv(), nv())
    mix("Vector3 / Vector3", l / r)
  }

  private fun pure58() {
    val l = Vector3(nv(), nv(), nv())
    val r = Quaternion(nv(), nv(), nv(), nv()).normalized()
    mix("Vector3 * Quaternion", l * r)
  }

  private fun pure59() {
    val l = Vector3(nv(), nv(), nv())
    val r = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
    mix("Vector3 * Basis", l * r)
  }

  private fun pure60() {
    val l = Vector3(nv(), nv(), nv())
    val r =
      Transform3D(
        Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())),
        Vector3(nv(), nv(), nv()),
      )
    mix("Vector3 * Transform3D", l * r)
  }

  private fun pure61() {
    val b = Vector3(nv(), nv(), nv())
    mix("Vector3.min_axis_index", b.minAxisIndex())
  }

  private fun pure62() {
    val b = Vector3(nv(), nv(), nv())
    mix("Vector3.max_axis_index", b.maxAxisIndex())
  }

  private fun pure63() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    mix("Vector3.direction_to", b.directionTo(a0))
  }

  private fun pure64() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    mix("Vector3.distance_to", b.distanceTo(a0))
  }

  private fun pure65() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    mix("Vector3.distance_squared_to", b.distanceSquaredTo(a0))
  }

  private fun pure66() {
    val b = Vector3(nv(), nv(), nv())
    mix("Vector3.length", b.length())
  }

  private fun pure67() {
    val b = Vector3(nv(), nv(), nv())
    mix("Vector3.length_squared", b.lengthSquared())
  }

  private fun pure68() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = nv()
    mix("Vector3.limit_length", b.limitLength(a0))
  }

  private fun pure69() {
    val b = Vector3(nv(), nv(), nv())
    mix("Vector3.normalized", b.normalized())
  }

  private fun pure70() {
    val b = Vector3(nv(), nv(), nv())
    mix("Vector3.is_normalized", b.isNormalized())
  }

  private fun pure71() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    mix("Vector3.is_equal_approx", b.isEqualApprox(a0))
  }

  private fun pure72() {
    val b = Vector3(nv(), nv(), nv())
    mix("Vector3.is_zero_approx", b.isZeroApprox())
  }

  private fun pure73() {
    val b = Vector3(nv(), nv(), nv())
    mix("Vector3.is_finite", b.isFinite())
  }

  private fun pure74() {
    val b = Vector3(nv(), nv(), nv())
    mix("Vector3.inverse", b.inverse())
  }

  private fun pure75() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    val a1 = Vector3(nv(), nv(), nv())
    mix("Vector3.clamp", b.clamp(a0, a1))
  }

  private fun pure76() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = nv()
    val a1 = nv()
    mix("Vector3.clampf", b.clampf(a0, a1))
  }

  private fun pure77() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    val a1 = nv()
    mix("Vector3.lerp", b.lerp(a0, a1))
  }

  private fun pure78() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    val a1 = nv()
    mix("Vector3.move_toward", b.moveToward(a0, a1))
  }

  private fun pure79() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    mix("Vector3.dot", b.dot(a0))
  }

  private fun pure80() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    mix("Vector3.cross", b.cross(a0))
  }

  private fun pure81() {
    val b = Vector3(nv(), nv(), nv())
    mix("Vector3.abs", b.abs())
  }

  private fun pure82() {
    val b = Vector3(nv(), nv(), nv())
    mix("Vector3.floor", b.floor())
  }

  private fun pure83() {
    val b = Vector3(nv(), nv(), nv())
    mix("Vector3.ceil", b.ceil())
  }

  private fun pure84() {
    val b = Vector3(nv(), nv(), nv())
    mix("Vector3.round", b.round())
  }

  private fun pure85() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = nv()
    mix("Vector3.posmod", b.posmod(a0))
  }

  private fun pure86() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    mix("Vector3.posmodv", b.posmodv(a0))
  }

  private fun pure87() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    mix("Vector3.project", b.project(a0))
  }

  private fun pure88() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = Vector3(nv(), nv(), nv()).normalized()
    mix("Vector3.slide", b.slide(a0))
  }

  private fun pure89() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = Vector3(nv(), nv(), nv()).normalized()
    mix("Vector3.bounce", b.bounce(a0))
  }

  private fun pure90() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = Vector3(nv(), nv(), nv()).normalized()
    mix("Vector3.reflect", b.reflect(a0))
  }

  private fun pure91() {
    val b = Vector3(nv(), nv(), nv())
    mix("Vector3.sign", b.sign())
  }

  private fun pure92() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    mix("Vector3.min", b.min(a0))
  }

  private fun pure93() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = nv()
    mix("Vector3.minf", b.minf(a0))
  }

  private fun pure94() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    mix("Vector3.max", b.max(a0))
  }

  private fun pure95() {
    val b = Vector3(nv(), nv(), nv())
    val a0 = nv()
    mix("Vector3.maxf", b.maxf(a0))
  }

  private fun pure96() {
    val l = Vector4(nv(), nv(), nv(), nv())
    mix("unary- Vector4", -l)
  }

  private fun pure97() {
    val l = Vector4(nv(), nv(), nv(), nv())
    mix("unary+ Vector4", +l)
  }

  private fun pure98() {
    val l = Vector4(nv(), nv(), nv(), nv())
    val r = ri().toLong()
    mix("Vector4 * int", l * r)
  }

  private fun pure99() {
    val l = Vector4(nv(), nv(), nv(), nv())
    val r = ri().toLong()
    mix("Vector4 / int", l / r)
  }

  private fun pure100() {
    val l = Vector4(nv(), nv(), nv(), nv())
    val r = nv()
    mix("Vector4 * float", l * r)
  }

  private fun pure101() {
    val l = Vector4(nv(), nv(), nv(), nv())
    val r = nv()
    mix("Vector4 / float", l / r)
  }

  private fun pure102() {
    val l = Vector4(nv(), nv(), nv(), nv())
    val r = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4 < Vector4", l < r)
  }

  private fun pure103() {
    val l = Vector4(nv(), nv(), nv(), nv())
    val r = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4 + Vector4", l + r)
  }

  private fun pure104() {
    val l = Vector4(nv(), nv(), nv(), nv())
    val r = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4 - Vector4", l - r)
  }

  private fun pure105() {
    val l = Vector4(nv(), nv(), nv(), nv())
    val r = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4 * Vector4", l * r)
  }

  private fun pure106() {
    val l = Vector4(nv(), nv(), nv(), nv())
    val r = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4 / Vector4", l / r)
  }

  private fun pure107() {
    val l = Vector4(nv(), nv(), nv(), nv())
    val r =
      Projection(
        Vector4(nv(), nv(), nv(), nv()),
        Vector4(nv(), nv(), nv(), nv()),
        Vector4(nv(), nv(), nv(), nv()),
        Vector4(nv(), nv(), nv(), nv()),
      )
    mix("Vector4 * Projection", l * r)
  }

  private fun pure108() {
    val b = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.min_axis_index", b.minAxisIndex())
  }

  private fun pure109() {
    val b = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.max_axis_index", b.maxAxisIndex())
  }

  private fun pure110() {
    val b = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.length", b.length())
  }

  private fun pure111() {
    val b = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.length_squared", b.lengthSquared())
  }

  private fun pure112() {
    val b = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.abs", b.abs())
  }

  private fun pure113() {
    val b = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.sign", b.sign())
  }

  private fun pure114() {
    val b = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.floor", b.floor())
  }

  private fun pure115() {
    val b = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.ceil", b.ceil())
  }

  private fun pure116() {
    val b = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.round", b.round())
  }

  private fun pure117() {
    val b = Vector4(nv(), nv(), nv(), nv())
    val a0 = Vector4(nv(), nv(), nv(), nv())
    val a1 = nv()
    mix("Vector4.lerp", b.lerp(a0, a1))
  }

  private fun pure118() {
    val b = Vector4(nv(), nv(), nv(), nv())
    val a0 = nv()
    mix("Vector4.posmod", b.posmod(a0))
  }

  private fun pure119() {
    val b = Vector4(nv(), nv(), nv(), nv())
    val a0 = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.posmodv", b.posmodv(a0))
  }

  private fun pure120() {
    val b = Vector4(nv(), nv(), nv(), nv())
    val a0 = Vector4(nv(), nv(), nv(), nv())
    val a1 = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.clamp", b.clamp(a0, a1))
  }

  private fun pure121() {
    val b = Vector4(nv(), nv(), nv(), nv())
    val a0 = nv()
    val a1 = nv()
    mix("Vector4.clampf", b.clampf(a0, a1))
  }

  private fun pure122() {
    val b = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.normalized", b.normalized())
  }

  private fun pure123() {
    val b = Vector4(nv(), nv(), nv(), nv())
    val a0 = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.direction_to", b.directionTo(a0))
  }

  private fun pure124() {
    val b = Vector4(nv(), nv(), nv(), nv())
    val a0 = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.distance_to", b.distanceTo(a0))
  }

  private fun pure125() {
    val b = Vector4(nv(), nv(), nv(), nv())
    val a0 = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.distance_squared_to", b.distanceSquaredTo(a0))
  }

  private fun pure126() {
    val b = Vector4(nv(), nv(), nv(), nv())
    val a0 = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.dot", b.dot(a0))
  }

  private fun pure127() {
    val b = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.inverse", b.inverse())
  }

  private fun pure128() {
    val b = Vector4(nv(), nv(), nv(), nv())
    val a0 = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.is_equal_approx", b.isEqualApprox(a0))
  }

  private fun pure129() {
    val b = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.is_zero_approx", b.isZeroApprox())
  }

  private fun pure130() {
    val b = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.is_finite", b.isFinite())
  }

  private fun pure131() {
    val b = Vector4(nv(), nv(), nv(), nv())
    val a0 = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.min", b.min(a0))
  }

  private fun pure132() {
    val b = Vector4(nv(), nv(), nv(), nv())
    val a0 = nv()
    mix("Vector4.minf", b.minf(a0))
  }

  private fun pure133() {
    val b = Vector4(nv(), nv(), nv(), nv())
    val a0 = Vector4(nv(), nv(), nv(), nv())
    mix("Vector4.max", b.max(a0))
  }

  private fun pure134() {
    val b = Vector4(nv(), nv(), nv(), nv())
    val a0 = nv()
    mix("Vector4.maxf", b.maxf(a0))
  }

  private fun pure135() {
    val l = Quaternion(nv(), nv(), nv(), nv()).normalized()
    mix("unary- Quaternion", -l)
  }

  private fun pure136() {
    val l = Quaternion(nv(), nv(), nv(), nv()).normalized()
    mix("unary+ Quaternion", +l)
  }

  private fun pure137() {
    val l = Quaternion(nv(), nv(), nv(), nv()).normalized()
    val r = ri().toLong()
    mix("Quaternion * int", l * r)
  }

  private fun pure138() {
    val l = Quaternion(nv(), nv(), nv(), nv()).normalized()
    val r = ri().toLong()
    mix("Quaternion / int", l / r)
  }

  private fun pure139() {
    val l = Quaternion(nv(), nv(), nv(), nv()).normalized()
    val r = nv()
    mix("Quaternion * float", l * r)
  }

  private fun pure140() {
    val l = Quaternion(nv(), nv(), nv(), nv()).normalized()
    val r = nv()
    mix("Quaternion / float", l / r)
  }

  private fun pure141() {
    val l = Quaternion(nv(), nv(), nv(), nv()).normalized()
    val r = Vector3(nv(), nv(), nv())
    mix("Quaternion * Vector3", l * r)
  }

  private fun pure142() {
    val l = Quaternion(nv(), nv(), nv(), nv()).normalized()
    val r = Quaternion(nv(), nv(), nv(), nv()).normalized()
    mix("Quaternion + Quaternion", l + r)
  }

  private fun pure143() {
    val l = Quaternion(nv(), nv(), nv(), nv()).normalized()
    val r = Quaternion(nv(), nv(), nv(), nv()).normalized()
    mix("Quaternion - Quaternion", l - r)
  }

  private fun pure144() {
    val l = Quaternion(nv(), nv(), nv(), nv()).normalized()
    val r = Quaternion(nv(), nv(), nv(), nv()).normalized()
    mix("Quaternion * Quaternion", l * r)
  }

  private fun pure145() {
    val b = Quaternion(nv(), nv(), nv(), nv()).normalized()
    mix("Quaternion.length", b.length())
  }

  private fun pure146() {
    val b = Quaternion(nv(), nv(), nv(), nv()).normalized()
    mix("Quaternion.length_squared", b.lengthSquared())
  }

  private fun pure147() {
    val b = Quaternion(nv(), nv(), nv(), nv()).normalized()
    mix("Quaternion.normalized", b.normalized())
  }

  private fun pure148() {
    val b = Quaternion(nv(), nv(), nv(), nv()).normalized()
    val a0 = Quaternion(nv(), nv(), nv(), nv()).normalized()
    mix("Quaternion.is_equal_approx", b.isEqualApprox(a0))
  }

  private fun pure149() {
    val b = Quaternion(nv(), nv(), nv(), nv()).normalized()
    mix("Quaternion.is_finite", b.isFinite())
  }

  private fun pure150() {
    val b = Quaternion(nv(), nv(), nv(), nv()).normalized()
    val a0 = Quaternion(nv(), nv(), nv(), nv()).normalized()
    mix("Quaternion.dot", b.dot(a0))
  }

  private fun pure151() {
    val l = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
    mix("unary- Plane", -l)
  }

  private fun pure152() {
    val l = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
    mix("unary+ Plane", +l)
  }

  private fun pure154() {
    val b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
    mix("Plane.get_center", b.getCenter())
  }

  private fun pure155() {
    val b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    mix("Plane.is_point_over", b.isPointOver(a0))
  }

  private fun pure156() {
    val b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    mix("Plane.distance_to", b.distanceTo(a0))
  }

  private fun pure157() {
    val b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    val a1 = nv()
    mix("Plane.has_point", b.hasPoint(a0, a1))
  }

  private fun pure158() {
    val b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    mix("Plane.project", b.project(a0))
  }

  private fun pure159() {
    val b = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
    val a0 = Vector3(nv(), nv(), nv())
    val a1 = Vector3(nv(), nv(), nv())
    mix("Plane.intersects_ray", b.intersectsRay(a0, a1))
  }

  private fun pure160() {
    val l = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    val r = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    mix("Rect2 * Transform2D", l * r)
  }

  private fun pure161() {
    val b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    mix("Rect2.get_center", b.getCenter())
  }

  private fun pure162() {
    val b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    mix("Rect2.get_area", b.area())
  }

  private fun pure163() {
    val b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    mix("Rect2.has_area", b.hasArea())
  }

  private fun pure164() {
    val b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    val a0 = Vector2(nv(), nv())
    mix("Rect2.has_point", b.hasPoint(a0))
  }

  private fun pure165() {
    val b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    val a0 = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    mix("Rect2.is_equal_approx", b.isEqualApprox(a0))
  }

  private fun pure166() {
    val b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    val a0 = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    val a1 = rb()
    mix("Rect2.intersects", b.intersects(a0, a1))
  }

  private fun pure167() {
    val b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    val a0 = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    mix("Rect2.encloses", b.encloses(a0))
  }

  private fun pure168() {
    val b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    val a0 = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    mix("Rect2.intersection", b.intersection(a0))
  }

  private fun pure169() {
    val b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    val a0 = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    mix("Rect2.merge", b.merge(a0))
  }

  private fun pure170() {
    val b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    val a0 = Vector2(nv(), nv())
    mix("Rect2.expand", b.expand(a0))
  }

  private fun pure171() {
    val b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    val a0 = Vector2(nv(), nv())
    mix("Rect2.get_support", b.getSupport(a0))
  }

  private fun pure172() {
    val b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    val a0 = nv()
    mix("Rect2.grow", b.grow(a0))
  }

  private fun pure173() {
    val b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    val a0 = rs().toLong()
    val a1 = nv()
    mix("Rect2.grow_side", b.growSide(a0, a1))
  }

  private fun pure174() {
    val b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    val a0 = nv()
    val a1 = nv()
    val a2 = nv()
    val a3 = nv()
    mix("Rect2.grow_individual", b.growIndividual(a0, a1, a2, a3))
  }

  private fun pure175() {
    val b = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    mix("Rect2.abs", b.abs())
  }

  private fun pure176() {
    val l = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
    val r =
      Transform3D(
        Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())),
        Vector3(nv(), nv(), nv()),
      )
    mix("AABB * Transform3D", l * r)
  }

  private fun pure177() {
    val b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
    mix("AABB.get_center", b.getCenter())
  }

  private fun pure178() {
    val b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
    mix("AABB.get_volume", b.volume())
  }

  private fun pure179() {
    val b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
    mix("AABB.has_volume", b.hasVolume())
  }

  private fun pure180() {
    val b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
    mix("AABB.has_surface", b.hasSurface())
  }

  private fun pure181() {
    val b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
    val a0 = Vector3(nv(), nv(), nv())
    mix("AABB.has_point", b.hasPoint(a0))
  }

  private fun pure182() {
    val b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
    val a0 = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
    mix("AABB.is_equal_approx", b.isEqualApprox(a0))
  }

  private fun pure183() {
    val b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
    val a0 = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
    mix("AABB.intersects", b.intersects(a0))
  }

  private fun pure184() {
    val b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
    val a0 = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
    mix("AABB.encloses", b.encloses(a0))
  }

  private fun pure185() {
    val b = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
    val a0 = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
    mix("AABB.merge", b.merge(a0))
  }

  private fun pure186() {
    val l = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
    val r = ri().toLong()
    mix("Basis * int", l * r)
  }

  private fun pure187() {
    val l = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
    val r = ri().toLong()
    mix("Basis / int", l / r)
  }

  private fun pure188() {
    val l = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
    val r = nv()
    mix("Basis * float", l * r)
  }

  private fun pure189() {
    val l = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
    val r = nv()
    mix("Basis / float", l / r)
  }

  private fun pure190() {
    val l = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
    val r = Vector3(nv(), nv(), nv())
    mix("Basis * Vector3", l * r)
  }

  private fun pure191() {
    val l = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
    val r = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
    mix("Basis * Basis", l * r)
  }

  private fun pure192() {
    val b = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
    val a0 = Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
    mix("Basis.is_equal_approx", b.isEqualApprox(a0))
  }

  private fun pure193() {
    val l =
      Transform3D(
        Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())),
        Vector3(nv(), nv(), nv()),
      )
    val r = ri().toLong()
    mix("Transform3D * int", l * r)
  }

  private fun pure194() {
    val l =
      Transform3D(
        Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())),
        Vector3(nv(), nv(), nv()),
      )
    val r = ri().toLong()
    mix("Transform3D / int", l / r)
  }

  private fun pure195() {
    val l =
      Transform3D(
        Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())),
        Vector3(nv(), nv(), nv()),
      )
    val r = nv()
    mix("Transform3D * float", l * r)
  }

  private fun pure196() {
    val l =
      Transform3D(
        Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())),
        Vector3(nv(), nv(), nv()),
      )
    val r = nv()
    mix("Transform3D / float", l / r)
  }

  private fun pure197() {
    val l =
      Transform3D(
        Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())),
        Vector3(nv(), nv(), nv()),
      )
    val r = Vector3(nv(), nv(), nv())
    mix("Transform3D * Vector3", l * r)
  }

  private fun pure198() {
    val l =
      Transform3D(
        Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())),
        Vector3(nv(), nv(), nv()),
      )
    val r = Plane(Vector3(nv(), nv(), nv()).normalized(), nv())
    mix("Transform3D * Plane", l * r)
  }

  private fun pure199() {
    val l =
      Transform3D(
        Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())),
        Vector3(nv(), nv(), nv()),
      )
    val r = AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())
    mix("Transform3D * AABB", l * r)
  }

  private fun pure200() {
    val l =
      Transform3D(
        Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())),
        Vector3(nv(), nv(), nv()),
      )
    val r =
      Transform3D(
        Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())),
        Vector3(nv(), nv(), nv()),
      )
    mix("Transform3D * Transform3D", l * r)
  }

  private fun pure201() {
    val l =
      Transform3D(
        Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())),
        Vector3(nv(), nv(), nv()),
      )
    val r = listOf(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))
    mix("Transform3D * PackedVector3Array", l * r)
  }

  private fun pure202() {
    val b =
      Transform3D(
        Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())),
        Vector3(nv(), nv(), nv()),
      )
    val a0 = Vector3(nv(), nv(), nv())
    mix("Transform3D.translated", b.translated(a0))
  }

  private fun pure203() {
    val b =
      Transform3D(
        Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())),
        Vector3(nv(), nv(), nv()),
      )
    val a0 = Vector3(nv(), nv(), nv())
    mix("Transform3D.translated_local", b.translatedLocal(a0))
  }

  private fun pure204() {
    val b =
      Transform3D(
        Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())),
        Vector3(nv(), nv(), nv()),
      )
    val a0 =
      Transform3D(
        Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())),
        Vector3(nv(), nv(), nv()),
      )
    mix("Transform3D.is_equal_approx", b.isEqualApprox(a0))
  }

  private fun pure205() {
    val l = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    val r = ri().toLong()
    mix("Transform2D * int", l * r)
  }

  private fun pure206() {
    val l = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    val r = ri().toLong()
    mix("Transform2D / int", l / r)
  }

  private fun pure207() {
    val l = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    val r = nv()
    mix("Transform2D * float", l * r)
  }

  private fun pure208() {
    val l = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    val r = nv()
    mix("Transform2D / float", l / r)
  }

  private fun pure209() {
    val l = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    val r = Vector2(nv(), nv())
    mix("Transform2D * Vector2", l * r)
  }

  private fun pure210() {
    val l = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    val r = Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())
    mix("Transform2D * Rect2", l * r)
  }

  private fun pure211() {
    val l = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    val r = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    mix("Transform2D * Transform2D", l * r)
  }

  private fun pure212() {
    val l = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    val r = listOf(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    mix("Transform2D * PackedVector2Array", l * r)
  }

  private fun pure213() {
    val b = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    mix("Transform2D.inverse", b.inverse())
  }

  private fun pure214() {
    val b = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    mix("Transform2D.get_origin", b.origin)
  }

  private fun pure215() {
    val b = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    val a0 = Vector2(nv(), nv())
    mix("Transform2D.translated", b.translated(a0))
  }

  private fun pure216() {
    val b = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    val a0 = Vector2(nv(), nv())
    mix("Transform2D.translated_local", b.translatedLocal(a0))
  }

  private fun pure217() {
    val b = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    val a0 = Vector2(nv(), nv())
    mix("Transform2D.basis_xform", b.basisXform(a0))
  }

  private fun pure218() {
    val b = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    val a0 = Vector2(nv(), nv())
    mix("Transform2D.basis_xform_inv", b.basisXformInv(a0))
  }

  private fun pure219() {
    val b = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    val a0 = Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))
    mix("Transform2D.is_equal_approx", b.isEqualApprox(a0))
  }

  private fun pure220() {
    val l =
      Projection(
        Vector4(nv(), nv(), nv(), nv()),
        Vector4(nv(), nv(), nv(), nv()),
        Vector4(nv(), nv(), nv(), nv()),
        Vector4(nv(), nv(), nv(), nv()),
      )
    val r = Vector4(nv(), nv(), nv(), nv())
    mix("Projection * Vector4", l * r)
  }

  private fun pure221() {
    val l =
      Projection(
        Vector4(nv(), nv(), nv(), nv()),
        Vector4(nv(), nv(), nv(), nv()),
        Vector4(nv(), nv(), nv(), nv()),
        Vector4(nv(), nv(), nv(), nv()),
      )
    val r =
      Projection(
        Vector4(nv(), nv(), nv(), nv()),
        Vector4(nv(), nv(), nv(), nv()),
        Vector4(nv(), nv(), nv(), nv()),
        Vector4(nv(), nv(), nv(), nv()),
      )
    mix("Projection * Projection", l * r)
  }

  private fun pure222() {
    val l = Color(nv(), nv(), nv(), nv())
    mix("unary- Color", -l)
  }

  private fun pure223() {
    val l = Color(nv(), nv(), nv(), nv())
    mix("unary+ Color", +l)
  }

  private fun pure224() {
    val l = Color(nv(), nv(), nv(), nv())
    val r = ri().toLong()
    mix("Color * int", l * r)
  }

  private fun pure225() {
    val l = Color(nv(), nv(), nv(), nv())
    val r = ri().toLong()
    mix("Color / int", l / r)
  }

  private fun pure226() {
    val l = Color(nv(), nv(), nv(), nv())
    val r = nv()
    mix("Color * float", l * r)
  }

  private fun pure227() {
    val l = Color(nv(), nv(), nv(), nv())
    val r = nv()
    mix("Color / float", l / r)
  }

  private fun pure228() {
    val l = Color(nv(), nv(), nv(), nv())
    val r = Color(nv(), nv(), nv(), nv())
    mix("Color + Color", l + r)
  }

  private fun pure229() {
    val l = Color(nv(), nv(), nv(), nv())
    val r = Color(nv(), nv(), nv(), nv())
    mix("Color - Color", l - r)
  }

  private fun pure230() {
    val l = Color(nv(), nv(), nv(), nv())
    val r = Color(nv(), nv(), nv(), nv())
    mix("Color * Color", l * r)
  }

  private fun pure231() {
    val l = Color(nv(), nv(), nv(), nv())
    val r = Color(nv(), nv(), nv(), nv())
    mix("Color / Color", l / r)
  }

  private fun pure232() {
    val b = Color(nv(), nv(), nv(), nv())
    val a0 = rb()
    mix("Color.to_html", b.toHtml(a0))
  }

  private fun pure233() {
    val b = Color(nv(), nv(), nv(), nv())
    val a0 = Color(nv(), nv(), nv(), nv())
    val a1 = Color(nv(), nv(), nv(), nv())
    mix("Color.clamp", b.clamp(a0, a1))
  }

  private fun pure234() {
    val b = Color(nv(), nv(), nv(), nv())
    mix("Color.inverted", b.inverted())
  }

  private fun pure235() {
    val b = Color(nv(), nv(), nv(), nv())
    val a0 = Color(nv(), nv(), nv(), nv())
    val a1 = nv()
    mix("Color.lerp", b.lerp(a0, a1))
  }

  private fun pure236() {
    val b = Color(nv(), nv(), nv(), nv())
    mix("Color.get_luminance", b.getLuminance())
  }

  private fun pure237() {
    val l = Vector2i(ri(), ri())
    mix("unary- Vector2i", -l)
  }

  private fun pure238() {
    val l = Vector2i(ri(), ri())
    mix("unary+ Vector2i", +l)
  }

  private fun pure239() {
    val l = Vector2i(ri(), ri())
    val r = ri().toLong()
    mix("Vector2i * int", l * r)
  }

  private fun pure240() {
    val l = Vector2i(ri(), ri())
    val r = rnz().toLong()
    mix("Vector2i / int", l / r)
  }

  private fun pure241() {
    val l = Vector2i(ri(), ri())
    val r = rnz().toLong()
    mix("Vector2i % int", l % r)
  }

  private fun pure242() {
    val l = Vector2i(ri(), ri())
    val r = nv()
    mix("Vector2i * float", l * r)
  }

  private fun pure243() {
    val l = Vector2i(ri(), ri())
    val r = nv()
    mix("Vector2i / float", l / r)
  }

  private fun pure244() {
    val l = Vector2i(ri(), ri())
    val r = Vector2i(ri(), ri())
    mix("Vector2i < Vector2i", l < r)
  }

  private fun pure245() {
    val l = Vector2i(ri(), ri())
    val r = Vector2i(ri(), ri())
    mix("Vector2i + Vector2i", l + r)
  }

  private fun pure246() {
    val l = Vector2i(ri(), ri())
    val r = Vector2i(ri(), ri())
    mix("Vector2i - Vector2i", l - r)
  }

  private fun pure247() {
    val l = Vector2i(ri(), ri())
    val r = Vector2i(ri(), ri())
    mix("Vector2i * Vector2i", l * r)
  }

  private fun pure248() {
    val l = Vector2i(ri(), ri())
    val r = Vector2i(rnz(), rnz())
    mix("Vector2i / Vector2i", l / r)
  }

  private fun pure249() {
    val l = Vector2i(ri(), ri())
    val r = Vector2i(rnz(), rnz())
    mix("Vector2i % Vector2i", l % r)
  }

  private fun pure250() {
    val b = Vector2i(ri(), ri())
    mix("Vector2i.aspect", b.aspect())
  }

  private fun pure251() {
    val b = Vector2i(ri(), ri())
    mix("Vector2i.max_axis_index", b.maxAxisIndex())
  }

  private fun pure252() {
    val b = Vector2i(ri(), ri())
    mix("Vector2i.min_axis_index", b.minAxisIndex())
  }

  private fun pure253() {
    val b = Vector2i(ri(), ri())
    val a0 = Vector2i(ri(), ri())
    mix("Vector2i.distance_to", b.distanceTo(a0))
  }

  private fun pure254() {
    val b = Vector2i(ri(), ri())
    val a0 = Vector2i(ri(), ri())
    mix("Vector2i.distance_squared_to", b.distanceSquaredTo(a0))
  }

  private fun pure255() {
    val b = Vector2i(ri(), ri())
    mix("Vector2i.length", b.length())
  }

  private fun pure256() {
    val b = Vector2i(ri(), ri())
    mix("Vector2i.length_squared", b.lengthSquared())
  }

  private fun pure257() {
    val b = Vector2i(ri(), ri())
    mix("Vector2i.sign", b.sign())
  }

  private fun pure258() {
    val b = Vector2i(ri(), ri())
    mix("Vector2i.abs", b.abs())
  }

  private fun pure259() {
    val b = Vector2i(ri(), ri())
    val a0 = Vector2i(ri(), ri())
    val a1 = Vector2i(ri(), ri())
    mix("Vector2i.clamp", b.clamp(a0, a1))
  }

  private fun pure260() {
    val b = Vector2i(ri(), ri())
    val a0 = ri().toLong()
    val a1 = ri().toLong()
    mix("Vector2i.clampi", b.clampi(a0, a1))
  }

  private fun pure261() {
    val b = Vector2i(ri(), ri())
    val a0 = Vector2i(ri(), ri())
    mix("Vector2i.min", b.min(a0))
  }

  private fun pure262() {
    val b = Vector2i(ri(), ri())
    val a0 = ri().toLong()
    mix("Vector2i.mini", b.mini(a0))
  }

  private fun pure263() {
    val b = Vector2i(ri(), ri())
    val a0 = Vector2i(ri(), ri())
    mix("Vector2i.max", b.max(a0))
  }

  private fun pure264() {
    val b = Vector2i(ri(), ri())
    val a0 = ri().toLong()
    mix("Vector2i.maxi", b.maxi(a0))
  }

  private fun pure265() {
    val l = Vector3i(ri(), ri(), ri())
    mix("unary- Vector3i", -l)
  }

  private fun pure266() {
    val l = Vector3i(ri(), ri(), ri())
    mix("unary+ Vector3i", +l)
  }

  private fun pure267() {
    val l = Vector3i(ri(), ri(), ri())
    val r = ri().toLong()
    mix("Vector3i * int", l * r)
  }

  private fun pure268() {
    val l = Vector3i(ri(), ri(), ri())
    val r = rnz().toLong()
    mix("Vector3i / int", l / r)
  }

  private fun pure269() {
    val l = Vector3i(ri(), ri(), ri())
    val r = rnz().toLong()
    mix("Vector3i % int", l % r)
  }

  private fun pure270() {
    val l = Vector3i(ri(), ri(), ri())
    val r = nv()
    mix("Vector3i * float", l * r)
  }

  private fun pure271() {
    val l = Vector3i(ri(), ri(), ri())
    val r = nv()
    mix("Vector3i / float", l / r)
  }

  private fun pure272() {
    val l = Vector3i(ri(), ri(), ri())
    val r = Vector3i(ri(), ri(), ri())
    mix("Vector3i < Vector3i", l < r)
  }

  private fun pure273() {
    val l = Vector3i(ri(), ri(), ri())
    val r = Vector3i(ri(), ri(), ri())
    mix("Vector3i + Vector3i", l + r)
  }

  private fun pure274() {
    val l = Vector3i(ri(), ri(), ri())
    val r = Vector3i(ri(), ri(), ri())
    mix("Vector3i - Vector3i", l - r)
  }

  private fun pure275() {
    val l = Vector3i(ri(), ri(), ri())
    val r = Vector3i(ri(), ri(), ri())
    mix("Vector3i * Vector3i", l * r)
  }

  private fun pure276() {
    val l = Vector3i(ri(), ri(), ri())
    val r = Vector3i(rnz(), rnz(), rnz())
    mix("Vector3i / Vector3i", l / r)
  }

  private fun pure277() {
    val l = Vector3i(ri(), ri(), ri())
    val r = Vector3i(rnz(), rnz(), rnz())
    mix("Vector3i % Vector3i", l % r)
  }

  private fun pure278() {
    val b = Vector3i(ri(), ri(), ri())
    mix("Vector3i.min_axis_index", b.minAxisIndex())
  }

  private fun pure279() {
    val b = Vector3i(ri(), ri(), ri())
    mix("Vector3i.max_axis_index", b.maxAxisIndex())
  }

  private fun pure280() {
    val b = Vector3i(ri(), ri(), ri())
    val a0 = Vector3i(ri(), ri(), ri())
    mix("Vector3i.distance_to", b.distanceTo(a0))
  }

  private fun pure281() {
    val b = Vector3i(ri(), ri(), ri())
    val a0 = Vector3i(ri(), ri(), ri())
    mix("Vector3i.distance_squared_to", b.distanceSquaredTo(a0))
  }

  private fun pure282() {
    val b = Vector3i(ri(), ri(), ri())
    mix("Vector3i.length", b.length())
  }

  private fun pure283() {
    val b = Vector3i(ri(), ri(), ri())
    mix("Vector3i.length_squared", b.lengthSquared())
  }

  private fun pure284() {
    val b = Vector3i(ri(), ri(), ri())
    mix("Vector3i.sign", b.sign())
  }

  private fun pure285() {
    val b = Vector3i(ri(), ri(), ri())
    mix("Vector3i.abs", b.abs())
  }

  private fun pure286() {
    val b = Vector3i(ri(), ri(), ri())
    val a0 = Vector3i(ri(), ri(), ri())
    val a1 = Vector3i(ri(), ri(), ri())
    mix("Vector3i.clamp", b.clamp(a0, a1))
  }

  private fun pure287() {
    val b = Vector3i(ri(), ri(), ri())
    val a0 = ri().toLong()
    val a1 = ri().toLong()
    mix("Vector3i.clampi", b.clampi(a0, a1))
  }

  private fun pure288() {
    val b = Vector3i(ri(), ri(), ri())
    val a0 = Vector3i(ri(), ri(), ri())
    mix("Vector3i.min", b.min(a0))
  }

  private fun pure289() {
    val b = Vector3i(ri(), ri(), ri())
    val a0 = ri().toLong()
    mix("Vector3i.mini", b.mini(a0))
  }

  private fun pure290() {
    val b = Vector3i(ri(), ri(), ri())
    val a0 = Vector3i(ri(), ri(), ri())
    mix("Vector3i.max", b.max(a0))
  }

  private fun pure291() {
    val b = Vector3i(ri(), ri(), ri())
    val a0 = ri().toLong()
    mix("Vector3i.maxi", b.maxi(a0))
  }

  private fun pure292() {
    val l = Vector4i(ri(), ri(), ri(), ri())
    mix("unary- Vector4i", -l)
  }

  private fun pure293() {
    val l = Vector4i(ri(), ri(), ri(), ri())
    mix("unary+ Vector4i", +l)
  }

  private fun pure294() {
    val l = Vector4i(ri(), ri(), ri(), ri())
    val r = ri().toLong()
    mix("Vector4i * int", l * r)
  }

  private fun pure295() {
    val l = Vector4i(ri(), ri(), ri(), ri())
    val r = rnz().toLong()
    mix("Vector4i / int", l / r)
  }

  private fun pure296() {
    val l = Vector4i(ri(), ri(), ri(), ri())
    val r = rnz().toLong()
    mix("Vector4i % int", l % r)
  }

  private fun pure297() {
    val l = Vector4i(ri(), ri(), ri(), ri())
    val r = nv()
    mix("Vector4i * float", l * r)
  }

  private fun pure298() {
    val l = Vector4i(ri(), ri(), ri(), ri())
    val r = nv()
    mix("Vector4i / float", l / r)
  }

  private fun pure299() {
    val l = Vector4i(ri(), ri(), ri(), ri())
    val r = Vector4i(ri(), ri(), ri(), ri())
    mix("Vector4i < Vector4i", l < r)
  }

  private fun pure300() {
    val l = Vector4i(ri(), ri(), ri(), ri())
    val r = Vector4i(ri(), ri(), ri(), ri())
    mix("Vector4i + Vector4i", l + r)
  }

  private fun pure301() {
    val l = Vector4i(ri(), ri(), ri(), ri())
    val r = Vector4i(ri(), ri(), ri(), ri())
    mix("Vector4i - Vector4i", l - r)
  }

  private fun pure302() {
    val l = Vector4i(ri(), ri(), ri(), ri())
    val r = Vector4i(ri(), ri(), ri(), ri())
    mix("Vector4i * Vector4i", l * r)
  }

  private fun pure303() {
    val l = Vector4i(ri(), ri(), ri(), ri())
    val r = Vector4i(rnz(), rnz(), rnz(), rnz())
    mix("Vector4i / Vector4i", l / r)
  }

  private fun pure304() {
    val l = Vector4i(ri(), ri(), ri(), ri())
    val r = Vector4i(rnz(), rnz(), rnz(), rnz())
    mix("Vector4i % Vector4i", l % r)
  }

  private fun pure305() {
    val b = Vector4i(ri(), ri(), ri(), ri())
    mix("Vector4i.min_axis_index", b.minAxisIndex())
  }

  private fun pure306() {
    val b = Vector4i(ri(), ri(), ri(), ri())
    mix("Vector4i.max_axis_index", b.maxAxisIndex())
  }

  private fun pure307() {
    val b = Vector4i(ri(), ri(), ri(), ri())
    mix("Vector4i.length", b.length())
  }

  private fun pure308() {
    val b = Vector4i(ri(), ri(), ri(), ri())
    mix("Vector4i.length_squared", b.lengthSquared())
  }

  private fun pure309() {
    val b = Vector4i(ri(), ri(), ri(), ri())
    mix("Vector4i.sign", b.sign())
  }

  private fun pure310() {
    val b = Vector4i(ri(), ri(), ri(), ri())
    mix("Vector4i.abs", b.abs())
  }

  private fun pure311() {
    val b = Vector4i(ri(), ri(), ri(), ri())
    val a0 = Vector4i(ri(), ri(), ri(), ri())
    val a1 = Vector4i(ri(), ri(), ri(), ri())
    mix("Vector4i.clamp", b.clamp(a0, a1))
  }

  private fun pure312() {
    val b = Vector4i(ri(), ri(), ri(), ri())
    val a0 = ri().toLong()
    val a1 = ri().toLong()
    mix("Vector4i.clampi", b.clampi(a0, a1))
  }

  private fun pure313() {
    val b = Vector4i(ri(), ri(), ri(), ri())
    val a0 = Vector4i(ri(), ri(), ri(), ri())
    mix("Vector4i.min", b.min(a0))
  }

  private fun pure314() {
    val b = Vector4i(ri(), ri(), ri(), ri())
    val a0 = ri().toLong()
    mix("Vector4i.mini", b.mini(a0))
  }

  private fun pure315() {
    val b = Vector4i(ri(), ri(), ri(), ri())
    val a0 = Vector4i(ri(), ri(), ri(), ri())
    mix("Vector4i.max", b.max(a0))
  }

  private fun pure316() {
    val b = Vector4i(ri(), ri(), ri(), ri())
    val a0 = ri().toLong()
    mix("Vector4i.maxi", b.maxi(a0))
  }

  private fun pure317() {
    val b = Vector4i(ri(), ri(), ri(), ri())
    val a0 = Vector4i(ri(), ri(), ri(), ri())
    mix("Vector4i.distance_to", b.distanceTo(a0))
  }

  private fun pure318() {
    val b = Vector4i(ri(), ri(), ri(), ri())
    val a0 = Vector4i(ri(), ri(), ri(), ri())
    mix("Vector4i.distance_squared_to", b.distanceSquaredTo(a0))
  }

  private fun pure319() {
    val b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    mix("Rect2i.get_center", b.getCenter())
  }

  private fun pure320() {
    val b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    mix("Rect2i.get_area", b.area())
  }

  private fun pure321() {
    val b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    mix("Rect2i.has_area", b.hasArea())
  }

  private fun pure322() {
    val b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    val a0 = Vector2i(ri(), ri())
    mix("Rect2i.has_point", b.hasPoint(a0))
  }

  private fun pure323() {
    val b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    val a0 = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    mix("Rect2i.intersects", b.intersects(a0))
  }

  private fun pure324() {
    val b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    val a0 = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    mix("Rect2i.encloses", b.encloses(a0))
  }

  private fun pure325() {
    val b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    val a0 = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    mix("Rect2i.intersection", b.intersection(a0))
  }

  private fun pure326() {
    val b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    val a0 = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    mix("Rect2i.merge", b.merge(a0))
  }

  private fun pure327() {
    val b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    val a0 = Vector2i(ri(), ri())
    mix("Rect2i.expand", b.expand(a0))
  }

  private fun pure328() {
    val b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    val a0 = ri().toLong()
    mix("Rect2i.grow", b.grow(a0))
  }

  private fun pure329() {
    val b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    val a0 = rs().toLong()
    val a1 = ri().toLong()
    mix("Rect2i.grow_side", b.growSide(a0, a1))
  }

  private fun pure330() {
    val b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    val a0 = ri().toLong()
    val a1 = ri().toLong()
    val a2 = ri().toLong()
    val a3 = ri().toLong()
    mix("Rect2i.grow_individual", b.growIndividual(a0, a1, a2, a3))
  }

  private fun pure331() {
    val b = Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())
    mix("Rect2i.abs", b.abs())
  }

  private fun pure332() {
    val l = RID(rl())
    val r = RID(rl())
    mix("RID < RID", l < r)
  }

  private fun pure333() {
    val b = RID(rl())
    mix("RID.is_valid", b.isValid())
  }

  private fun pure334() {
    val b = RID(rl())
    mix("RID.get_id", b.getId())
  }

  private fun facade0() {
    val b = Vector2(nv(), nv()).normalized()
    mix("Vector2.angle", b.angle())
  }

  private fun facade9() {
    val b = Vector2(nv(), nv()).normalized()
    val a0 = nv()
    mix("Vector2.rotated", b.rotated(a0))
  }

  private fun facade14() {
    val b = Vector3(nv(), nv(), nv()).normalized()
    val a0 = Vector3(nv(), nv(), nv()).normalized()
    val a1 = Vector3(nv(), nv(), nv()).normalized()
    mix("Vector3.signed_angle_to", b.signedAngleTo(a0, a1))
  }

  private fun facade17() {
    val b = Vector3(nv(), nv(), nv()).normalized()
    val a0 = Vector3(nv(), nv(), nv()).normalized()
    val a1 = nv()
    mix("Vector3.rotated", b.rotated(a0, a1))
  }

  private fun facade36() {
    val b = Quaternion(nv(), nv(), nv(), nv()).normalized()
    val a0 = Quaternion(nv(), nv(), nv(), nv()).normalized()
    val a1 = nv()
    mix("Quaternion.slerp", b.slerp(a0, a1))
  }

  private fun facade66() {
    val b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
    mix("Basis.inverse", b.inverse())
  }

  private fun facade67() {
    val b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
    mix("Basis.transposed", b.transposed())
  }

  private fun facade68() {
    val b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
    mix("Basis.orthonormalized", b.orthonormalized())
  }

  private fun facade69() {
    val b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
    mix("Basis.determinant", b.determinant())
  }

  private fun facade70() {
    val b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
    val a0 = Vector3(nv(), nv(), nv()).normalized()
    val a1 = nv()
    mix("Basis.rotated", b.rotated(a0, a1))
  }

  private fun facade71() {
    val b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
    val a0 = Vector3(nv(), nv(), nv()).normalized()
    mix("Basis.scaled", b.scaled(a0))
  }

  private fun facade73() {
    val b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
    mix("Basis.get_scale", b.getScale())
  }

  private fun facade82() {
    val b = Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())
    mix("Basis.get_rotation_quaternion", b.getRotationQuaternion())
  }

  private fun facade88() {
    val b =
      Transform3D(Basis(Quaternion(nv(), nv(), nv(), nv()).normalized()), Vector3(nv(), nv(), nv()))
    mix("Transform3D.orthonormalized", b.orthonormalized())
  }

  private var seed = 2463534242L

  private fun nextRandom(): Long {
    seed = seed xor ((seed shl 13) and 0xFFFFFFFFL)
    seed = seed xor (seed ushr 17)
    seed = seed xor ((seed shl 5) and 0xFFFFFFFFL)
    return seed
  }

  private fun skip(draws: Int) = repeat(draws) { nextRandom() }

  private fun nv(): Double {
    val r = nextRandom()
    return ((r % 200001) - 100000) / 10000.0 * SCALES[((r ushr 24) % 7).toInt()]
  }

  private fun ri(): Int = ((nextRandom() % 60001) - 30000).toInt()

  private fun rnz(): Int = ri().let { if (it == 0) 1 else it }

  private fun rs(): Int = (nextRandom() % 6).toInt()

  private fun rl(): Long = nextRandom()

  private fun rb(): Boolean = (nextRandom() and 1L) == 1L

  private fun rotation2D(x: Vector2, origin: Vector2): Transform2D =
    Transform2D(x, x.orthogonal(), origin)

  private val hashes = linkedMapOf<String, Long>()

  private fun mixLong(name: String, value: Long) {
    for (bits in longArrayOf(value and 0xFFFFFFFFL, (value ushr 32) and 0xFFFFFFFFL)) {
      hashes[name] = ((hashes[name] ?: 2166136261L) xor bits) * 16777619L and 0xFFFFFFFFL
    }
  }

  private fun mix(key: String, value: Any?) {
    val name = key.replace(' ', '_')
    when (value) {
      null -> mixLong(name, -1L)
      is Double -> mixLong(name, if (value.isNaN()) 0x7FF8000000000000L else value.toRawBits())
      is Long -> mixLong(name, value)
      is Int -> mixLong(name, value.toLong())
      is Boolean -> mixLong(name, if (value) 1L else 0L)
      is String -> value.forEach { mixLong(name, it.code.toLong()) }
      is RID -> mixLong(name, value.value)
      is Vector2 -> listOf(value.x, value.y).forEach { mix(key, it) }
      is Vector3 -> listOf(value.x, value.y, value.z).forEach { mix(key, it) }
      is Vector4 -> listOf(value.x, value.y, value.z, value.w).forEach { mix(key, it) }
      is Quaternion -> listOf(value.x, value.y, value.z, value.w).forEach { mix(key, it) }
      is Color -> listOf(value.r, value.g, value.b, value.a).forEach { mix(key, it) }
      is Vector2i -> listOf(value.x, value.y).forEach { mix(key, it) }
      is Vector3i -> listOf(value.x, value.y, value.z).forEach { mix(key, it) }
      is Vector4i -> listOf(value.x, value.y, value.z, value.w).forEach { mix(key, it) }
      is Rect2 -> listOf(value.position, value.size).forEach { mix(key, it) }
      is Rect2i -> listOf(value.position, value.size).forEach { mix(key, it) }
      is AABB -> listOf(value.position, value.size).forEach { mix(key, it) }
      is Plane -> listOf(value.normal, value.d).forEach { mix(key, it) }
      is Basis -> listOf(value.x, value.y, value.z).forEach { mix(key, it) }
      is Transform2D -> listOf(value.x, value.y, value.origin).forEach { mix(key, it) }
      is Transform3D -> listOf(value.basis, value.origin).forEach { mix(key, it) }
      is Projection -> listOf(value.x, value.y, value.z, value.w).forEach { mix(key, it) }
      is List<*> -> value.forEach { mix(key, it) }
      else -> error("no parity mix for ${value::class}")
    }
  }

  private companion object {
    val SCALES = doubleArrayOf(0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0)

    // Godot 4.7.2's hashes for the entries above (scripts/fixtures/builtin_parity_expected.json).
    val EXPECTED =
      mapOf(
        "unary-_Vector2" to "bff51eac",
        "unary+_Vector2" to "87182468",
        "Vector2_*_int" to "cc17162f",
        "Vector2_/_int" to "d9734e0f",
        "Vector2_*_float" to "6c7f20fd",
        "Vector2_/_float" to "e9f8055d",
        "Vector2_<_Vector2" to "32ae5bbd",
        "Vector2_+_Vector2" to "d4778dcd",
        "Vector2_-_Vector2" to "864e752a",
        "Vector2_*_Vector2" to "bc095606",
        "Vector2_/_Vector2" to "4913758e",
        "Vector2_*_Transform2D" to "5b4c5617",
        "Vector2.direction_to" to "6df4c227",
        "Vector2.distance_to" to "f07e6121",
        "Vector2.distance_squared_to" to "d0a4436",
        "Vector2.length" to "7d4b04cb",
        "Vector2.length_squared" to "b357f941",
        "Vector2.limit_length" to "376d98eb",
        "Vector2.normalized" to "f3c21c70",
        "Vector2.is_equal_approx" to "4d7705c5",
        "Vector2.is_zero_approx" to "4d7705c5",
        "Vector2.is_finite" to "256151c5",
        "Vector2.posmod" to "afb0d439",
        "Vector2.posmodv" to "2086f53d",
        "Vector2.project" to "f8ca937c",
        "Vector2.lerp" to "51971dbd",
        "Vector2.max_axis_index" to "2dc7c3e5",
        "Vector2.min_axis_index" to "ec6a4025",
        "Vector2.move_toward" to "623e1912",
        "Vector2.orthogonal" to "30a7bc88",
        "Vector2.floor" to "679042c5",
        "Vector2.ceil" to "39c78145",
        "Vector2.round" to "1f6e6dc5",
        "Vector2.aspect" to "36a24e21",
        "Vector2.dot" to "58fc6b40",
        "Vector2.slide" to "6a910763",
        "Vector2.bounce" to "169f22e",
        "Vector2.reflect" to "5db40213",
        "Vector2.cross" to "7de0b2c9",
        "Vector2.abs" to "1b6b94bb",
        "Vector2.sign" to "29316dc5",
        "Vector2.clamp" to "6641f183",
        "Vector2.clampf" to "c3d31a96",
        "Vector2.min" to "766ce2a3",
        "Vector2.minf" to "4ee2b1a1",
        "Vector2.max" to "55a9eb08",
        "Vector2.maxf" to "26ace4a9",
        "unary-_Vector3" to "86035a3c",
        "unary+_Vector3" to "f9132143",
        "Vector3_*_int" to "e9687953",
        "Vector3_/_int" to "273d60ee",
        "Vector3_*_float" to "dc490226",
        "Vector3_/_float" to "6b50ad2a",
        "Vector3_<_Vector3" to "24f4325d",
        "Vector3_+_Vector3" to "7b6be503",
        "Vector3_-_Vector3" to "d67229b9",
        "Vector3_*_Vector3" to "20c9e5da",
        "Vector3_/_Vector3" to "bccb0238",
        "Vector3_*_Quaternion" to "cd0266c4",
        "Vector3_*_Basis" to "9992a641",
        "Vector3_*_Transform3D" to "49c8e3bb",
        "Vector3.min_axis_index" to "a4116c2f",
        "Vector3.max_axis_index" to "a4089404",
        "Vector3.direction_to" to "a51430f9",
        "Vector3.distance_to" to "b9b45f8f",
        "Vector3.distance_squared_to" to "591c172",
        "Vector3.length" to "52d0848e",
        "Vector3.length_squared" to "a10ea00c",
        "Vector3.limit_length" to "3fbc831c",
        "Vector3.normalized" to "49ef98c3",
        "Vector3.is_normalized" to "4d7705c5",
        "Vector3.is_equal_approx" to "4d7705c5",
        "Vector3.is_zero_approx" to "4d7705c5",
        "Vector3.is_finite" to "256151c5",
        "Vector3.inverse" to "328dc7de",
        "Vector3.clamp" to "39107bce",
        "Vector3.clampf" to "b01caf17",
        "Vector3.lerp" to "d2cb72ab",
        "Vector3.move_toward" to "82c427a5",
        "Vector3.dot" to "fbc1cc35",
        "Vector3.cross" to "7a881afe",
        "Vector3.abs" to "49182d2a",
        "Vector3.floor" to "659445",
        "Vector3.ceil" to "2c0dc9c5",
        "Vector3.round" to "f538b145",
        "Vector3.posmod" to "c85f1d46",
        "Vector3.posmodv" to "577ef991",
        "Vector3.project" to "6420579c",
        "Vector3.slide" to "bd8338c1",
        "Vector3.bounce" to "62d5a53e",
        "Vector3.reflect" to "f8a53c47",
        "Vector3.sign" to "146bd5c5",
        "Vector3.min" to "6bac2da1",
        "Vector3.minf" to "6c32a94",
        "Vector3.max" to "42175725",
        "Vector3.maxf" to "2ddc6cb0",
        "unary-_Vector4" to "2dbfae70",
        "unary+_Vector4" to "c05dc25e",
        "Vector4_*_int" to "1668ca5e",
        "Vector4_/_int" to "ba37bbed",
        "Vector4_*_float" to "c50e3d09",
        "Vector4_/_float" to "fdc820de",
        "Vector4_<_Vector4" to "cac71605",
        "Vector4_+_Vector4" to "967a557c",
        "Vector4_-_Vector4" to "4b0eadd",
        "Vector4_*_Vector4" to "3b58a3a7",
        "Vector4_/_Vector4" to "90215c3",
        "Vector4_*_Projection" to "c5cd9a67",
        "Vector4.min_axis_index" to "76810f55",
        "Vector4.max_axis_index" to "1378d206",
        "Vector4.length" to "56718cdd",
        "Vector4.length_squared" to "4298341b",
        "Vector4.abs" to "b82daf9c",
        "Vector4.sign" to "cfa63dc5",
        "Vector4.floor" to "9c41c5",
        "Vector4.ceil" to "f95bfdc5",
        "Vector4.round" to "5077ea45",
        "Vector4.lerp" to "a9746a44",
        "Vector4.posmod" to "9e64aee",
        "Vector4.posmodv" to "7d9e3e0a",
        "Vector4.clamp" to "d92b64ab",
        "Vector4.clampf" to "d99b73d1",
        "Vector4.normalized" to "89910005",
        "Vector4.direction_to" to "26573237",
        "Vector4.distance_to" to "2087a5f0",
        "Vector4.distance_squared_to" to "c1ea7923",
        "Vector4.dot" to "5e6a4866",
        "Vector4.inverse" to "a3e5e258",
        "Vector4.is_equal_approx" to "4d7705c5",
        "Vector4.is_zero_approx" to "4d7705c5",
        "Vector4.is_finite" to "256151c5",
        "Vector4.min" to "7d73869b",
        "Vector4.minf" to "7afba5b7",
        "Vector4.max" to "18e14153",
        "Vector4.maxf" to "6d261d75",
        "unary-_Quaternion" to "5cf2427a",
        "unary+_Quaternion" to "2dba9b98",
        "Quaternion_*_int" to "501f87da",
        "Quaternion_/_int" to "124f3884",
        "Quaternion_*_float" to "2396c3a4",
        "Quaternion_/_float" to "8580a26b",
        "Quaternion_*_Vector3" to "6ce76fde",
        "Quaternion_+_Quaternion" to "bf5d1929",
        "Quaternion_-_Quaternion" to "5a0d5afc",
        "Quaternion_*_Quaternion" to "a5234f86",
        "Quaternion.length" to "445d9f95",
        "Quaternion.length_squared" to "e11e2f90",
        "Quaternion.normalized" to "f68bd34b",
        "Quaternion.is_equal_approx" to "4d7705c5",
        "Quaternion.is_finite" to "256151c5",
        "Quaternion.dot" to "a877e0c7",
        "unary-_Plane" to "1ad24f1",
        "unary+_Plane" to "fe28113e",
        "Plane.get_center" to "fa4f1ad2",
        "Plane.is_point_over" to "b3adceed",
        "Plane.distance_to" to "b63646d1",
        "Plane.has_point" to "339f6114",
        "Plane.project" to "e68ab864",
        "Plane.intersects_ray" to "15fe3e6c",
        "Rect2_*_Transform2D" to "137375ea",
        "Rect2.get_center" to "d60a2dad",
        "Rect2.get_area" to "87c4e353",
        "Rect2.has_area" to "256151c5",
        "Rect2.has_point" to "d274c294",
        "Rect2.is_equal_approx" to "4d7705c5",
        "Rect2.intersects" to "d65e5fdd",
        "Rect2.encloses" to "90c15f55",
        "Rect2.intersection" to "f799287e",
        "Rect2.merge" to "908b8fef",
        "Rect2.expand" to "7f8ad23e",
        "Rect2.get_support" to "139e85a1",
        "Rect2.grow" to "dc452272",
        "Rect2.grow_side" to "cc1b164d",
        "Rect2.grow_individual" to "afb25a8f",
        "Rect2.abs" to "42315ff3",
        "AABB_*_Transform3D" to "73d77d70",
        "AABB.get_center" to "3333397f",
        "AABB.get_volume" to "716b66f7",
        "AABB.has_volume" to "256151c5",
        "AABB.has_surface" to "256151c5",
        "AABB.has_point" to "4d7705c5",
        "AABB.is_equal_approx" to "4d7705c5",
        "AABB.intersects" to "ef81e3c5",
        "AABB.encloses" to "4d7705c5",
        "AABB.merge" to "591677c7",
        "Basis_*_int" to "58df7e5b",
        "Basis_/_int" to "9e064a74",
        "Basis_*_float" to "9e8f1507",
        "Basis_/_float" to "84266a5b",
        "Basis_*_Vector3" to "2ee39b",
        "Basis_*_Basis" to "78020d31",
        "Basis.is_equal_approx" to "4d7705c5",
        "Transform3D_*_int" to "4a3a8e3a",
        "Transform3D_/_int" to "87b739ce",
        "Transform3D_*_float" to "13b7f704",
        "Transform3D_/_float" to "7b94f0d6",
        "Transform3D_*_Vector3" to "1756c0f9",
        "Transform3D_*_Plane" to "5fcde4f9",
        "Transform3D_*_AABB" to "97069290",
        "Transform3D_*_Transform3D" to "6f886a28",
        "Transform3D_*_PackedVector3Array" to "1b7bd38c",
        "Transform3D.translated" to "e29ba9ae",
        "Transform3D.translated_local" to "d0d443c1",
        "Transform3D.is_equal_approx" to "4d7705c5",
        "Transform2D_*_int" to "eb7a9b5b",
        "Transform2D_/_int" to "c6f2e809",
        "Transform2D_*_float" to "78bb9e",
        "Transform2D_/_float" to "930ddb3a",
        "Transform2D_*_Vector2" to "98e47f2f",
        "Transform2D_*_Rect2" to "506876a9",
        "Transform2D_*_Transform2D" to "aa73f46b",
        "Transform2D_*_PackedVector2Array" to "8900c1d4",
        "Transform2D.inverse" to "5115bc9b",
        "Transform2D.get_origin" to "d13dba24",
        "Transform2D.translated" to "2ba3357b",
        "Transform2D.translated_local" to "26298b83",
        "Transform2D.basis_xform" to "e18255a2",
        "Transform2D.basis_xform_inv" to "a6162571",
        "Transform2D.is_equal_approx" to "4d7705c5",
        "Projection_*_Vector4" to "c58a3ecf",
        "Projection_*_Projection" to "cb443da1",
        "unary-_Color" to "237c6c0c",
        "unary+_Color" to "fa40b47a",
        "Color_*_int" to "512d3ed6",
        "Color_/_int" to "8129472",
        "Color_*_float" to "b84a7917",
        "Color_/_float" to "bb0ada20",
        "Color_+_Color" to "33acd714",
        "Color_-_Color" to "c235c10b",
        "Color_*_Color" to "336de16d",
        "Color_/_Color" to "12265580",
        "Color.to_html" to "a67ec83",
        "Color.clamp" to "eed8573c",
        "Color.inverted" to "e21444f5",
        "Color.lerp" to "40a0e6c0",
        "Color.get_luminance" to "d4093a28",
        "unary-_Vector2i" to "8485ffc4",
        "unary+_Vector2i" to "9c80a3be",
        "Vector2i_*_int" to "b8cf429e",
        "Vector2i_/_int" to "90056542",
        "Vector2i_%_int" to "aa95c33e",
        "Vector2i_*_float" to "5b9cef41",
        "Vector2i_/_float" to "51cc0c43",
        "Vector2i_<_Vector2i" to "bfcd19e5",
        "Vector2i_+_Vector2i" to "8fe115",
        "Vector2i_-_Vector2i" to "ccffde03",
        "Vector2i_*_Vector2i" to "d45b60a4",
        "Vector2i_/_Vector2i" to "b14ec00a",
        "Vector2i_%_Vector2i" to "ae0e6b2d",
        "Vector2i.aspect" to "915fc822",
        "Vector2i.max_axis_index" to "53c02454",
        "Vector2i.min_axis_index" to "ea22c985",
        "Vector2i.distance_to" to "205e0230",
        "Vector2i.distance_squared_to" to "837d68b1",
        "Vector2i.length" to "59150efa",
        "Vector2i.length_squared" to "ed8591d7",
        "Vector2i.sign" to "1b5e05c6",
        "Vector2i.abs" to "7bb1ca82",
        "Vector2i.clamp" to "6c70cc6c",
        "Vector2i.clampi" to "c25c5a1",
        "Vector2i.min" to "9e0801fd",
        "Vector2i.mini" to "7193a776",
        "Vector2i.max" to "a9988edb",
        "Vector2i.maxi" to "2a838be5",
        "unary-_Vector3i" to "23986858",
        "unary+_Vector3i" to "1a21ecaf",
        "Vector3i_*_int" to "2147c553",
        "Vector3i_/_int" to "d10dc1c1",
        "Vector3i_%_int" to "a5be7c8b",
        "Vector3i_*_float" to "a3a9dae5",
        "Vector3i_/_float" to "473dbef0",
        "Vector3i_<_Vector3i" to "2d6d83ac",
        "Vector3i_+_Vector3i" to "dc16461f",
        "Vector3i_-_Vector3i" to "ec70cd50",
        "Vector3i_*_Vector3i" to "55b62d44",
        "Vector3i_/_Vector3i" to "1fdfc2cf",
        "Vector3i_%_Vector3i" to "8be6b0c4",
        "Vector3i.min_axis_index" to "68c0c6d7",
        "Vector3i.max_axis_index" to "429d475f",
        "Vector3i.distance_to" to "6ddd8033",
        "Vector3i.distance_squared_to" to "a2399bc7",
        "Vector3i.length" to "65f1e190",
        "Vector3i.length_squared" to "cab5b078",
        "Vector3i.sign" to "6156c951",
        "Vector3i.abs" to "a41a9fc9",
        "Vector3i.clamp" to "e34d4f22",
        "Vector3i.clampi" to "ddd8c7a1",
        "Vector3i.min" to "f1f3af30",
        "Vector3i.mini" to "5815cc04",
        "Vector3i.max" to "212e701e",
        "Vector3i.maxi" to "1379d37c",
        "unary-_Vector4i" to "c220df2a",
        "unary+_Vector4i" to "d6dc4392",
        "Vector4i_*_int" to "47447071",
        "Vector4i_/_int" to "13e9e707",
        "Vector4i_%_int" to "22e94206",
        "Vector4i_*_float" to "ea0e2f9a",
        "Vector4i_/_float" to "3528066c",
        "Vector4i_<_Vector4i" to "10c803c5",
        "Vector4i_+_Vector4i" to "f7487982",
        "Vector4i_-_Vector4i" to "a0db4613",
        "Vector4i_*_Vector4i" to "9e5c3174",
        "Vector4i_/_Vector4i" to "c9289174",
        "Vector4i_%_Vector4i" to "645a572e",
        "Vector4i.min_axis_index" to "66093d55",
        "Vector4i.max_axis_index" to "36c97e27",
        "Vector4i.length" to "ae6bc92f",
        "Vector4i.length_squared" to "9797655f",
        "Vector4i.sign" to "9224823a",
        "Vector4i.abs" to "3a64a73",
        "Vector4i.clamp" to "895a466d",
        "Vector4i.clampi" to "d958310a",
        "Vector4i.min" to "f2957b3f",
        "Vector4i.mini" to "9ec09598",
        "Vector4i.max" to "4bb6cb51",
        "Vector4i.maxi" to "a06dff4a",
        "Vector4i.distance_to" to "fa3ab98e",
        "Vector4i.distance_squared_to" to "69acf41f",
        "Rect2i.get_center" to "724e255",
        "Rect2i.get_area" to "96aab20f",
        "Rect2i.has_area" to "256151c5",
        "Rect2i.has_point" to "2f131454",
        "Rect2i.intersects" to "703d7855",
        "Rect2i.encloses" to "9d04a95d",
        "Rect2i.intersection" to "ea3b5b08",
        "Rect2i.merge" to "dc7836df",
        "Rect2i.expand" to "67e4e022",
        "Rect2i.grow" to "b0fa6e5b",
        "Rect2i.grow_side" to "3dce5a42",
        "Rect2i.grow_individual" to "462329c4",
        "Rect2i.abs" to "935357a9",
        "RID_<_RID" to "472500f4",
        "RID.is_valid" to "256151c5",
        "RID.get_id" to "2fb520b",
      )

    // Godot's facade-row hashes for the Web-local methods (task 134 D1).
    val EXPECTED_FACADE =
      mapOf(
        "Vector2.angle" to "de9e786f",
        "Vector2.rotated" to "8a74d037",
        "Vector3.signed_angle_to" to "a75726b1",
        "Vector3.rotated" to "1069e14",
        "Quaternion.slerp" to "c2b54b9b",
        "Basis.inverse" to "ce48829e",
        "Basis.transposed" to "fa223aa5",
        "Basis.orthonormalized" to "f4e2e5a9",
        "Basis.determinant" to "f98ab5b8",
        "Basis.rotated" to "7cc66c7e",
        "Basis.scaled" to "38df11e4",
        "Basis.get_scale" to "e1da9658",
        "Basis.get_rotation_quaternion" to "97bbb30b",
        "Transform3D.orthonormalized" to "f4a1be29",
      )
  }
}
