// Generated by scripts/generate_platform_backend_contract.py — do not edit.
@file:OptIn(InternalKanamaBackendApi::class)

package net.multigesture.kanama.backend

object InitialGodotCallDescriptors {
  val NODE_GET_CHILD_COUNT =
    GodotCallDescriptor(
      opcode = 1,
      className = "Node",
      methodName = "get_child_count",
      hash = 894402480L,
      shape = GodotCallShape.BOOL_RET_INT,
      executionMode = GodotExecutionMode.IMMEDIATE_RESULT,
      returnOwnership = GodotReturnOwnership.BORROWED,
    )

  val NODE2D_GET_POSITION =
    GodotCallDescriptor(
      opcode = 2,
      className = "Node2D",
      methodName = "get_position",
      hash = 3341600327L,
      shape = GodotCallShape.NOARGS_RET_VECTOR2,
      executionMode = GodotExecutionMode.SNAPSHOT_READ,
      returnOwnership = GodotReturnOwnership.BORROWED,
    )

  val NODE2D_SET_POSITION =
    GodotCallDescriptor(
      opcode = 3,
      className = "Node2D",
      methodName = "set_position",
      hash = 743155724L,
      shape = GodotCallShape.VECTOR2_ARG,
      executionMode = GodotExecutionMode.QUEUED_MUTATION,
      returnOwnership = GodotReturnOwnership.BORROWED,
    )
}
