#!/usr/bin/env python3
"""Dry-run the conservative wrapper generator across the full Godot API."""

from __future__ import annotations

import argparse
import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from generate_api_wrapper import (
    render_draft,
    render_property,
    render_signal_constants,
    rendered_method_names,
)
from wrapper_model import ApiClass, load_api_classes, load_api_singletons, object_type_names, scan_wrapper_classes


ROOT = Path(__file__).resolve().parents[1]
UNSUPPORTED_SHAPE_RE = re.compile(r"unsupported helper shape args=(.*) return=(.*)")


@dataclass(frozen=True)
class ClassReport:
    name: str
    total_methods: int
    generated_methods: int
    total_properties: int
    generated_properties: int
    total_signals: int
    generated_signals: int
    skipped_methods: int

    @property
    def generated_percent(self) -> float:
        return 100.0 if self.total_methods == 0 else self.generated_methods / self.total_methods * 100.0


def method_count(cls: ApiClass) -> int:
    return sum(len(methods) for methods in cls.methods.values())


def generated_property_count(
    cls: ApiClass,
    emitted_methods: set[str],
    object_types: set[str],
    wrapper_classes: set[str],
    api_classes: dict[str, ApiClass],
    api_dir: Path,
) -> int:
    return sum(
        1
        for prop in cls.properties
        if render_property(cls, prop, emitted_methods, object_types, wrapper_classes, api_classes, api_dir) is not None
    )


def classify_skip(reason: str) -> str:
    if "Variant" in reason:
        return "Variant"
    if "Dictionary" in reason:
        return "Dictionary"
    if "Packed" in reason:
        return "Packed array"
    if "Array" in reason or "typedarray" in reason:
        return "Array / typed array"
    if reason.startswith("vararg"):
        return "Vararg"
    if reason.startswith("internal/virtual"):
        return "Virtual/internal"
    if "ownership/builtin-sensitive" in reason or "ownership-sensitive" in reason:
        return "Blocked object wrapper"
    if reason.startswith("object argument wrapper is missing"):
        return "Missing object arg wrapper"
    if reason.startswith("object return wrapper is missing") or "has no nullable wrap" in reason:
        return "Missing object return wrapper"
    if reason.startswith("unsupported helper shape"):
        return "Missing helper shape"
    return "Other"


def skip_reason(skip_line: str) -> str:
    return skip_line.split(": ", 1)[1] if ": " in skip_line else skip_line


def render_markdown(
    reports: list[ClassReport],
    skip_reasons: Counter[str],
    skip_categories: Counter[str],
    helper_shapes: Counter[str],
    draft_dir: Path,
) -> str:
    total_classes = len(reports)
    total_methods = sum(report.total_methods for report in reports)
    generated_methods = sum(report.generated_methods for report in reports)
    total_properties = sum(report.total_properties for report in reports)
    generated_properties = sum(report.generated_properties for report in reports)
    total_signals = sum(report.total_signals for report in reports)
    generated_signals = sum(report.generated_signals for report in reports)
    skipped_methods = sum(report.skipped_methods for report in reports)
    generated_classes = sum(1 for report in reports if report.generated_methods or report.generated_properties or report.generated_signals)
    complete_method_classes = sum(1 for report in reports if report.total_methods and report.generated_methods == report.total_methods)

    ready = [
        report
        for report in reports
        if report.total_methods
        and report.generated_methods == report.total_methods
        and report.generated_methods >= 2
    ]
    near_ready = [
        report
        for report in reports
        if report.total_methods >= 5 and report.generated_percent >= 80.0 and report.skipped_methods > 0
    ]
    largest = sorted(reports, key=lambda report: (report.generated_methods, report.generated_properties), reverse=True)[:20]

    try:
        display_draft_dir = draft_dir.relative_to(ROOT)
    except ValueError:
        display_draft_dir = draft_dir
    display_draft_dir_text = display_draft_dir.as_posix()

    lines = [
        "# Wrapper Generator Report",
        "",
        "Generated by `python3 scripts/api_wrapper_generator_report.py --markdown docs/contributing/wrapper-generator-report.md`.",
        "",
        f"Draft wrapper output is written to `{display_draft_dir_text}` during local runs and is not committed.",
        "",
        "## Role",
        "",
        "The wrapper generator turns Godot's `extension_api.json` into conservative Kotlin wrapper drafts. Its job is to scale API coverage without hand-writing thousands of MethodBind calls, while refusing shapes where Kanama has not defined ABI, ownership, or marshalling policy yet.",
        "",
        "Generated drafts are not automatically promoted. A class only becomes public source after review, smoke coverage where practical, and reproducibility checks against the generator output. This keeps broad wrapper growth auditable instead of relying on one-off manual wrappers.",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "| --- | ---: |",
        f"| API classes | {total_classes} |",
        f"| Classes with generated output | {generated_classes} |",
        f"| Classes with complete method generation | {complete_method_classes} |",
        f"| Methods generated | {generated_methods}/{total_methods} ({generated_methods / total_methods * 100.0:.1f}%) |",
        f"| Methods skipped | {skipped_methods} |",
        f"| Properties generated | {generated_properties}/{total_properties} ({generated_properties / total_properties * 100.0:.1f}%) |",
        f"| Signals generated | {generated_signals}/{total_signals} ({generated_signals / total_signals * 100.0:.1f}%) |",
        "",
        "## Skip Categories",
        "",
        "| Category | Skipped Methods |",
        "| --- | ---: |",
    ]
    lines.extend(f"| {category} | {count} |" for category, count in skip_categories.most_common())

    lines.extend(
        [
            "",
            "## Missing Helper Shapes",
            "",
            "These are the highest-leverage ptrcall helper shapes to add next, excluding broader data-type policy work.",
            "",
            "| Shape | Count |",
            "| --- | ---: |",
        ],
    )
    if helper_shapes:
        lines.extend(f"| `{shape}` | {count} |" for shape, count in helper_shapes.most_common(25))
    else:
        lines.append("| _None_ | 0 |")

    lines.extend(
        [
            "",
            "## Top Skip Reasons",
            "",
            "| Reason | Count |",
            "| --- | ---: |",
        ],
    )
    lines.extend(f"| `{reason}` | {count} |" for reason, count in skip_reasons.most_common(25))

    lines.extend(
        [
            "",
            "## Complete Method Classes",
            "",
            "These classes have every method covered by the conservative generator. Promotion remains a deliberate API review step.",
            "",
            "| Class | Methods | Properties | Signals |",
            "| --- | ---: | ---: | ---: |",
        ],
    )
    lines.extend(
        f"| {report.name} | {report.generated_methods}/{report.total_methods} | "
        f"{report.generated_properties}/{report.total_properties} | {report.generated_signals}/{report.total_signals} |"
        for report in sorted(ready, key=lambda report: (report.generated_methods, report.name), reverse=True)[:50]
    )

    lines.extend(
        [
            "",
            "## Near Ready Classes",
            "",
            "| Class | Methods | Properties | Signals | Skips |",
            "| --- | ---: | ---: | ---: | ---: |",
        ],
    )
    lines.extend(
        f"| {report.name} | {report.generated_methods}/{report.total_methods} ({report.generated_percent:.1f}%) | "
        f"{report.generated_properties}/{report.total_properties} | {report.generated_signals}/{report.total_signals} | "
        f"{report.skipped_methods} |"
        for report in sorted(near_ready, key=lambda report: (report.generated_percent, report.generated_methods), reverse=True)[:50]
    )

    lines.extend(
        [
            "",
            "## Largest Generated Drafts",
            "",
            "| Class | Methods | Properties | Signals | Skips |",
            "| --- | ---: | ---: | ---: | ---: |",
        ],
    )
    lines.extend(
        f"| {report.name} | {report.generated_methods}/{report.total_methods} | "
        f"{report.generated_properties}/{report.total_properties} | {report.generated_signals}/{report.total_signals} | "
        f"{report.skipped_methods} |"
        for report in largest
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--api", type=Path, default=ROOT / "extension_api.json")
    parser.add_argument("--api-dir", type=Path, default=ROOT / "src/main/kotlin/net/multigesture/kanama/api")
    parser.add_argument("--output-dir", type=Path, default=ROOT / "build/wrapper-generator/drafts")
    parser.add_argument("--skip-report", type=Path, default=ROOT / "build/wrapper-generator/skips.txt")
    parser.add_argument("--markdown", type=Path, help="Write a markdown report.")
    parser.add_argument("--check", action="store_true", help="Fail if the markdown report is stale.")
    args = parser.parse_args()

    api_classes = load_api_classes(args.api)
    singleton_names = load_api_singletons(args.api)
    object_types = object_type_names(api_classes)
    wrapper_classes = scan_wrapper_classes(args.api_dir)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    args.skip_report.parent.mkdir(parents=True, exist_ok=True)

    reports: list[ClassReport] = []
    skip_lines: list[str] = []
    skip_reasons: Counter[str] = Counter()
    skip_categories: Counter[str] = Counter()
    helper_shapes: Counter[str] = Counter()

    for cls in api_classes.values():
        emitted_methods = rendered_method_names(cls, object_types, wrapper_classes, api_classes, args.api_dir)
        generated_props = generated_property_count(cls, emitted_methods, object_types, wrapper_classes, api_classes, args.api_dir)
        generated_signal_text = render_signal_constants(cls)
        generated_signals = len(cls.signals) if generated_signal_text else 0
        content, skips = render_draft(cls, object_types, wrapper_classes, api_classes, args.api_dir, singleton_names)
        (args.output_dir / f"{cls.name}.kt").write_text(content, encoding="utf-8")

        for skip in skips:
            reason = skip_reason(skip)
            skip_lines.append(f"{cls.name}: {skip}")
            skip_reasons[reason] += 1
            skip_categories[classify_skip(reason)] += 1
            if match := UNSUPPORTED_SHAPE_RE.search(reason):
                helper_shapes[f"args={match.group(1)} return={match.group(2)}"] += 1

        reports.append(
            ClassReport(
                name=cls.name,
                total_methods=method_count(cls),
                generated_methods=len(emitted_methods),
                total_properties=len(cls.properties),
                generated_properties=generated_props,
                total_signals=len(cls.signals),
                generated_signals=generated_signals,
                skipped_methods=len(skips),
            ),
        )

    args.skip_report.write_text("\n".join(skip_lines) + ("\n" if skip_lines else ""), encoding="utf-8")

    total_methods = sum(report.total_methods for report in reports)
    generated_methods = sum(report.generated_methods for report in reports)
    print(
        "[wrapper_generator_report] "
        f"classes={len(reports)} generated_methods={generated_methods}/{total_methods} "
        f"skips={sum(report.skipped_methods for report in reports)} "
        f"drafts={args.output_dir} skip_report={args.skip_report}",
    )

    if args.markdown:
        markdown = render_markdown(reports, skip_reasons, skip_categories, helper_shapes, args.output_dir)
        if args.check:
            if not args.markdown.exists() or args.markdown.read_text(encoding="utf-8") != markdown:
                print(f"[wrapper_generator_report] FAIL stale markdown: {args.markdown}")
                return 1
            print(f"[wrapper_generator_report] PASS markdown up to date: {args.markdown}")
        else:
            args.markdown.parent.mkdir(parents=True, exist_ok=True)
            args.markdown.write_text(markdown, encoding="utf-8")
            print(f"[wrapper_generator_report] wrote {args.markdown}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
