#!/usr/bin/env python3
"""Report hand-written Kotlin API wrapper coverage against extension_api.json."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from wrapper_model import ApiClass, category_for, load_api_classes, scan_wrapper_classes, scan_wrappers


ROOT = Path(__file__).resolve().parents[1]
GENERATOR_REPORT = ROOT / "docs" / "contributing" / "wrapper-generator-report.md"


def bar(percent: float, width: int = 12) -> str:
    filled = round(max(0.0, min(100.0, percent)) / 100.0 * width)
    return "█" * filled + "░" * (width - filled)


def pct(count: int, total: int) -> float:
    return (count / total * 100.0) if total else 0.0


def regular_method_count(cls: ApiClass) -> int:
    """Method names with at least one non-virtual overload — the callable wrapper surface."""
    return sum(1 for overloads in cls.methods.values() if not all(m.is_virtual for m in overloads))


def virtual_method_count(cls: ApiClass) -> int:
    """Method names that are engine virtuals — overridden via @OverrideVirtual, not wrapped."""
    return sum(1 for overloads in cls.methods.values() if all(m.is_virtual for m in overloads))


def generator_summary() -> list[tuple[str, str]]:
    if not GENERATOR_REPORT.exists():
        return []

    rows: list[tuple[str, str]] = []
    in_summary = False
    for line in GENERATOR_REPORT.read_text(encoding="utf-8").splitlines():
        if line == "## Summary":
            in_summary = True
            continue
        if in_summary and line.startswith("## "):
            break
        if not in_summary or not line.startswith("| "):
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if len(cells) != 2 or cells[0] in {"Metric", "---"}:
            continue
        rows.append((cells[0], cells[1]))
    return rows


def ratio_bar(count: int, total: int) -> str:
    return f"`{bar(pct(count, total))}` {pct(count, total):.1f}%" if total else ""


def parse_ratio(value: str) -> tuple[int, int] | None:
    match = re.match(r"^(\d+)/(\d+)(?:\s+\([^)]+\))?$", value)
    if not match:
        return None
    return int(match.group(1)), int(match.group(2))


def render_markdown(
    classes: dict[str, ApiClass],
    wrapped_methods: dict[str, set[str]],
    wrapper_classes: set[str],
) -> str:
    generated = "Generated by `python3 scripts/api_wrapper_coverage.py --markdown docs/contributing/api-coverage.md`."
    total_classes = len(classes)
    # Engine virtuals are overridden via @OverrideVirtual, not called through a wrapper, so they are
    # tracked on their own axis below rather than counted against callable-method coverage (Phase 5.4).
    total_methods = sum(regular_method_count(cls) for cls in classes.values())
    total_virtuals = sum(virtual_method_count(cls) for cls in classes.values())
    covered_classes = len(wrapper_classes & set(classes))
    covered_methods = sum(len(methods) for class_name, methods in wrapped_methods.items() if class_name in classes)
    class_percent = pct(covered_classes, total_classes)
    method_percent = pct(covered_methods, total_methods)
    dry_run_summary = generator_summary()

    buckets: dict[str, list[ApiClass]] = {}
    for cls in classes.values():
        buckets.setdefault(category_for(cls.name, classes), []).append(cls)

    preferred_order = [
        "Core",
        "Scene",
        "Resources",
        "Input",
        "UI",
        "2D",
        "3D",
        "Physics",
        "Rendering",
        "Audio",
        "Multiplayer",
        "Editor",
    ]
    category_names = [name for name in preferred_order if name in buckets] + sorted(set(buckets) - set(preferred_order))

    lines: list[str] = [
        "# API Coverage",
        "",
        generated,
        "",
        "This page distinguishes generator coverage from promoted source coverage. "
        "Generator coverage is the practical API reach for upcoming wrapper promotion; promoted coverage only counts wrappers currently checked into `src/main/kotlin/net/multigesture/kanama/api`.",
        "",
        "## Generator Summary",
        "",
        "Generated drafts are emitted to `build/wrapper-generator/drafts` during local runs. "
        "A small allowlisted set is promoted into source and checked for reproducibility.",
        "",
        "| Metric | Count |",
        "| --- | ---: |",
    ]

    if dry_run_summary:
        summary_values = dict(dry_run_summary)
        total_classes_value = summary_values.get("API classes")
        total_classes_for_bars = int(total_classes_value) if total_classes_value and total_classes_value.isdigit() else 0
        lines[-1] = "| --- | ---: | --- |"
        lines[-2] = "| Metric | Count | Coverage |"
        for metric, count in dry_run_summary:
            progress = ""
            ratio = parse_ratio(count)
            if ratio is not None:
                generated, total = ratio
                progress = ratio_bar(generated, total)
            elif metric in {"Classes with generated output", "Classes with complete method generation"} and count.isdigit():
                progress = ratio_bar(int(count), total_classes_for_bars)
            lines.append(f"| {metric} | {count} | {progress} |")
    else:
        lines.append("| Status | Run `python3 scripts/api_wrapper_generator_report.py --markdown docs/contributing/wrapper-generator-report.md` |  |")

    lines.extend(
        [
            "",
            "See [Wrapper Generator Report](wrapper-generator-report.md) for skip categories, missing helper shapes, and complete generated classes.",
            "",
            "## Promoted Source Summary",
            "",
            "These numbers count only checked-in Kotlin API wrappers. Class coverage may include shell wrappers for Godot extension points whose public callable surface is virtual-only; method coverage counts promoted callable wrappers.",
            "Rows marked `inherited only` are promoted wrappers whose Godot class declares no own methods in `extension_api.json`; behavior comes from their parent wrapper.",
            "",
            f"- Classes: {covered_classes} / {total_classes} `{bar(class_percent)}` {class_percent:.1f}%",
            f"- Methods: {covered_methods} / {total_methods} `{bar(method_percent)}` {method_percent:.1f}% (callable methods; engine virtuals excluded — see below)",
            "",
            "## Virtual Methods",
            "",
            f"`extension_api.json` declares **{total_virtuals}** engine virtual methods (the `_*` "
            "callbacks). These are not wrapped as callable methods — a script overrides them with "
            "`@OverrideVirtual` (Phase 5), where the Kotlin function name is the virtual name "
            "(GDScript-style `fun _draw()`). The processor validates each override against a generated "
            "signature table (`scripts/generate_virtual_signature_table.py`, all virtuals) and dispatches "
            "it on both targets. They are reported here separately so they neither dilute callable-method "
            "coverage nor count as wrapper gaps. Practical marshalling bounds: desktop/Android cover the "
            "audited Variant shapes; iOS value-returns currently cover Bool/Int/Float/Vector2/Vector2i "
            "(string/packed/Variant returns deferred).",
            "",
            "## Promoted Source By Area",
            "",
            "| Area | Classes | Class Coverage | Methods | Method Coverage |",
            "| --- | ---: | --- | ---: | --- |",
        ],
    )

    for name in category_names:
        bucket = buckets[name]
        bucket_names = {cls.name for cls in bucket}
        bucket_class_total = len(bucket)
        bucket_class_count = len(wrapper_classes & bucket_names)
        bucket_method_total = sum(regular_method_count(cls) for cls in bucket)
        bucket_method_count = sum(
            len(methods)
            for class_name, methods in wrapped_methods.items()
            if class_name in bucket_names
        )
        cp = pct(bucket_class_count, bucket_class_total)
        mp = pct(bucket_method_count, bucket_method_total)
        lines.append(
            f"| {name} | {bucket_class_count}/{bucket_class_total} | `{bar(cp)}` {cp:.1f}% | "
            f"{bucket_method_count}/{bucket_method_total} | `{bar(mp)}` {mp:.1f}% |",
        )

    lines += [
        "",
        "## Demo Port Signals",
        "",
        "These notes summarize wrapper feedback from real ports. They are contextual signals, not a ranking.",
        "",
        "- GDQuest third-person controller: the remaining friction is mostly port ergonomics around nested node access, signal callbacks, and scene-script parity rather than missing core 3D wrappers.",
        "- Official TPS demo: core classes now have wrappers; the main policy-heavy areas are RPC annotations, `MultiplayerSynchronizer` scripts, threaded `ResourceLoader` progress arrays, signal `.bind(...)` usage, and headless/multiplayer smoke strategy.",
        "- Godot official demo-projects: small demos are most useful when they exercise a distinct behavior or policy area.",
        "",
        "## Promoted Source Wrapped Classes",
        "",
        "| Class | Area | Methods | Coverage |",
        "| --- | --- | ---: | --- |",
    ]

    for class_name in sorted(wrapper_classes & set(classes)):
        cls = classes[class_name]
        method_count = len(wrapped_methods.get(class_name, set()))
        method_total = regular_method_count(cls)
        percent = pct(method_count, method_total)
        coverage = f"`{bar(percent, 8)}` {percent:.1f}%" if method_total else "inherited only"
        lines.append(
            f"| `{class_name}` | {category_for(class_name, classes)} | {method_count}/{method_total} | {coverage} |",
        )

    unwrapped = [cls for cls in classes.values() if cls.name not in wrapper_classes]
    unwrapped.sort(key=lambda cls: (-regular_method_count(cls), cls.name))
    if unwrapped:
        lines += [
            "",
            "## Largest Unpromoted Classes",
            "",
            "| Class | Area | Methods |",
            "| --- | --- | ---: |",
        ]
        for cls in unwrapped[:30]:
            lines.append(f"| `{cls.name}` | {category_for(cls.name, classes)} | {regular_method_count(cls)} |")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--api", type=Path, default=Path("extension_api.json"))
    parser.add_argument("--api-dir", type=Path, default=Path("src/main/kotlin/net/multigesture/kanama/api"))
    parser.add_argument("--details", action="store_true", help="Print wrapped method signatures.")
    parser.add_argument("--json", action="store_true", help="Print a machine-readable coverage manifest.")
    parser.add_argument(
        "--markdown",
        nargs="?",
        const="-",
        metavar="PATH",
        help="Print Markdown to stdout, or write a full status page to PATH.",
    )
    parser.add_argument("--check", action="store_true", help="With --markdown PATH, fail if PATH is stale.")
    args = parser.parse_args()

    api_classes = load_api_classes(args.api)
    classes = {name: cls.methods for name, cls in api_classes.items()}
    wrapped = scan_wrappers(args.api_dir)
    wrapper_classes = scan_wrapper_classes(args.api_dir)

    errors: list[str] = []
    for class_name, method_names in sorted(wrapped.items()):
        if class_name not in classes:
            errors.append(f"{class_name}: wrapper class not found in extension_api.json")
            continue
        for method_name in sorted(method_names):
            if method_name not in classes[class_name]:
                errors.append(f"{class_name}.{method_name}: wrapper method not found in extension_api.json")

    if errors:
        for error in errors:
            print(f"[api_wrapper_coverage] ERROR {error}", file=sys.stderr)
        return 1

    total_wrapped = sum(len(methods) for methods in wrapped.values())
    if args.json:
        manifest: dict[str, object] = {
            "wrapped_classes": len(wrapped),
            "wrapped_methods": total_wrapped,
            "classes": {},
        }
        manifest_classes = manifest["classes"]
        assert isinstance(manifest_classes, dict)
        for class_name in sorted(wrapped):
            api_methods = classes[class_name]
            wrapped_methods = wrapped[class_name]
            missing_methods = sorted(set(api_methods) - wrapped_methods)
            manifest_classes[class_name] = {
                "wrapped_count": len(wrapped_methods),
                "total_count": len(api_methods),
                "coverage_percent": (len(wrapped_methods) / len(api_methods) * 100.0) if api_methods else 0.0,
                "wrapped": {
                    method_name: [method.to_json() for method in api_methods[method_name]]
                    for method_name in sorted(wrapped_methods)
                },
                "missing": {
                    method_name: [method.to_json() for method in api_methods[method_name]]
                    for method_name in missing_methods
                },
            }
        print(json.dumps(manifest, indent=2, sort_keys=True))
        return 0

    if args.markdown is not None:
        markdown = render_markdown(api_classes, wrapped, wrapper_classes)
        if args.markdown == "-":
            print(markdown, end="")
            return 0

        output_path = Path(args.markdown)
        if args.check:
            current = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
            if current != markdown:
                print(f"[api_wrapper_coverage] FAIL stale markdown: {output_path}", file=sys.stderr)
                print(
                    f"[api_wrapper_coverage] run: python3 scripts/api_wrapper_coverage.py --markdown {output_path}",
                    file=sys.stderr,
                )
                return 1
            print(f"[api_wrapper_coverage] PASS markdown up to date: {output_path}")
            return 0

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(markdown, encoding="utf-8")
        print(f"[api_wrapper_coverage] wrote {output_path}")
        return 0

    api_wrapper_classes = wrapper_classes & set(classes)
    shell_only_classes = api_wrapper_classes - set(wrapped)
    print(
        "[api_wrapper_coverage] "
        f"wrapped_classes={len(api_wrapper_classes)} "
        f"method_wrapped_classes={len(wrapped)} "
        f"shell_only_classes={len(shell_only_classes)} "
        f"wrapped_methods={total_wrapped}",
    )
    for class_name in sorted(wrapped):
        api_methods = classes[class_name]
        wrapped_methods = wrapped[class_name]
        total_methods = len(api_methods)
        count = len(wrapped_methods)
        percent = (count / total_methods * 100.0) if total_methods else 0.0
        print(f"[api_wrapper_coverage] {class_name}: {count}/{total_methods} methods ({percent:.1f}%)")
        if args.details:
            for method_name in sorted(wrapped_methods):
                overloads = api_methods[method_name]
                signatures = "; ".join(method.signature for method in overloads)
                print(f"  - {signatures}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
