#!/usr/bin/env python3
"""Gate: every swallowed failure in the gate scripts is justified in the code (task 118).

A gate that swallows a failure is worse than no gate: it produces green evidence for a red state. This
finds every construct that can swallow one, and requires that each either is an idiom whose verdict
cannot change (see IDIOMS) or carries a `# justified: <why>` comment, on its own line (trailing), on any
line of the same statement, or in the comment block directly above the statement. The comment IS the
reason: the audit table in scripts/README-gates.md is generated from these comments, so it cannot
drift from the code.

Sites (shell and workflow `run:` steps): `|| true`, `|| :`, `|| continue`, `|| exit 0`, `|| return 0`,
`2>/dev/null`, `>/dev/null`, `set +e`, `continue-on-error`, a bare `continue`.
Sites (Python): every `except` handler (one that raises, records an error or prints is LOUD and needs no
comment), `check=False`, `sys.exit(0)`, `contextlib.suppress`, `errors="ignore"`, `DEVNULL`.
A bare `return 0` that ends `main()` after every check passed is not an error path and is not listed.

Scanned: scripts/*.sh, scripts/**/*.sh, scripts/*.py, scripts/web/*.py, .github/workflows/*.yml.

Usage:
    python3 scripts/audit_swallowed_failures.py            # --check (the default): fail on an unjustified site
                                                           #   or when the README table is stale
    python3 scripts/audit_swallowed_failures.py --write    # regenerate the table block in README-gates.md
    python3 scripts/audit_swallowed_failures.py --root DIR --label demos:   # another repo's scripts/ (not checked)
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "scripts" / "README-gates.md"
BEGIN = "<!-- audit-table:begin (generated by scripts/audit_swallowed_failures.py --write) -->"
END = "<!-- audit-table:end -->"
TAG = "[audit_swallowed_failures]"

# Files whose sites are deferred while another task owns the file (remove the entry when it lands).
DEFERRED = {
    "scripts/runtime_smoke.sh": "deferred: in-flight task 132",
    "scripts/audit_generator_shape_policy.py": "deferred: in-flight task 132",
}

SHELL_SITE = re.compile(
    r"\|\| true|\|\| :|\|\| continue|\|\| exit 0|\|\| return 0|2>/dev/null|>/dev/null|set \+e|continue-on-error"
)
BARE_CONTINUE = re.compile(r"^\s*continue\b(?!-)")
JUSTIFIED = re.compile(r"#\s*justified:\s*(.*)$")

# (regex over the statement text, verdict): constructs whose verdict cannot change by definition.
IDIOMS = [
    (re.compile(r"command -v \S+ >/dev/null 2>&1"), "justified: probe; the exit status is the test, only its output is dropped"),
    (re.compile(r"kill -0 \S+ 2>/dev/null"), "justified: liveness probe (`kill -0`); the exit status is the test"),
    (re.compile(r"^\s*(if|while|elif)\s.*>/dev/null( 2>&1)?\s*;"), "justified: output dropped, the command's exit status is the condition of the `if`"),
    (re.compile(r"\|\| die\b"), "justified: not a swallow; `|| die` fails the script with a message"),
]
STDOUT_ONLY = "justified: stdout only; stderr and the exit status are kept, so errexit still fails the script"


def comment_of(line: str) -> str | None:
    match = JUSTIFIED.search(line)
    return match.group(1).strip() if match else None


def statement_start(lines: list[str], index: int) -> int:
    """Index of the first line of the (backslash-continued) shell statement holding lines[index]."""
    while index > 0 and lines[index - 1].rstrip().endswith("\\"):
        index -= 1
    return index


def block_above(lines: list[str], start: int, comment_prefix: str = "#") -> str | None:
    """The reason in the contiguous comment block directly above lines[start]: from its `justified:` line
    to the end of the block, joined into one sentence."""
    block: list[str] = []
    i = start - 1
    while i >= 0 and lines[i].strip().startswith(comment_prefix):
        block.append(lines[i].strip().lstrip("#").strip())
        i -= 1
    block.reverse()
    for n, text in enumerate(block):
        if text.startswith("justified:"):
            return " ".join([text[len("justified:") :].strip(), *block[n + 1 :]]).strip()
    return None


def shell_reason(lines: list[str], index: int) -> str | None:
    start = statement_start(lines, index)
    for i in range(start, index + 1):
        reason = comment_of(lines[i])
        if reason:
            return reason
    return block_above(lines, start)


def classify_shell(lines: list[str], index: int) -> str | None:
    reason = shell_reason(lines, index)
    if reason:
        return f"justified: {reason}"
    start = statement_start(lines, index)
    statement = " ".join(lines[start : index + 1])
    for pattern, verdict in IDIOMS:
        if pattern.search(statement):
            return verdict
    line = lines[index]
    if ">/dev/null" in line and "2>&1" not in line and "2>/dev/null" not in line and "|| true" not in line:
        return STDOUT_ONLY
    return None


def shell_sites(text: str) -> list[tuple[int, str]]:
    sites = []
    for number, line in enumerate(text.splitlines(), 1):
        code = line.split("  #")[0] if "  #" in line else line
        if line.strip().startswith("#"):
            continue
        if SHELL_SITE.search(code) or BARE_CONTINUE.search(code):
            sites.append((number, line))
    return sites


def python_sites(text: str) -> list[tuple[int, str, str]]:
    """(line, construct line, kind) with kind loud | silent | other."""
    try:
        tree = ast.parse(text)
    except SyntaxError as error:
        raise SystemExit(f"{TAG} FAIL cannot parse a Python script: {error}") from error
    lines = text.splitlines()
    sites: list[tuple[int, str, str]] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ExceptHandler):
            loud = False
            for n in ast.walk(ast.Module(body=node.body, type_ignores=[])):
                if isinstance(n, ast.Raise):
                    loud = True
                if isinstance(n, ast.Call):
                    f = n.func
                    name = f.attr if isinstance(f, ast.Attribute) else (f.id if isinstance(f, ast.Name) else "")
                    if name in ("append", "print", "exit", "SystemExit", "error", "fail", "extend", "add_finding", "ParseError"):
                        loud = True
                if isinstance(n, ast.Return) and isinstance(n.value, ast.Constant) and n.value.value not in (0, None, False):
                    loud = True
            sites.append((node.lineno, lines[node.lineno - 1], "loud" if loud else "silent"))
        elif isinstance(node, ast.keyword) and node.arg == "check" and isinstance(node.value, ast.Constant) and node.value.value is False:
            sites.append((node.value.lineno, lines[node.value.lineno - 1], "other"))
    for number, line in enumerate(lines, 1):
        if line.strip().startswith("#"):
            continue
        if re.search(r"sys\.exit\(0\)|SystemExit\(0\)|contextlib\.suppress|errors=.ignore|DEVNULL", line):
            sites.append((number, line, "other"))
    return sorted(set(sites))


def classify_python(lines: list[str], tree_node_end: int, number: int, kind: str) -> str | None:
    index = number - 1
    if kind == "loud":
        return "justified: the handler reports (raises, records an error or prints a FAIL), so the failure reaches the verdict"
    # a comment on the construct's own line, within the handler body, or the block directly above it
    for i in range(index, min(len(lines), tree_node_end)):
        reason = comment_of(lines[i])
        if reason:
            return f"justified: {reason}"
    reason = block_above(lines, index)
    return f"justified: {reason}" if reason else None


def handler_end(text: str) -> dict[int, int]:
    ends: dict[int, int] = {}
    for node in ast.walk(ast.parse(text)):
        if isinstance(node, (ast.ExceptHandler, ast.Call)):
            ends[node.lineno] = max(ends.get(node.lineno, 0), node.end_lineno or node.lineno)
    return ends


def norm(line: str) -> str:
    line = re.sub(r"\s+#\s.*$", "", line)
    return re.sub(r"\s+", " ", line.strip())[:110]


def files_under(root: Path) -> list[Path]:
    found: list[Path] = []
    scripts = root / "scripts"
    for path in sorted(scripts.rglob("*")):
        rel = path.relative_to(root).as_posix()
        if "node_modules" in rel or "__pycache__" in rel or "/fixtures/" in rel or rel == "scripts/audit_swallowed_failures.py":
            continue
        if path.suffix == ".sh" or (path.suffix == ".py" and path.parent in (scripts, scripts / "web")):
            found.append(path)
    found.extend(sorted((root / ".github" / "workflows").glob("*.yml")))
    return found


def audit(root: Path, label: str) -> tuple[list[tuple[str, int, str, str]], list[str]]:
    rows: list[tuple[str, int, str, str]] = []
    unclassified: list[str] = []
    for path in files_under(root):
        rel = path.relative_to(root).as_posix()
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()
        if path.suffix == ".py":
            ends = handler_end(text)
            for number, line, kind in python_sites(text):
                verdict = classify_python(lines, ends.get(number, number), number, kind)
                verdict = DEFERRED.get(rel) if (verdict is None and rel in DEFERRED and not label) else verdict
                if verdict is None:
                    unclassified.append(f"{label}{rel}:{number}: {line.strip()}")
                    continue
                rows.append((f"{label}{rel}", number, norm(line), verdict))
        else:
            for number, line in shell_sites(text):
                if BARE_CONTINUE.search(line) and not shell_reason(lines, number - 1):
                    verdict = None
                else:
                    verdict = classify_shell(lines, number - 1)
                if verdict is None and rel in DEFERRED and not label:
                    verdict = DEFERRED[rel]
                if verdict is None:
                    unclassified.append(f"{label}{rel}:{number}: {line.strip()}")
                    continue
                rows.append((f"{label}{rel}", number, norm(line), verdict))
    return rows, unclassified


def render(rows: list[tuple[str, int, str, str]], with_lines: bool = True) -> list[str]:
    out = []
    for rel, number, construct, verdict in rows:
        where = f"{rel}:{number}" if with_lines else rel
        out.append(f"| `{where}` | `{construct.replace('|', chr(92) + '|')}` | {verdict.replace('|', chr(92) + '|')} |")
    return out


def strip_lines(row: str) -> str:
    return re.sub(r"^\| `([^`]+?):\d+` \|", r"| `\1` |", row)


def block_of(readme_text: str) -> list[str] | None:
    if BEGIN not in readme_text or END not in readme_text:
        return None
    body = readme_text.split(BEGIN, 1)[1].split(END, 1)[0]
    return [line for line in body.strip().splitlines() if line.startswith("| `")]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--write", action="store_true", help="regenerate the table block in scripts/README-gates.md")
    parser.add_argument("--root", type=Path, default=ROOT, help="the repo to scan (default: this one)")
    parser.add_argument("--label", default="", help="prefix for the file column, e.g. demos:")
    args = parser.parse_args()

    rows, unclassified = audit(args.root.resolve(), args.label)
    if args.root.resolve() != ROOT:
        print("\n".join(["| file:line | construct | verdict |", "|---|---|---|", *render(rows)]))
        for item in unclassified:
            print(f"UNCLASSIFIED {item}", file=sys.stderr)
        return 1 if unclassified else 0

    if unclassified:
        print(f"{TAG} FAIL {len(unclassified)} swallowed-failure site(s) with no `# justified: <why>` and no known idiom:", file=sys.stderr)
        for item in unclassified:
            print(f"  {item}", file=sys.stderr)
        print(f"{TAG} Make the failure fatal (with the captured output), or say why it cannot change the verdict.", file=sys.stderr)
        return 1

    table = ["| file:line | construct | verdict |", "|---|---|---|", *render(rows)]
    readme = README.read_text(encoding="utf-8")
    if args.write:
        if BEGIN not in readme or END not in readme:
            print(f"{TAG} FAIL README-gates.md has no {BEGIN} ... {END} block", file=sys.stderr)
            return 1
        head, rest = readme.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        README.write_text(f"{head}{BEGIN}\n\n" + "\n".join(table) + f"\n\n{END}{tail}", encoding="utf-8")
        print(f"{TAG} wrote {len(rows)} rows to {README.relative_to(ROOT)}")
        return 0

    current = block_of(readme)
    if current is None:
        print(f"{TAG} FAIL README-gates.md has no generated table block; run with --write", file=sys.stderr)
        return 1
    if [strip_lines(r) for r in current] != [strip_lines(r) for r in render(rows)]:
        print(f"{TAG} FAIL the audit table in scripts/README-gates.md is stale (a site or its `# justified:` text changed); "
              "run `python3 scripts/audit_swallowed_failures.py --write`", file=sys.stderr)
        return 1
    print(f"{TAG} PASS {len(rows)} swallowed-failure sites, every one justified in the code; README table current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
