#!/usr/bin/env python3
"""Generate and drift-check the first neutral Godot backend call descriptors."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from platform_backend_contract import INITIAL_BACKEND_CALLS


def validate_api(api_path: Path) -> None:
    payload = json.loads(api_path.read_text())
    classes = {entry["name"]: entry for entry in payload["classes"]}
    utilities = payload["utility_functions"]
    for policy in INITIAL_BACKEND_CALLS:
        candidates = (
            utilities
            if policy.scope == "utility"
            else classes[policy.class_name].get("methods", ())
        )
        method = next(
            entry
            for entry in candidates
            if entry["name"] == policy.method_name and entry["hash"] == policy.expected_hash
        )
        arguments = tuple(argument["type"] for argument in method.get("arguments", ()))
        return_type = method.get("return_value", {}).get(
            "type", method.get("return_type", "void")
        )
        actual = (method["hash"], arguments, return_type, method.get("is_vararg", False))
        expected = (
            policy.expected_hash,
            policy.arguments,
            policy.return_type,
            policy.is_vararg,
        )
        if actual != expected:
            raise ValueError(
                f"Godot API drift for {policy.class_name}.{policy.method_name}: "
                f"expected {expected}, received {actual}"
            )


def const_name(class_name: str, method_name: str) -> str:
    owner = "UTILITY" if class_name == "@GlobalScope" else class_name.upper()
    return f"{owner}_{method_name.upper()}"


def render() -> str:
    lines = [
        "// Generated by scripts/generate_platform_backend_contract.py — do not edit.",
        "@file:OptIn(InternalKanamaBackendApi::class)",
        "",
        "package net.multigesture.kanama.backend",
        "",
        "object InitialGodotCallDescriptors {",
    ]
    for policy in INITIAL_BACKEND_CALLS:
        descriptor_name = policy.descriptor_name or const_name(policy.class_name, policy.method_name)
        lines.extend(
            [
                f"  val {descriptor_name} =",
                "    GodotCallDescriptor(",
                f"      opcode = {policy.opcode},",
                f'      className = "{policy.class_name}",',
                f'      methodName = "{policy.method_name}",',
                f"      hash = {policy.expected_hash}L,",
                f"      shape = GodotCallShape.{policy.shape},",
                f"      executionMode = GodotExecutionMode.{policy.execution_mode.value},",
                f"      returnOwnership = GodotReturnOwnership.{policy.return_ownership},",
                "    )",
                "",
            ]
        )
    if lines[-1] == "":
        lines.pop()
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--api", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    validate_api(args.api)
    generated = render()
    if args.check:
        current = args.output.read_text() if args.output.is_file() else ""
        if current != generated:
            print(
                f"[platform_backend_contract] FAIL generated descriptor drift: {args.output}",
                file=sys.stderr,
            )
            return 1
        print("[platform_backend_contract] PASS")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
