#!/usr/bin/env python3
"""Generate the Kotlin/Wasm Web wrapper tree from the Web call contract (task 96).

Every opcode in `scripts/platform_backend_calls.json` becomes one member on the Godot class that
owns it, in `web-runtime/src/commonMain/kotlin/net/multigesture/kanama/api/generated/<Class>.kt`
(one class, one file). The member's name, parameters, defaults and return type come from
`extension_api.json` (the same source the native wrapper generator reads), the call itself goes
straight to `GodotBackendCalls.invoke<Shape>(InitialGodotCallDescriptors.X, ...)`, so the former
hand-written probe + wrapper pair collapses into one generated layer.

What stays hand-written is explicit and short: `WEB_HANDSHAPED` names the bespoke facades that
live in hand-written files under `api/`, and `CLASS_POLICY[...]["custom"]` carries the Web-specific
members the contract cannot express (compositions over several opcodes, Kotlin-side mirrors,
lifetime helpers). Both are checked by `--check`, which also fails if a hand-written file under
`api/` dispatches an opcode the generated tree owns.

Usage:
    python3 scripts/generate_web_wrappers.py            # regenerate the tree
    python3 scripts/generate_web_wrappers.py --check    # committed == fresh regen, gate mode
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from generate_web_backend import SIGNATURES  # noqa: E402  (SPI parameter list per call shape)
from platform_backend_contract import INITIAL_BACKEND_CALLS, BackendCallPolicy  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
API_PATH = ROOT / "extension_api.json"
API_DIR = ROOT / "web-runtime/src/commonMain/kotlin/net/multigesture/kanama/api"
GENERATED_DIR = API_DIR / "generated"
TAG = "[web_wrappers]"

HEADER = "// Generated by scripts/generate_web_wrappers.py — do not edit.\n"


class GenerationError(RuntimeError):
    pass


# --------------------------------------------------------------------------------------------------
# extension_api.json access
# --------------------------------------------------------------------------------------------------


class Api:
    def __init__(self, path: Path = API_PATH) -> None:
        payload = json.loads(path.read_text())
        self.classes: dict[str, dict] = {c["name"]: c for c in payload["classes"]}
        self.utilities: dict[str, dict] = {u["name"]: u for u in payload["utility_functions"]}
        self.global_enums: dict[str, dict] = {e["name"]: e for e in payload["global_enums"]}
        self.singletons: set[str] = {s["name"] for s in payload.get("singletons", ())}

    def parent(self, name: str) -> str | None:
        return self.classes[name].get("inherits")

    def chain(self, name: str) -> list[str]:
        out = []
        while name:
            out.append(name)
            name = self.parent(name)
        return out

    def method(self, call: BackendCallPolicy) -> dict:
        if call.scope == "utility":
            return self.utilities[call.method_name]
        for method in self.classes[call.class_name].get("methods", ()):
            if method["name"] == call.method_name and method["hash"] == call.expected_hash:
                return method
        raise GenerationError(f"opcode {call.opcode}: {call.class_name}.{call.method_name} not in API")

    def property_for(self, class_name: str, method_name: str) -> dict | None:
        """The non-indexed property of `class_name` (or an ancestor) that `method_name` gets/sets."""
        for owner in self.chain(class_name):
            for prop in self.classes[owner].get("properties", ()):
                if "index" in prop:
                    continue
                if prop.get("setter") == method_name or prop.get("getter") == method_name:
                    return prop
        return None

    def enum_values(self, owner: str, enum: str) -> dict[str, int]:
        source = (
            self.global_enums.get(enum)
            if owner == "@GlobalScope"
            else next((e for e in self.classes[owner].get("enums", ()) if e["name"] == enum), None)
        )
        if source is None:
            raise GenerationError(f"enum {owner}.{enum} not in API")
        return {v["name"]: v["value"] for v in source["values"]}

    def constant(self, owner: str, name: str) -> int:
        for constant in self.classes[owner].get("constants", ()):
            if constant["name"] == name:
                return constant["value"]
        raise GenerationError(f"constant {owner}.{name} not in API")

    def has_signal(self, class_name: str, signal: str) -> bool:
        return any(
            s["name"] == signal
            for owner in self.chain(class_name)
            for s in self.classes[owner].get("signals", ())
        )


# --------------------------------------------------------------------------------------------------
# Naming
# --------------------------------------------------------------------------------------------------

KEYWORD_RENAMES = {"internal": "internalMode", "class": "className", "object": "target", "RID": "rid"}


def camel(snake: str) -> str:
    parts = snake.split("_")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def param_name(godot_name: str) -> str:
    return KEYWORD_RENAMES.get(godot_name, camel(godot_name))


def kotlin_class_name(godot_name: str) -> str:
    return "GodotObject" if godot_name == "Object" else godot_name


# --------------------------------------------------------------------------------------------------
# Type mapping. Kotlin public types follow the desktop generator (`wrapper_model.value_policy`):
# int32-meta ints are Int, everything else Long, enums/bitfields Long, float Double. Conversions to
# and from the SPI's contract value types are one-liners on the generated support file.
# --------------------------------------------------------------------------------------------------

INT32_METAS = {"int8", "int16", "int32", "char32", "uint8", "uint16"}
VALUE_TYPES = {"Vector2", "Vector3", "Vector2i", "Vector3i", "Color", "Rect2", "Basis", "Transform3D"}
STRING_TYPES = {"String", "StringName", "NodePath"}
# SPI value type -> Kotlin API type, for Variant-typed arguments whose shape fixes the type.
SPI_TO_API = {
    "Boolean": "Boolean",
    "Int": "Int",
    "Long": "Long",
    "Double": "Double",
    "String": "String",
    "GodotVector2": "Vector2",
    "GodotVector3": "Vector3",
    "GodotVector2i": "Vector2i",
    "GodotVector3i": "Vector3i",
    "GodotColor": "Color",
    "GodotRect2": "Rect2",
    "GodotBasis": "Basis",
    "GodotTransform3D": "Transform3D",
}


def int_type(meta: str) -> str:
    return "Int" if meta in INT32_METAS else "Long"


@dataclass
class Tree:
    """The generated class set: every contract class plus its Godot ancestors plus EXTRA_CLASSES."""

    api: Api
    classes: set[str]

    def wrapper_for(self, godot_type: str) -> str:
        """Kotlin wrapper for an object-typed slot: the class, else its nearest generated ancestor."""
        name = godot_type.split("::")[-1]
        for owner in self.api.chain(name) if name in self.api.classes else ["Object"]:
            if owner in self.classes or owner == "Object":
                return kotlin_class_name(owner)
        return "GodotObject"

    def is_object(self, godot_type: str) -> bool:
        return godot_type in self.api.classes or godot_type in ("Object", "Variant")


def api_param_type(tree: Tree, godot_type: str, meta: str, spi_type: str) -> str:
    """Kotlin parameter type for a Godot argument bound to an SPI slot of `spi_type`."""
    if godot_type == "bool":
        return "Boolean"
    if godot_type == "int":
        return int_type(meta)
    if godot_type.startswith("enum::") or godot_type.startswith("bitfield::"):
        return "Long"
    if godot_type == "float":
        return "Double"
    if godot_type in STRING_TYPES:
        return "String"
    if godot_type in VALUE_TYPES:
        return godot_type
    if godot_type == "Variant":
        if spi_type.startswith("GodotHandle"):
            return "GodotObject" + ("?" if spi_type.endswith("?") else "")
        return SPI_TO_API[spi_type]
    if godot_type == "RID":
        return "GodotObject"  # Web adaptation: the applier derives the RID engine-side.
    if tree.is_object(godot_type):
        return tree.wrapper_for(godot_type) + ("?" if spi_type.endswith("?") else "")
    raise GenerationError(f"no Kotlin parameter type for Godot type {godot_type!r}")


def to_backend(expr: str, kotlin_type: str, spi_type: str) -> str:
    """Expression converting a Kotlin API value to the SPI slot type."""
    if spi_type in ("GodotHandle", "GodotHandle?"):
        return f"{expr}?.requireOpenHandle()" if kotlin_type.endswith("?") else f"{expr}.requireOpenHandle()"
    if spi_type == "Long" and kotlin_type == "Int":
        return f"{expr}.toLong()"
    if spi_type.startswith("Godot"):
        return f"{expr}.toBackend()"
    return expr


def api_return(tree: Tree, godot_type: str, meta: str, spi_ret: str) -> tuple[str, str]:
    """(Kotlin return type, conversion suffix applied to the SPI result expression)."""
    if spi_ret == "":
        return "", ""
    if spi_ret in ("Boolean", "Double", "String"):
        return spi_ret, ""
    if spi_ret == "Int":
        return ("Long", ".toLong()") if godot_type == "int" and int_type(meta) == "Long" else ("Int", "")
    if spi_ret == "Long":
        if godot_type == "int" and int_type(meta) == "Int":
            return "Int", ".toInt()"
        return "Long", ""
    if spi_ret == "List<String>":
        return "List<String>", ""
    if spi_ret == "List<GodotVector3i>":
        return "List<Vector3i>", ".map { it.toApi() }"
    if spi_ret in SPI_TO_API:
        return SPI_TO_API[spi_ret], ".toApi()"
    if spi_ret == "GodotHandle?":
        wrapper = tree.wrapper_for(godot_type) if godot_type != "Variant" else "GodotObject"
        return f"{wrapper}?", f"?.let {{ {wrapper}(it.toWebId()) }}"
    if spi_ret == "List<GodotHandle>":
        element = godot_type.split("::")[-1]
        wrapper = tree.wrapper_for(element)
        return f"List<{wrapper}>", f".map {{ {wrapper}(it.toWebId()) }}"
    raise GenerationError(f"no Kotlin return mapping for SPI type {spi_ret!r}")


def kotlin_default(godot_default: str, kotlin_type: str) -> str | None:
    """Kotlin literal for a Godot default value, or None when it cannot be expressed."""
    if godot_default in ("null", "[]", "{}"):
        return None
    if kotlin_type == "Boolean":
        return godot_default
    if kotlin_type == "Int":
        return str(int(godot_default))
    if kotlin_type == "Long":
        return f"{int(godot_default)}L"
    if kotlin_type == "Double":
        return repr(float(godot_default))
    if kotlin_type == "String":
        return '"' + godot_default.lstrip("&").strip('"') + '"'
    known = {
        "Vector3(0, 0, 0)": "Vector3.ZERO",
        "Vector3(0, 1, 0)": "Vector3.UP",
        "Vector2(0, 0)": "Vector2.ZERO",
        "Color(1, 1, 1, 1)": "Color(1f, 1f, 1f, 1f)",
    }
    if godot_default in known:
        return known[godot_default]
    raise GenerationError(f"no Kotlin default for {godot_default!r} as {kotlin_type}")


# --------------------------------------------------------------------------------------------------
# Rendering (filled in family by family)
# --------------------------------------------------------------------------------------------------


@dataclass
class Param:
    name: str
    kotlin_type: str
    default: str | None = None
    backend_expr: str | None = None  # None for baked (not carried) arguments
    guard: str | None = None


@dataclass
class Member:
    """One rendered class member plus its top-level import-compat alias."""

    body: list[str]
    alias: list[str] = field(default_factory=list)
    name: str = ""


def spi_slots(shape: str) -> tuple[bool, list[tuple[str, str]]]:
    """(has receiver, [(slot name, slot type)]) for a call shape's GodotBackendCalls facade."""
    params, _ = SIGNATURES[shape]
    slots = [tuple(p.split(": ", 1)) for p in params]
    has_receiver = bool(slots) and slots[0][0] == "receiver"
    return has_receiver, [(n, t) for n, t in slots if n != "receiver"]


def invoke_name(shape: str) -> str:
    from generate_web_backend import _method_name

    return _method_name(shape)


def descriptor_name(call: BackendCallPolicy) -> str:
    if call.descriptor_name:
        return call.descriptor_name
    owner = "UTILITY" if call.class_name == "@GlobalScope" else call.class_name.upper()
    return f"{owner}_{call.method_name.upper()}"


def member_name(call: BackendCallPolicy, policy: dict) -> str:
    if "name" in policy:
        return str(policy["name"])
    return camel(call.method_name)


def bind_arguments(tree: Tree, call: BackendCallPolicy, method: dict, policy: dict) -> list[Param]:
    """Bind the shape's SPI slots to the Godot arguments positionally; the rest are baked."""
    _, slots = spi_slots(call.shape)
    godot_args = list(method.get("arguments", ()))
    for i, tail_type in enumerate(call.typed_vararg_tail):
        godot_args.append({"name": f"__tail{i}", "type": tail_type})
    if len(slots) > len(godot_args):
        raise GenerationError(
            f"opcode {call.opcode}: shape {call.shape} carries {len(slots)} values but "
            f"{call.class_name}.{call.method_name} has {len(godot_args)} arguments; add a `bind` policy"
        )
    params: list[Param] = []
    tail_names = list(policy.get("tail_names", ()))
    for (slot_name, slot_type), arg in zip(slots, godot_args):
        if arg["name"].startswith("__tail"):
            name = tail_names.pop(0) if tail_names else slot_name
        else:
            name = param_name(arg["name"])
        kotlin_type = policy.get("param_types", {}).get(name) or api_param_type(
            tree, arg["type"], arg.get("meta", ""), slot_type
        )
        default = kotlin_default(arg["default_value"], kotlin_type) if "default_value" in arg else None
        params.append(Param(name, kotlin_type, default, to_backend(name, kotlin_type, slot_type)))
    label = f"{call.class_name}.{call.method_name}"
    baked_values = dict(policy.get("baked", {}))
    for arg in godot_args[len(slots) :]:
        name = param_name(arg["name"])
        if name in policy.get("hide", ()):
            continue
        kotlin_type = api_param_type(tree, arg["type"], arg.get("meta", ""), "GodotHandle?")
        if name in baked_values:
            default = str(baked_values.pop(name))
        elif "default_value" in arg:
            default = kotlin_default(arg["default_value"], kotlin_type)
            if default is None:
                continue  # Variant/Array defaults the shape cannot carry are not exposed at all
        else:
            raise GenerationError(f"{label}: argument {name} is not carried and has no default; add `baked`")
        guard = f'require({name} == {default}) {{ "Web {label} supports only {name} = {default}" }}'
        params.append(Param(name, kotlin_type, default, None, guard))
    if baked_values:
        raise GenerationError(f"{label}: baked policy names unknown arguments {sorted(baked_values)}")
    return params


MAX_WIDTH = 100


def wrap_call(prefix: str, args: list[str], suffix: str, indent: str) -> list[str]:
    """`prefix(args)suffix` on one line when it fits, else one argument per line (ktfmt shape)."""
    one_line = f"{indent}{prefix}({', '.join(args)}){suffix}"
    if len(one_line) <= MAX_WIDTH or not args:
        return [one_line]
    lines = [f"{indent}{prefix}("]
    lines += [f"{indent}  {arg}," for arg in args]
    lines.append(f"{indent}){suffix}")
    return lines


def render_signature(name: str, params: list[Param], ret: str, modifiers: str = "", indent: str = "  ") -> list[str]:
    rendered = [
        f"{p.name}: {p.kotlin_type}" + (f" = {p.default}" if p.default is not None else "") for p in params
    ]
    suffix = f": {ret}" if ret else ""
    return wrap_call(f"{modifiers}fun {name}", rendered, suffix, indent)


def emit_opcode(tree: Tree, call: BackendCallPolicy, policy: dict) -> Member:
    api = tree.api
    method = api.method(call)
    has_receiver, _ = spi_slots(call.shape)
    name = member_name(call, policy)
    if "bind" in policy:
        params = [Param(*spec) for spec in policy["bind"]]
    else:
        params = bind_arguments(tree, call, method, policy)
    godot_ret = method.get("return_value", {}).get("type", method.get("return_type", "void"))
    ret_meta = method.get("return_value", {}).get("meta", "")
    _, spi_ret = SIGNATURES[call.shape]
    ret, convert = api_return(tree, godot_ret, ret_meta, spi_ret)
    if "ret" in policy:
        ret = str(policy["ret"])
        convert = ""
        if ret == "Unit":
            ret = ""
    if policy.get("raw_handle_return"):
        ret, convert = "GodotHandle?", "?.let { it.toWebId() }"
    nonnull = policy.get("nonnull")
    call_args = [f"D.{descriptor_name(call)}"]
    if has_receiver:
        call_args.append("requireOpenHandle()")
    if "args" in policy:
        call_args += list(policy["args"])
    else:
        call_args += [p.backend_expr for p in params if p.backend_expr is not None]
    call_args += list(policy.get("extra_args", ()))
    invoke = f"GodotBackendCalls.{invoke_name(call.shape)}"
    guards = [p.guard for p in params if p.guard] + list(policy.get("guards", ()))
    pre = list(policy.get("pre", ()))
    post = list(policy.get("post", ()))
    fluent = policy.get("fluent")
    owner = kotlin_class_name(call.class_name) if call.class_name != "@GlobalScope" else "GD"
    if fluent:
        ret = owner
    if nonnull:
        ret = ret.rstrip("?")
    modifiers = ""
    if policy.get("visibility"):
        modifiers += f"{policy['visibility']} "
    if policy.get("open"):
        modifiers += "open "
    doc = policy.get("doc")
    body: list[str] = []
    if doc:
        body.append(f"  /** {doc} */")
    signature = render_signature(name, params, ret, modifiers)
    expression_body = not (guards or pre or post or fluent or nonnull or "body" in policy)
    if expression_body and ret:
        body += signature[:-1] + [signature[-1] + " ="]
        body += wrap_call(invoke, call_args, convert, "    ")
        return Member(body, _alias(owner, name, params, ret), name)
    body += signature[:-1] + [signature[-1] + " {"]
    if "body" in policy:
        body += [f"    {line}" for line in policy["body"]]
    else:
        body += [f"    {line}" for line in pre]
        body += [f"    {g}" for g in guards]
        if fluent:
            body += wrap_call(invoke, call_args, "", "    val returned = ")
            same = "returned.backendToken() == backendHandle.backendToken()"
            if fluent == "self":
                body.append(f"    check(returned != null && {same}) {{ \"{owner}.{name} did not return its receiver\" }}")
                body.append("    return this")
            else:
                body.append(f"    return if (returned == null || {same}) this else {owner}(returned.toWebId())")
        elif nonnull:
            body += wrap_call(invoke, call_args, convert, "    val returned = ")
            body.append(f'    return checkNotNull(returned) {{ "{nonnull}" }}')
        elif post:
            body += wrap_call(invoke, call_args, convert, "    ")
            body += [f"    {line}" for line in post]
        else:
            body += wrap_call(invoke, call_args, convert, "    return " if ret else "    ")
    body.append("  }")
    alias = [] if policy.get("visibility") in ("internal", "protected", "private") else _alias(owner, name, params, ret)
    return Member(body, alias, name)


def _alias(owner: str, name: str, params: list[Param], ret: str) -> list[str]:
    """Import-compat extension so `import net.multigesture.kanama.api.<name>` keeps resolving."""
    forward = ", ".join(p.name for p in params)
    lines = ['@Suppress("EXTENSION_SHADOWED_BY_MEMBER")']
    signature = render_signature(f"{owner}.{name}", params, ret, indent="")
    lines += signature[:-1] + [f"{signature[-1]} = {name}({forward})"]
    return lines


# --------------------------------------------------------------------------------------------------
# Web-local wrapper policy. Per-opcode overrides where the contract alone does not fix the Kotlin
# spelling; per-class hand-shaped members (custom sections), factories, lifetimes and constants.
# --------------------------------------------------------------------------------------------------

_UNIT = 'section + "\\u001F" + key'  # the applier splits packed ConfigFile keys on the unit separator

WRAPPER_POLICY: dict[int, dict] = {
    # Callable-taking calls: the shape carries (target, method) in place of Godot's Callable.
    22: {
        "visibility": "internal",
        "bind": [
            ("signal", "String", None, "signal"),
            ("target", "GodotObject", None, "target.requireOpenHandle()"),
            ("method", "String", None, "method"),
            ("flags", "Long", "0L", "flags"),
        ],
    },
    34: {
        "name": "connectBound",
        "visibility": "internal",
        "bind": [
            ("signal", "String", None, "signal"),
            ("target", "GodotObject", None, "target.requireOpenHandle()"),
            ("method", "String", None, "method"),
            ("boundValue", "Long", None, "boundValue"),
            ("flags", "Long", "0L", "flags"),
        ],
    },
    193: {
        "name": "disconnectBound",
        "visibility": "internal",
        "ret": "Unit",
        "bind": [
            ("signal", "String", None, "signal"),
            ("target", "GodotObject", None, "target.requireOpenHandle()"),
            ("method", "String", None, "method"),
            ("boundValue", "Long", None, "boundValue"),
        ],
        "extra_args": ["-1L"],
    },
    137: {
        "ret": "Unit",
        "doc": "Chain a callback step to a registered method on a Kanama script (FPS change_weapon).",
        "bind": [("target", "GodotObject", None, "target.requireOpenHandle()"), ("method", "String", None, "method")],
    },
    192: {
        "ret": "Unit",
        "doc": "Tween a registered method with an interpolated double (the Callable binds proxy-side).",
        "bind": [
            ("target", "GodotObject", None, "target.requireOpenHandle()"),
            ("method", "String", None, "method"),
            ("from", "Double", None, "from"),
            ("to", "Double", None, "to"),
            ("duration", "Double", None, "duration"),
        ],
    },
    # The shape carries the surface only; the material is baked to null (clear the override).
    189: {"baked": {"material": "null"}, "doc": "Web supports only clearing an override (material baked null in the family)."},
    # ConfigFile keys ride one StringName packed with a unit separator; values carry a type tag.
    266: {"bind": [("section", "String", None, None), ("key", "String", None, None)], "args": [_UNIT]},
    267: {
        "bind": [("section", "String", None, None), ("key", "String", None, None), ("value", "Any?", None, None)],
        "pre": [
            "val tagged =",
            "  when (value) {",
            '    is Boolean -> "b:$value"',
            '    is Long -> "i:$value"',
            '    is Int -> "i:$value"',
            '    is Double -> "f:$value"',
            '    is String -> "s:$value"',
            '    else -> error("Kanama Web ConfigFile does not carry ${value?.let { it::class }} values")',
            "  }",
        ],
        "args": [_UNIT + ' + "\\u001F" + tagged'],
    },
    268: {
        "ret": "Any?",
        "bind": [("section", "String", None, None), ("key", "String", None, None)],
        "body": [
            "val tagged =",
            f"  GodotBackendCalls.invokeStringNameRetString(D.CONFIGFILE_GET_VALUE, requireOpenHandle(), {_UNIT})",
            "val body = tagged.drop(2)",
            "return when {",
            '  tagged.startsWith("b:") -> body == "true"',
            '  tagged.startsWith("i:") -> body.toLong()',
            '  tagged.startsWith("f:") -> body.toDouble()',
            '  tagged.startsWith("s:") -> body',
            "  else -> null",
            "}",
        ],
    },
    # propagate_call("set", [property, value]) with a Boolean value (the shadow-mapping sweep).
    279: {
        "name": "propagateSet",
        "doc": 'Godot\'s `propagate_call("set", [property, value])` (the shadow-mapping sweep).',
        "bind": [("property", "String", None, "property"), ("value", "Boolean", None, "value")],
    },
}
CLASS_POLICY: dict[str, dict] = {}
# Leaf and intermediate Godot classes the corpus types against that own no opcode themselves.
EXTRA_CLASSES: tuple[str, ...] = (
    "AnimationTree", "Area2D", "AudioStream", "BoneAttachment3D", "ColorRect", "LightmapGIData",
    "Marker2D", "Marker3D", "MultiMeshInstance3D", "OmniLight3D", "ProgressBar", "SpinBox",
    "SpotLight3D", "StaticBody3D", "Texture2D", "TextureButton",
)
# Bespoke facades that stay hand-written under api/ (name -> why the generator cannot emit it).
WEB_HANDSHAPED: dict[str, str] = {
    "Window": "handle-less browser-window mirror shared with the handle-backed root window (tps settings menu)",
    "PhysicsDirectSpaceState3D": "owner-bound facade; the ray query packs a Dictionary result into one string",
}
# Opcodes a hand-written facade in WEB_HANDSHAPED may dispatch directly.
HANDSHAPED_OPCODES: frozenset[str] = frozenset(
    {"WINDOW_SET_MODE", "WINDOW_GET_MODE", "PHYSICSDIRECTSPACESTATE3D_INTERSECT_RAY"}
)

PACKAGE_IMPORTS = {
    "GodotBackendCalls": "net.multigesture.kanama.backend.GodotBackendCalls",
    "D.": "net.multigesture.kanama.backend.InitialGodotCallDescriptors as D",
    "BackendGodotHandle": "net.multigesture.kanama.backend.GodotHandle as BackendGodotHandle",
    "WebObjectId": "net.multigesture.kanama.web.WebObjectId",
    "Vector2": "net.multigesture.kanama.types.Vector2",
    "Vector3": "net.multigesture.kanama.types.Vector3",
    "Vector2i": "net.multigesture.kanama.types.Vector2i",
    "Vector3i": "net.multigesture.kanama.types.Vector3i",
    "Color": "net.multigesture.kanama.types.Color",
    "Rect2": "net.multigesture.kanama.types.Rect2",
    "Basis": "net.multigesture.kanama.types.Basis",
    "Transform3D": "net.multigesture.kanama.types.Transform3D",
    "Quaternion": "net.multigesture.kanama.types.Quaternion",
    "NodePath": "net.multigesture.kanama.types.NodePath",
}


def build_tree(api: Api) -> Tree:
    classes: set[str] = set()
    for call in INITIAL_BACKEND_CALLS:
        if call.class_name != "@GlobalScope":
            classes.update(api.chain(call.class_name))
    for extra in EXTRA_CLASSES:
        classes.update(api.chain(extra))
    classes -= set(WEB_HANDSHAPED)
    return Tree(api, classes)


def imports_for(body: str, extra: list[str]) -> list[str]:
    imports = set(extra)
    for token, statement in PACKAGE_IMPORTS.items():
        if re.search(r"(?<![A-Za-z0-9_.])" + re.escape(token), body):
            imports.add(statement)
    return sorted(imports)


def file_text(body_lines: list[str], extra_imports: list[str]) -> str:
    body = "\n".join(body_lines)
    imports = imports_for(body, extra_imports)
    parts = [HEADER.rstrip("\n"), "@file:OptIn(InternalKanamaBackendApi::class)", "", "package net.multigesture.kanama.api", ""]
    parts += [f"import {i}" for i in imports]
    parts.append("import net.multigesture.kanama.backend.InternalKanamaBackendApi")
    parts += ["", body, ""]
    return "\n".join(parts)


def emit_properties(tree: Tree, godot_name: str, calls: list[BackendCallPolicy]) -> list[Member]:
    """Kotlin properties for every API property whose getter or setter is an admitted opcode.

    Both accessors admitted -> `var`; setter only -> write-only `var` whose getter names the
    missing engine getter through the coverage marker; getter only -> `val`. Accessors delegate to
    the generated methods, so conversions live in one place.
    """
    api = tree.api
    if godot_name not in api.classes:
        return []  # @GlobalScope utilities have no property table
    owner = kotlin_class_name(godot_name)
    by_method = {call.method_name: call for call in calls if not WRAPPER_POLICY.get(call.opcode, {}).get("no_property")}
    props: dict[str, dict] = {}
    for call in calls:
        prop = api.property_for(godot_name, call.method_name)
        if prop is not None and not WRAPPER_POLICY.get(call.opcode, {}).get("no_property"):
            props.setdefault(prop["name"], prop)
    members: list[Member] = []
    for prop_name, prop in props.items():
        getter = by_method.get(prop.get("getter", ""))
        setter = by_method.get(prop.get("setter", ""))
        kotlin_name = camel(prop_name)
        if getter is not None:
            getter_method = api.method(getter)
            kotlin_type, _ = api_return(
                tree,
                getter_method.get("return_value", {}).get("type", "void"),
                getter_method.get("return_value", {}).get("meta", ""),
                SIGNATURES[getter.shape][1],
            )
            get_expr = f"{member_name(getter, WRAPPER_POLICY.get(getter.opcode, {}))}()"
        else:
            setter_method = api.method(setter)
            arg = setter_method["arguments"][0]
            kotlin_type = api_param_type(tree, arg["type"], arg.get("meta", ""), spi_slots(setter.shape)[1][0][1])
            get_expr = f'unsupportedWebGameplayFamily("{godot_name}.{prop.get("getter", "get_" + prop_name)}")'
        body = [f"  {'var' if setter else 'val'} {kotlin_name}: {kotlin_type}", f"    get() = {get_expr}"]
        alias = ['@Suppress("EXTENSION_SHADOWED_BY_MEMBER")', f"{'var' if setter else 'val'} {owner}.{kotlin_name}: {kotlin_type}", f"  get() = {kotlin_name}"]
        if setter is not None:
            set_name = member_name(setter, WRAPPER_POLICY.get(setter.opcode, {}))
            body.append(f"    set(value) = {set_name}(value)")
            alias += ["  set(value) {", f"    {kotlin_name} = value", "  }"]
        members.append(Member(body, alias, kotlin_name))
    return members


def emit_constants(api: Api, godot_name: str, class_policy: dict) -> list[str]:
    """`const val` lines: whole enums (`enums`), single class constants, from extension_api.json."""
    lines: list[str] = []
    for spec in class_policy.get("enums", ()):
        owner, enum = spec.split(".") if "." in spec else (godot_name, spec)
        for const_name, value in api.enum_values(owner, enum).items():
            lines.append(f"    const val {const_name}: Long = {value}L")
    for const_name in class_policy.get("constants", ()):
        lines.append(f"    const val {const_name}: Long = {api.constant(godot_name, const_name)}L")
    return lines


def emit_signals(api: Api, godot_name: str, class_policy: dict) -> list[str]:
    names = class_policy.get("signals", ())
    if not names:
        return []
    lines = ["  object Signals {"]
    for signal in names:
        if not api.has_signal(godot_name, signal):
            raise GenerationError(f"{godot_name} has no signal {signal}")
        lines.append(f'    const val {camel(signal)}: String = "{signal}"')
    lines.append("  }")
    return lines


def emit_companion(godot_name: str, class_policy: dict, constants: list[str]) -> list[str]:
    """Companion: factories (`instantiable`, `from_*`), constants, and the policy's own text."""
    name = kotlin_class_name(godot_name)
    lines: list[str] = []
    if class_policy.get("instantiable"):
        lines += [
            f"    /** Constructs a new {godot_name} engine-side; the wrapper owns the handle (close what you create). */",
            f"    fun create(): {name} =",
            f'      {name}(checkNotNull(ClassDB.instantiate("{godot_name}")) {{ "Godot could not instantiate {godot_name}" }}.toWebId())',
        ]
    if class_policy.get("from_class_check"):
        lines += [
            f"    /** Engine-side class check: null when [value] is not a {godot_name}. */",
            f"    fun from(value: GodotObject): {name}? =",
            f'      value.takeIf {{ it.isClass("{godot_name}") }}?.let {{ {name}(it.handle) }}',
        ]
    if class_policy.get("from_object"):
        lines += [
            f"    /** Re-types any Godot object as a {godot_name} (the Web bridge carries no class metadata). */",
            f"    fun fromObject(value: GodotObject?): {name}? = value?.let {{ {name}(it.handle) }}",
        ]
    if class_policy.get("from_object_checked"):
        lines += [
            f"    fun fromObject(value: GodotObject?): {name}? =",
            f'      value?.takeIf {{ it.isClass("{godot_name}") }}?.let {{ {name}(it.handle) }}',
        ]
    if class_policy.get("from_resource"):
        lines += [f"    fun fromResource(resource: Resource?): {name}? = resource?.let {{ {name}(it.handle) }}"]
    if class_policy.get("from_handle"):
        lines += [f"    fun fromHandle(handle: GodotHandle): {name} = {name}(handle)"]
    if constants:
        if lines:
            lines.append("")
        lines += constants
    if class_policy.get("companion"):
        if lines:
            lines.append("")
        lines += class_policy["companion"].rstrip("\n").split("\n")
    if not lines:
        return []
    return ["  companion object {", *lines, "  }"]


RELEASE_CALLS = {
    "resource": "releaseWebResource",
    "constructed": "releaseWebConstructedObject",
    "tracked": "releaseWebTrackedObject",
    "collision": "releaseWebCollision",
}


def emit_release(godot_name: str, class_policy: dict) -> list[str]:
    """`close()` for owning wrappers; `guard` adds the closed flag + receiver guard (use-after-close)."""
    kind = class_policy.get("release")
    if not kind:
        return []
    name = kotlin_class_name(godot_name)
    release = RELEASE_CALLS[kind]
    if class_policy.get("guard"):
        return [
            "  private var closed = false",
            "",
            "  override fun requireOpenHandle(): BackendGodotHandle {",
            f'    check(!closed) {{ "{name} is closed" }}',
            "    return backendHandle",
            "  }",
            "",
            "  /** Releases the owned handle; a second close is a no-op, any later call fails loud. */",
            "  fun close() {",
            "    if (closed) return",
            "    closed = true",
            f"    {release}(handle.value)",
            "  }",
        ]
    return [
        "  /** Releases the owned handle (already-released is an error). */",
        "  fun close() {",
        f"    {release}(handle.value)",
        "  }",
    ]


def render_class(tree: Tree, godot_name: str, calls: list[BackendCallPolicy]) -> str:
    api = tree.api
    name = kotlin_class_name(godot_name)
    class_policy = CLASS_POLICY.get(godot_name, {})
    singleton = godot_name in api.singletons or godot_name == "@GlobalScope"
    members = [emit_opcode(tree, call, WRAPPER_POLICY.get(call.opcode, {})) for call in calls]
    members += emit_properties(tree, godot_name, calls)
    lines: list[str] = []
    if singleton:
        object_name = "GD" if godot_name == "@GlobalScope" else name
        visibility = class_policy.get("visibility", "")
        lines.append(f"{visibility + ' ' if visibility else ''}object {object_name} {{")
    else:
        parent = api.parent(godot_name)
        while parent is not None and parent not in tree.classes and parent != "Object":
            parent = api.parent(parent)
        has_children = any(api.parent(c) == godot_name for c in tree.classes)
        open_ = "open " if has_children or class_policy.get("open") else ""
        if godot_name == "Object":
            lines.append(f"{open_}class GodotObject(godotObject: GodotHandle) {{")
            lines.append("  internal val backendHandle: BackendGodotHandle = godotObject.toBackendHandle()")
            lines.append("")
            lines.append("  /** The live backend handle; guarded wrappers (closeable resources) override this. */")
            lines.append("  internal open fun requireOpenHandle(): BackendGodotHandle = backendHandle")
            lines.append("")
        else:
            lines.append(f"{open_}class {name}(godotObject: GodotHandle) : {kotlin_class_name(parent)}(godotObject) {{")
    sections: list[list[str]] = [m.body for m in members]
    if class_policy.get("custom"):
        sections.append(class_policy["custom"].rstrip("\n").split("\n"))
    sections.append(emit_release(godot_name, class_policy))
    sections.append(emit_signals(api, godot_name, class_policy))
    constants = emit_constants(api, godot_name, class_policy)
    if singleton:
        # An `object` has no companion: constants and factories sit directly in its body.
        sections.append([line[2:] for line in constants])
        if class_policy.get("companion"):
            sections.append(class_policy["companion"].rstrip("\n").split("\n"))
    else:
        sections.append(emit_companion(godot_name, class_policy, constants))
    first = True
    for section in sections:
        if not section:
            continue
        if not first or godot_name == "Object":
            lines.append("")
        first = False
        lines += section
    lines.append("}")
    for member in members:
        if member.alias:
            lines.append("")
            lines += member.alias
    if class_policy.get("top_level"):
        lines.append("")
        lines += class_policy["top_level"].rstrip("\n").split("\n")
    return file_text(lines, list(class_policy.get("imports", ())))


def render_all(api: Api) -> dict[str, str]:
    """Render every generated file: file name -> content."""
    tree = build_tree(api)
    by_class: dict[str, list[BackendCallPolicy]] = {c: [] for c in tree.classes}
    by_class["@GlobalScope"] = []
    for call in INITIAL_BACKEND_CALLS:
        if call.class_name in WEB_HANDSHAPED:
            if descriptor_name(call) not in HANDSHAPED_OPCODES:
                raise GenerationError(f"opcode {call.opcode} belongs to hand-shaped {call.class_name} but is not allowlisted")
            continue
        by_class[call.class_name].append(call)
    files: dict[str, str] = {}
    for godot_name, calls in by_class.items():
        file_name = ("GD" if godot_name == "@GlobalScope" else kotlin_class_name(godot_name)) + ".kt"
        files[file_name] = render_class(tree, godot_name, sorted(calls, key=lambda c: c.opcode))
    return files


# --------------------------------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=GENERATED_DIR)
    parser.add_argument("--check", action="store_true", help="fail if the committed tree drifts")
    args = parser.parse_args()

    api = Api()
    rendered = render_all(api)
    out_dir: Path = args.output_dir

    if args.check:
        failures: list[str] = []
        committed = {p.name: p for p in out_dir.glob("*.kt")} if out_dir.is_dir() else {}
        for name, text in rendered.items():
            path = committed.pop(name, None)
            if path is None:
                failures.append(f"missing generated file {name}")
            elif path.read_text() != text:
                failures.append(f"drift in {name}")
        for name in sorted(committed):
            failures.append(f"stray file in generated tree: {name}")
        if failures:
            for failure in failures:
                print(f"{TAG} FAIL {failure}", file=sys.stderr)
            print(f"{TAG} run scripts/generate_web_wrappers.py to regenerate", file=sys.stderr)
            return 1
        print(f"{TAG} PASS {len(rendered)} generated files match the contract")
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    for stale in out_dir.glob("*.kt"):
        if stale.name not in rendered:
            stale.unlink()
    for name, text in rendered.items():
        (out_dir / name).write_text(text)
    print(f"{TAG} wrote {len(rendered)} files to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
