#!/usr/bin/env python3
"""Generate the value types' builtin operators and methods from extension_api.json (task 134 B).

Godot declares, per builtin class, an operator list (`builtin_classes[*].operators`) and a method
list (`builtin_classes[*].methods`). This generator gives every value type (Vector2 ... Color,
plus RID) a Kotlin member for each of them, in one region per class it owns:

  // ===== BEGIN GENERATED BUILTIN MEMBERS: Vector2 (generate_builtin_ops.py) =====
  // ===== BEGIN GENERATED BUILTIN STATICS: Vector2 (generate_builtin_ops.py) =====  (in the companion)

Two implementations, chosen per member:

* **pure Kotlin** -- every operator, and the methods in PURE_METHODS: Godot's own formula, ported
  with Godot's operand order and evaluated at the stored `real_t` width (component-wise ones are
  emitted from templates here; the composite ones call the hand-ported formulas in
  `types/BuiltinFormulas.kt` and `types/shared/RealMath.kt`/`BuiltinMath.kt`), so the result is the
  engine's to the bit;
* **the BuiltinCalls facade** -- every other method: the engine runs it (exact Godot semantics,
  edge cases and MATH_CHECKS errors included).

Members that are already hand-written in the class (outside the regions) are left alone and only
counted. The runtime smoke proves both kinds against GDScript: this generator also writes the
probe pair `example_project/BuiltinParitySmoke.kt` + `builtin_parity_ref.gd`, which print a
per-member FNV hash over fixed-seed random inputs -- every pure member (generated or hand-written)
over PARITY_INPUTS inputs, every facade-backed member over FACADE_INPUTS -- and
`scripts/runtime_smoke.sh` requires the Kotlin and the GDScript line to be identical.

Outputs (all regenerated by --write, compared by --check):
  * the GENERATED BUILTIN regions of `src/commonMain/.../types/<Type>.kt`;
  * `src/commonMain/.../types/BuiltinMarshalling.kt` (layouts, method binds, facade shims);
  * `src/commonMain/.../types/BuiltinScalarOperators.kt` (`2.0 * v`, `points * transform`);
  * the Web value types' GENERATED BUILTIN regions (`web-runtime/.../types/WebValueTypes.kt`) and
    `WebScalarOperators.kt`: the pure members of the classes the Web backend has (it has no
    builtin-call path yet, so facade members wait for parcel D);
  * the parity probe pair above.

The comparison ignores whitespace, trailing commas and KDoc (ktfmt formats the regions and
`sync_kdoc_from_godot_docs.py` documents them), so run `./gradlew ktfmtFormat` and the KDoc sync
after --write. `scripts/check_builtin_coverage.py` is the gate that every API operator and method
has a member or a recorded reason.

Usage:
    python3 scripts/generate_builtin_ops.py --write
    python3 scripts/generate_builtin_ops.py --check
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
API_PATH = ROOT / "extension_api.json"
TYPES_DIR = ROOT / "src/commonMain/kotlin/net/multigesture/kanama/types"
MARSHALLING = TYPES_DIR / "BuiltinMarshalling.kt"
SCALAR_OPS = TYPES_DIR / "BuiltinScalarOperators.kt"
WEB_TYPES_DIR = ROOT / "web-runtime/src/commonMain/kotlin/net/multigesture/kanama/types"
WEB_TYPES = WEB_TYPES_DIR / "WebValueTypes.kt"
WEB_SCALAR_OPS = WEB_TYPES_DIR / "WebScalarOperators.kt"
PARITY_KT = ROOT / "example_project/BuiltinParitySmoke.kt"
PARITY_GD = ROOT / "example_project/builtin_parity_ref.gd"

GENERATOR = "scripts/generate_builtin_ops.py"
# The region markers name the generator without its directory: a marker must fit ktfmt's 100
# columns at a companion's indent, or ktfmt wraps it.
MARKER_GEN = "generate_builtin_ops.py"
BEGIN = "// ===== BEGIN GENERATED BUILTIN MEMBERS: {name} ({gen}) ====="
END = "// ===== END GENERATED BUILTIN MEMBERS: {name} ====="
SBEGIN = "// ===== BEGIN GENERATED BUILTIN STATICS: {name} ({gen}) ====="
SEND = "// ===== END GENERATED BUILTIN STATICS: {name} ====="

PARITY_INPUTS = 256
FACADE_INPUTS = 8

# ---------------------------------------------------------------------------------------------
# The value types: how each is laid out for the facade (Godot's memory layout) and built back.
# ---------------------------------------------------------------------------------------------


@dataclass(frozen=True)
class ValueType:
    name: str
    kind: str  # "real" (real_t components), "int" (int32), "color" (float32)
    pack: tuple[str, ...]  # component expressions on a receiver `v`, in Godot's layout order
    unpack: str  # Kotlin expression over `c[i]` building the value
    tag: str  # PT_* of a real_t struct (BArg.Floats)
    comps: tuple[str, ...] = ()  # component-wise members: the stored components, in order
    web: bool = False  # the Web backend has this class with the same stored components

    @property
    def count(self) -> int:
        return len(self.pack)


def _v(prefix: str, names: str) -> tuple[str, ...]:
    return tuple(f"{prefix}raw{c}" for c in names)


VALUE_TYPES: dict[str, ValueType] = {
    "Vector2": ValueType("Vector2", "real", _v("v.", "XY"), "Vector2.raw(c[0], c[1])", "PT_VECTOR2", ("rawX", "rawY"), web=True),
    "Vector3": ValueType("Vector3", "real", _v("v.", "XYZ"), "Vector3.raw(c[0], c[1], c[2])", "PT_VECTOR3", ("rawX", "rawY", "rawZ"), web=True),
    "Vector4": ValueType("Vector4", "real", _v("v.", "XYZW"), "Vector4.raw(c[0], c[1], c[2], c[3])", "PT_VECTOR4", ("rawX", "rawY", "rawZ", "rawW")),
    "Quaternion": ValueType("Quaternion", "real", _v("v.", "XYZW"), "Quaternion.raw(c[0], c[1], c[2], c[3])", "PT_QUATERNION", ("rawX", "rawY", "rawZ", "rawW"), web=True),
    "Plane": ValueType("Plane", "real", _v("v.normal.", "XYZ") + ("v.rawD",), "Plane.raw(Vector3.raw(c[0], c[1], c[2]), c[3])", "PT_PLANE", web=True),
    "Rect2": ValueType("Rect2", "real", _v("v.position.", "XY") + _v("v.size.", "XY"), "Rect2(Vector2.raw(c[0], c[1]), Vector2.raw(c[2], c[3]))", "PT_RECT2"),
    "AABB": ValueType("AABB", "real", _v("v.position.", "XYZ") + _v("v.size.", "XYZ"), "AABB(Vector3.raw(c[0], c[1], c[2]), Vector3.raw(c[3], c[4], c[5]))", "PT_AABB"),
    "Basis": ValueType(
        "Basis",
        "real",
        ("v.x.rawX", "v.y.rawX", "v.z.rawX", "v.x.rawY", "v.y.rawY", "v.z.rawY", "v.x.rawZ", "v.y.rawZ", "v.z.rawZ"),
        "basisFromRows(c[0], c[1], c[2], c[3], c[4], c[5], c[6], c[7], c[8])",
        "PT_BASIS",
    ),
    "Transform3D": ValueType(
        "Transform3D",
        "real",
        tuple(e.replace("v.", "v.basis.") for e in ("v.x.rawX", "v.y.rawX", "v.z.rawX", "v.x.rawY", "v.y.rawY", "v.z.rawY", "v.x.rawZ", "v.y.rawZ", "v.z.rawZ"))
        + _v("v.origin.", "XYZ"),
        "Transform3D(basisFromRows(c[0], c[1], c[2], c[3], c[4], c[5], c[6], c[7], c[8]), Vector3.raw(c[9], c[10], c[11]))",
        "PT_TRANSFORM3D",
    ),
    "Transform2D": ValueType(
        "Transform2D",
        "real",
        _v("v.x.", "XY") + _v("v.y.", "XY") + _v("v.origin.", "XY"),
        "Transform2D(Vector2.raw(c[0], c[1]), Vector2.raw(c[2], c[3]), Vector2.raw(c[4], c[5]))",
        "PT_TRANSFORM2D",
    ),
    "Projection": ValueType(
        "Projection",
        "real",
        _v("v.x.", "XYZW") + _v("v.y.", "XYZW") + _v("v.z.", "XYZW") + _v("v.w.", "XYZW"),
        "Projection(Vector4.raw(c[0], c[1], c[2], c[3]), Vector4.raw(c[4], c[5], c[6], c[7]), "
        "Vector4.raw(c[8], c[9], c[10], c[11]), Vector4.raw(c[12], c[13], c[14], c[15]))",
        "PT_PROJECTION",
    ),
    "Color": ValueType("Color", "color", ("v.rawR", "v.rawG", "v.rawB", "v.rawA"), "Color.raw(c[0], c[1], c[2], c[3])", "", ("rawR", "rawG", "rawB", "rawA"), web=True),
    "Vector2i": ValueType("Vector2i", "int", ("v.x", "v.y"), "Vector2i(c[0], c[1])", "", ("x", "y"), web=True),
    "Vector3i": ValueType("Vector3i", "int", ("v.x", "v.y", "v.z"), "Vector3i(c[0], c[1], c[2])", "", ("x", "y", "z"), web=True),
    "Vector4i": ValueType("Vector4i", "int", ("v.x", "v.y", "v.z", "v.w"), "Vector4i(c[0], c[1], c[2], c[3])", "", ("x", "y", "z", "w")),
    "Rect2i": ValueType("Rect2i", "int", ("v.position.x", "v.position.y", "v.size.x", "v.size.y"), "Rect2i(Vector2i(c[0], c[1]), Vector2i(c[2], c[3]))", ""),
}

# Classes whose members this generator owns besides the value types: RID (a Long value class).
OWNED_CLASSES = list(VALUE_TYPES) + ["RID"]

# Kotlin names that differ from the camel-cased Godot name (hand-written before task 134 B).
NAME_OVERRIDES = {
    ("Rect2", "get_area"): "area",
    ("Rect2i", "get_area"): "area",
    ("AABB", "get_volume"): "volume",
}

# Godot getters a Kotlin property already answers (`t.origin` is `get_origin()`): no method, since
# `getOrigin()` would clash with the property's JVM getter.
PROPERTY_MEMBERS = {
    ("Transform2D", "get_origin"): "origin",
}

# Methods implemented in pure Kotlin (Godot's formula; parity-tested), by Godot name. Every other
# method of a value type is a facade call. Kept to short, exactly portable formulas: anything with
# a transcendental, a MATH_CHECKS early return, or a long body stays with the engine.
_VEC_PURE = {"abs", "floor", "ceil", "round", "sign", "min", "max", "minf", "maxf", "clampf", "is_finite"}
_INT_PURE = {"abs", "sign", "min", "max", "mini", "maxi", "clamp", "clampi", "length_squared", "length",
             "distance_squared_to", "distance_to", "max_axis_index", "min_axis_index"}
PURE_METHODS: dict[str, set[str]] = {
    "Vector2": _VEC_PURE | {"direction_to", "cross", "orthogonal", "aspect", "max_axis_index", "min_axis_index"},
    "Vector3": _VEC_PURE | {"direction_to", "inverse", "min_axis_index", "clamp"},
    "Vector4": _VEC_PURE | {"inverse", "max_axis_index", "min_axis_index", "clamp", "normalized", "direction_to",
                            "distance_to", "distance_squared_to"},
    "Vector2i": _INT_PURE | {"aspect"},
    "Vector3i": set(_INT_PURE),
    "Vector4i": set(_INT_PURE),
    "Quaternion": {"is_finite"},
    "Color": {"inverted", "get_luminance", "to_html"},
    "Rect2": {"get_center", "has_area"},
    "Rect2i": {"get_center", "has_area"},
    "AABB": {"get_center", "has_volume", "has_surface"},
    "RID": {"get_id"},
}

# Members with no Kotlin implementation, and why (the coverage gate reads these).
DEFERRED_METHODS: dict[tuple[str, str], str] = {}

KOTLIN_SCALAR = {"float": "Double", "int": "Long", "bool": "Boolean", "String": "String"}
LIST_TYPES = {"PackedVector2Array": "Vector2", "PackedVector3Array": "Vector3"}


def camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def kotlin_name(cls: str, method: str) -> str:
    return NAME_OVERRIDES.get((cls, method), camel(method))


def kotlin_type(godot: str) -> str | None:
    if godot in KOTLIN_SCALAR:
        return KOTLIN_SCALAR[godot]
    if godot in VALUE_TYPES or godot == "RID":
        return godot
    if godot in LIST_TYPES:
        return f"List<{LIST_TYPES[godot]}>"
    return None


def kotlin_default(godot_type: str, value: str) -> str:
    if godot_type == "float":
        return value if any(ch in value for ch in ".e") else f"{value}.0"
    if godot_type == "int":
        return f"{value}L"
    if godot_type == "bool":
        return value
    match = re.fullmatch(r"(\w+)\((.*)\)", value)
    if match and match.group(1) in VALUE_TYPES:
        args = [a.strip() for a in match.group(2).split(",")]
        if VALUE_TYPES[match.group(1)].kind == "int":
            return f"{match.group(1)}({', '.join(args)})"
        return f"{match.group(1)}({', '.join(a if '.' in a else a + '.0' for a in args)})"
    raise SystemExit(f"[generate_builtin_ops] no Kotlin form for default {godot_type} = {value}")


# ---------------------------------------------------------------------------------------------
# Hand-written members: everything in a class file outside the generated regions.
# ---------------------------------------------------------------------------------------------

FUN_RE = re.compile(
    r"\bfun\s+(?:<[^>]*>\s*)?(?:(?P<receiver>[A-Za-z0-9_.<>]+)\.)?(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\("
    r"\s*(?:(?:vararg\s+)?[A-Za-z_][A-Za-z0-9_]*\s*:\s*(?P<ptype>[A-Za-z0-9_.<>?]+))?"
)


def strip_regions(source: str) -> str:
    return re.sub(
        r"// ===== BEGIN GENERATED BUILTIN (?:MEMBERS|STATICS): .*?// ===== END GENERATED BUILTIN (?:MEMBERS|STATICS): \w+ =====",
        "",
        source,
        flags=re.S,
    )


def class_body(source: str, name: str) -> str:
    """The text of class [name]'s body in a file that may hold several classes (the Web one)."""
    match = re.search(rf"^(?:data |value |@JvmInline\s+value )?class {name}\b", source, re.M)
    if not match:
        return ""
    brace = source.find("{", match.end())
    # A primary constructor's parentheses may hold default values with braces; skip them first.
    paren = source.find("(", match.end())
    if 0 <= paren < brace:
        depth = 0
        for i in range(paren, len(source)):
            if source[i] == "(":
                depth += 1
            elif source[i] == ")":
                depth -= 1
                if depth == 0:
                    brace = source.find("{", i)
                    break
    depth = 0
    for i in range(brace, len(source)):
        if source[i] == "{":
            depth += 1
        elif source[i] == "}":
            depth -= 1
            if depth == 0:
                return source[brace : i + 1]
    return source[brace:]


def hand_members(body: str) -> set[tuple[str, str | None]]:
    """(name, first parameter type) of each `fun` in [body] outside the generated regions."""
    found: set[tuple[str, str | None]] = set()
    for match in FUN_RE.finditer(strip_regions(body)):
        if match.group("receiver"):
            continue
        found.add((match.group("name"), match.group("ptype")))
    return found


def has_member(members: set[tuple[str, str | None]], name: str, ptype: str | None = "*") -> bool:
    if ptype == "*":
        return any(n == name for n, _ in members)
    return (name, ptype) in members


# ---------------------------------------------------------------------------------------------
# Member model.
# ---------------------------------------------------------------------------------------------


@dataclass
class Member:
    cls: str
    key: str  # coverage/parity key: "Vector2.abs", "Vector2 * Transform2D", "unary- Vector2"
    kind: str  # "op", "method"
    impl: str  # "pure", "facade", "hand-pure", "hand-facade", "deferred"
    code: str = ""  # Kotlin member source ("" for hand-written / deferred)
    static: bool = False
    godot: dict = field(default_factory=dict)
    reason: str = ""
    web: str = ""  # the Web copy of [code] ("" when the Web class does not get it)


OP_KOTLIN = {"+": "plus", "-": "minus", "*": "times", "/": "div", "%": "rem", "unary-": "unaryMinus", "unary+": "unaryPlus"}
COMPARE_OPS = {"<", "<=", ">", ">="}


def raw_ctor(vt: ValueType, values: list[str]) -> str:
    if vt.kind == "int":
        return f"{vt.name}({', '.join(values)})"
    return f"raw({', '.join(values)})"


def componentwise(vt: ValueType, fmt: str) -> str:
    """`fmt` over every component: `{c}` is this component, `{o}` the other's."""
    return raw_ctor(vt, [fmt.format(c=c, o=f"other.{c}") for c in vt.comps])


def scalar_param(right: str) -> list[tuple[str, str]]:
    """Kotlin parameter types for a Godot scalar right operand, and how each converts."""
    if right == "int":
        return [("Int", "Int"), ("Long", "Long")]
    return [("Double", "Double")]


def op_members(cls: str, op: dict, hand: set) -> list[tuple[str, str, str]]:
    """(kotlin member name, first param type, source) for one API operator of [cls]."""
    name = op["name"]
    right = op.get("right_type", "")
    ret = op["return_type"]
    vt = VALUE_TYPES.get(cls)
    out: list[tuple[str, str, str]] = []

    if name in ("unary-", "unary+"):
        fn = OP_KOTLIN[name]
        if name == "unary+":
            body = "this"
        elif cls == "Color":
            body = componentwise(vt, "1.0f - {c}")
        elif cls == "Plane":
            body = "raw(-normal, -rawD)"
        else:
            body = componentwise(vt, "-{c}")
        return [(fn, "", f"operator fun {fn}(): {cls} = {body}")]

    if name in COMPARE_OPS:
        if cls == "RID":
            return [("compareTo", cls, f"operator fun compareTo(other: {cls}): Int = value.toULong().compareTo(other.value.toULong())")]
        steps = [f"godotCompareStep({c}, other.{c})" for c in vt.comps]
        lines = [f"operator fun compareTo(other: {cls}): Int {{"]
        for i, step in enumerate(steps[:-1]):
            lines.append(f"  val c{i} = {step}")
            lines.append(f"  if (c{i} != 0) return c{i}")
        lines.append(f"  return {steps[-1]}")
        lines.append("}")
        return [("compareTo", cls, "\n".join(lines))]

    fn = OP_KOTLIN[name]
    if right in ("int", "float"):
        out = []
        for ptype, _ in scalar_param(right):
            if ptype in ("Int", "Long") and vt and vt.kind != "int":
                src = f"operator fun {fn}(scalar: {ptype}): {ret} = {fn}(scalar.toDouble())"
            elif vt and vt.kind == "int" and ret == cls:
                if ptype == "Long":
                    src = f"operator fun {fn}(scalar: Long): {ret} = {fn}(scalar.toInt())"
                else:
                    sym = {"times": "*", "div": "/", "rem": "%"}[fn]
                    src = f"operator fun {fn}(scalar: Int): {ret} = " + raw_ctor(vt, [f"{c} {sym} scalar" for c in vt.comps])
            elif vt and vt.kind == "int":  # Vector2i * float -> Vector2
                sym = {"times": "*", "div": "/"}[fn]
                comps = ", ".join(f"narrowReal({c}.toDouble()) {sym} s" for c in vt.comps)
                src = f"operator fun {fn}(scalar: Double): {ret} {{\n  val s = narrowReal(scalar)\n  return {ret}.raw({comps})\n}}"
            elif cls == "Color":
                sym = {"times": "*", "div": "/"}[fn]
                src = f"operator fun {fn}(scalar: Double): Color {{\n  val s = scalar.toFloat()\n  return {componentwise(vt, '{c} ' + sym + ' s')}\n}}"
            elif cls in ("Vector2", "Vector3", "Vector4", "Quaternion"):
                sym = {"times": "*", "div": "/"}[fn]
                if cls == "Quaternion" and fn == "div":
                    # `Quaternion::operator/(real_t s)` is `*this * (1 / s)`.
                    src = "operator fun div(scalar: Double): Quaternion {\n  val s = narrowReal(1.0) / narrowReal(scalar)\n  return " + componentwise(vt, "{c} * s") + "\n}"
                else:
                    src = f"operator fun {fn}(scalar: Double): {cls} {{\n  val s = narrowReal(scalar)\n  return {componentwise(vt, '{c} ' + sym + ' s')}\n}}"
            elif cls == "Basis":
                sym = {"times": "*", "div": "/"}[fn]
                src = f"operator fun {fn}(scalar: Double): Basis {{\n  val s = narrowReal(scalar)\n  return basisMap(this) {{ it {sym} s }}\n}}"
            elif cls == "Transform2D":
                sym = {"times": "*", "div": "/"}[fn]
                src = f"operator fun {fn}(scalar: Double): Transform2D = Transform2D(x {sym} scalar, y {sym} scalar, origin {sym} scalar)"
            elif cls == "Transform3D":
                sym = {"times": "*", "div": "/"}[fn]
                src = f"operator fun {fn}(scalar: Double): Transform3D {{\n  val s = narrowReal(scalar)\n  return Transform3D(basisMap(basis) {{ it {sym} s }}, origin {sym} scalar)\n}}"
            else:
                raise SystemExit(f"[generate_builtin_ops] no template for {cls} {name} {right}")
            out.append((fn, ptype, src))
        return out

    if right == cls and vt and vt.comps and name in ("+", "-", "*", "/", "%"):
        sym = name
        return [(fn, cls, f"operator fun {fn}(other: {cls}): {cls} = " + componentwise(vt, "{c} " + sym + " {o}"))]

    composite = {
        ("Vector2", "Transform2D"): "transform2DXformInv(other, this)",
        ("Rect2", "Transform2D"): "transform2DXformInvRect(other, this)",
        ("Transform2D", "Transform2D"): "transform2DMultiply(this, other)",
        ("Transform2D", "Vector2"): "transform2DXform(this, other)",
        ("Transform2D", "Rect2"): "transform2DXformRect(this, other)",
        ("Transform2D", "PackedVector2Array"): "other.map { transform2DXform(this, it) }",
        ("Vector3", "Quaternion"): "quaternionXformInv(other, this)",
        ("Vector3", "Basis"): "basisXformInv(other, this)",
        ("Vector3", "Transform3D"): "transform3DXformInv(other, this)",
        ("Vector4", "Projection"): "projectionXformInv(other, this)",
        ("Plane", "Transform3D"): "transform3DXformInvPlane(other, this)",
        ("Quaternion", "Vector3"): "quaternionXform(this, other)",
        ("AABB", "Transform3D"): "transform3DXformInvAabb(other, this)",
        ("Basis", "Vector3"): "basisXform(this, other)",
        ("Basis", "Basis"): "basisMultiply(this, other)",
        ("Transform3D", "Vector3"): "transform3DXform(this, other)",
        ("Transform3D", "Plane"): "transform3DXformPlane(this, other)",
        ("Transform3D", "AABB"): "transform3DXformAabb(this, other)",
        ("Transform3D", "Transform3D"): "transform3DMultiply(this, other)",
        ("Transform3D", "PackedVector3Array"): "other.map { transform3DXform(this, it) }",
        ("Projection", "Vector4"): "projectionXform(this, other)",
        ("Projection", "Projection"): "projectionMultiply(this, other)",
        ("Quaternion", "Quaternion"): None,  # hand-written (Quaternion.kt, A2)
    }
    if name == "*" and (cls, right) in composite and composite[(cls, right)]:
        ptype = kotlin_type(right)
        rtype = kotlin_type(ret)
        return [(fn, ptype, f"operator fun times(other: {ptype}): {rtype} = {composite[(cls, right)]}")]
    raise SystemExit(f"[generate_builtin_ops] no template for operator {cls} {name} {right}")


def interesting_ops(cls_api: dict) -> list[dict]:
    """The operators a Kotlin member implements (the rest have a language-level reason)."""
    out = []
    for op in cls_api.get("operators", []):
        if op["name"] in ("==", "!=", "not", "in"):
            continue
        out.append(op)
    return out


# ----- pure method templates -----------------------------------------------------------------


def pure_method(cls: str, m: dict) -> str:
    vt = VALUE_TYPES.get(cls)
    name = m["name"]
    kn = kotlin_name(cls, name)
    args = m.get("arguments", [])
    real = vt is not None and vt.kind == "real"
    if cls == "RID" and name == "get_id":
        return "fun getId(): Long = value"
    if cls in ("Vector2", "Vector3", "Vector4"):
        if name in ("abs", "floor", "ceil", "round", "sign"):
            fn = {"abs": "godotFabs", "floor": "godotFloor", "ceil": "godotCeil", "round": "godotRound", "sign": "godotSign"}[name]
            return f"fun {kn}(): {cls} = " + componentwise(vt, fn + "({c})")
        if name in ("min", "max"):
            fn = "godotMin" if name == "min" else "godotMax"
            return f"fun {kn}(with: {cls}): {cls} = " + componentwise(vt, fn + "({c}, with.{c})")
        if name in ("minf", "maxf"):
            fn = "godotMin" if name == "minf" else "godotMax"
            return f"fun {kn}(with: Double): {cls} {{\n  val s = narrowReal(with)\n  return " + componentwise(vt, fn + "({c}, s)") + "\n}"
        if name == "clampf":
            return f"fun clampf(min: Double, max: Double): {cls} {{\n  val lo = narrowReal(min)\n  val hi = narrowReal(max)\n  return " + componentwise(vt, "godotClamp({c}, lo, hi)") + "\n}"
        if name == "clamp":
            return f"fun clamp(min: {cls}, max: {cls}): {cls} = " + componentwise(vt, "godotClamp({c}, min.{c}, max.{c})")
        if name == "is_finite":
            return "fun isFinite(): Boolean = " + " && ".join(f"{c}.isFinite()" for c in vt.comps)
        if name == "direction_to":
            return f"fun directionTo(to: {cls}): {cls} = " + raw_ctor(vt, [f"to.{c} - {c}" for c in vt.comps]) + ".normalized()"
        if name == "inverse":
            return f"fun inverse(): {cls} {{\n  val one = narrowReal(1.0)\n  return " + componentwise(vt, "one / {c}") + "\n}"
        if name == "cross":
            return "fun cross(with: Vector2): Double = widenReal(rawX * with.rawY - rawY * with.rawX)"
        if name == "orthogonal":
            return "fun orthogonal(): Vector2 = raw(rawY, -rawX)"
        if name == "aspect":
            return "fun aspect(): Double = widenReal(rawX / rawY)"
        if name in ("max_axis_index", "min_axis_index"):
            return axis_index(cls, name, vt)
        if name == "normalized":
            comps = ", ".join(f"{c} / len" for c in vt.comps)
            return (
                f"fun normalized(): {cls} =\n  realNormalize(isFinite(), rawLengthSquared(), {{ ZERO }}, {{ len -> raw({comps}) }})"
            )
        if name == "distance_to":
            return f"fun distanceTo(to: {cls}): Double = (to - this).length()"
        if name == "distance_squared_to":
            return f"fun distanceSquaredTo(to: {cls}): Double = (to - this).lengthSquared()"
    if vt is not None and vt.kind == "int" and cls != "Rect2i":
        if name == "abs":
            return f"fun abs(): {cls} = " + componentwise(vt, "godotAbs({c})")
        if name == "sign":
            return f"fun sign(): {cls} = " + componentwise(vt, "godotSign({c})")
        if name in ("min", "max"):
            fn = "godotMin" if name == "min" else "godotMax"
            return f"fun {kn}(with: {cls}): {cls} = " + componentwise(vt, fn + "({c}, with.{c})")
        if name in ("mini", "maxi"):
            fn = "godotMin" if name == "mini" else "godotMax"
            return f"fun {kn}(with: Long): {cls} {{\n  val s = with.toInt()\n  return " + componentwise(vt, fn + "({c}, s)") + "\n}"
        if name == "clamp":
            return f"fun clamp(min: {cls}, max: {cls}): {cls} = " + componentwise(vt, "godotClamp({c}, min.{c}, max.{c})")
        if name == "clampi":
            return f"fun clampi(min: Long, max: Long): {cls} {{\n  val lo = min.toInt()\n  val hi = max.toInt()\n  return " + componentwise(vt, "godotClamp({c}, lo, hi)") + "\n}"
        if name == "length_squared":
            return "fun lengthSquared(): Long = " + " + ".join(f"{c}.toLong() * {c}" for c in vt.comps)
        if name == "length":
            return "fun length(): Double = godotSqrt(lengthSquared().toDouble())"
        if name == "distance_squared_to":
            return f"fun distanceSquaredTo(to: {cls}): Long = (to - this).lengthSquared()"
        if name == "distance_to":
            return f"fun distanceTo(to: {cls}): Double = (to - this).length()"
        if name in ("max_axis_index", "min_axis_index"):
            return axis_index(cls, name, vt)
        if name == "aspect":
            return "fun aspect(): Double = widenReal(narrowReal(x.toDouble()) / narrowReal(y.toDouble()))"
    if cls == "Quaternion" and name == "is_finite":
        return "fun isFinite(): Boolean = " + " && ".join(f"{c}.isFinite()" for c in vt.comps)
    if cls == "Color":
        if name == "inverted":
            return "fun inverted(): Color = raw(1.0f - rawR, 1.0f - rawG, 1.0f - rawB, rawA)"
        if name == "get_luminance":
            return "fun getLuminance(): Double = (0.2126f * rawR + 0.7152f * rawG + 0.0722f * rawB).toDouble()"
        if name == "to_html":
            return (
                "fun toHtml(withAlpha: Boolean = true): String {\n  val out = StringBuilder(8)\n"
                "  godotHexByte(rawR, out)\n  godotHexByte(rawG, out)\n  godotHexByte(rawB, out)\n"
                "  if (withAlpha) godotHexByte(rawA, out)\n  return out.toString()\n}"
            )
    if cls in ("Rect2", "AABB"):
        comps = "XY" if cls == "Rect2" else "XYZ"
        vec = "Vector2" if cls == "Rect2" else "Vector3"
        if name == "get_center":
            parts = ", ".join(f"position.raw{c} + size.raw{c} * half" for c in comps)
            return f"fun getCenter(): {vec} {{\n  val half = narrowReal(0.5)\n  return {vec}.raw({parts})\n}}"
        if name in ("has_area", "has_volume"):
            return f"fun {kn}(): Boolean = " + " && ".join(f"size.{c.lower()} > 0.0" for c in comps)
        if name == "has_surface":
            return "fun hasSurface(): Boolean = size.x > 0.0 || size.y > 0.0 || size.z > 0.0"
    if cls == "Rect2i":
        if name == "get_center":
            return "fun getCenter(): Vector2i = Vector2i(position.x + size.x / 2, position.y + size.y / 2)"
        if name == "has_area":
            return "fun hasArea(): Boolean = size.x > 0 && size.y > 0"
    raise SystemExit(f"[generate_builtin_ops] no pure template for {cls}.{name}")


def axis_index(cls: str, name: str, vt: ValueType) -> str:
    kn = camel(name)
    c = vt.comps
    if len(c) == 2:
        expr = f"if ({c[0]} < {c[1]}) 1L else 0L" if name == "max_axis_index" else f"if ({c[0]} < {c[1]}) 0L else 1L"
        return f"fun {kn}(): Long = {expr}"
    if len(c) == 3:
        x, y, z = c
        if name == "max_axis_index":
            expr = f"if ({x} < {y}) (if ({y} < {z}) 2L else 1L) else (if ({x} < {z}) 2L else 0L)"
        else:
            expr = f"if ({x} < {y}) (if ({x} < {z}) 0L else 2L) else (if ({y} < {z}) 1L else 2L)"
        return f"fun {kn}(): Long = {expr}"
    # Vector4/Vector4i: Godot's loop (`<=` for min, `>` for max: ties go to the later/earlier axis).
    cmp = ">" if name == "max_axis_index" else "<="
    lines = [f"fun {kn}(): Long {{", "  var index = 0L", f"  var value = {c[0]}"]
    for i, comp in enumerate(c[1:], start=1):
        lines.append(f"  if ({comp} {cmp} value) {{\n    index = {i}L\n    value = {comp}\n  }}")
    lines.append("  return index")
    lines.append("}")
    return "\n".join(lines)


# ----- facade method template ------------------------------------------------------------------


def facade_arg(godot_type: str, expr: str) -> str:
    if godot_type == "float":
        return f"argReal({expr})"
    if godot_type == "int":
        return f"argLong({expr})"
    if godot_type == "bool":
        return f"argBool({expr})"
    if godot_type == "String":
        return f"argString({expr})"
    if godot_type in VALUE_TYPES:
        return f"{expr}.builtinArg()"
    raise SystemExit(f"[generate_builtin_ops] no facade argument form for {godot_type}")


def facade_method(cls: str, m: dict) -> str:
    kn = kotlin_name(cls, m["name"])
    static = m.get("is_static", False)
    params = []
    for arg in m.get("arguments", []):
        ktype = kotlin_type(arg["type"])
        default = f" = {kotlin_default(arg['type'], arg['default_value'])}" if "default_value" in arg else ""
        params.append(f"{camel(arg['name'])}: {ktype}{default}")
    args = [facade_arg(a["type"], camel(a["name"])) for a in m.get("arguments", [])]
    arglist = f"listOf({', '.join(args)})" if args else "emptyList()"
    base = "null" if static else "builtinArg()"
    bind = f"{cls}Methods.{kn}"
    ret = m.get("return_type", "void")
    if ret == "float":
        rtype, call = "Double", f"builtinDouble({bind}, {base}, {arglist})"
    elif ret == "int":
        rtype, call = "Long", f"builtinLong({bind}, {base}, {arglist})"
    elif ret == "bool":
        rtype, call = "Boolean", f"builtinBool({bind}, {base}, {arglist})"
    elif ret == "Variant":
        # Plane.intersect_3 / intersects_* and AABB.intersects_*: a Vector3 or null.
        rtype = "Vector3?"
        call = f"builtinVariantReals({bind}, {base}, 3, {arglist})?.let {{ c -> Vector3.raw(c[0], c[1], c[2]) }}"
    elif ret in VALUE_TYPES:
        vt = VALUE_TYPES[ret]
        fn = {"real": "builtinReals", "int": "builtinInts", "color": "builtinFloat32s"}[vt.kind]
        rtype, call = ret, f"builtin{ret}({fn}({bind}, {base}, {vt.count}, {arglist}))"
    else:
        raise SystemExit(f"[generate_builtin_ops] no facade return form for {cls}.{m['name']} -> {ret}")
    return f"fun {kn}({', '.join(params)}): {rtype} =\n  {call}"


def facade_supported(m: dict) -> str | None:
    """None when the facade can carry this method's signature, else the reason it cannot."""
    for arg in m.get("arguments", []):
        if arg["type"] not in KOTLIN_SCALAR and arg["type"] not in VALUE_TYPES:
            return f"argument type {arg['type']} has no facade form"
    ret = m.get("return_type", "void")
    if ret not in ("float", "int", "bool", "Variant") and ret not in VALUE_TYPES:
        return f"return type {ret} has no facade form"
    return None


# ---------------------------------------------------------------------------------------------
# Building the member set.
# ---------------------------------------------------------------------------------------------


def load_api() -> dict:
    return json.loads(API_PATH.read_text(encoding="utf-8"))


def builtin_class(api: dict, name: str) -> dict:
    for cls in api["builtin_classes"]:
        if cls["name"] == name:
            return cls
    raise SystemExit(f"[generate_builtin_ops] {name} is not a builtin class")


def op_key(cls: str, op: dict) -> str:
    right = op.get("right_type", "")
    return f"{op['name']} {cls}" if not right else f"{cls} {op['name']} {right}"


def build_members(api: dict, hand_bodies: dict[str, str]) -> list[Member]:
    members: list[Member] = []
    for cls in OWNED_CLASSES:
        cls_api = builtin_class(api, cls)
        hand = hand_members(hand_bodies.get(cls, ""))
        vt = VALUE_TYPES.get(cls)
        seen_sources: set[tuple[str, str]] = set()
        for op in interesting_ops(cls_api):
            key = op_key(cls, op)
            if op["name"] in ("%",) and op.get("right_type") in ("Variant",):
                continue
            produced = op_members(cls, op, hand)
            for fn, ptype, src in produced:
                if (fn, ptype) in seen_sources:
                    continue
                seen_sources.add((fn, ptype))
                if has_member(hand, fn, ptype if ptype else None) or (not ptype and has_member(hand, fn)):
                    members.append(Member(cls, key, "op", "hand-pure", godot=op))
                    continue
                web = src if (vt and vt.web and web_op_ok(cls, op)) else ""
                members.append(Member(cls, key, "op", "pure", src, godot=op, web=web))
        for m in cls_api.get("methods", []):
            key = f"{cls}.{m['name']}"
            kn = kotlin_name(cls, m["name"])
            static = m.get("is_static", False)
            if has_member(hand, kn) or (cls, m["name"]) in PROPERTY_MEMBERS:
                members.append(Member(cls, key, "method", "hand", static=static, godot=m))
                continue
            if (cls, m["name"]) in DEFERRED_METHODS:
                members.append(Member(cls, key, "method", "deferred", static=static, godot=m, reason=DEFERRED_METHODS[(cls, m["name"])]))
                continue
            if m["name"] in PURE_METHODS.get(cls, set()):
                src = pure_method(cls, m)
                web = src if (vt and vt.web and web_method_ok(cls, m["name"])) else ""
                members.append(Member(cls, key, "method", "pure", src, static=static, godot=m, web=web))
                continue
            reason = facade_supported(m)
            if reason or vt is None:
                members.append(Member(cls, key, "method", "deferred", static=static, godot=m, reason=reason or "no facade layout"))
                continue
            members.append(Member(cls, key, "method", "facade", facade_method(cls, m), static=static, godot=m))
    return members


# The Web value types (web-runtime) share the stored-component layout for these classes; only
# component-wise members (no Basis/Transform formulas, no facade) are emitted there.
WEB_METHOD_OK = {
    "Vector2": {"abs", "floor", "ceil", "round", "sign", "min", "max", "minf", "maxf", "clampf", "is_finite",
                "direction_to", "cross", "orthogonal", "aspect", "max_axis_index", "min_axis_index"},
    "Vector3": {"abs", "floor", "ceil", "round", "sign", "min", "max", "minf", "maxf", "clampf", "is_finite",
                "direction_to", "inverse", "min_axis_index", "clamp"},
    "Vector2i": set(_INT_PURE) | {"aspect"},
    "Vector3i": set(_INT_PURE),
    "Quaternion": {"is_finite"},
    "Color": {"inverted", "get_luminance", "to_html"},
}


def web_method_ok(cls: str, name: str) -> bool:
    return name in WEB_METHOD_OK.get(cls, set())


def web_op_ok(cls: str, op: dict) -> bool:
    right = op.get("right_type", "")
    return right in ("", "int", "float", cls) and not (cls == "Plane" and right)


# ---------------------------------------------------------------------------------------------
# Rendering.
# ---------------------------------------------------------------------------------------------


def indent(src: str, prefix: str) -> str:
    return "\n".join(prefix + line if line else line for line in src.splitlines())


def render_region(name: str, sources: list[str], begin: str, end: str, pad: str) -> str:
    lines = [pad + begin.format(name=name, gen=MARKER_GEN)]
    for src in sources:
        lines.append(indent(src, pad))
        lines.append("")
    lines.append(pad + end.format(name=name))
    return "\n".join(lines)


def comparison_key(text: str) -> str:
    text = re.sub(r"/\*\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r",(\s*[)\]])", r"\1", text)
    text = text.replace(";", "")
    return re.sub(r"\s+", "", text)


def splice(source: str, name: str, region: str, begin: str, end: str, anchor) -> str:
    """Replace the [name] region in [source], or insert it at [anchor](source) when absent."""
    b = begin.format(name=name, gen=MARKER_GEN)
    e = end.format(name=name)
    if b in source:
        start = source.rfind("\n", 0, source.index(b)) + 1
        stop = source.index(e) + len(e)
        old = source[start:stop]
        if comparison_key(old) == comparison_key(region):
            return source
        return source[:start] + region + source[stop:]
    pos = anchor(source)
    return source[:pos] + region + "\n\n" + source[pos:]


def class_companion_anchor(name: str, web: bool):
    def anchor(source: str) -> int:
        start = re.search(rf"^(?:data |value |@JvmInline\s+value )?class {name}\b", source, re.M).start()
        body = class_body(source, name)
        body_start = source.index(body, start)
        match = re.search(r"^  (?:internal )?companion object", body, re.M)
        if match:
            return body_start + match.start()
        # No companion: before the closing brace.
        close = body_start + len(body) - 1
        return source.rfind("\n", 0, close) + 1

    return anchor


def companion_open_anchor(name: str):
    def anchor(source: str) -> int:
        start = re.search(rf"^(?:data |value |@JvmInline\s+value )?class {name}\b", source, re.M).start()
        body = class_body(source, name)
        body_start = source.index(body, start)
        match = re.search(r"^  companion object \{\n", body, re.M)
        if not match:
            raise SystemExit(f"[generate_builtin_ops] {name} has statics but no public `companion object {{`")
        return body_start + match.end()

    return anchor


def render_marshalling(api: dict, members: list[Member]) -> str:
    variant_ids = {}
    for enum in api["global_enums"]:
        if enum["name"] == "Variant.Type":
            for value in enum["values"]:
                variant_ids[value["name"].removeprefix("TYPE_").replace("_", "")] = value["value"]
    out = [
        f"// GENERATED by {GENERATOR} from extension_api.json — do not edit.",
        "package net.multigesture.kanama.types",
        "",
        "import net.multigesture.kanama.binding.runtime.BArg",
        "import net.multigesture.kanama.binding.runtime.BuiltinCalls",
        "import net.multigesture.kanama.binding.runtime.PT_AABB",
        "import net.multigesture.kanama.binding.runtime.PT_BASIS",
        "import net.multigesture.kanama.binding.runtime.PT_PLANE",
        "import net.multigesture.kanama.binding.runtime.PT_PROJECTION",
        "import net.multigesture.kanama.binding.runtime.PT_QUATERNION",
        "import net.multigesture.kanama.binding.runtime.PT_RECT2",
        "import net.multigesture.kanama.binding.runtime.PT_TRANSFORM2D",
        "import net.multigesture.kanama.binding.runtime.PT_TRANSFORM3D",
        "import net.multigesture.kanama.binding.runtime.PT_VECTOR2",
        "import net.multigesture.kanama.binding.runtime.PT_VECTOR3",
        "import net.multigesture.kanama.binding.runtime.PT_VECTOR4",
        "",
        "// The value types' facade glue (task 134 B): each type's Godot memory layout as a builtin-call",
        "// argument and back, the resolved method pointers (one lazy per method), and short names for",
        "// the BuiltinCalls entry points the generated members call.",
        "",
        "internal fun argReal(value: Double): BArg = BArg.Real(value)",
        "",
        "internal fun argLong(value: Long): BArg = BArg.Int64(value)",
        "",
        "internal fun argBool(value: Boolean): BArg = BArg.Bool(value)",
        "",
        "internal fun argString(value: String): BArg = BArg.Str(value)",
        "",
        "internal fun builtinReals(method: Long, base: BArg?, count: Int, args: List<BArg>): GodotRealArray =",
        "  BuiltinCalls.invokeReals(method, base, count, args)",
        "",
        "internal fun builtinInts(method: Long, base: BArg?, count: Int, args: List<BArg>): IntArray =",
        "  BuiltinCalls.invokeInts(method, base, count, args)",
        "",
        "internal fun builtinFloat32s(method: Long, base: BArg?, count: Int, args: List<BArg>): FloatArray =",
        "  BuiltinCalls.invokeFloat32s(method, base, count, args)",
        "",
        "internal fun builtinDouble(method: Long, base: BArg?, args: List<BArg>): Double =",
        "  BuiltinCalls.invokeDouble(method, base, args)",
        "",
        "internal fun builtinLong(method: Long, base: BArg?, args: List<BArg>): Long =",
        "  BuiltinCalls.invokeLong(method, base, args)",
        "",
        "internal fun builtinBool(method: Long, base: BArg?, args: List<BArg>): Boolean =",
        "  BuiltinCalls.invokeBool(method, base, args)",
        "",
        "internal fun builtinVariantReals(method: Long, base: BArg?, count: Int, args: List<BArg>): GodotRealArray? =",
        "  BuiltinCalls.invokeVariantReals(method, base, count, args)",
        "",
    ]
    for name, vt in VALUE_TYPES.items():
        values = ", ".join(e.replace("v.", "") for e in vt.pack)
        if vt.kind == "real":
            assigns = "; ".join(f"it[{i}] = {e.replace('v.', '')}" for i, e in enumerate(vt.pack))
            out.append(f"internal fun {name}.builtinArg(): BArg =")
            out.append(f"  BArg.Floats({vt.tag}, GodotRealArray({vt.count}).also {{ {assigns} }})")
            out.append("")
            out.append(f"internal fun builtin{name}(c: GodotRealArray): {name} = {vt.unpack}")
        elif vt.kind == "int":
            out.append(f"internal fun {name}.builtinArg(): BArg = BArg.Ints(intArrayOf({values}))")
            out.append("")
            out.append(f"internal fun builtin{name}(c: IntArray): {name} = {vt.unpack}")
        else:
            out.append(f"internal fun {name}.builtinArg(): BArg = BArg.Float32s(floatArrayOf({values}))")
            out.append("")
            out.append(f"internal fun builtin{name}(c: FloatArray): {name} = {vt.unpack}")
        out.append("")
    by_class: dict[str, list[Member]] = {}
    for member in members:
        if member.impl == "facade":
            by_class.setdefault(member.cls, []).append(member)
    for cls, facade in by_class.items():
        vid = variant_ids[cls.upper()]
        out.append(f"/** {cls}'s builtin method pointers, resolved on first use. */")
        out.append(f"internal object {cls}Methods {{")
        for member in facade:
            m = member.godot
            kn = kotlin_name(cls, m["name"])
            out.append(f"  val {kn}: Long by lazy {{ BuiltinCalls.getBuiltinMethod({vid}, \"{m['name']}\", {m['hash']}L) }}")
            out.append("")
        if out[-1] == "":
            out.pop()
        out.append("}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


SCALAR_LEFT_TYPES = {"Vector2", "Vector2i", "Vector3", "Vector3i", "Vector4", "Vector4i", "Quaternion", "Color"}


def render_scalar_ops(api: dict, web: bool) -> str:
    out = [
        f"// GENERATED by {GENERATOR} from extension_api.json — do not edit.",
        "package net.multigesture.kanama.types",
        "",
        "// The operators whose left operand is not a value type (task 134 B): GDScript's `2.0 * v` and",
        "// `points * transform`. Godot evaluates `scalar * v` as `v * scalar`, so these delegate.",
        "",
    ]
    for left, kinds in (("int", ("Int", "Long")), ("float", ("Double",))):
        cls_api = builtin_class(api, left)
        for op in cls_api["operators"]:
            right = op.get("right_type", "")
            if op["name"] != "*" or right not in SCALAR_LEFT_TYPES:
                continue
            if web and not (VALUE_TYPES[right].web):
                continue
            for k in kinds:
                out.append(f"operator fun {k}.times(other: {right}): {kotlin_type(op['return_type'])} = other * this")
                out.append("")
    if not web:
        out.append("operator fun List<Vector2>.times(transform: Transform2D): List<Vector2> =")
        out.append("  map { transform2DXformInv(transform, it) }")
        out.append("")
        out.append("operator fun List<Vector3>.times(transform: Transform3D): List<Vector3> =")
        out.append("  map { transform3DXformInv(transform, it) }")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------------------------------------
# Parity probe pair.
# ---------------------------------------------------------------------------------------------

# How each type's random input is built, identically in Kotlin and GDScript (only constructors and
# parity-proven members, so the inputs themselves are the same bits on both sides).
INPUT_KT = {
    "float": "nv()",
    "int": "ri()",
    "bool": "rb()",
    "Vector2": "Vector2(nv(), nv())",
    "Vector3": "Vector3(nv(), nv(), nv())",
    "Vector4": "Vector4(nv(), nv(), nv(), nv())",
    "Quaternion": "Quaternion(nv(), nv(), nv(), nv()).normalized()",
    "Color": "Color(nv(), nv(), nv(), nv())",
    "Plane": "Plane(Vector3(nv(), nv(), nv()).normalized(), nv())",
    "Rect2": "Rect2(Vector2(nv(), nv()), Vector2(nv(), nv()).abs())",
    "AABB": "AABB(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()).abs())",
    "Basis": "Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))",
    "Transform2D": "Transform2D(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))",
    "Transform3D": "Transform3D(Basis(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv())), Vector3(nv(), nv(), nv()))",
    "Projection": "Projection(Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()), Vector4(nv(), nv(), nv(), nv()))",
    "Vector2i": "Vector2i(ri(), ri())",
    "Vector3i": "Vector3i(ri(), ri(), ri())",
    "Vector4i": "Vector4i(ri(), ri(), ri(), ri())",
    "Rect2i": "Rect2i(Vector2i(ri(), ri()), Vector2i(ri(), ri()).abs())",
    "RID": "RID(rl())",
    "PackedVector2Array": "listOf(Vector2(nv(), nv()), Vector2(nv(), nv()), Vector2(nv(), nv()))",
    "PackedVector3Array": "listOf(Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()), Vector3(nv(), nv(), nv()))",
}
# Facade inputs: rotations where an engine method asserts one (MATH_CHECKS), small indices.
FACADE_INPUT_KT = dict(INPUT_KT)
FACADE_INPUT_KT.update(
    {
        "int": "rs()",
        # Unit vectors: slide/reflect/bounce/rotated/slerp assert normalized arguments.
        "Vector2": "Vector2(nv(), nv()).normalized()",
        "Vector3": "Vector3(nv(), nv(), nv()).normalized()",
        "Basis": "Basis(Quaternion(nv(), nv(), nv(), nv()).normalized())",
        "Transform3D": "Transform3D(Basis(Quaternion(nv(), nv(), nv(), nv()).normalized()), Vector3(nv(), nv(), nv()))",
        "Transform2D": "rotation2D(Vector2(nv(), nv()).normalized(), Vector2(nv(), nv()))",
        "String": "\"#ff8000\"",
    }
)
# Non-zero integer divisors (Kotlin throws and GDScript errors on integer division by zero).
NONZERO_KT = {
    "int": "rnz()",
    "Vector2i": "Vector2i(rnz(), rnz())",
    "Vector3i": "Vector3i(rnz(), rnz(), rnz())",
    "Vector4i": "Vector4i(rnz(), rnz(), rnz(), rnz())",
}


def to_gd(expr: str) -> str:
    """The GDScript spelling of an INPUT_KT expression."""
    expr = expr.replace("RID(rl())", "rid_from(rl())")
    expr = expr.replace("rotation2D(", "rotation_2d(")
    return expr


def gd_input(godot_type: str, expr: str) -> str:
    if godot_type in LIST_TYPES:
        assert expr.startswith("listOf(") and expr.endswith(")")
        return f"{godot_type}([{to_gd(expr[len('listOf('):-1])}])"
    return to_gd(expr)


def call_args(m: dict, table: dict, nonzero: bool = False) -> list[tuple[str, str, str]]:
    out = []
    for arg in m.get("arguments", []):
        t = arg["type"]
        expr = table[t]
        if t == "int" and table is INPUT_KT:
            expr = "ri()"
        out.append((t, expr + (".toLong()" if t == "int" else ""), gd_input(t, expr)))
    return out


# Per pure parity entry: the class, the Godot types its inputs use, and the Kotlin member it calls
# (name, first parameter type or None) -- what the Web parity test needs to know whether the Web
# value types can run the same entry.
ENTRY_META: dict[str, tuple[str, tuple[str, ...], str, str | None]] = {}


def parity_entries(members: list[Member]) -> tuple[list[tuple[str, list[str], list[str]]], list[tuple[str, list[str], list[str]]]]:
    """(name, kotlin lines, gdscript lines) per parity entry: (pure, facade)."""
    ENTRY_META.clear()
    pure: list = []
    facade: list = []
    done: set[str] = set()
    for member in members:
        if member.impl == "deferred":
            continue
        if member.kind == "op":
            op = member.godot
            key = member.key
            if key in done:
                continue
            done.add(key)
            right = op.get("right_type", "")
            cls = member.cls
            if op["name"] in COMPARE_OPS:
                fn, ptype = "compareTo", cls
            elif not right:
                fn, ptype = OP_KOTLIN[op["name"]], None
            else:
                fn = OP_KOTLIN[op["name"]]
                ptype = {"int": "Long", "float": "Double"}.get(right) or kotlin_type(right)
            ENTRY_META[key] = (cls, (cls, right) if right else (cls,), fn, ptype)
            lt = INPUT_KT[cls]
            kt: list[str] = [f"val l = {lt}"]
            gd: list[str] = [f"var l = {gd_input(cls, lt)}"]
            if not right:
                sym = "-" if op["name"] == "unary-" else "+"
                kt.append(f'mix("{key}", {sym}l)')
                gd.append(f'mix("{key}", {sym}l)')
            else:
                divisor = op["name"] in ("/", "%") and (VALUE_TYPES.get(cls) and VALUE_TYPES[cls].kind == "int") and right in NONZERO_KT
                rt = NONZERO_KT[right] if divisor else INPUT_KT[right]
                if right == "int":
                    kt.append(f"val r = {rt}.toLong()")
                else:
                    kt.append(f"val r = {rt}")
                gd.append(f"var r = {gd_input(right, rt)}")
                sym = op["name"]
                kt.append(f'mix("{key}", l {sym} r)')
                gd.append(f'mix("{key}", l {sym} r)')
            pure.append((key, kt, gd))
            continue
        m = member.godot
        cls = member.cls
        kn = kotlin_name(cls, m["name"])
        is_facade = member.impl in ("facade",) or (member.impl == "hand" and member_calls_engine(member))
        table = FACADE_INPUT_KT if is_facade else INPUT_KT
        args = call_args(m, table)
        kt = []
        gd = []
        for i, (t, k, g) in enumerate(args):
            kt.append(f"val a{i} = {k}")
            gd.append(f"var a{i} = {g}")
        names = ", ".join(f"a{i}" for i in range(len(args)))
        if member.static:
            kt.append(f'mix("{member.key}", {cls}.{kn}({names}))')
            gd.append(f'mix("{member.key}", {cls}.{m["name"]}({names}))')
        else:
            base = table[cls] if cls in table else INPUT_KT[cls]
            kt.insert(0, f"val b = {base}")
            gd.insert(0, f"var b = {gd_input(cls, base)}")
            prop = PROPERTY_MEMBERS.get((cls, m["name"]))
            kt.append(f'mix("{member.key}", b.{prop})' if prop else f'mix("{member.key}", b.{kn}({names}))')
            gd.append(f'mix("{member.key}", b.{m["name"]}({names}))')
        if not is_facade:
            types = tuple(a["type"] for a in m.get("arguments", [])) + (() if member.static else (cls,))
            ENTRY_META[member.key] = (cls, types, kn, None)
        (facade if is_facade else pure).append((member.key, kt, gd))
    return pure, facade


# ----- the Web half: the same pure entries, run by the Web value types under Node ----------------

EXPECTED_PATH = ROOT / "scripts/fixtures/builtin_parity_expected.json"
WEB_TEST = ROOT / "web-runtime/src/wasmJsTest/kotlin/net/multigesture/kanama/types/WebBuiltinParityTest.kt"
WEB_INPUT_TYPES = {"float", "int", "bool", "Vector2", "Vector3", "Color", "Vector2i", "Vector3i", "Quaternion", "Plane"}
DRAW_RE = re.compile(r"\b(?:nv|ri|rnz|rs|rl|rb)\(\)")


def summary_key(key: str) -> str:
    return key.replace(" ", "_")


def web_capable(key: str, web_members: dict[str, set]) -> bool:
    cls, types, fn, ptype = ENTRY_META[key]
    if cls not in web_members or not set(types) <= WEB_INPUT_TYPES:
        return False
    found = web_members[cls]
    if ptype is None:
        return any(name == fn for name, _ in found)
    return (fn, ptype) in found


def web_members_now(web_source: str) -> dict[str, set]:
    return {cls: hand_members_all(class_body(web_source, cls)) for cls, vt in VALUE_TYPES.items() if vt.web}


def hand_members_all(body: str) -> set[tuple[str, str | None]]:
    """Every `fun` of [body], generated regions included."""
    return {(m.group("name"), m.group("ptype")) for m in FUN_RE.finditer(body) if not m.group("receiver")}


def load_expected() -> dict[str, str]:
    if not EXPECTED_PATH.exists():
        return {}
    return json.loads(EXPECTED_PATH.read_text(encoding="utf-8"))["pure"]


def render_web_test(pure, web_source: str) -> str:
    expected = load_expected()
    members_by_class = web_members_now(web_source)
    calls: list[str] = []
    bodies: list[str] = []
    checked: list[str] = []
    for i, (key, kt, _) in enumerate(pure):
        if web_capable(key, members_by_class) and summary_key(key) in expected:
            calls.append(f"    pure{i}()")
            bodies.append(f"  private fun pure{i}() {{")
            bodies.extend("    " + line for line in kt)
            bodies.append("  }")
            bodies.append("")
            checked.append(key)
        else:
            draws = sum(len(DRAW_RE.findall(line)) for line in kt)
            if draws:
                calls.append(f"    skip({draws}) // {key}")
    out = [
        f"// GENERATED by {GENERATOR} from extension_api.json — do not edit.",
        "@file:Suppress(\"UNUSED_VARIABLE\")",
        "",
        "package net.multigesture.kanama.types",
        "",
        "import kotlin.test.Test",
        "import kotlin.test.assertEquals",
        "",
        "/**",
        " * Task 134 B: the Web value types run the runtime smoke's builtin parity row (the same fixed-seed",
        " * inputs, entry for entry; the entries the Web types cannot run only consume their draws) and",
        " * must produce the hashes Godot 4.7.2's GDScript printed for it, recorded in",
        " * `scripts/fixtures/builtin_parity_expected.json` (`generate_builtin_ops.py --record-parity`; the",
        " * runtime smoke re-checks the recording against the live GDScript line).",
        " */",
        "class WebBuiltinParityTest {",
        "  @Test",
        "  fun webMembersMatchGodot() {",
        f"    repeat({PARITY_INPUTS}) {{ round() }}",
        "    val wrong = EXPECTED.filter { (key, hash) -> hashes[key]?.toString(16) != hash }.keys",
        "    assertEquals(emptySet(), wrong, \"entries whose hash differs from Godot's\")",
        "  }",
        "",
        "  private fun round() {",
        *calls,
        "  }",
        "",
        *bodies,
        "  private var seed = 2463534242L",
        "",
        "  private fun nextRandom(): Long {",
        "    seed = seed xor ((seed shl 13) and 0xFFFFFFFFL)",
        "    seed = seed xor (seed ushr 17)",
        "    seed = seed xor ((seed shl 5) and 0xFFFFFFFFL)",
        "    return seed",
        "  }",
        "",
        "  private fun skip(draws: Int) = repeat(draws) { nextRandom() }",
        "",
        "  private fun nv(): Double {",
        "    val r = nextRandom()",
        "    return ((r % 200001) - 100000) / 10000.0 * SCALES[((r ushr 24) % 7).toInt()]",
        "  }",
        "",
        "  private fun ri(): Int = ((nextRandom() % 60001) - 30000).toInt()",
        "",
        "  private fun rnz(): Int = ri().let { if (it == 0) 1 else it }",
        "",
        "  private fun rb(): Boolean = (nextRandom() and 1L) == 1L",
        "",
        "  private val hashes = linkedMapOf<String, Long>()",
        "",
        "  private fun mixLong(name: String, value: Long) {",
        "    for (bits in longArrayOf(value and 0xFFFFFFFFL, (value ushr 32) and 0xFFFFFFFFL)) {",
        "      hashes[name] = ((hashes[name] ?: 2166136261L) xor bits) * 16777619L and 0xFFFFFFFFL",
        "    }",
        "  }",
        "",
        "  private fun mix(key: String, value: Any?) {",
        "    val name = key.replace(' ', '_')",
        "    when (value) {",
        "      null -> mixLong(name, -1L)",
        "      is Double -> mixLong(name, if (value.isNaN()) 0x7FF8000000000000L else value.toRawBits())",
        "      is Long -> mixLong(name, value)",
        "      is Int -> mixLong(name, value.toLong())",
        "      is Boolean -> mixLong(name, if (value) 1L else 0L)",
        "      is String -> value.forEach { mixLong(name, it.code.toLong()) }",
        "      is Vector2 -> listOf(value.x, value.y).forEach { mix(key, it) }",
        "      is Vector3 -> listOf(value.x, value.y, value.z).forEach { mix(key, it) }",
        "      is Quaternion -> listOf(value.x, value.y, value.z, value.w).forEach { mix(key, it) }",
        "      is Color -> listOf(value.r, value.g, value.b, value.a).forEach { mix(key, it) }",
        "      is Vector2i -> listOf(value.x, value.y).forEach { mix(key, it) }",
        "      is Vector3i -> listOf(value.x, value.y, value.z).forEach { mix(key, it) }",
        "      is Plane -> listOf(value.normal, value.d).forEach { mix(key, it) }",
        "      else -> error(\"no parity mix for ${value::class}\")",
        "    }",
        "  }",
        "",
        "  private companion object {",
        "    val SCALES = doubleArrayOf(0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0)",
        "",
        "    // Godot 4.7.2's hashes for the entries above (scripts/fixtures/builtin_parity_expected.json).",
        "    val EXPECTED =",
        "      mapOf(",
        *[f'        "{summary_key(k)}" to "{expected[summary_key(k)]}",' for k in checked],
        "      )",
        "  }",
        "}",
    ]
    return "\n".join(out) + "\n"


def web_parity_keys(pure, web_source: str) -> list[str]:
    members_by_class = web_members_now(web_source)
    return [summary_key(key) for key, _, _ in pure if web_capable(key, members_by_class)]


def parse_gdscript_pure(log: str) -> dict[str, str]:
    match = re.search(r"BuiltinParity gdscript pure=n=\d+ (.*)", log)
    if not match:
        raise SystemExit("[generate_builtin_ops] the log has no `BuiltinParity gdscript pure=` line")
    return dict(item.rsplit("=", 1) for item in match.group(1).split())


ENGINE_CALL_RE = re.compile(r"\bBuiltinCalls\.|\bbuiltin(?:Reals|Ints|Float32s|Double|Long|Bool|VariantReals)\s*\(|\bcallVector3RealRetVector3\s*\(")
HAND_BODIES: dict[str, str] = {}


def member_calls_engine(member: Member) -> bool:
    """A hand-written method whose body reaches the engine (facade) rather than Kotlin math."""
    body = HAND_BODIES.get(member.cls, "")
    kn = kotlin_name(member.cls, member.godot["name"])
    match = re.search(rf"\bfun\s+{re.escape(kn)}\s*\(", body)
    if not match:
        return False
    nxt = re.search(r"\n  (?:(?:override |operator |internal |private )*fun |val |companion |// =====)", body[match.end():])
    snippet = body[match.start() : match.end() + (nxt.start() if nxt else len(body))]
    if ENGINE_CALL_RE.search(snippet):
        return True
    # One level of private helper (e.g. `fromGodotRealArray(BuiltinCalls...)` lives in the body).
    return False


def render_parity_kt(pure, facade) -> str:
    def block(entries, fn):
        lines = []
        for i, (name, kt, _) in enumerate(entries):
            lines.append(f"  private fun {fn}{i}() {{")
            lines.extend("    " + line for line in kt)
            lines.append("  }")
            lines.append("")
        return lines

    out = [
        f"// GENERATED by {GENERATOR} from extension_api.json — do not edit.",
        "@file:Suppress(\"UNUSED_VARIABLE\", \"NAME_SHADOWING\")",
        "",
        "package net.multigesture.kanama.example",
        "",
        "import net.multigesture.kanama.annotations.OnReady",
        "import net.multigesture.kanama.annotations.ScriptClass",
        "import net.multigesture.kanama.api.GodotHandle",
        "import net.multigesture.kanama.api.KanamaScript",
        "import net.multigesture.kanama.api.Node2D",
        "import net.multigesture.kanama.types.*",
        "",
        "/**",
        " * Task 134 B parity probe, run by `scripts/runtime_smoke.sh` (`builtin_parity_smoke.tscn`) beside",
        " * `builtin_parity_ref.gd`, which prints the same two lines from GDScript in the same run.",
        " *",
        " * `pure=`: every value-type operator and every method implemented in Kotlin (generated or",
        " * hand-written), each hashed over the same fixed-seed random inputs; one differing bit in one",
        " * result changes its hash. `facade=`: every method the engine runs through BuiltinCalls, over a",
        " * smaller sample (the result is the engine's; this proves the marshalling).",
        " */",
        "@ScriptClass(attachTo = \"Node2D\")",
        "class BuiltinParitySmoke(godotObject: GodotHandle) : KanamaScript<Node2D>(godotObject, ::Node2D) {",
        "  @OnReady",
        "  fun ready() {",
        f"    repeat({PARITY_INPUTS}) {{ pureRound() }}",
        f"    report(\"pure=n={PARITY_INPUTS} \" + summary())",
        "    hashes.clear()",
        f"    repeat({FACADE_INPUTS}) {{ facadeRound() }}",
        f"    report(\"facade=n={FACADE_INPUTS} \" + summary())",
        "  }",
        "",
        "  private fun pureRound() {",
    ]
    out.extend(f"    pure{i}()" for i in range(len(pure)))
    out.append("  }")
    out.append("")
    out.append("  private fun facadeRound() {")
    out.extend(f"    facade{i}()" for i in range(len(facade)))
    out.append("  }")
    out.append("")
    out.extend(block(pure, "pure"))
    out.extend(block(facade, "facade"))
    out.extend(
        [
            "  private var seed = 2463534242L",
            "",
            "  private fun nextRandom(): Long {",
            "    seed = seed xor ((seed shl 13) and 0xFFFFFFFFL)",
            "    seed = seed xor (seed ushr 17)",
            "    seed = seed xor ((seed shl 5) and 0xFFFFFFFFL)",
            "    return seed",
            "  }",
            "",
            "  private fun nv(): Double {",
            "    val r = nextRandom()",
            "    return ((r % 200001) - 100000) / 10000.0 * SCALES[((r ushr 24) % 7).toInt()]",
            "  }",
            "",
            "  private fun ri(): Int = ((nextRandom() % 60001) - 30000).toInt()",
            "",
            "  private fun rnz(): Int = ri().let { if (it == 0) 1 else it }",
            "",
            "  private fun rs(): Int = (nextRandom() % 6).toInt()",
            "",
            "  private fun rl(): Long = nextRandom()",
            "",
            "  private fun rb(): Boolean = (nextRandom() and 1L) == 1L",
            "",
            "  private fun rotation2D(x: Vector2, origin: Vector2): Transform2D =",
            "    Transform2D(x, x.orthogonal(), origin)",
            "",
            "  private val hashes = linkedMapOf<String, Long>()",
            "",
            "  private fun mixBits(name: String, bits: Long) {",
            "    hashes[name] = ((hashes[name] ?: 2166136261L) xor bits) * 16777619L and 0xFFFFFFFFL",
            "  }",
            "",
            "  private fun mixLong(name: String, value: Long) {",
            "    mixBits(name, value and 0xFFFFFFFFL)",
            "    mixBits(name, (value ushr 32) and 0xFFFFFFFFL)",
            "  }",
            "",
            "  private fun mix(name: String, value: Any?) {",
            "    when (value) {",
            "      null -> mixLong(name, -1L)",
            "      is Double -> mixLong(name, if (value.isNaN()) 0x7FF8000000000000L else value.toRawBits())",
            "      is Long -> mixLong(name, value)",
            "      is Int -> mixLong(name, value.toLong())",
            "      is Boolean -> mixLong(name, if (value) 1L else 0L)",
            "      is String -> value.forEach { mixLong(name, it.code.toLong()) }",
            "      is RID -> mixLong(name, value.value)",
            "      is Vector2 -> listOf(value.x, value.y).forEach { mix(name, it) }",
            "      is Vector3 -> listOf(value.x, value.y, value.z).forEach { mix(name, it) }",
            "      is Vector4 -> listOf(value.x, value.y, value.z, value.w).forEach { mix(name, it) }",
            "      is Quaternion -> listOf(value.x, value.y, value.z, value.w).forEach { mix(name, it) }",
            "      is Color -> listOf(value.r, value.g, value.b, value.a).forEach { mix(name, it) }",
            "      is Vector2i -> listOf(value.x, value.y).forEach { mix(name, it) }",
            "      is Vector3i -> listOf(value.x, value.y, value.z).forEach { mix(name, it) }",
            "      is Vector4i -> listOf(value.x, value.y, value.z, value.w).forEach { mix(name, it) }",
            "      is Rect2 -> listOf(value.position, value.size).forEach { mix(name, it) }",
            "      is Rect2i -> listOf(value.position, value.size).forEach { mix(name, it) }",
            "      is AABB -> listOf(value.position, value.size).forEach { mix(name, it) }",
            "      is Plane -> listOf(value.normal, value.d).forEach { mix(name, it) }",
            "      is Basis -> listOf(value.x, value.y, value.z).forEach { mix(name, it) }",
            "      is Transform2D -> listOf(value.x, value.y, value.origin).forEach { mix(name, it) }",
            "      is Transform3D -> listOf(value.basis, value.origin).forEach { mix(name, it) }",
            "      is Projection -> listOf(value.x, value.y, value.z, value.w).forEach { mix(name, it) }",
            "      is List<*> -> value.forEach { mix(name, it) }",
            "      else -> error(\"no parity mix for ${value::class}\")",
            "    }",
            "  }",
            "",
            "  private fun summary(): String =",
            "    hashes.entries.joinToString(\" \") { (name, hash) -> \"${name.replace(' ', '_')}=${hash.toString(16)}\" }",
            "",
            "  private fun report(line: String) {",
            "    System.err.println(\"[kanama:kt] BuiltinParity kotlin $line\")",
            "  }",
            "",
            "  private companion object {",
            "    val SCALES = doubleArrayOf(0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0)",
            "  }",
            "}",
        ]
    )
    return "\n".join(out) + "\n"


def render_parity_gd(pure, facade) -> str:
    out = [
        f"# GENERATED by {GENERATOR} from extension_api.json — do not edit.",
        "extends Node2D",
        "# Task 134 B: the GDScript half of builtin_parity_smoke.tscn. Prints the same two lines as",
        "# BuiltinParitySmoke.kt; scripts/runtime_smoke.sh requires the two to be identical.",
        "",
        "const SCALES := [0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0]",
        "var seed := 2463534242",
        "var hashes := {}",
        "var hash_order := []",
        "",
        "",
        "func _ready() -> void:",
        f"\tfor i in {PARITY_INPUTS}:",
        "\t\tpure_round()",
        f"\treport(\"pure=n={PARITY_INPUTS} \" + summary())",
        "\thashes.clear()",
        "\thash_order.clear()",
        f"\tfor i in {FACADE_INPUTS}:",
        "\t\tfacade_round()",
        f"\treport(\"facade=n={FACADE_INPUTS} \" + summary())",
        "",
        "",
        "func pure_round() -> void:",
    ]
    out.extend(f"\tpure{i}()" for i in range(len(pure)))
    if not pure:
        out.append("\tpass")
    out.append("")
    out.append("")
    out.append("func facade_round() -> void:")
    out.extend(f"\tfacade{i}()" for i in range(len(facade)))
    if not facade:
        out.append("\tpass")
    for prefix, entries in (("pure", pure), ("facade", facade)):
        for i, (_, _, gd) in enumerate(entries):
            out.append("")
            out.append("")
            out.append(f"func {prefix}{i}() -> void:")
            out.extend("\t" + line for line in gd)
    out.extend(
        [
            "",
            "",
            "func next_random() -> int:",
            "\tseed = seed ^ ((seed << 13) & 0xFFFFFFFF)",
            "\tseed = seed ^ (seed >> 17)",
            "\tseed = seed ^ ((seed << 5) & 0xFFFFFFFF)",
            "\treturn seed",
            "",
            "",
            "func nv() -> float:",
            "\tvar r := next_random()",
            "\treturn ((r % 200001) - 100000) / 10000.0 * SCALES[(r >> 24) % 7]",
            "",
            "",
            "func ri() -> int:",
            "\treturn (next_random() % 60001) - 30000",
            "",
            "",
            "func rnz() -> int:",
            "\tvar v := ri()",
            "\treturn 1 if v == 0 else v",
            "",
            "",
            "func rs() -> int:",
            "\treturn next_random() % 6",
            "",
            "",
            "func rl() -> int:",
            "\treturn next_random()",
            "",
            "",
            "func rb() -> bool:",
            "\treturn (next_random() & 1) == 1",
            "",
            "",
            "func rid_from(value: int) -> RID:",
            "\treturn rid_from_int64(value)",
            "",
            "",
            "func rotation_2d(x: Vector2, origin: Vector2) -> Transform2D:",
            "\treturn Transform2D(x, x.orthogonal(), origin)",
            "",
            "",
            "func mix_bits(name: String, bits: int) -> void:",
            "\tif not hashes.has(name):",
            "\t\thashes[name] = 2166136261",
            "\t\thash_order.append(name)",
            "\thashes[name] = ((hashes[name] ^ bits) * 16777619) & 0xFFFFFFFF",
            "",
            "",
            "func mix_long(name: String, value: int) -> void:",
            "\tmix_bits(name, value & 0xFFFFFFFF)",
            "\tmix_bits(name, (value >> 32) & 0xFFFFFFFF)",
            "",
            "",
            "func mix(name: String, value) -> void:",
            "\tif value == null:",
            "\t\tmix_long(name, -1)",
            "\telif value is float:",
            "\t\tif is_nan(value):",
            "\t\t\tmix_long(name, 0x7FF8000000000000)",
            "\t\telse:",
            "\t\t\tmix_long(name, PackedFloat64Array([value]).to_byte_array().decode_s64(0))",
            "\telif value is bool:",
            "\t\tmix_long(name, 1 if value else 0)",
            "\telif value is int:",
            "\t\tmix_long(name, value)",
            "\telif value is String:",
            "\t\tfor i in value.length():",
            "\t\t\tmix_long(name, value.unicode_at(i))",
            "\telif value is RID:",
            "\t\tmix_long(name, value.get_id())",
            "\telif value is Vector2 or value is Vector2i:",
            "\t\tfor c in [value.x, value.y]: mix(name, c)",
            "\telif value is Vector3 or value is Vector3i:",
            "\t\tfor c in [value.x, value.y, value.z]: mix(name, c)",
            "\telif value is Vector4 or value is Vector4i or value is Quaternion:",
            "\t\tfor c in [value.x, value.y, value.z, value.w]: mix(name, c)",
            "\telif value is Color:",
            "\t\tfor c in [value.r, value.g, value.b, value.a]: mix(name, c)",
            "\telif value is Rect2 or value is Rect2i or value is AABB:",
            "\t\tfor c in [value.position, value.size]: mix(name, c)",
            "\telif value is Plane:",
            "\t\tfor c in [value.normal, value.d]: mix(name, c)",
            "\telif value is Basis:",
            "\t\tfor c in [value.x, value.y, value.z]: mix(name, c)",
            "\telif value is Transform2D:",
            "\t\tfor c in [value.x, value.y, value.origin]: mix(name, c)",
            "\telif value is Transform3D:",
            "\t\tfor c in [value.basis, value.origin]: mix(name, c)",
            "\telif value is Projection:",
            "\t\tfor c in [value.x, value.y, value.z, value.w]: mix(name, c)",
            "\telif value is PackedVector2Array or value is PackedVector3Array:",
            "\t\tfor c in value: mix(name, c)",
            "\telse:",
            "\t\tpush_error(\"no parity mix for %s\" % type_string(typeof(value)))",
            "",
            "",
            "func summary() -> String:",
            "\tvar parts := []",
            "\tfor name in hash_order:",
            "\t\tparts.append(\"%s=%x\" % [name.replace(\" \", \"_\"), hashes[name]])",
            "\treturn \" \".join(parts)",
            "",
            "",
            "func report(line: String) -> void:",
            "\tprinterr(\"[kanama:kt] BuiltinParity gdscript \", line)",
        ]
    )
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------------------------
# Main.
# ---------------------------------------------------------------------------------------------


def class_file(cls: str) -> Path:
    return TYPES_DIR / f"{cls}.kt"


def regenerate(api: dict) -> dict[Path, str]:
    """Every output path -> its regenerated content."""
    outputs: dict[Path, str] = {}
    sources = {cls: class_file(cls).read_text(encoding="utf-8") for cls in OWNED_CLASSES}
    hand_bodies = {cls: class_body(src, cls) for cls, src in sources.items()}
    HAND_BODIES.clear()
    HAND_BODIES.update({cls: strip_regions(body) for cls, body in hand_bodies.items()})
    members = build_members(api, hand_bodies)
    for cls in OWNED_CLASSES:
        source = sources[cls]
        instance = [m.code for m in members if m.cls == cls and m.code and not m.static]
        statics = [m.code for m in members if m.cls == cls and m.code and m.static]
        if instance:
            region = render_region(cls, instance, BEGIN, END, "  ")
            source = splice(source, cls, region, BEGIN, END, class_companion_anchor(cls, False))
        if statics:
            region = render_region(cls, statics, SBEGIN, SEND, "    ")
            source = splice(source, cls, region, SBEGIN, SEND, companion_open_anchor(cls))
        outputs[class_file(cls)] = source
    outputs[MARSHALLING] = render_marshalling(api, members)
    outputs[SCALAR_OPS] = render_scalar_ops(api, web=False)
    # Web: the pure, component-wise members of the classes it has.
    web_source = WEB_TYPES.read_text(encoding="utf-8")
    for cls, vt in VALUE_TYPES.items():
        if not vt.web:
            continue
        web_body = class_body(web_source, cls)
        web_hand = hand_members(web_body)
        codes = []
        for m in members:
            if m.cls != cls or not m.web:
                continue
            fn_match = re.search(r"fun\s+(\w+)\s*\(\s*(?:\w+\s*:\s*([\w<>]+))?", m.web)
            if fn_match and has_member(web_hand, fn_match.group(1), fn_match.group(2)):
                continue
            if fn_match and not fn_match.group(2) and has_member(web_hand, fn_match.group(1)):
                continue
            codes.append(m.web)
        if codes:
            region = render_region(cls, codes, BEGIN, END, "  ")
            web_source = splice(web_source, cls, region, BEGIN, END, class_companion_anchor(cls, True))
    outputs[WEB_TYPES] = web_source
    outputs[WEB_SCALAR_OPS] = render_scalar_ops(api, web=True)
    pure, facade = parity_entries(members)
    outputs[PARITY_KT] = render_parity_kt(pure, facade)
    outputs[PARITY_GD] = render_parity_gd(pure, facade)
    outputs[WEB_TEST] = render_web_test(pure, web_source)
    return outputs


def members_for_gate(api: dict) -> list[Member]:
    sources = {cls: class_file(cls).read_text(encoding="utf-8") for cls in OWNED_CLASSES}
    hand_bodies = {cls: class_body(src, cls) for cls, src in sources.items()}
    return build_members(api, hand_bodies)


def same(path: Path, content: str) -> bool:
    if not path.exists():
        return False
    current = path.read_text(encoding="utf-8")
    if path.suffix == ".kt":
        return comparison_key(current) == comparison_key(content)
    return current == content


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument(
        "--record-parity",
        metavar="LOG",
        type=Path,
        help="record the GDScript hashes of the Web-capable parity entries from a runtime smoke log",
    )
    mode.add_argument(
        "--verify-recorded",
        metavar="LOG",
        type=Path,
        help="fail when the recorded hashes differ from the log's GDScript line (runtime smoke)",
    )
    args = parser.parse_args()
    api = load_api()
    outputs = regenerate(api)
    if args.record_parity or args.verify_recorded:
        log = (args.record_parity or args.verify_recorded).read_text(encoding="utf-8", errors="replace")
        live = parse_gdscript_pure(log)
        sources = {cls: class_file(cls).read_text(encoding="utf-8") for cls in OWNED_CLASSES}
        members = build_members(api, {cls: class_body(src, cls) for cls, src in sources.items()})
        pure, _ = parity_entries(members)
        keys = web_parity_keys(pure, outputs[WEB_TYPES])
        if args.record_parity:
            missing = [k for k in keys if k not in live]
            if missing:
                raise SystemExit(f"[generate_builtin_ops] the log lacks {len(missing)} entries: {missing[:5]}")
            EXPECTED_PATH.parent.mkdir(parents=True, exist_ok=True)
            payload = {
                "comment": "Godot 4.7.2 GDScript hashes of the builtin parity row (float32 build), for the "
                "entries the Web value types run (WebBuiltinParityTest). Written by "
                "`scripts/generate_builtin_ops.py --record-parity <runtime smoke log>`.",
                "pure": {k: live[k] for k in keys},
            }
            EXPECTED_PATH.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n", encoding="utf-8")
            print(f"[generate_builtin_ops] recorded {len(keys)} Web parity hashes; rerun --write for the Web test")
            return 0
        recorded = load_expected()
        problems = [f"{k}: recorded {v}, GDScript {live.get(k)}" for k, v in recorded.items() if live.get(k) != v]
        problems += [f"{k}: not recorded (run --record-parity)" for k in keys if k not in recorded]
        if problems:
            print(f"[generate_builtin_ops] FAIL: the recorded Web parity hashes are stale ({len(problems)}):", file=sys.stderr)
            for line in problems[:20]:
                print(f"    {line}", file=sys.stderr)
            return 1
        print(f"[generate_builtin_ops] PASS: {len(recorded)} recorded Web parity hashes match GDScript")
        return 0
    stale = [path for path, content in outputs.items() if not same(path, content)]
    if args.check:
        if stale:
            print(f"[generate_builtin_ops] FAIL: {len(stale)} file(s) differ from a fresh generation:", file=sys.stderr)
            for path in stale:
                print(f"    {path.relative_to(ROOT)}", file=sys.stderr)
            print("    fix: python3 scripts/generate_builtin_ops.py --write && ./gradlew ktfmtFormat", file=sys.stderr)
            return 1
        print(f"[generate_builtin_ops] PASS: {len(outputs)} outputs current")
        return 0
    for path in stale:
        path.write_text(outputs[path], encoding="utf-8")
    print(f"[generate_builtin_ops] wrote {len(stale)} of {len(outputs)} outputs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
