#!/usr/bin/env python3
"""Generate engine-wide Godot name constants from extension_api.json."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_API = ROOT / "extension_api.json"
DEFAULT_OUTPUT_DIR = ROOT / "src/jvmMain/kotlin/net/multigesture/kanama/api"

KOTLIN_KEYWORDS = {
    "as",
    "break",
    "class",
    "continue",
    "do",
    "else",
    "false",
    "for",
    "fun",
    "if",
    "in",
    "interface",
    "internal",
    "is",
    "null",
    "object",
    "package",
    "return",
    "super",
    "this",
    "throw",
    "true",
    "try",
    "typealias",
    "typeof",
    "val",
    "var",
    "when",
    "while",
}


def kotlin_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def constant_identifier(name: str) -> str:
    parts = [part for part in re.split(r"[_\-\s\.:/]+", name.strip("_")) if part]
    cleaned_parts: list[str] = []
    for index, part in enumerate(parts):
        cleaned = "".join(ch for ch in part if ch.isalnum() or ch == "_")
        if not cleaned:
            continue
        if index == 0:
            cleaned_parts.append(cleaned[:1].lower() + cleaned[1:])
        else:
            cleaned_parts.append(cleaned[:1].upper() + cleaned[1:])
    base = "".join(cleaned_parts) or "name"
    if not (base[0].isalpha() or base[0] == "_"):
        base = "name" + base[:1].upper() + base[1:]
    return f"`{base}`" if base in KOTLIN_KEYWORDS else base


def unique_constants(names: set[str]) -> list[tuple[str, str]]:
    constants: list[tuple[str, str]] = []
    seen: dict[str, str] = {}
    for name in sorted(names, key=lambda value: (len(value) - len(value.lstrip("_")), value)):
        base = constant_identifier(name)
        existing = seen.get(base)
        if existing == name:
            continue
        if existing is None:
            seen[base] = name
            constants.append((base, name))
            continue

        bare = base.removeprefix("`").removesuffix("`")
        index = 2
        while True:
            candidate_bare = f"{bare}{index}"
            candidate = f"`{candidate_bare}`" if candidate_bare in KOTLIN_KEYWORDS else candidate_bare
            existing = seen.get(candidate)
            if existing is None:
                seen[candidate] = name
                constants.append((candidate, name))
                break
            if existing == name:
                break
            index += 1
    return constants


def named_items(items: object) -> set[str]:
    names: set[str] = set()
    if not isinstance(items, list):
        return names
    for item in items:
        if not isinstance(item, dict):
            continue
        name = item.get("name")
        if isinstance(name, str) and name:
            names.add(name)
    return names


def collect_names(api: dict[str, object]) -> tuple[set[str], set[str], set[str]]:
    method_names: set[str] = set()
    property_names: set[str] = set()
    signal_names: set[str] = set()

    method_names.update(named_items(api.get("utility_functions")))

    for cls in list(api.get("builtin_classes") or ()) + list(api.get("classes") or ()):
        if not isinstance(cls, dict):
            continue
        method_names.update(named_items(cls.get("methods")))
        property_names.update(named_items(cls.get("members")))
        property_names.update(named_items(cls.get("properties")))
        signal_names.update(named_items(cls.get("signals")))

    return method_names, property_names, signal_names


def render_object(object_name: str, constants: list[tuple[str, str]], version: str) -> str:
    lines = [
        "// Generated by generate_name_constants.py -- do not edit.",
        f"// Source: extension_api.json ({version})",
        "package net.multigesture.kanama.api",
        "",
        "/**",
        f" * Engine-wide Godot {object_name.removesuffix('Name').lower()} name constants.",
        " *",
        " * Values are raw Godot snake_case names for APIs that accept StringName-style",
        " * arguments, such as dynamic method calls, signal connections, and grouped",
        " * property updates.",
        " */",
        f"object {object_name} {{",
    ]
    for identifier, value in constants:
        lines.append(f"    const val {identifier}: String = {kotlin_string(value)}")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--api", type=Path, default=DEFAULT_API)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    api = json.loads(args.api.read_text(encoding="utf-8"))
    header = api.get("header") if isinstance(api.get("header"), dict) else {}
    version = str(header.get("version_full_name") or "unknown Godot API")

    methods, properties, signals = collect_names(api)
    outputs = {
        "MethodName.kt": render_object("MethodName", unique_constants(methods), version),
        "PropertyName.kt": render_object("PropertyName", unique_constants(properties), version),
        "SignalName.kt": render_object("SignalName", unique_constants(signals), version),
    }

    args.output_dir.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []
    for filename, content in outputs.items():
        path = args.output_dir / filename
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path))
        else:
            write_if_changed(path, content)

    if stale:
        print("[name_constants] stale generated files:")
        for path in stale:
            print(f"  {path}")
        print("[name_constants] run scripts/generate_name_constants.py")
        return 1

    action = "checked" if args.check else "generated"
    print(
        "[name_constants] "
        f"{action} methods={len(methods)} properties={len(properties)} signals={len(signals)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
