#!/usr/bin/env python3
"""Generate the Kotlin/Wasm Web wrapper tree from the Web call contract (task 96).

Every opcode in `scripts/platform_backend_calls.json` becomes one member on the Godot class that
owns it, in `web-runtime/src/commonMain/kotlin/net/multigesture/kanama/api/generated/<Class>.kt`
(one class, one file). The member's name, parameters, defaults and return type come from
`extension_api.json` (the same source the native wrapper generator reads), the call itself goes
straight to `GodotBackendCalls.invoke<Shape>(InitialGodotCallDescriptors.X, ...)`, so the former
hand-written probe + wrapper pair collapses into one generated layer.

What stays hand-written is explicit and short: `WEB_HANDSHAPED` names the bespoke facades that
live in hand-written files under `api/`, and `CLASS_POLICY[...]["custom"]` carries the Web-specific
members the contract cannot express (compositions over several opcodes, Kotlin-side mirrors,
lifetime helpers). Both are checked by `--check`, which also fails if a hand-written file under
`api/` dispatches an opcode the generated tree owns.

Usage:
    python3 scripts/generate_web_wrappers.py            # regenerate the tree
    python3 scripts/generate_web_wrappers.py --check    # committed == fresh regen, gate mode
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from generate_web_backend import SIGNATURES  # noqa: E402  (SPI parameter list per call shape)
from platform_backend_contract import INITIAL_BACKEND_CALLS, BackendCallPolicy  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
API_PATH = ROOT / "extension_api.json"
API_DIR = ROOT / "web-runtime/src/commonMain/kotlin/net/multigesture/kanama/api"
GENERATED_DIR = API_DIR / "generated"
TAG = "[web_wrappers]"

HEADER = "// Generated by scripts/generate_web_wrappers.py — do not edit.\n"


class GenerationError(RuntimeError):
    pass


# --------------------------------------------------------------------------------------------------
# extension_api.json access
# --------------------------------------------------------------------------------------------------


class Api:
    def __init__(self, path: Path = API_PATH) -> None:
        payload = json.loads(path.read_text())
        self.classes: dict[str, dict] = {c["name"]: c for c in payload["classes"]}
        self.utilities: dict[str, dict] = {u["name"]: u for u in payload["utility_functions"]}
        self.global_enums: dict[str, dict] = {e["name"]: e for e in payload["global_enums"]}
        self.singletons: set[str] = {s["name"] for s in payload.get("singletons", ())}

    def parent(self, name: str) -> str | None:
        return self.classes[name].get("inherits")

    def chain(self, name: str) -> list[str]:
        out = []
        while name:
            out.append(name)
            name = self.parent(name)
        return out

    def method(self, call: BackendCallPolicy) -> dict:
        if call.scope == "utility":
            return self.utilities[call.method_name]
        for method in self.classes[call.class_name].get("methods", ()):
            if method["name"] == call.method_name and method["hash"] == call.expected_hash:
                return method
        raise GenerationError(f"opcode {call.opcode}: {call.class_name}.{call.method_name} not in API")

    def property_for(self, class_name: str, method_name: str) -> dict | None:
        """The non-indexed property of `class_name` (or an ancestor) that `method_name` gets/sets."""
        for owner in self.chain(class_name):
            for prop in self.classes[owner].get("properties", ()):
                if "index" in prop:
                    continue
                if prop.get("setter") == method_name or prop.get("getter") == method_name:
                    return prop
        return None

    def enum_values(self, owner: str, enum: str) -> dict[str, int]:
        source = (
            self.global_enums.get(enum)
            if owner == "@GlobalScope"
            else next((e for e in self.classes[owner].get("enums", ()) if e["name"] == enum), None)
        )
        if source is None:
            raise GenerationError(f"enum {owner}.{enum} not in API")
        return {v["name"]: v["value"] for v in source["values"]}

    def constant(self, owner: str, name: str) -> int:
        for constant in self.classes[owner].get("constants", ()):
            if constant["name"] == name:
                return constant["value"]
        raise GenerationError(f"constant {owner}.{name} not in API")

    def has_signal(self, class_name: str, signal: str) -> bool:
        return any(
            s["name"] == signal
            for owner in self.chain(class_name)
            for s in self.classes[owner].get("signals", ())
        )


# --------------------------------------------------------------------------------------------------
# Naming
# --------------------------------------------------------------------------------------------------

KEYWORD_RENAMES = {"internal": "internalMode", "class": "className", "object": "target", "RID": "rid"}


def camel(snake: str) -> str:
    parts = snake.split("_")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def param_name(godot_name: str) -> str:
    return KEYWORD_RENAMES.get(godot_name, camel(godot_name))


def kotlin_class_name(godot_name: str) -> str:
    return "GodotObject" if godot_name == "Object" else godot_name


# --------------------------------------------------------------------------------------------------
# Type mapping. Kotlin public types follow the desktop generator (`wrapper_model.value_policy`):
# int32-meta ints are Int, everything else Long, enums/bitfields Long, float Double. Conversions to
# and from the SPI's contract value types are one-liners on the generated support file.
# --------------------------------------------------------------------------------------------------

INT32_METAS = {"int8", "int16", "int32", "char32", "uint8", "uint16"}
VALUE_TYPES = {"Vector2", "Vector3", "Vector2i", "Vector3i", "Color", "Rect2", "Basis", "Transform3D"}
STRING_TYPES = {"String", "StringName", "NodePath"}
# SPI value type -> Kotlin API type, for Variant-typed arguments whose shape fixes the type.
SPI_TO_API = {
    "Boolean": "Boolean",
    "Int": "Int",
    "Long": "Long",
    "Double": "Double",
    "String": "String",
    "GodotVector2": "Vector2",
    "GodotVector3": "Vector3",
    "GodotVector2i": "Vector2i",
    "GodotVector3i": "Vector3i",
    "GodotColor": "Color",
    "GodotRect2": "Rect2",
    "GodotBasis": "Basis",
    "GodotTransform3D": "Transform3D",
}


def int_type(meta: str) -> str:
    return "Int" if meta in INT32_METAS else "Long"


@dataclass
class Tree:
    """The generated class set: every contract class plus its Godot ancestors plus EXTRA_CLASSES."""

    api: Api
    classes: set[str]

    def wrapper_for(self, godot_type: str) -> str:
        """Kotlin wrapper for an object-typed slot: the class, else its nearest generated ancestor."""
        name = godot_type.split("::")[-1]
        for owner in self.api.chain(name) if name in self.api.classes else ["Object"]:
            if owner in self.classes or owner == "Object":
                return kotlin_class_name(owner)
        return "GodotObject"

    def is_object(self, godot_type: str) -> bool:
        return godot_type in self.api.classes or godot_type in ("Object", "Variant")


def api_param_type(tree: Tree, godot_type: str, meta: str, spi_type: str) -> str:
    """Kotlin parameter type for a Godot argument bound to an SPI slot of `spi_type`."""
    if godot_type == "bool":
        return "Boolean"
    if godot_type == "int":
        return "Int" if spi_type == "Int" else int_type(meta)
    if godot_type.startswith("enum::") or godot_type.startswith("bitfield::"):
        return "Long"
    if godot_type == "float":
        return "Double"
    if godot_type in STRING_TYPES:
        return "String"
    if godot_type in VALUE_TYPES:
        return godot_type
    if godot_type == "Variant":
        if spi_type.startswith("GodotHandle"):
            return "GodotObject" + ("?" if spi_type.endswith("?") else "")
        return SPI_TO_API[spi_type]
    if godot_type == "RID":
        return "GodotObject"  # Web adaptation: the applier derives the RID engine-side.
    if tree.is_object(godot_type):
        return tree.wrapper_for(godot_type) + ("?" if spi_type.endswith("?") else "")
    raise GenerationError(f"no Kotlin parameter type for Godot type {godot_type!r}")


def to_backend(expr: str, kotlin_type: str, spi_type: str) -> str:
    """Expression converting a Kotlin API value to the SPI slot type."""
    if spi_type in ("GodotHandle", "GodotHandle?"):
        return f"{expr}?.requireOpenHandle()" if kotlin_type.endswith("?") else f"{expr}.requireOpenHandle()"
    if spi_type == "Long" and kotlin_type == "Int":
        return f"{expr}.toLong()"
    if spi_type.startswith("Godot"):
        return f"{expr}.toBackend()"
    return expr


def api_return(tree: Tree, godot_type: str, meta: str, spi_ret: str) -> tuple[str, str]:
    """(Kotlin return type, conversion suffix applied to the SPI result expression)."""
    if spi_ret == "":
        return "", ""
    if spi_ret in ("Boolean", "Double", "String"):
        return spi_ret, ""
    if spi_ret == "Int":
        return ("Long", ".toLong()") if godot_type == "int" and int_type(meta) == "Long" else ("Int", "")
    if spi_ret == "Long":
        if godot_type == "int" and int_type(meta) == "Int":
            return "Int", ".toInt()"
        return "Long", ""
    if spi_ret == "List<String>":
        return "List<String>", ""
    if spi_ret == "List<GodotVector3i>":
        return "List<Vector3i>", ".map { it.toApi() }"
    if spi_ret in SPI_TO_API:
        return SPI_TO_API[spi_ret], ".toApi()"
    if spi_ret == "GodotHandle?":
        wrapper = tree.wrapper_for(godot_type) if godot_type != "Variant" else "GodotObject"
        return f"{wrapper}?", f"?.let {{ {wrapper}(it.toWebId()) }}"
    if spi_ret == "List<GodotHandle>":
        element = godot_type.split("::")[-1]
        wrapper = tree.wrapper_for(element)
        return f"List<{wrapper}>", f".map {{ {wrapper}(it.toWebId()) }}"
    raise GenerationError(f"no Kotlin return mapping for SPI type {spi_ret!r}")


def kotlin_default(godot_default: str, kotlin_type: str) -> str | None:
    """Kotlin literal for a Godot default value, or None when it cannot be expressed."""
    if godot_default in ("null", "[]", "{}"):
        return None
    if kotlin_type == "Boolean":
        return godot_default
    if kotlin_type == "Int":
        return str(int(godot_default))
    if kotlin_type == "Long":
        return f"{int(godot_default)}L"
    if kotlin_type == "Double":
        return repr(float(godot_default))
    if kotlin_type == "String":
        return '"' + godot_default.lstrip("&").strip('"') + '"'
    known = {
        "Vector3(0, 0, 0)": "Vector3.ZERO",
        "Vector3(0, 1, 0)": "Vector3.UP",
        "Vector2(0, 0)": "Vector2.ZERO",
        "Color(1, 1, 1, 1)": "Color(1f, 1f, 1f, 1f)",
    }
    if godot_default in known:
        return known[godot_default]
    raise GenerationError(f"no Kotlin default for {godot_default!r} as {kotlin_type}")


# --------------------------------------------------------------------------------------------------
# Rendering (filled in family by family)
# --------------------------------------------------------------------------------------------------


@dataclass
class Param:
    name: str
    kotlin_type: str
    default: str | None = None
    backend_expr: str | None = None  # None for baked (not carried) arguments
    guard: str | None = None


@dataclass
class Member:
    """One rendered class member plus its top-level import-compat alias."""

    body: list[str]
    alias: list[str] = field(default_factory=list)
    name: str = ""
    params: list[Param] = field(default_factory=list)
    ret: str = ""


def spi_slots(shape: str) -> tuple[bool, list[tuple[str, str]]]:
    """(has receiver, [(slot name, slot type)]) for a call shape's GodotBackendCalls facade."""
    params, _ = SIGNATURES[shape]
    slots = [tuple(p.split(": ", 1)) for p in params]
    has_receiver = bool(slots) and slots[0][0] == "receiver"
    return has_receiver, [(n, t) for n, t in slots if n != "receiver"]


def invoke_name(shape: str) -> str:
    from generate_web_backend import _method_name

    return _method_name(shape)


def descriptor_name(call: BackendCallPolicy) -> str:
    if call.descriptor_name:
        return call.descriptor_name
    owner = "UTILITY" if call.class_name == "@GlobalScope" else call.class_name.upper()
    return f"{owner}_{call.method_name.upper()}"


def member_name(call: BackendCallPolicy, policy: dict) -> str:
    if "name" in policy:
        return str(policy["name"])
    return camel(call.method_name)


def bind_arguments(tree: Tree, call: BackendCallPolicy, method: dict, policy: dict) -> list[Param]:
    """Bind the shape's SPI slots to the Godot arguments positionally; the rest are baked."""
    _, slots = spi_slots(call.shape)
    godot_args = list(method.get("arguments", ()))
    for i, tail_type in enumerate(call.typed_vararg_tail):
        godot_args.append({"name": f"__tail{i}", "type": tail_type})
    if len(slots) > len(godot_args):
        raise GenerationError(
            f"opcode {call.opcode}: shape {call.shape} carries {len(slots)} values but "
            f"{call.class_name}.{call.method_name} has {len(godot_args)} arguments; add a `bind` policy"
        )
    params: list[Param] = []
    tail_names = list(policy.get("tail_names", ()))
    for (slot_name, slot_type), arg in zip(slots, godot_args):
        if arg["name"].startswith("__tail"):
            name = tail_names.pop(0) if tail_names else slot_name
        else:
            name = param_name(arg["name"])
        kotlin_type = policy.get("param_types", {}).get(name) or api_param_type(
            tree, arg["type"], arg.get("meta", ""), slot_type
        )
        default = kotlin_default(arg["default_value"], kotlin_type) if "default_value" in arg else None
        params.append(Param(name, kotlin_type, default, to_backend(name, kotlin_type, slot_type)))
    label = f"{call.class_name}.{call.method_name}"
    baked_values = dict(policy.get("baked", {}))
    for arg in godot_args[len(slots) :]:
        name = param_name(arg["name"])
        if name in policy.get("hide", ()):
            continue
        kotlin_type = api_param_type(tree, arg["type"], arg.get("meta", ""), "GodotHandle?")
        if name in baked_values:
            default = str(baked_values.pop(name))
        elif "default_value" in arg:
            default = kotlin_default(arg["default_value"], kotlin_type)
            if default is None:
                continue  # Variant/Array defaults the shape cannot carry are not exposed at all
        else:
            raise GenerationError(f"{label}: argument {name} is not carried and has no default; add `baked`")
        shown = default.replace('"', "'")
        guard = f'require({name} == {default}) {{ "Web {label} supports only {name} = {shown}" }}'
        params.append(Param(name, kotlin_type, default, None, guard))
    if baked_values:
        raise GenerationError(f"{label}: baked policy names unknown arguments {sorted(baked_values)}")
    return params


MAX_WIDTH = 100


def wrap_call(prefix: str, args: list[str], suffix: str, indent: str, lead: str = "") -> list[str]:
    """`lead prefix(args)suffix` on one line when it fits, else one argument per line (ktfmt shape)."""
    one_line = f"{indent}{lead}{prefix}({', '.join(args)}){suffix}"
    if len(one_line) <= MAX_WIDTH or not args:
        return [one_line]
    lines = [f"{indent}{lead}{prefix}("]
    lines += [f"{indent}  {arg}," for arg in args]
    lines.append(f"{indent}){suffix}")
    return lines


def render_signature(name: str, params: list[Param], ret: str, modifiers: str = "", indent: str = "  ") -> list[str]:
    rendered = [
        f"{p.name}: {p.kotlin_type}" + (f" = {p.default}" if p.default is not None else "") for p in params
    ]
    suffix = f": {ret}" if ret else ""
    return wrap_call(f"{modifiers}fun {name}", rendered, suffix, indent)


def emit_opcode(tree: Tree, call: BackendCallPolicy, policy: dict) -> Member:
    api = tree.api
    method = api.method(call)
    has_receiver, _ = spi_slots(call.shape)
    name = member_name(call, policy)
    if "bind" in policy:
        params = [Param(*spec) for spec in policy["bind"]]
    else:
        params = bind_arguments(tree, call, method, policy)
    godot_ret = method.get("return_value", {}).get("type", method.get("return_type", "void"))
    ret_meta = method.get("return_value", {}).get("meta", "")
    _, spi_ret = SIGNATURES[call.shape]
    ret, convert = api_return(tree, godot_ret, ret_meta, spi_ret)
    if "ret" in policy:
        ret = str(policy["ret"])
        convert = ""
        if ret == "Unit":
            ret = ""
    if policy.get("raw_handle_return"):
        ret, convert = "GodotHandle?", "?.let { it.toWebId() }"
    nonnull = policy.get("nonnull")
    call_args = [f"D.{descriptor_name(call)}"]
    if has_receiver:
        call_args.append("requireOpenHandle()")
    if "args" in policy:
        call_args += list(policy["args"])
    else:
        call_args += [p.backend_expr for p in params if p.backend_expr is not None]
    call_args += list(policy.get("extra_args", ()))
    invoke = f"GodotBackendCalls.{invoke_name(call.shape)}"
    guards = [p.guard for p in params if p.guard] + list(policy.get("guards", ()))
    pre = list(policy.get("pre", ()))
    post = list(policy.get("post", ()))
    fluent = policy.get("fluent")
    owner = kotlin_class_name(call.class_name) if call.class_name != "@GlobalScope" else "GD"
    if fluent:
        ret = owner
    if nonnull:
        ret = ret.rstrip("?")
    modifiers = ""
    if policy.get("visibility"):
        modifiers += f"{policy['visibility']} "
    if policy.get("open"):
        modifiers += "open "
    doc = policy.get("doc")
    body: list[str] = []
    if doc:
        body.append(f"  /** {doc} */")
    signature = render_signature(name, params, ret, modifiers)
    expression_body = not (guards or pre or post or fluent or nonnull or "body" in policy)
    if expression_body and ret:
        body += signature[:-1] + [signature[-1] + " ="]
        body += wrap_call(invoke, call_args, convert, "    ")
        alias = [] if policy.get("visibility") in ("internal", "protected", "private") else _alias(owner, name, params, ret)
        return Member(body, alias, name, params, ret)
    body += signature[:-1] + [signature[-1] + " {"]
    if "body" in policy:
        body += [f"    {line}" for line in policy["body"]]
    else:
        body += [f"    {line}" for line in pre]
        body += [f"    {g}" for g in guards]
        if fluent:
            body += wrap_call(invoke, call_args, "", "    ", "val returned = ")
            same = "returned.backendToken() == backendHandle.backendToken()"
            if fluent == "self":
                body.append(f"    check(returned != null && {same}) {{ \"{owner}.{name} did not return its receiver\" }}")
                body.append("    return this")
            else:
                body.append(f"    return if (returned == null || {same}) this else {owner}(returned.toWebId())")
        elif nonnull:
            body += wrap_call(invoke, call_args, convert, "    ", "val returned = ")
            body.append(f'    return checkNotNull(returned) {{ "{nonnull}" }}')
        elif post:
            body += wrap_call(invoke, call_args, convert, "    ")
            body += [f"    {line}" for line in post]
        else:
            body += wrap_call(invoke, call_args, convert, "    ", "return " if ret else "")
    body.append("  }")
    alias = [] if policy.get("visibility") in ("internal", "protected", "private") else _alias(owner, name, params, ret)
    return Member(body, alias, name, params, ret)


def emit_extras(tree: Tree, call: BackendCallPolicy, policy: dict, primary: Member) -> list[Member]:
    """Extra spellings a policy asks for: forwarding names and typed ResourceLoader loads."""
    owner = kotlin_class_name(call.class_name) if call.class_name != "@GlobalScope" else "GD"
    extras: list[Member] = []
    forward = ", ".join(p.name for p in primary.params)
    for extra in policy.get("extra_names", ()):
        signature = render_signature(extra, primary.params, primary.ret)
        body = signature[:-1] + [f"{signature[-1]} = {primary.name}({forward})"]
        extras.append(Member(body, _alias(owner, extra, primary.params, primary.ret), extra, primary.params, primary.ret))
    for godot_type, extra in policy.get("typed_loads", {}).items():
        wrapper = tree.wrapper_for(godot_type)
        params = [Param("path", "String"), Param("cacheMode", "Long", "1L")]
        signature = render_signature(extra, params, f"{wrapper}?")
        body = signature[:-1] + [f'{signature[-1]} = {primary.name}(path, "{godot_type}", cacheMode)?.let {{ {wrapper}(it.handle) }}']
        extras.append(Member(body, _alias(owner, extra, params, f"{wrapper}?"), extra, params, f"{wrapper}?"))
    return extras


def _alias(owner: str, name: str, params: list[Param], ret: str) -> list[str]:
    """Import-compat extension so `import net.multigesture.kanama.api.<name>` keeps resolving."""
    forward = ", ".join(p.name for p in params)
    lines = ['@Suppress("EXTENSION_SHADOWED_BY_MEMBER")']
    signature = render_signature(f"{owner}.{name}", params, ret, indent="")
    lines += signature[:-1] + [f"{signature[-1]} = {name}({forward})"]
    return lines


# --------------------------------------------------------------------------------------------------
# Web-local wrapper policy. Per-opcode overrides where the contract alone does not fix the Kotlin
# spelling; per-class hand-shaped members (custom sections), factories, lifetimes and constants.
# --------------------------------------------------------------------------------------------------

_UNIT = 'section + "\\u001F" + key'  # the applier splits packed ConfigFile keys on the unit separator

WRAPPER_POLICY: dict[int, dict] = {
    # Callable-taking calls: the shape carries (target, method) in place of Godot's Callable.
    22: {
        "visibility": "internal",
        "bind": [
            ("signal", "String", None, "signal"),
            ("target", "GodotObject", None, "target.requireOpenHandle()"),
            ("method", "String", None, "method"),
            ("flags", "Long", "0L", "flags"),
        ],
    },
    34: {
        "name": "connectBound",
        "visibility": "internal",
        "bind": [
            ("signal", "String", None, "signal"),
            ("target", "GodotObject", None, "target.requireOpenHandle()"),
            ("method", "String", None, "method"),
            ("boundValue", "Long", None, "boundValue"),
            ("flags", "Long", "0L", "flags"),
        ],
    },
    193: {
        "name": "disconnectBound",
        "visibility": "internal",
        "ret": "Unit",
        "bind": [
            ("signal", "String", None, "signal"),
            ("target", "GodotObject", None, "target.requireOpenHandle()"),
            ("method", "String", None, "method"),
            ("boundValue", "Long", None, "boundValue"),
        ],
        "extra_args": ["-1L"],
    },
    137: {
        "ret": "Unit",
        "doc": "Chain a callback step to a registered method on a Kanama script (FPS change_weapon).",
        "bind": [("target", "GodotObject", None, "target.requireOpenHandle()"), ("method", "String", None, "method")],
    },
    192: {
        "ret": "Unit",
        "doc": "Tween a registered method with an interpolated double (the Callable binds proxy-side).",
        "bind": [
            ("target", "GodotObject", None, "target.requireOpenHandle()"),
            ("method", "String", None, "method"),
            ("from", "Double", None, "from"),
            ("to", "Double", None, "to"),
            ("duration", "Double", None, "duration"),
        ],
    },
    # The shape carries the surface only; the material is baked to null (clear the override).
    189: {"baked": {"material": "null"}, "doc": "Web supports only clearing an override (material baked null in the family)."},
    # ConfigFile keys ride one StringName packed with a unit separator; values carry a type tag.
    266: {"bind": [("section", "String", None, None), ("key", "String", None, None)], "args": [_UNIT]},
    267: {
        "bind": [("section", "String", None, None), ("key", "String", None, None), ("value", "Any?", None, None)],
        "pre": [
            "val tagged =",
            "  when (value) {",
            '    is Boolean -> "b:$value"',
            '    is Long -> "i:$value"',
            '    is Int -> "i:$value"',
            '    is Double -> "f:$value"',
            '    is String -> "s:$value"',
            '    else -> error("Kanama Web ConfigFile does not carry ${value?.let { it::class }} values")',
            "  }",
        ],
        "args": [_UNIT + ' + "\\u001F" + tagged'],
    },
    268: {
        "ret": "Any?",
        "bind": [("section", "String", None, None), ("key", "String", None, None)],
        "body": [
            "val tagged =",
            f"  GodotBackendCalls.invokeStringNameRetString(D.CONFIGFILE_GET_VALUE, requireOpenHandle(), {_UNIT})",
            "val body = tagged.drop(2)",
            "return when {",
            '  tagged.startsWith("b:") -> body == "true"',
            '  tagged.startsWith("i:") -> body.toLong()',
            '  tagged.startsWith("f:") -> body.toDouble()',
            '  tagged.startsWith("s:") -> body',
            "  else -> null",
            "}",
        ],
    },
    # propagate_call("set", [property, value]) with a Boolean value (the shadow-mapping sweep).
    279: {
        "name": "propagateSet",
        "doc": 'Godot\'s `propagate_call("set", [property, value])` (the shadow-mapping sweep).',
        "bind": [("property", "String", None, "property"), ("value", "Boolean", None, "value")],
    },
    # Typed vararg arms: `emit_signal`/`call`/`call_deferred` keep the corpus's parameter names and
    # the Unit return the hand-written dispatcher exposed.
    8: {"ret": "Unit", "tail_names": ["value"]},
    28: {"ret": "Unit", "tail_names": ["value"]},
    35: {"ret": "Unit"},
    148: {"ret": "Unit", "tail_names": ["value"]},
    196: {"ret": "Unit", "tail_names": ["value"]},
    105: {"tail_names": ["argument"], "doc": "Dynamic one-String-argument method call (e.g. a native GDScript autoload's play(path))."},
    132: {"tail_names": ["value"], "doc": "Dynamic one-Double-argument method call (the FPS's damage(amount) on ray hits)."},
    191: {"tail_names": ["first", "second"], "doc": "Dynamic two-Vector3 dispatch (the corpus's damage(impact, force) convention)."},
    281: {"tail_names": ["argument"]},
    # Object.get / set_indexed restricted to one value type each; the descriptor name says which.
    149: {"name": "getObjectProperty", "doc": "Object.get restricted to object-valued properties; non-objects resolve to null."},
    233: {"name": "getVector2", "doc": "Vector2-valued property read (the robot's aim blend position)."},
    151: {"name": "set", "doc": "Property-path write (AnimationTree parameters); the typed overloads pick the transport."},
    230: {"name": "set"},
    231: {"name": "set"},
    232: {"name": "set"},
    # Owning construction stays behind the generated factories.
    12: {"visibility": "internal", "ret": "BackendGodotHandle?"},
    # Tween/Tweener fluent returns collapse onto the receiver (desktop's self-collapse policy).
    37: {
        "doc": "Desktop parity: kill() on a tween that already finished is a legal no-op (the FPS clears its weapon-swap tween on every swap and at exit_tree).",
        "pre": ["if (!isWebBrowserHandleLive(handle.value)) return"],
        "post": ["WebSignalCallbackRegistry.releaseSource(handle.value)"],
    },
    38: {"fluent": "self_or_wrap"},
    134: {"fluent": "self"},
    135: {"fluent": "self"},
    41: {"fluent": "self_or_wrap"},
    42: {"fluent": "self_or_wrap"},
    290: {"fluent": "self_or_wrap", "doc": "Custom starting value, COLOR arm (task 64 tier 2); see the Any? overload for the arms that do not exist."},
    # Non-null tree/environment reads: the corpus never handles the null.
    51: {"nonnull": "Node is not inside a SceneTree"},
    81: {"nonnull": "WorldEnvironment has no Environment resource"},
    # SceneTree: the exit code must fit Godot's int32 ABI before any command is emitted; the root
    # window stays a raw handle because Window is a hand-shaped facade (see WEB_HANDSHAPED).
    52: {"param_types": {"exitCode": "Long"}, "guards": ['require(exitCode in Int.MIN_VALUE.toLong()..Int.MAX_VALUE.toLong()) { "SceneTree.quit exit code must fit Godot\'s int32 ABI" }']},
    250: {"raw_handle_return": True, "nonnull": "SceneTree has no root window", "no_property": True, "doc": "Root window as a tracked handle; wrap it with [Window] to reach the mode calls, or use [root] for the Viewport view."},
    168: {"extra_names": ["setPaused"]},
    # AnimationMixer root-motion rotation crosses as euler angles (the applier converts).
    235: {
        "ret": "Quaternion",
        "doc": "Web adaptation: the engine's Quaternion crosses as euler angles and is recomposed here.",
        "body": [
            "return Basis.fromEuler(",
            "    GodotBackendCalls.invokeNoArgsRetVector3(",
            "        D.ANIMATIONMIXER_GET_ROOT_MOTION_ROTATION,",
            "        requireOpenHandle(),",
            "      )",
            "      .toApi()",
            "  )",
            "  .getRotationQuaternion()",
        ],
    },
    # State-machine travel tracks the last target client-side and tolerates a freed playback.
    150: {
        "pre": [
            "lastTravelled = toNode",
            "// Children free before parents during scene teardown: a dying skin's playback handle",
            "// may already be released while its owner still forwards states (Tween.kill precedent).",
            "if (!isWebBrowserHandleLive(handle.value)) return",
        ],
    },
    # AnimationPlayer.seek: the applier passes update=true, not Godot's default.
    182: {"baked": {"update": "true"}},
    # Node3D.look_at_from_position: use_model_front rides the same opcode by mirroring the target.
    108: {
        "doc": "Position the node and orient the forward axis at [target]: -Z by default, +Z when [useModelFront]. Web bakes the up vector to Godot's default; `Basis::looking_at(d, up, true)` equals `looking_at(-d, up, false)`, so the mirrored target is exact.",
        "bind": [
            ("position", "Vector3", None, "position.toBackend()"),
            ("target", "Vector3", None, "engineTarget.toBackend()"),
            ("up", "Vector3", "Vector3.UP", None),
            ("useModelFront", "Boolean", "false", None),
        ],
        "pre": [
            'require(up == Vector3.UP) { "Web look_at_from_position supports only the default up vector Vector3.UP" }',
            "val engineTarget = if (useModelFront) position - (target - position) else target",
        ],
    },
    # ShapeCast3D keeps the Long count/index the ported corpus spells (its loops index with it).
    172: {"ret": "Long"},
    173: {"param_types": {"index": "Long"}},
    174: {"param_types": {"index": "Long"}},
    # RID never crosses the Web seam: the excluded body itself is the argument.
    170: {"bind": [("body", "GodotObject", None, "body.requireOpenHandle()")], "doc": "Web adaptation: exclusion takes the collision OBJECT (the applier derives the RID engine-side)."},
    # Typed ProjectSettings read: the shape fixes Double, so the name says so.
    187: {"name": "getSettingDouble", "doc": "Float-valued setting read (x1000 integer transport; millis precision)."},
    # Camera getter: keep the corpus's `getCamera3D` spelling next to Godot's `getCamera3d`.
    194: {"extra_names": ["getCamera3D"]},
    # Resource.duplicate is open so Material can re-type the copy.
    222: {"open": True},
    # ResourceLoader.load: hand back the typed variants the corpus spells.
    7: {"typed_loads": {"Texture2D": "loadTexture2D", "PackedScene": "loadPackedScene", "AudioStream": "loadAudioStream"}},
}
# Per-class hand-shaped content. `custom` is emitted inside the class body, `companion` inside the
# companion object, `top_level` after the class (import-compat aliases for custom members, private
# helpers). Everything here is Web-specific glue the contract cannot express: compositions over
# several opcodes, Kotlin-side mirrors, and the Variant-style dispatchers over the typed arms.
CLASS_POLICY: dict[str, dict] = {
    "Object": {
        "enums": ["ConnectFlags"],
        "custom": """
  val handle: GodotHandle
    get() = WebObjectId(backendHandle.backendToken().toInt())

  /** Returns true when both wrappers refer to the same Godot object instance. */
  fun isSameInstance(other: GodotObject): Boolean =
    backendHandle.backendToken() == other.backendHandle.backendToken()

  fun signal(name: String): GodotSignal = GodotSignal(this, name)

  /**
   * Variant-style emit over the typed arms the Web backend admits: Web models desktop's variadic
   * `emit_signal` as the typed argument shapes the corpus dispatches.
   */
  fun emitSignal(signal: String, vararg args: Any?) {
    if (args.isEmpty()) return emitSignal(signal)
    when (val value = args.singleOrNull()) {
      is Int -> emitSignal(signal, value)
      is Long -> emitSignal(signal, value.toInt())
      is String -> emitSignal(signal, value)
      is GodotObject -> emitSignal(signal, value)
      is Vector2i -> emitSignal(signal, value)
      else -> unsupportedWebGameplayFamily("GodotObject.emit_signal_typed")
    }
  }
""",
    },
    "Node": {
        "enums": ["ProcessMode"],
        "custom": """
  fun <T : GodotObject> getAsOrNull(path: String, ctor: (GodotHandle) -> T): T? =
    getNodeOrNull(path)?.let { ctor(it.handle) }

  fun <T : GodotObject> getAsOrNull(path: NodePath, ctor: (GodotHandle) -> T): T? =
    getAsOrNull(path.path, ctor)

  fun <T : GodotObject> requireAs(path: String, ctor: (GodotHandle) -> T): T =
    getAsOrNull(path, ctor) ?: error("Required node '$path' was not found")

  fun <T : GodotObject> requireAs(path: NodePath, ctor: (GodotHandle) -> T): T =
    requireAs(path.path, ctor)

  fun hasNode(path: String): Boolean = getNodeOrNull(path) != null

  fun getNode(path: String): Node? = getNodeOrNull(path)

  /** All children as tracked handles, walked over get_child_count + get_child. */
  fun getChildren(includeInternal: Boolean = false): List<Node> {
    require(!includeInternal) { "Web get_children supports only include_internal=false" }
    return (0 until getChildCount()).mapNotNull { getChild(it) }
  }

  /** Web adaptation: the corpus runs the default 60 Hz fixed physics tick. */
  fun getPhysicsProcessDeltaTime(): Double = 1.0 / 60.0

  /** Web no-ops: generated proxies dispatch input only to scripts that declare handlers. */
  fun setProcessInput(@Suppress("UNUSED_PARAMETER") enable: Boolean) = Unit

  fun setProcessUnhandledInput(@Suppress("UNUSED_PARAMETER") enable: Boolean) = Unit
""",
        "top_level": """
@Suppress("EXTENSION_SHADOWED_BY_MEMBER")
fun Node.getChildren(includeInternal: Boolean = false): List<Node> = getChildren(includeInternal)

@Suppress("EXTENSION_SHADOWED_BY_MEMBER")
fun Node.getPhysicsProcessDeltaTime(): Double = getPhysicsProcessDeltaTime()

@Suppress("EXTENSION_SHADOWED_BY_MEMBER")
fun Node.setProcessInput(enable: Boolean) = setProcessInput(enable)

@Suppress("EXTENSION_SHADOWED_BY_MEMBER")
fun Node.setProcessUnhandledInput(enable: Boolean) = setProcessUnhandledInput(enable)
""",
    },
    "CanvasItem": {
        "custom": """
  fun show() {
    visible = true
  }

  fun hide() {
    visible = false
  }
""",
    },
    "Node3D": {
        "custom": """
  fun hide() {
    visible = false
  }

  fun show() {
    visible = true
  }

  /** The node's local rotation+scale basis; writes decompose to the two snapshot families. */
  var basis: Basis
    get() = composeBasis(rotation, scale)
    set(value) {
      rotation = value.getEuler()
      scale = value.getScale()
    }

  /** The node's local transform (basis + origin over the mirrored snapshots). */
  var transform: Transform3D
    get() = Transform3D(basis, position)
    set(value) {
      position = value.origin
      basis = value.basis
    }

  /** The node's world transform; rotation/origin cross synchronously, global scale assumed 1. */
  var globalTransform: Transform3D
    get() = Transform3D(Basis.fromEuler(globalRotation), globalPosition)
    set(value) {
      globalPosition = value.origin
      globalRotation = value.basis.getEuler()
    }

  /** World-space rotation basis over the synchronous global-rotation reads (scale-1 rigs). */
  var globalBasis: Basis
    get() = Basis.fromEuler(globalRotation)
    set(value) {
      globalRotation = value.getEuler()
    }

  /** Orient the forward axis at [target] from the current position (rides look_at_from_position). */
  fun lookAt(target: Vector3, up: Vector3 = Vector3.UP, useModelFront: Boolean = false) {
    lookAtFromPosition(globalPosition, target, up, useModelFront)
  }

  /** Godot's rotate_object_local: right-multiply the local basis by an axis-angle rotation. */
  fun rotateObjectLocal(axis: Vector3, angle: Double) {
    basis = basis * Basis.fromAxisAngle(axis, angle)
  }

  /** Godot's Node3D.orthonormalize: re-orthonormalize the local basis in place. */
  fun orthonormalize() {
    basis = basis.orthonormalized()
  }
""",
        "top_level": """
private fun composeBasis(rotation: Vector3, scale: Vector3): Basis {
  val rotationBasis = Basis.fromEuler(rotation)
  // Node basis = R * S: columns scaled (Godot composes scale on the right of rotation).
  return Basis(
    rotationBasis.getColumn(0) * scale.x,
    rotationBasis.getColumn(1) * scale.y,
    rotationBasis.getColumn(2) * scale.z,
  )
}

@Suppress("EXTENSION_SHADOWED_BY_MEMBER") fun Node3D.hide() = hide()

@Suppress("EXTENSION_SHADOWED_BY_MEMBER") fun Node3D.show() = show()

@Suppress("EXTENSION_SHADOWED_BY_MEMBER")
var Node3D.basis: Basis
  get() = basis
  set(value) {
    basis = value
  }

@Suppress("EXTENSION_SHADOWED_BY_MEMBER")
var Node3D.transform: Transform3D
  get() = transform
  set(value) {
    transform = value
  }

@Suppress("EXTENSION_SHADOWED_BY_MEMBER")
var Node3D.globalTransform: Transform3D
  get() = globalTransform
  set(value) {
    globalTransform = value
  }

@Suppress("EXTENSION_SHADOWED_BY_MEMBER")
var Node3D.globalBasis: Basis
  get() = globalBasis
  set(value) {
    globalBasis = value
  }

@Suppress("EXTENSION_SHADOWED_BY_MEMBER")
fun Node3D.lookAt(target: Vector3, up: Vector3 = Vector3.UP, useModelFront: Boolean = false) =
  lookAt(target, up, useModelFront)

@Suppress("EXTENSION_SHADOWED_BY_MEMBER")
fun Node3D.rotateObjectLocal(axis: Vector3, angle: Double) = rotateObjectLocal(axis, angle)

@Suppress("EXTENSION_SHADOWED_BY_MEMBER") fun Node3D.orthonormalize() = orthonormalize()
""",
    },
    "Sprite2D": {"instantiable": True},
    "Resource": {"from_handle": True, "from_object": True},
    "Texture2D": {"release": "resource", "guard": True},
    "AudioStream": {"release": "resource"},
    "PackedScene": {"release": "resource"},
    "Tween": {
        "enums": ["TransitionType", "EaseType"],
        "signals": ["finished"],
        "custom": """
  /**
   * Variant-style final value over the typed arms; a component path such as `"position:y"` takes a
   * number, and Int/Long are accepted so a caller writing `0` for a float property need not care.
   */
  fun tweenProperty(
    target: GodotObject,
    property: String,
    finalValue: Any?,
    duration: Double,
  ): PropertyTweener? =
    when (finalValue) {
      is Vector2 -> tweenProperty(target, property, finalValue, duration)
      is Color -> tweenProperty(target, property, finalValue, duration)
      is Vector3 -> tweenProperty(target, property, finalValue, duration)
      is Double -> tweenProperty(target, property, finalValue, duration)
      is Float -> tweenProperty(target, property, finalValue.toDouble(), duration)
      is Int -> tweenProperty(target, property, finalValue.toDouble(), duration)
      is Long -> tweenProperty(target, property, finalValue.toDouble(), duration)
      else ->
        unsupportedWebGameplayCall(
          "Tween.tween_property final value ${finalValue?.let { it::class.simpleName } ?: "null"}"
        )
    }
""",
    },
    "PropertyTweener": {
        "custom": """
  /** Variant-style starting value: Color is the one arm the Web backend has (Icone's fade). */
  fun from(value: Any?): PropertyTweener =
    when (value) {
      is Color -> from(value)
      else ->
        unsupportedWebGameplayCall(
          "PropertyTweener.from value ${value?.let { it::class.simpleName } ?: "null"} " +
            "(the Web backend has the Color arm only)"
        )
    }
""",
    },
    "SceneTree": {
        "imports": [
            "kotlin.coroutines.resume",
            "kotlinx.coroutines.Job",
            "kotlinx.coroutines.suspendCancellableCoroutine",
        ],
        "custom": """
  /** The root window as its Viewport face (the tps corpus's `getTree().root`). */
  val root: Viewport
    get() = Viewport(getRoot())

  /** Instance form of [Companion.delaySeconds] for `getTree().delaySeconds(...)` call sites. */
  suspend fun delaySeconds(seconds: Double) = SceneTree.delaySeconds(seconds)
""",
        "companion": """
    suspend fun delaySeconds(seconds: Double) {
      require(seconds.isFinite() && seconds >= 0.0) {
        "SceneTree.delaySeconds requires a finite, non-negative duration"
      }
      suspendCancellableCoroutine { continuation ->
        val taskId =
          WebFrameScheduler.scheduleDelay(seconds, continuation.context[Job]) {
            if (continuation.isActive) continuation.resume(Unit)
          }
        continuation.invokeOnCancellation { WebFrameScheduler.cancelTask(taskId) }
      }
    }
""",
        "top_level": """
@Suppress("EXTENSION_SHADOWED_BY_MEMBER")
val SceneTree.root: Viewport
  get() = root
""",
    },
    "AudioStreamPlayer": {
        "instantiable": True,
        "signals": ["finished"],
        "custom": """
  /** Load-assign-release: the engine takes its reference before the temporary handle is dropped. */
  fun setStreamFromPath(path: String) {
    val stream = ResourceLoader.loadAudioStream(path) ?: return
    try {
      setStream(stream)
    } finally {
      stream.close()
    }
  }
""",
    },
    "AudioStreamPlayer3D": {"signals": ["finished"]},
    "Timer": {"signals": ["timeout"]},
    "Area3D": {"signals": ["body_entered", "body_exited"]},
    "BaseButton": {"signals": ["pressed"]},
    "AnimationMixer": {
        "signals": ["animation_finished"],
        "custom": """
  /** Resolve the playback object behind a `parameters/.../playback` property. */
  fun getStateMachinePlayback(path: String): AnimationNodeStateMachinePlayback =
    getObjectProperty(path)?.let { AnimationNodeStateMachinePlayback(it.handle) }
      ?: error("AnimationMixer parameter '$path' is not an AnimationNodeStateMachinePlayback")

  /** Double-valued blend parameter write (the run tilt add_amount). */
  fun setParameter(path: String, value: Double) {
    set(path, value)
  }

  /** Long parameters (one-shot requests) ride the double family; Godot coerces Variants. */
  fun setParameter(path: String, value: Long) {
    set(path, value.toDouble())
  }
""",
        "top_level": """
@Suppress("EXTENSION_SHADOWED_BY_MEMBER")
fun AnimationMixer.getStateMachinePlayback(path: String): AnimationNodeStateMachinePlayback =
  getStateMachinePlayback(path)

@Suppress("EXTENSION_SHADOWED_BY_MEMBER")
fun AnimationMixer.setParameter(path: String, value: Double) = setParameter(path, value)

@Suppress("EXTENSION_SHADOWED_BY_MEMBER")
fun AnimationMixer.setParameter(path: String, value: Long) = setParameter(path, value)
""",
    },
    "AnimationNodeStateMachinePlayback": {
        "custom": """
  private var lastTravelled: String = ""

  /**
   * Web adaptation: the last travelled state, tracked client-side (the engine node may still be
   * mid-transition; the corpus only compares against its own travel targets).
   */
  fun getCurrentNode(): String = lastTravelled
""",
    },
    "AnimationPlayer": {
        "custom": """
  /**
   * The name of the currently playing animation (empty when nothing plays). No typed opcode
   * carries this string read, so it rides the task-76 generic `callv` tier.
   */
  fun getCurrentAnimation(): String {
    genericWebGameplayFallback("AnimationPlayer.get_current_animation")
    return webGenericImmediateStringCall(this, "get_current_animation")
  }
""",
    },
    "@GlobalScope": {
        "custom": """
  fun randiRange(from: Long, to: Long): Long {
    require(from <= to)
    val range = to - from + 1
    return from + (randi().toULong() % range.toULong()).toLong()
  }

  /** Normally-distributed random (Box-Muller over the engine-seeded randf). */
  fun randfn(mean: Double, deviation: Double): Double {
    val u1 = randf().coerceAtLeast(1e-12)
    val u2 = randf()
    val gaussian =
      kotlin.math.sqrt(-2.0 * kotlin.math.ln(u1)) * kotlin.math.cos(2.0 * kotlin.math.PI * u2)
    return mean + deviation * gaussian
  }

  /** Web adaptation: liveness of the tracked script/browser handle. */
  fun isInstanceValid(instance: GodotObject?): Boolean {
    if (instance == null) return false
    val handle = instance.handle.value
    return webScriptInstance(handle) != null || isWebBrowserHandleLive(handle)
  }

  fun randfRange(from: Double, to: Double): Double {
    require(from <= to)
    return from + (to - from) * randf()
  }

  fun lerpf(from: Double, to: Double, weight: Double): Double = Mathf.lerp(from, to, weight)

  fun signf(value: Double): Double = if (value > 0.0) 1.0 else if (value < 0.0) -1.0 else 0.0

  /** Godot's remap: linear map of [value] from [istart, istop] onto [ostart, ostop]. */
  fun remap(value: Double, istart: Double, istop: Double, ostart: Double, ostop: Double): Double =
    ostart + (ostop - ostart) * ((value - istart) / (istop - istart))

  fun clampf(value: Double, min: Double, max: Double): Double = Mathf.clamp(value, min, max)

  fun lerpAngle(from: Double, to: Double, weight: Double): Double =
    Mathf.lerpAngle(from, to, weight)

  fun degToRad(degrees: Double): Double = degrees * kotlin.math.PI / 180.0

  fun radToDeg(radians: Double): Double = radians * 180.0 / kotlin.math.PI

  /** Web adaptation: Godot's print lands on the browser console via Wasm stdout. */
  fun print(message: Any?) {
    println(message)
  }

  fun pushError(message: Any?) {
    println("ERROR: $message")
  }
""",
        "imports": ["net.multigesture.kanama.web.webScriptInstance"],
        "top_level": """
@Suppress("EXTENSION_SHADOWED_BY_MEMBER") fun GD.radToDeg(radians: Double): Double = radToDeg(radians)

@Suppress("EXTENSION_SHADOWED_BY_MEMBER") fun GD.pushError(message: Any?) = pushError(message)
""",
    },
    "Input": {
        "enums": ["MouseMode"],
        "custom": """
  /**
   * Composed from two get_axis reads (deadzone-normalized identically for digital keys, the only
   * inputs the Web demos drive), clamped to unit length like Godot's get_vector.
   */
  fun getVector(
    negativeX: String,
    positiveX: String,
    negativeY: String,
    positiveY: String,
    deadzone: Double = -1.0,
  ): Vector2 {
    val vector = Vector2(getAxis(negativeX, positiveX), getAxis(negativeY, positiveY))
    val length = vector.length()
    if (deadzone >= 0.0) {
      // Godot's deadzone remap: inside the deadzone reads zero, outside rescales to [0, 1].
      if (length <= deadzone) return Vector2.ZERO
      if (length > 1.0) return vector / length
      return vector * ((length - deadzone) / (1.0 - deadzone) / length)
    }
    return if (length > 1.0) vector / length else vector
  }
""",
    },
    "InputEventKey": {
        "instantiable": True,
        "release": "constructed",
        "from_class_check": True,
        "enums": ["@GlobalScope.Key"],
    },
    "InputEventMouseButton": {"from_class_check": True, "enums": ["@GlobalScope.MouseButton"]},
    "InputEventMouseMotion": {"from_class_check": True},
    "Mesh": {"from_object_checked": True},
    "Material": {
        "from_resource": True,
        "release": "tracked",
        "custom": """
  /** Duplicate this material; the copy is owned (close it, or release it at teardown). */
  override fun duplicate(deep: Boolean): Material? = super.duplicate(deep)?.let { Material(it.handle) }
""",
    },
    "ShaderMaterial": {"from_resource": True},
    "LightmapGI": {"instantiable": True},
    "ButtonGroup": {"instantiable": True, "release": "constructed"},
    "ConfigFile": {"instantiable": True, "release": "constructed"},
    "FastNoiseLite": {"instantiable": True, "release": "constructed"},
    "MeshLibrary": {"instantiable": True, "release": "constructed"},
    "KinematicCollision3D": {"release": "collision", "guard": True},
    "Light3D": {
        "enums": ["Param"],
        "custom": """
  /** Write-only on Web: light_energy is Light3D.set_param(PARAM_ENERGY, value). */
  var lightEnergy: Double
    get() = unsupportedWebGameplayFamily("Light3D.get_light_energy")
    set(value) = setParam(PARAM_ENERGY, value)

  /** Write-only on Web: shadow_opacity is Light3D.set_param(PARAM_SHADOW_OPACITY, value). */
  var shadowOpacity: Double
    get() = unsupportedWebGameplayFamily("Light3D.get_shadow_opacity")
    set(value) = setParam(PARAM_SHADOW_OPACITY, value)
""",
    },
    "DirectionalLight3D": {"enums": ["SkyMode"]},
    "Animation": {"enums": ["LoopMode"]},
    "GridMap": {"constants": ["INVALID_CELL_ITEM"]},
    "ResourceLoader": {"enums": ["CacheMode"]},
    "RenderingServer": {"enums": ["ShadowQuality"]},
    "Viewport": {"enums": ["Scaling3DMode", "MSAA", "ScreenSpaceAA"]},
    "PhysicsBody3D": {"enums": ["PhysicsServer3D.BodyAxis"]},
    "OS": {
        "custom": """
  /** Web ships the release template; debug-gated tooling stays off. */
  fun isDebugBuild(): Boolean = false
""",
    },
    "ClassDB": {"visibility": "internal"},
}

SUPPORT_FILE = '''@file:OptIn(InternalKanamaBackendApi::class)

package net.multigesture.kanama.api

import net.multigesture.kanama.backend.GodotBasis
import net.multigesture.kanama.backend.GodotColor
import net.multigesture.kanama.backend.GodotHandle as BackendGodotHandle
import net.multigesture.kanama.backend.GodotRect2
import net.multigesture.kanama.backend.GodotTransform3D
import net.multigesture.kanama.backend.GodotVector2
import net.multigesture.kanama.backend.GodotVector2i
import net.multigesture.kanama.backend.GodotVector3
import net.multigesture.kanama.backend.GodotVector3i
import net.multigesture.kanama.backend.InternalKanamaBackendApi
import net.multigesture.kanama.types.Basis
import net.multigesture.kanama.types.Color
import net.multigesture.kanama.types.Rect2
import net.multigesture.kanama.types.Transform3D
import net.multigesture.kanama.types.Vector2
import net.multigesture.kanama.types.Vector2i
import net.multigesture.kanama.types.Vector3
import net.multigesture.kanama.types.Vector3i
import net.multigesture.kanama.web.WebObjectId

// Conversions between the public value types and the contract's value types; every generated
// member goes through these, so the float/double policy lives in exactly one place.

internal fun GodotHandle.toBackendHandle(): BackendGodotHandle =
  BackendGodotHandle.fromBackendToken(value.toLong())

internal fun BackendGodotHandle.toWebId(): WebObjectId = WebObjectId(backendToken().toInt())

internal fun Vector2.toBackend(): GodotVector2 = GodotVector2(x.toFloat(), y.toFloat())

internal fun GodotVector2.toApi(): Vector2 = Vector2(x.toDouble(), y.toDouble())

internal fun Vector3.toBackend(): GodotVector3 =
  GodotVector3(x.toFloat(), y.toFloat(), z.toFloat())

internal fun GodotVector3.toApi(): Vector3 = Vector3(x.toDouble(), y.toDouble(), z.toDouble())

internal fun Vector2i.toBackend(): GodotVector2i = GodotVector2i(x, y)

internal fun GodotVector2i.toApi(): Vector2i = Vector2i(x, y)

internal fun Vector3i.toBackend(): GodotVector3i = GodotVector3i(x, y, z)

internal fun GodotVector3i.toApi(): Vector3i = Vector3i(x, y, z)

internal fun Color.toBackend(): GodotColor = GodotColor(r, g, b, a)

internal fun GodotColor.toApi(): Color = Color(r, g, b, a)

internal fun GodotRect2.toApi(): Rect2 = Rect2(position.toApi(), size.toApi())

internal fun Basis.toBackend(): GodotBasis =
  GodotBasis(x.toBackend(), y.toBackend(), z.toBackend())

internal fun Transform3D.toBackend(): GodotTransform3D =
  GodotTransform3D(basis.toBackend(), origin.toBackend())
'''
# Leaf and intermediate Godot classes the corpus types against that own no opcode themselves.
EXTRA_CLASSES: tuple[str, ...] = (
    "AnimationTree", "Area2D", "AudioStream", "BoneAttachment3D", "ButtonGroup", "ColorRect",
    "LightmapGIData", "Marker2D", "Marker3D", "MultiMeshInstance3D", "OmniLight3D", "ProgressBar",
    "SpinBox", "SpotLight3D", "StaticBody3D", "Texture2D", "TextureButton",
)
# Bespoke facades that stay hand-written under api/ (name -> why the generator cannot emit it).
WEB_HANDSHAPED: dict[str, str] = {
    "Window": "handle-less browser-window mirror shared with the handle-backed root window (tps settings menu)",
    "PhysicsDirectSpaceState3D": "owner-bound facade; the ray query packs a Dictionary result into one string",
}
# Opcodes a hand-written facade in WEB_HANDSHAPED may dispatch directly.
HANDSHAPED_OPCODES: frozenset[str] = frozenset(
    {"WINDOW_SET_MODE", "WINDOW_GET_MODE", "PHYSICSDIRECTSPACESTATE3D_INTERSECT_RAY"}
)

PACKAGE_IMPORTS = {
    "GodotBackendCalls": "net.multigesture.kanama.backend.GodotBackendCalls",
    "D.": "net.multigesture.kanama.backend.InitialGodotCallDescriptors as D",
    "BackendGodotHandle": "net.multigesture.kanama.backend.GodotHandle as BackendGodotHandle",
    "WebObjectId": "net.multigesture.kanama.web.WebObjectId",
    "Vector2": "net.multigesture.kanama.types.Vector2",
    "Vector3": "net.multigesture.kanama.types.Vector3",
    "Vector2i": "net.multigesture.kanama.types.Vector2i",
    "Vector3i": "net.multigesture.kanama.types.Vector3i",
    "Color": "net.multigesture.kanama.types.Color",
    "Rect2": "net.multigesture.kanama.types.Rect2",
    "Basis": "net.multigesture.kanama.types.Basis",
    "Transform3D": "net.multigesture.kanama.types.Transform3D",
    "Quaternion": "net.multigesture.kanama.types.Quaternion",
    "NodePath": "net.multigesture.kanama.types.NodePath",
}


def build_tree(api: Api) -> Tree:
    classes: set[str] = set()
    for call in INITIAL_BACKEND_CALLS:
        if call.class_name != "@GlobalScope":
            classes.update(api.chain(call.class_name))
    for extra in EXTRA_CLASSES:
        classes.update(api.chain(extra))
    classes -= set(WEB_HANDSHAPED)
    return Tree(api, classes)


def imports_for(body: str, extra: list[str]) -> list[str]:
    imports = set(extra)
    for token, statement in PACKAGE_IMPORTS.items():
        if re.search(r"(?<![A-Za-z0-9_.])" + re.escape(token), body):
            imports.add(statement)
    return sorted(imports)


def file_text(body_lines: list[str], extra_imports: list[str]) -> str:
    body = "\n".join(body_lines)
    imports = imports_for(body, extra_imports)
    parts = [HEADER.rstrip("\n"), "@file:OptIn(InternalKanamaBackendApi::class)", "", "package net.multigesture.kanama.api", ""]
    parts += [f"import {i}" for i in imports]
    parts.append("import net.multigesture.kanama.backend.InternalKanamaBackendApi")
    parts += ["", body, ""]
    return "\n".join(parts)


def emit_properties(tree: Tree, godot_name: str, calls: list[BackendCallPolicy]) -> list[Member]:
    """Kotlin properties for every API property whose getter or setter is an admitted opcode.

    Both accessors admitted -> `var`; setter only -> write-only `var` whose getter names the
    missing engine getter through the coverage marker; getter only -> `val`. Accessors delegate to
    the generated methods, so conversions live in one place.
    """
    api = tree.api
    if godot_name not in api.classes:
        return []  # @GlobalScope utilities have no property table
    owner = kotlin_class_name(godot_name)
    by_method = {call.method_name: call for call in calls if not WRAPPER_POLICY.get(call.opcode, {}).get("no_property")}
    props: dict[str, dict] = {}
    for call in calls:
        prop = api.property_for(godot_name, call.method_name)
        if prop is not None and not WRAPPER_POLICY.get(call.opcode, {}).get("no_property"):
            props.setdefault(prop["name"], prop)
    members: list[Member] = []
    for prop_name, prop in props.items():
        getter = by_method.get(prop.get("getter", ""))
        setter = by_method.get(prop.get("setter", ""))
        kotlin_name = camel(prop_name)
        if getter is not None:
            getter_method = api.method(getter)
            kotlin_type, _ = api_return(
                tree,
                getter_method.get("return_value", {}).get("type", "void"),
                getter_method.get("return_value", {}).get("meta", ""),
                SIGNATURES[getter.shape][1],
            )
            if WRAPPER_POLICY.get(getter.opcode, {}).get("nonnull"):
                kotlin_type = kotlin_type.rstrip("?")
            get_expr = f"{member_name(getter, WRAPPER_POLICY.get(getter.opcode, {}))}()"
        else:
            setter_method = api.method(setter)
            arg = setter_method["arguments"][0]
            kotlin_type = api_param_type(tree, arg["type"], arg.get("meta", ""), spi_slots(setter.shape)[1][0][1])
            get_expr = f'unsupportedWebGameplayFamily("{godot_name}.{prop.get("getter", "get_" + prop_name)}")'
        body = [f"  {'var' if setter else 'val'} {kotlin_name}: {kotlin_type}", f"    get() = {get_expr}"]
        alias = ['@Suppress("EXTENSION_SHADOWED_BY_MEMBER")', f"{'var' if setter else 'val'} {owner}.{kotlin_name}: {kotlin_type}", f"  get() = {kotlin_name}"]
        if setter is not None:
            set_name = member_name(setter, WRAPPER_POLICY.get(setter.opcode, {}))
            body.append(f"    set(newValue) = {set_name}(newValue)")
            alias += ["  set(newValue) {", f"    {kotlin_name} = newValue", "  }"]
        members.append(Member(body, alias, kotlin_name))
    return members


def emit_constants(api: Api, godot_name: str, class_policy: dict) -> list[str]:
    """`const val` lines: whole enums (`enums`), single class constants, from extension_api.json."""
    lines: list[str] = []
    for spec in class_policy.get("enums", ()):
        owner, enum = spec.split(".") if "." in spec else (godot_name, spec)
        for const_name, value in api.enum_values(owner, enum).items():
            lines.append(f"    const val {const_name}: Long = {value}L")
    for const_name in class_policy.get("constants", ()):
        lines.append(f"    const val {const_name}: Long = {api.constant(godot_name, const_name)}L")
    return lines


def emit_signals(api: Api, godot_name: str, class_policy: dict) -> list[str]:
    names = class_policy.get("signals", ())
    if not names:
        return []
    lines = ["  object Signals {"]
    for signal in names:
        if not api.has_signal(godot_name, signal):
            raise GenerationError(f"{godot_name} has no signal {signal}")
        lines.append(f'    const val {camel(signal)}: String = "{signal}"')
    lines.append("  }")
    return lines


def emit_companion(godot_name: str, class_policy: dict, constants: list[str]) -> list[str]:
    """Companion: factories (`instantiable`, `from_*`), constants, and the policy's own text."""
    name = kotlin_class_name(godot_name)
    lines: list[str] = []
    if class_policy.get("instantiable"):
        lines += [
            f"    /** Constructs a new {godot_name} engine-side; the wrapper owns the handle (close what you create). */",
            f"    fun create(): {name} =",
            f'      {name}(checkNotNull(ClassDB.instantiate("{godot_name}")) {{ "Godot could not instantiate {godot_name}" }}.toWebId())',
        ]
    if class_policy.get("from_class_check"):
        lines += [
            f"    /** Engine-side class check: null when [value] is not a {godot_name}. */",
            f"    fun from(value: GodotObject): {name}? =",
            f'      value.takeIf {{ it.isClass("{godot_name}") }}?.let {{ {name}(it.handle) }}',
        ]
    if class_policy.get("from_object"):
        lines += [
            f"    /** Re-types any Godot object as a {godot_name} (the Web bridge carries no class metadata). */",
            f"    fun fromObject(value: GodotObject?): {name}? = value?.let {{ {name}(it.handle) }}",
        ]
    if class_policy.get("from_object_checked"):
        lines += [
            f"    fun fromObject(value: GodotObject?): {name}? =",
            f'      value?.takeIf {{ it.isClass("{godot_name}") }}?.let {{ {name}(it.handle) }}',
        ]
    if class_policy.get("from_resource"):
        lines += [f"    fun fromResource(resource: Resource?): {name}? = resource?.let {{ {name}(it.handle) }}"]
    if class_policy.get("from_handle"):
        lines += [f"    fun fromHandle(handle: GodotHandle): {name} = {name}(handle)"]
    if constants:
        if lines:
            lines.append("")
        lines += constants
    if class_policy.get("companion"):
        if lines:
            lines.append("")
        lines += class_policy["companion"].strip("\n").split("\n")
    if not lines:
        return []
    return ["  companion object {", *lines, "  }"]


RELEASE_CALLS = {
    "resource": "releaseWebResource",
    "constructed": "releaseWebConstructedObject",
    "tracked": "releaseWebTrackedObject",
    "collision": "releaseWebCollision",
}


def emit_release(godot_name: str, class_policy: dict) -> list[str]:
    """`close()` for owning wrappers; `guard` adds the closed flag + receiver guard (use-after-close)."""
    kind = class_policy.get("release")
    if not kind:
        return []
    name = kotlin_class_name(godot_name)
    release = RELEASE_CALLS[kind]
    if class_policy.get("guard"):
        return [
            "  private var closed = false",
            "",
            "  override fun requireOpenHandle(): BackendGodotHandle {",
            f'    check(!closed) {{ "{name} is closed" }}',
            "    return backendHandle",
            "  }",
            "",
            "  /** Releases the owned handle; a second close is a no-op, any later call fails loud. */",
            "  fun close() {",
            "    if (closed) return",
            "    closed = true",
            f"    {release}(handle.value)",
            "  }",
        ]
    return [
        "  /** Releases the owned handle (already-released is an error). */",
        "  fun close() {",
        f"    {release}(handle.value)",
        "  }",
    ]


def render_class(tree: Tree, godot_name: str, calls: list[BackendCallPolicy]) -> str:
    api = tree.api
    name = kotlin_class_name(godot_name)
    class_policy = CLASS_POLICY.get(godot_name, {})
    singleton = godot_name in api.singletons or godot_name == "@GlobalScope"
    members: list[Member] = []
    for call in calls:
        policy = WRAPPER_POLICY.get(call.opcode, {})
        primary = emit_opcode(tree, call, policy)
        members.append(primary)
        members += emit_extras(tree, call, policy, primary)
    members += emit_properties(tree, godot_name, calls)
    lines: list[str] = []
    if singleton:
        object_name = "GD" if godot_name == "@GlobalScope" else name
        visibility = class_policy.get("visibility", "")
        lines.append(f"{visibility + ' ' if visibility else ''}object {object_name} {{")
    else:
        parent = api.parent(godot_name)
        while parent is not None and parent not in tree.classes and parent != "Object":
            parent = api.parent(parent)
        has_children = any(api.parent(c) == godot_name for c in tree.classes)
        open_ = "open " if has_children or class_policy.get("open") else ""
        if godot_name == "Object":
            lines.append(f"{open_}class GodotObject(godotObject: GodotHandle) {{")
            lines.append("  internal val backendHandle: BackendGodotHandle = godotObject.toBackendHandle()")
            lines.append("")
            lines.append("  /** Backend-handle form for the generated proxies and the wrappers' own returns. */")
            lines.append("  internal constructor(backendHandle: BackendGodotHandle) : this(backendHandle.toWebId())")
            lines.append("")
            lines.append("  /** The live backend handle; guarded wrappers (closeable resources) override this. */")
            lines.append("  internal open fun requireOpenHandle(): BackendGodotHandle = backendHandle")
        else:
            lines.append(f"{open_}class {name}(godotObject: GodotHandle) : {kotlin_class_name(parent)}(godotObject) {{")
            lines.append("  internal constructor(backendHandle: BackendGodotHandle) : this(backendHandle.toWebId())")
    sections: list[list[str]] = [m.body for m in members]
    if class_policy.get("custom"):
        sections.append(class_policy["custom"].strip("\n").split("\n"))
    sections.append(emit_release(godot_name, class_policy))
    sections.append(emit_signals(api, godot_name, class_policy))
    constants = emit_constants(api, godot_name, class_policy)
    if singleton:
        # An `object` has no companion: constants and factories sit directly in its body.
        sections.append([line[2:] for line in constants])
        if class_policy.get("companion"):
            sections.append(class_policy["companion"].strip("\n").split("\n"))
    else:
        sections.append(emit_companion(godot_name, class_policy, constants))
    first = True
    for section in sections:
        if not section:
            continue
        if not first or godot_name == "Object":
            lines.append("")
        first = False
        lines += section
    lines.append("}")
    for member in members:
        if member.alias:
            lines.append("")
            lines += member.alias
    if class_policy.get("top_level"):
        lines.append("")
        lines += class_policy["top_level"].strip("\n").split("\n")
    return file_text(lines, list(class_policy.get("imports", ())))


def render_all(api: Api) -> dict[str, str]:
    """Render every generated file: file name -> content."""
    tree = build_tree(api)
    by_class: dict[str, list[BackendCallPolicy]] = {c: [] for c in tree.classes}
    by_class["@GlobalScope"] = []
    for call in INITIAL_BACKEND_CALLS:
        if call.class_name in WEB_HANDSHAPED:
            if descriptor_name(call) not in HANDSHAPED_OPCODES:
                raise GenerationError(f"opcode {call.opcode} belongs to hand-shaped {call.class_name} but is not allowlisted")
            continue
        by_class[call.class_name].append(call)
    files: dict[str, str] = {"WebWrapperSupport.kt": HEADER + SUPPORT_FILE}
    for godot_name, calls in by_class.items():
        file_name = ("GD" if godot_name == "@GlobalScope" else kotlin_class_name(godot_name)) + ".kt"
        files[file_name] = render_class(tree, godot_name, sorted(calls, key=lambda c: c.opcode))
    return files


# --------------------------------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------------------------------


_DESCRIPTOR_REF = re.compile(r"\b(?:D|InitialGodotCallDescriptors)\.([A-Z][A-Z0-9_]+)\b")
_DECLARATION = re.compile(r"^(?:open |abstract |internal |private )*(?:class|object) ([A-Z][A-Za-z0-9]*)", re.M)


def check_hand_written(api_dir: Path, rendered: dict[str, str]) -> list[str]:
    """The exit-gate half of --check: no hand-written member dispatches an opcode the tree owns.

    Hand-written files under api/ (everything outside generated/) may reference a descriptor only
    for the WEB_HANDSHAPED facades' allowlisted opcodes, may not redeclare a generated class, and
    every WEB_HANDSHAPED name must still exist somewhere hand-written (rot check).
    """
    failures: list[str] = []
    generated_names = {
        m.group(1) for text in rendered.values() for m in _DECLARATION.finditer(text)
    }
    declared: set[str] = set()
    for path in sorted(api_dir.glob("*.kt")):
        text = path.read_text()
        for match in _DESCRIPTOR_REF.finditer(text):
            if match.group(1) not in HANDSHAPED_OPCODES:
                failures.append(
                    f"{path.name} dispatches {match.group(1)} by hand; the generated tree owns it "
                    "(add the member through scripts/generate_web_wrappers.py or allowlist a WEB_HANDSHAPED facade)"
                )
        for match in _DECLARATION.finditer(text):
            declared.add(match.group(1))
            if match.group(1) in generated_names:
                failures.append(f"{path.name} redeclares generated class {match.group(1)}")
    for name in sorted(WEB_HANDSHAPED):
        if name not in declared:
            failures.append(f"WEB_HANDSHAPED names {name} but no hand-written file under api/ declares it")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=GENERATED_DIR)
    parser.add_argument("--check", action="store_true", help="fail if the committed tree drifts")
    args = parser.parse_args()

    api = Api()
    rendered = render_all(api)
    out_dir: Path = args.output_dir

    if args.check:
        failures: list[str] = []
        committed = {p.name: p for p in out_dir.glob("*.kt")} if out_dir.is_dir() else {}
        for name, text in rendered.items():
            path = committed.pop(name, None)
            if path is None:
                failures.append(f"missing generated file {name}")
            elif path.read_text() != text:
                failures.append(f"drift in {name}")
        for name in sorted(committed):
            failures.append(f"stray file in generated tree: {name}")
        failures += check_hand_written(out_dir.parent, rendered)
        if failures:
            for failure in failures:
                print(f"{TAG} FAIL {failure}", file=sys.stderr)
            print(f"{TAG} run scripts/generate_web_wrappers.py to regenerate", file=sys.stderr)
            return 1
        print(f"{TAG} PASS {len(rendered)} generated files match the contract")
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    for stale in out_dir.glob("*.kt"):
        if stale.name not in rendered:
            stale.unlink()
    for name, text in rendered.items():
        (out_dir / name).write_text(text)
    print(f"{TAG} wrote {len(rendered)} files to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
