#!/usr/bin/env python3
"""Generate the virtual-method signature table consumed by the KSP processor.

Reads ``extension_api.json`` and emits a compact TSV resource describing, per
class, every ``is_virtual`` method's argument and return types (Godot type
strings) plus a class -> parent inheritance map. The processor
(`VirtualSignatureTable`) loads this to resolve and validate ``@OverrideVirtual``
declarations against a script's attach-to class hierarchy.

A TSV resource (not a Kotlin map literal) avoids both the JVM 64KB method-size
limit on huge initializers and a JSON dependency the processor deliberately
does not carry.

Format (tab-separated, one record per line):
  I<TAB>Class<TAB>Parent                       # inheritance edge
  V<TAB>Class<TAB>_virtual<TAB>argTypesCsv<TAB>returnTypeOrEmpty[<TAB>required]

The optional sixth field (schema 2, task 128 B) is `required` when Godot marks the return
`meta: "required"` (the two `_get_space_state` object returns): the processor then refuses a
nullable Kotlin return for that override. `enum::X` / `bitfield::X` types are kept verbatim; the
processor maps them to the typed value classes through `godot-enums.tsv`.

Output: processor/src/main/resources/net/multigesture/kanama/processor/virtual-signatures.tsv
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_API = ROOT / "extension_api.json"
OUT = (
    ROOT
    / "processor/src/main/resources/net/multigesture/kanama/processor/virtual-signatures.tsv"
)


def render(api_path: pathlib.Path) -> str:
    api = json.loads(api_path.read_text())
    header = api["header"]
    lines = [
        f"# virtual-signatures table — generated by scripts/{pathlib.Path(__file__).name}",
        f"# source: {header['version_full_name']}",
        "# schemaVersion=2",
    ]
    inherits = []
    virtuals = []
    vcount = 0
    for c in api["classes"]:
        name = c["name"]
        parent = c.get("inherits", "")
        if parent:
            inherits.append(f"I\t{name}\t{parent}")
        for m in c.get("methods", []):
            if not m.get("is_virtual"):
                continue
            return_value = m.get("return_value", {})
            ret = return_value.get("type", "") or ""
            arg_types = ",".join(a["type"] for a in m.get("arguments", []))
            row = f"V\t{name}\t{m['name']}\t{arg_types}\t{ret}"
            if return_value.get("meta") == "required":
                row += "\trequired"
            virtuals.append(row)
            vcount += 1
    lines += sorted(inherits)
    lines += sorted(virtuals)
    lines.append(f"# counts: inherits={len(inherits)} virtuals={vcount}")
    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv
    args = [a for a in sys.argv[1:] if a != "--check"]
    api_path = pathlib.Path(args[0]) if args else DEFAULT_API
    rendered = render(api_path)
    if check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != rendered:
            print("[virtual_signature_table] STALE — re-run scripts/generate_virtual_signature_table.py")
            return 1
        print("[virtual_signature_table] up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered)
    nv = rendered.count("\nV\t")
    print(f"[virtual_signature_table] wrote {OUT.relative_to(ROOT)} : {nv} virtuals")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
