#!/usr/bin/env python3
"""Generate (and with `--check`, drift-gate) the engine method-name table the KSP processor reads.

Every public function of a Kanama script class is registered with Godot under its snake_case
name (task 133 B). One that lands on a method the attached class already has -- `fun queueFree()`
is `queue_free`, `fun getName()` is `get_name` -- would shadow the engine's method for every
`call()`, `Callable` and saved scene connection on that node, so the processor refuses it unless
the name is confirmed with `@GodotName("...")`. It needs each class's own (non-virtual) method
names and the class -> parent map; this script derives both from ``extension_api.json``.

Virtual methods (`_ready`, `_draw`, ...) are not listed: the processor checks those against
`virtual-signatures.tsv` (scripts/generate_virtual_signature_table.py).

A TSV resource (not a Kotlin map literal) for the same reasons as the virtual table: no JVM
method-size limit, no JSON dependency in the processor.

Format (tab-separated, one record per line):
  I<TAB>Class<TAB>Parent              # inheritance edge
  M<TAB>Class<TAB>name1,name2,...     # the class's own non-virtual methods, sorted

Output: processor/src/main/resources/net/multigesture/kanama/processor/engine-methods.tsv

    python3 scripts/generate_engine_method_table.py            # write
    python3 scripts/generate_engine_method_table.py --check    # fail on drift
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_API = ROOT / "extension_api.json"
OUT = ROOT / "processor/src/main/resources/net/multigesture/kanama/processor/engine-methods.tsv"


def render(api_path: pathlib.Path) -> str:
    api = json.loads(api_path.read_text())
    header = api["header"]
    lines = [
        f"# engine-methods table — generated by scripts/{pathlib.Path(__file__).name}",
        f"# source: {header['version_full_name']}",
        "# schemaVersion=1",
    ]
    inherits = []
    methods = []
    count = 0
    for c in api["classes"]:
        name = c["name"]
        parent = c.get("inherits", "")
        if parent:
            inherits.append(f"I\t{name}\t{parent}")
        own = sorted({m["name"] for m in c.get("methods", []) if not m.get("is_virtual")})
        if own:
            methods.append(f"M\t{name}\t{','.join(own)}")
            count += len(own)
    lines += sorted(inherits)
    lines += sorted(methods)
    lines.append(f"# counts: inherits={len(inherits)} classes={len(methods)} methods={count}")
    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv
    args = [a for a in sys.argv[1:] if a != "--check"]
    api_path = pathlib.Path(args[0]) if args else DEFAULT_API
    rendered = render(api_path)
    if check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != rendered:
            print("[engine_method_table] STALE — re-run scripts/generate_engine_method_table.py")
            return 1
        print("[engine_method_table] up to date")
        return 0
    OUT.write_text(rendered)
    print(f"[engine_method_table] wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
