#!/usr/bin/env python3
"""The typed Godot enum model (task 128 A): every Godot enum / bitfield as a Kotlin value class.

One module owns everything about the enum types so the wrapper generator, the migration script
(`scripts/migrate_enum_constants.py`), the migration table and the gate (`scripts/check_typed_enums.py`)
cannot disagree:

* **Type names** (decision 1). A class enum nests in its owner (`Node.ProcessMode`; Godot's `Object` is
  Kanama's `GodotObject`, so `GodotObject.ConnectFlags`). A global enum is top-level in
  `net.multigesture.kanama.api` under Godot's name, renamed only on a collision: `Error` -> `GodotError`
  (Kotlin's default-imported `Error`), `PropertyHint` -> `GodotPropertyHint` (Kanama's annotation
  constants), and the dotted `Variant.Type` / `Variant.Operator` -> `VariantType` / `VariantOperator`.
* **Value names** (decision 2, final). [enum_value_name] is the ONE naming function: Godot's C# rule
  (`modules/mono/editor/bindings_generator.cpp` `_determine_enum_prefix` /
  `_apply_prefix_to_enum_constants`) ported exactly, SCREAMING_CASE kept. The prefix of every enum is
  FROZEN in [LOCK_PATH]: the generator computes a prefix only for an enum the lock does not know yet
  and never changes an existing entry, so a later Godot adding a value cannot rename its siblings; a
  value that does not carry the frozen prefix keeps its full Godot name.
* **Rendering** of one value class for each render target ([render_enum_class]).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
API_PACKAGE = "net.multigesture.kanama.api"
LOCK_PATH = ROOT / "scripts/enum_prefix_lock.json"
LOCK_HEADER = "generated by generate_api_wrapper.py — do not edit"
# The marker every generated enum/bitfield value class implements (declared in the generated
# GlobalEnums.kt): the Variant encoders map a boxed one to INT with its `value`, so a typed enum
# handed to a dynamic `Any?` argument (`call`, `set`, `ConfigFile.setValue`) is not lost.
MARKER_INTERFACE = "GodotEnumValue"

# Godot class names whose Kotlin wrapper carries another name.
OWNER_KOTLIN_NAMES = {"Object": "GodotObject"}
# Global enums renamed on a collision (decision 1). Every other global keeps Godot's name.
GLOBAL_ENUM_RENAMES = {
    "Error": "GodotError",
    "PropertyHint": "GodotPropertyHint",
    "Variant.Type": "VariantType",
    "Variant.Operator": "VariantOperator",
}


@dataclass(frozen=True)
class EnumValue:
    name: str
    value: int


@dataclass(frozen=True)
class EnumSpec:
    """One Godot enum or bitfield. [key] is Godot's qualified name (`Node.ProcessMode`, `Key`,
    `Variant.Type`), the key of the lock and of `enum::` / `bitfield::` type strings."""

    key: str
    owner: str | None
    name: str
    is_bitfield: bool
    values: tuple[EnumValue, ...]
    # Owned by a builtin value type (`Vector3.Axis`): nested in Kanama's hand-written
    # `net.multigesture.kanama.types.Vector3` instead of a wrapper class.
    builtin: bool = False

    @property
    def kotlin_owner(self) -> str | None:
        return OWNER_KOTLIN_NAMES.get(self.owner, self.owner) if self.owner else None

    @property
    def simple_name(self) -> str:
        """The Kotlin classifier name (nested name for a class enum, top-level name for a global)."""
        if self.owner:
            return self.name
        return GLOBAL_ENUM_RENAMES.get(self.key, self.key)

    @property
    def kotlin_name(self) -> str:
        """The type as code outside the owner spells it: `Node.ProcessMode`, `GodotError`."""
        return f"{self.kotlin_owner}.{self.name}" if self.owner else self.simple_name


def load_enums(api_path: Path) -> dict[str, EnumSpec]:
    """Every global, class and builtin-class enum of extension_api.json, keyed by Godot's qualified
    name. Builtin-class enums (`Vector3.Axis`, `Projection.Planes`) nest in Kanama's value types."""
    data = json.loads(api_path.read_text(encoding="utf-8"))
    enums: dict[str, EnumSpec] = {}

    def add(key: str, owner: str | None, name: str, spec: dict, builtin: bool = False) -> None:
        enums[key] = EnumSpec(
            key=key,
            owner=owner,
            name=name,
            is_bitfield=bool(spec.get("is_bitfield", False)),
            values=tuple(EnumValue(str(v["name"]), int(v["value"])) for v in spec.get("values") or ()),
            builtin=builtin,
        )

    for spec in data.get("global_enums", []):
        add(spec["name"], None, spec["name"], spec)
    for cls in data.get("classes", []):
        for spec in cls.get("enums") or ():
            add(f"{cls['name']}.{spec['name']}", cls["name"], spec["name"], spec)
    for cls in data.get("builtin_classes", []):
        for spec in cls.get("enums") or ():
            add(f"{cls['name']}.{spec['name']}", cls["name"], spec["name"], spec, builtin=True)
    return enums


def enum_key_of_type(type_name: str) -> str | None:
    """`enum::Node.ProcessMode` -> `Node.ProcessMode`; `bitfield::X` -> `X`; anything else -> None."""
    for prefix in ("enum::", "bitfield::"):
        if type_name.startswith(prefix):
            return type_name[len(prefix) :]
    return None


# --- value names (decision 2) -----------------------------------------------------------------


def determine_prefix(value_names: list[str]) -> str:
    """Godot's `_determine_enum_prefix`, ported exactly; returns the prefix words joined by `_`.

    The candidate is every word of the FIRST value but its last; each value shortens it to the
    longest word-wise common prefix, where the last candidate word may differ as FLAG vs FLAGS
    (Godot's hard-coded exception for `FLAG_*` enums with a `FLAGS_DEFAULT`). Empty = no prefix.
    """
    if not value_names:
        return ""
    front = value_names[0].split("_")
    candidate = len(front) - 1
    if candidate == 0:
        return ""
    for name in value_names:
        parts = name.split("_")
        i = 0
        while i < candidate and i < len(parts):
            if front[i] != parts[i]:
                exception = i == candidate - 1 and {front[i], parts[i]} == {"FLAG", "FLAGS"}
                if not exception:
                    break
            i += 1
        candidate = i
        if candidate == 0:
            return ""
    return "_".join(front[:candidate])


def enum_value_name(prefix: str, godot_name: str) -> str:
    """THE naming function: the Kotlin name of Godot constant [godot_name] under the frozen [prefix].

    Godot's `_apply_prefix_to_enum_constants`, ported exactly, plus the frozen-prefix rule: a value
    whose words do not start with the prefix words (FLAG/FLAGS allowed on the last word, as when the
    prefix was determined) keeps its full Godot name. A remainder that would start with a digit
    backs the prefix off one word at a time (`KEY_0` stays `KEY_0`).
    """
    if not prefix:
        return godot_name
    prefix_words = prefix.split("_")
    length = len(prefix_words)
    parts = godot_name.split("_")
    if len(parts) <= length:
        return godot_name
    for i, word in enumerate(prefix_words):
        if parts[i] != word and not (i == length - 1 and {word, parts[i]} == {"FLAG", "FLAGS"}):
            return godot_name
    current = length
    if parts[current][:1].isdigit():
        current -= 1
        while current > 0 and parts[current][:1].isdigit():
            current -= 1
    return "_".join(parts[current:])


def read_lock(path: Path = LOCK_PATH) -> dict[str, str]:
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return dict(data.get("prefixes", {}))


def render_lock(prefixes: dict[str, str]) -> str:
    return (
        json.dumps(
            {"_comment": LOCK_HEADER, "prefixes": dict(sorted(prefixes.items()))},
            indent=2,
            ensure_ascii=False,
        )
        + "\n"
    )


def locked_prefixes(enums: dict[str, EnumSpec], lock: dict[str, str]) -> dict[str, str]:
    """The lock after this regen: every existing entry as-is, a computed entry for each new enum.

    Entries of enums the API no longer has are kept (a removed enum may come back; its prefix must
    not change), so the file only ever grows.
    """
    result = dict(lock)
    for key, spec in enums.items():
        if key not in result:
            result[key] = determine_prefix([v.name for v in spec.values])
    return result


def value_names(spec: EnumSpec, prefix: str) -> list[tuple[str, EnumValue]]:
    """(Kotlin name, Godot value) for every value of [spec], in Godot's order."""
    return [(enum_value_name(prefix, value.name), value) for value in spec.values]


def constant_for_value(spec: EnumSpec, prefix: str, number: int) -> str | None:
    """The Kotlin value name of the first constant equal to [number] (aliases: Godot's first)."""
    for kotlin_name, value in value_names(spec, prefix):
        if value.value == number:
            return kotlin_name
    return None


# --- rendering --------------------------------------------------------------------------------

# `expect` (common declaration of an enum-only expect class), `actual` (its platform actuals) or
# `plain` (everything else).
MODES = ("plain", "expect", "actual")


def render_enum_class(
    spec: EnumSpec, prefix: str, indent: str, *, jvm_inline: bool, mode: str = "plain", step: str = "    "
) -> str:
    """One value class: `value class X(val value: Long)` + bitfield operators + companion values.

    [jvm_inline] is False for files compiled by Kotlin/Native alone (`@JvmInline` is an
    `@OptionalExpectation` that only common and JVM sources may name).
    """
    assert mode in MODES
    name = spec.simple_name
    act = "actual " if mode == "actual" else ""
    inner = indent + step
    lines: list[str] = []
    if jvm_inline:
        lines.append(f"{indent}@JvmInline")
    # The builtin value types live in `net.multigesture.kanama.types`, so they name the marker
    # package-qualified; everything else is in the marker's own package.
    marker = f"{API_PACKAGE}.{MARKER_INTERFACE}" if spec.builtin else MARKER_INTERFACE
    if mode == "actual":
        # One `actual` per line, each at the line start: the Android copy compiles the JVM actual as
        # plain Kotlin and strips a LEADING `actual` only (KanamaAndroidRemap.ACTUAL_MODIFIER).
        lines += [
            f"{indent}actual value class {name}",
            f"{indent}actual constructor(",
            f"{indent}{step}actual override val value: Long,",
            f"{indent}) : {marker} {{",
        ]
    else:
        lines.append(f"{indent}value class {name}(override val value: Long) : {marker} {{")
    if spec.is_bitfield:
        if mode == "expect":
            lines += [
                f"{inner}infix fun or(other: {name}): {name}",
                "",
                f"{inner}infix fun and(other: {name}): {name}",
                "",
                f"{inner}infix fun xor(other: {name}): {name}",
                "",
                f"{inner}fun inv(): {name}",
                "",
                f"{inner}operator fun contains(other: {name}): Boolean",
            ]
        else:
            lines += [
                f"{inner}{act}infix fun or(other: {name}): {name} = {name}(value or other.value)",
                "",
                f"{inner}{act}infix fun and(other: {name}): {name} = {name}(value and other.value)",
                "",
                f"{inner}{act}infix fun xor(other: {name}): {name} = {name}(value xor other.value)",
                "",
                f"{inner}{act}fun inv(): {name} = {name}(value.inv())",
                "",
                f"{inner}{act}operator fun contains(other: {name}): Boolean = (value and other.value) == other.value",
            ]
        lines.append("")
    lines.append(f"{inner}{act}companion object {{")
    seen: set[str] = set()
    for kotlin_name, value in value_names(spec, prefix):
        if kotlin_name in seen:  # the gate proves this never happens; never emit a redeclaration
            raise ValueError(f"{spec.key}: duplicate value name {kotlin_name}")
        seen.add(kotlin_name)
        if mode == "expect":
            lines.append(f"{inner}{step}val {kotlin_name}: {name}")
        else:
            # Getter-only (no backing field, no companion static initialiser): the smallest JVM shape
            # that keeps the values typed (task 128 A size measurements).
            lines.append(f"{inner}{step}{act}val {kotlin_name}: {name} get() = {name}({value.value}L)")
    lines.append(f"{inner}}}")
    lines.append(f"{indent}}}")
    return "\n".join(lines)
