#!/usr/bin/env python3
"""The names Kotlin already gives a receiver (task 134 D2 review): kotlin-stdlib's extension
functions and `java.lang.String`'s members, read with `javap`, so that no generated builtin extension
(`net.multigesture.kanama.builtins`) takes one of them.

Why: a star import (`import net.multigesture.kanama.builtins.*`) outranks Kotlin's default imports,
so an extension named like a stdlib one silently changes what an existing call means
(`"ff".hexToInt()`, `"%d".format(5)`). The rule: a generated extension never takes a name that
kotlin-stdlib or `java.lang.String` already has for the same receiver; such a Godot method gets a
`godot` prefix instead (`godotHexToInt()`).

The names are recorded in `scripts/fixtures/kotlin_stdlib_names.txt` (one `<receiver>\\t<name>` line
each; a receiver is javap's spelling of the extension's first parameter, generics included, or
`java.lang.String#member` / `java.lang.String#static`) so the generator stays deterministic without
a JDK. `python3 scripts/stdlib_names.py --write` re-reads the jar of the Kotlin version the build
uses (from the Gradle cache) and the JDK's String; `check_builtin_coverage.py` re-checks the record
whenever both are available and fails on any generated name that collides.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "scripts/fixtures/kotlin_stdlib_names.txt"
HEADER = (
    "# kotlin-stdlib {version} extension functions and java.lang.String members: <receiver>\\t<name>.\n"
    "# GENERATED by scripts/stdlib_names.py --write (javap); read by builtin_boxed_methods.py and\n"
    "# check_builtin_coverage.py so that no generated builtin extension shadows one of them.\n"
)
METHOD_RE = re.compile(r"^\s*(?:public|private|protected)?\s*(?P<mods>(?:\w+\s+)*)(?:<[^>]*>\s+)?[\w.$<>?,\[\] ]+?\s+(?P<name>[\w$]+)\((?P<params>.*)\)")


def kotlin_version() -> str:
    match = re.search(r'kotlin\("multiplatform"\) version "([^"]+)"', (ROOT / "build.gradle.kts").read_text(encoding="utf-8"))
    if not match:
        raise SystemExit("[stdlib_names] no Kotlin version in build.gradle.kts")
    return match.group(1)


def stdlib_jar(version: str) -> Path | None:
    cache = Path(os.environ.get("GRADLE_USER_HOME", Path.home() / ".gradle")) / "caches/modules-2/files-2.1"
    found = sorted((cache / "org.jetbrains.kotlin/kotlin-stdlib" / version).glob(f"*/kotlin-stdlib-{version}.jar"))
    return found[0] if found else None


def javap() -> str | None:
    home = os.environ.get("JAVA_HOME")
    if home and (Path(home) / "bin/javap").exists():
        return str(Path(home) / "bin/javap")
    return shutil.which("javap")


def first_param(params: str) -> str:
    depth = 0
    for i, ch in enumerate(params):
        if ch == "<":
            depth += 1
        elif ch == ">":
            depth -= 1
        elif ch == "," and depth == 0:
            return params[:i].strip()
    return params.strip()


def collect(jar: Path, tool: str) -> list[str]:
    with zipfile.ZipFile(jar) as zf:
        classes = sorted(
            n[:-6].replace("/", ".")
            for n in zf.namelist()
            if n.endswith(".class") and "Kt" in n.rsplit("/", 1)[-1] and not n.startswith("META-INF")
        )
    lines: set[str] = set()
    for i in range(0, len(classes), 200):
        # `-p`: an @InlineOnly function (`String.format`, `CharSequence.find`, `count()`) is private
        # in bytecode, so private statics count too; a stdlib-private helper of the same name only
        # costs a prefix.
        out = subprocess.run([tool, "-p", "-cp", str(jar), *classes[i : i + 200]], check=True, capture_output=True, text=True).stdout
        for line in out.splitlines():
            m = METHOD_RE.match(line)
            if not m or "static" not in m.group("mods").split() or not m.group("params").strip() or "$" in m.group("name"):
                continue
            lines.add(f"{first_param(m.group('params'))}\t{m.group('name')}")
    out = subprocess.run([tool, "-public", "java.lang.String"], check=True, capture_output=True, text=True).stdout
    for line in out.splitlines():
        m = METHOD_RE.match(line)
        if m:
            kind = "static" if "static" in m.group("mods").split() else "member"
            lines.add(f"java.lang.String#{kind}\t{m.group('name')}")
    # kotlin.String's own members (the mapped type; `plus`/`get` are not java.lang.String's).
    for name in ("plus", "get", "length", "subSequence", "compareTo", "equals", "hashCode", "toString"):
        lines.add(f"java.lang.String#member\t{name}")
    return sorted(lines)


def render(version: str, lines: list[str]) -> str:
    return HEADER.format(version=version) + "\n".join(lines) + "\n"


def load() -> dict[str, set[str]]:
    """receiver -> names, from the recorded fixture."""
    out: dict[str, set[str]] = {}
    for line in FIXTURE.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        receiver, name = line.split("\t")
        out.setdefault(receiver, set()).add(name)
    return out


def live() -> tuple[str, str] | None:
    """(version, fixture text) read now, or None when the jar or javap is not available."""
    version = kotlin_version()
    jar, tool = stdlib_jar(version), javap()
    if jar is None or tool is None:
        return None
    return version, render(version, collect(jar, tool))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--write", action="store_true", help="re-read the stdlib and rewrite the fixture")
    args = parser.parse_args()
    now = live()
    if now is None:
        print("[stdlib_names] kotlin-stdlib jar or javap not found (run a Gradle build first)", file=sys.stderr)
        return 1
    version, text = now
    if args.write:
        FIXTURE.write_text(text, encoding="utf-8")
        print(f"[stdlib_names] wrote {FIXTURE.relative_to(ROOT)} ({len(text.splitlines()) - 3} names, kotlin-stdlib {version})")
        return 0
    current = FIXTURE.read_text(encoding="utf-8") if FIXTURE.exists() else ""
    if current != text:
        print("[stdlib_names] FAIL: the recorded stdlib names are stale: python3 scripts/stdlib_names.py --write", file=sys.stderr)
        return 1
    print("[stdlib_names] PASS: the recorded names match kotlin-stdlib " + version)
    return 0


if __name__ == "__main__":
    sys.exit(main())
