plugins {
    kotlin("multiplatform")
    id("com.google.devtools.ksp")
}

import java.io.File

// The iOS @ScriptClass registry is generated by the shared KSP processor (:processor) running on
// the Kotlin/Native targets — the exact same platform-neutral model used for desktop/Android.
// The old regex parser (parseIosScript) + generateIosScriptRegistry Gradle codegen were removed
// in Phase 3.2 (script-model-unification-design.md) after the parallel-run gate proved the two
// produced an identical registry. The processor emits, per native target:
//   - net.multigesture.kanama.ios.KanamaIosProjectRegistry.generated.kt (registry + bridges)
//   - net.multigesture.kanama.generated.KanamaIosScriptConstants.generated.kt (signal/name helpers)
//   - <pkg>.KanamaIosCompatibility.generated.kt (removeIf / System K/N shims)
// into the KSP kotlin output dir, which the KSP plugin adds to the compilation automatically.

fun iosScriptDirs(raw: String?): List<String> =
    raw
        ?.split(File.pathSeparator, ",")
        ?.map { it.trim() }
        ?.filter { it.isNotEmpty() }
        .orEmpty()

val configuredIosScriptDirs =
    providers.gradleProperty("kanamaIosProjectScriptsDirs")
        .orElse(providers.gradleProperty("kanamaIosProjectScriptsDir"))
        .orElse(providers.gradleProperty("kanamaProjectScriptsDirs"))
        .orElse(providers.gradleProperty("kanamaProjectScriptsDir"))

val kanamaPrecision = providers.gradleProperty("kanamaPrecision").orElse("single")

kotlin {
    iosArm64()
    iosSimulatorArm64()

    targets.withType<org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget>().configureEach {
        compilations.getByName("main") {
            cinterops {
                val kanama_ios by creating {
                    defFile(project.file("src/nativeInterop/cinterop/kanama_ios.def"))
                    includeDirs(rootProject.file("ios/include"))
                }
            }
        }

        binaries {
            staticLib {
                baseName = "kanama_ios_runtime"
            }
        }
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation(kotlin("stdlib"))
                implementation(project(":kanama-common-api"))
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0")
            }
        }
        val iosMain by creating {
            dependsOn(commonMain)
        }
        val iosArm64Main by getting {
            dependsOn(iosMain)
            iosScriptDirs(configuredIosScriptDirs.orNull).forEach { kotlin.srcDir(file(it)) }
        }
        val iosSimulatorArm64Main by getting {
            dependsOn(iosMain)
            iosScriptDirs(configuredIosScriptDirs.orNull).forEach { kotlin.srcDir(file(it)) }
        }
    }
}

tasks.configureEach {
    if (name.startsWith("compileKotlinIos")) {
        inputs.property("kanamaPrecision", kanamaPrecision)
        doFirst {
            val selected = kanamaPrecision.get()
            if (selected != "single") {
                throw GradleException(
                    "iOS currently supports only single-precision Godot real_t; " +
                        "-PkanamaPrecision=$selected is unsupported for :ios-runtime",
                )
            }
        }
    }
}

dependencies {
    add("kspIosArm64", project(":processor"))
    add("kspIosSimulatorArm64", project(":processor"))
}

ksp {
    // The processor derives each script's `res://…` path relative to these roots, and emits the
    // iOS registry as real `.kt` (vs the `.kt.txt` resources used during the Phase 3.2 gate).
    arg(
        "kanamaScriptRoots",
        iosScriptDirs(configuredIosScriptDirs.orNull)
            .map { file(it).absolutePath }
            .joinToString(File.pathSeparator),
    )
    arg("kanamaIosRegistryAsResource", "false")
}
